@echo off
echo DA Library Batch Build -- Version 0.1

:: NOTE: This assumes that you have already gotten the entire library source tree from source safe

:: If the configuration variables are not set in the environment, set them to their defaults
iff NOT DEFINED BUILD_TARGET_PLATFORM then
set BUILD_TARGET_PLATFORM=Win32
echo BUILD_TARGE_PLATFORM undefined. Setting to "%BUILD_TARGET_PLATFORM%".
endiff

iff NOT DEFINED BUILD_TARGET_CONFIG then
set BUILD_TARGET_CONFIG=Release
echo BUILD_TARGET_CONFIG undefined. Setting to "%BUILD_TARGET_CONFIG%".
endiff

iff NOT DEFINED MSDEV_BIN_PATH then
set MSDEV_BIN_PATH=c:\visstudio\common\msdev98\bin
echo MSDEV_BIN_PATH undefined. Setting to "%MSDEV_BIN_PATH%".
endiff

iff NOT DEFINED VSS_BIN_PATH then
set VSS_BIN_PATH=c:\visstudio\common\vss\win32
echo VSS_BIN_PATH undefined. Setting to "%VSS_BIN_PATH%".
endiff

iff NOT DEFINED BUILD_ROOT then
set BUILD_ROOT=d:\libs\dev
endiff

iff NOT DEFINED SSUSER then
set SSUSER=tbratton
echo WARNING: SSUSER not set. Setting to "%SSUSER%"
endiff

iff NOT DEFINED SSDIR then
set SSDIR=\\nt\libs\tools\libvss
echo WARNING: SSDIR not set. Setting to "%SSDIR%"
endiff

iff NOT DEFINED BUILD_TEMP_PATH then
set BUILD_TEMP_PATH=c:\windows\temp
echo BUILD_TEMP_PATH undefined. Setting to "%BUILD_TEMP_PATH%"
endiff

:: Derive some environment variables from the configuration variables,
:: such as target platform and configuration

set BUILD_CONFIG=Builder - %BUILD_TARGET_PLATFORM% %BUILD_TARGET_CONFIG%
set SS=%VSS_BIN_PATH%\ss.exe

:: Retrieve the entire development tree from source safe
echo ============ BEGIN SOURCE CODE RETRIEVAL ============
inkey /k"yn" Retrieve source from network archive? %%GET_SOURCE
iff "%GET_SOURCE%"=="y" then
%SS Get $/libs/dev/static -R
%SS Get $/libs/dev/include -R
%SS Get $/libs/dev/src -R
%SS Get $/libs/dev/builder -R
endiff
echo ============  END SOURCE CODE RETRIEVAL  ============

:: Lock the library version file and increment the build number within that file.
:: An environment variable will be set that contains the version string, so that we can
:: label the source tree with the build number.
:: NOTE: The perl script writes to %BUILD_TEMP_PATH%\setVersion.bat a batch file that will set
:: the BUILD_VERSION environment variable to a string containing the major, minor, and build numbers

copy %BUILD_ROOT%\src\libver.h %BUILD_ROOT%\src\libver.h.old
%SS Checkout $/libs/dev/src/libver.h -GF
echo print "Oops! Perl shouldn't be running this.\n" > %BUILD_TEMP_PATH%\setVersion.bat
perl incrementBuild.pl %BUILD_TEMP_PATH%\setVersion.bat < %BUILD_ROOT%\src\libver.h.old > %BUILD_ROOT%\src\libver.h
call %BUILD_TEMP_PATH%\setVersion.bat
::del %BUILD_TEMP_PATH%\setVersion.bat

:: Attrib and generate the file that will cause this build to be marked as 'official'
attrib -r %BUILD_ROOT%\src\buildres.h
echo // BuildRes.h - Build specific resource information > %BUILD_ROOT%\src\buildres.h
echo // AUTOMATICALLY GENERATED BY THE BUILD PROGRAM >> %BUILD_ROOT%\src\buildres.h
echo #define OFFICIAL_BUILD >> %BUILD_ROOT%\src\buildres.h

:: Clean and build the builder project, which is dependant on all other projects in the workspace
echo ============ BEGIN BUILD ============
echo Configuration:   "%BUILD_CONFIG%"
echo Library version: %BUILD_VERSION%
inkey /k"yn" Perform the build? %%GET_SOURCE
iff "%GET_SOURCE%"=="y" then
::%MSDEV_BIN_PATH%\msdev fullbuild.dsw /MAKE "%BUILD_CONFIG%" /REBUILD
%MSDEV_BIN_PATH%\msdev fullbuild.dsw /MAKE "%BUILD_CONFIG%"
endiff
echo ============ END BUILD ============

:: Clean up the temporary build files
del %BUILD_ROOT%\src\buildres.h
%SS Get $/libs/dev/src/buildres.h -GF
%SS Checkin $/libs/dev/src/libver.h -GF	-C-
