//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Editor.rc
//
#define ID_OPEN_SCENARIO                0
#define IDC_RESET                       3
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_EDITORTYPE                  129
#define IDS_CSETTINGS                   129
#define IDD_SIDEBAR                     130
#define IDS_PLAYER_NUM                  130
#define IDB_BITMAP1                     131
#define IDS_ED_STRINGVALUE              131
#define IDS_ED_STRINGID                 132
#define IDS_STRING_NEW                  133
#define IDS_SYSTEMS                     134
#define IDS_SCRIPTS                     135
#define IDB_SECTORTB                    140
#define IDI_ICON_FOLDER                 157
#define IDI_ICON_ROCKET                 158
#define IDI_ICON_FOLDER2                159
#define IDI_ICON_MSTART                 164
#define IDI_ICON_MCAMPAIGN              165
#define IDI_ICON_MSCENARIO              166
#define IDI_ICON_MSECTOR                167
#define IDI_ICON_MSYSTEM                168
#define IDR_MAINFRAME1                  169
#define IDC_CURSOR1                     171
#define IDD_NEW_CAMPAIGN                172
#define ID_FILE_SAVESENARIO             174
#define ID_FILE_SAVEASMISSION           175
#define IDB_BITMAP2                     177
#define IDB_SPLASH                      177
#define ID_PLAYER_PLAYERONE             178
#define ID_PLAYER_PLAYERTWO             179
#define ID_PLAYER_PLAYERTHREE           180
#define ID_PLAYER_PLAYERFOUR            181
#define ID_PLAYER_PLAYERFIVE            182
#define ID_PLAYER_PLAYERSIX             183
#define ID_PLAYER_PLAYERSEVEN           184
#define ID_PLAYER_PLAYEREIGHT           185
#define IDD_ERROR                       186
#define IDD_STRING_TABLE                187
#define IDR_STRING_TABLE_MENU           188
#define ID_FILE_SAVE189                 189
#define ID_FILE_LOAD                    190
#define ID_FILE_EXIT                    191
#define ID_LANGUAGE_NEW                 192
#define ID_LANGUAGE_CHOOSE              193
#define ID_CHOOSE_ENGLISH               194
#define ID_STRING_TABLE                 195
#define IDD_EDIT_STRING_ENTRY           196
#define IDD_OBJPROPS                    197
#define IDD_OP_BASIC                    199
#define IDD_OP_ARMOR                    200
#define IDR_OBJECT_MENU                 200
#define ID_OBJECTCOMMAND_DELETE         201
#define IDD_OP_BLACKHOLE                201
#define IDR_WORMHOLE_MENU               201
#define ID_OBJECTCOMMAND_RENAME         202
#define IDR_MENU_GROUPS                 202
#define ID_OBJECTCOMMAND_CLONE          203
#define IDR_MENU_GROUP                  203
#define ID_OBJECTCOMMAND_PROPERTIES     204
#define ID_OBJECTCOMMAND_WARP           205
#define IDD_SYSTEMPROPS                 206
#define ID_OBJECTCOMMAND_GOTO           207
#define IDD_OP_TRIGGER                  207
#define ID_MODE_CAMPAIGN_VIEW           208
#define IDD_NEW_GROUP                   208
#define ID_MODE_SCENARIO_VIEW           209
#define IDD_CHOOSE_GROUP                209
#define ID_MODE_SECTOR_VIEW             210
#define ID_MODE_SYSTEM_VIEW             211
#define ID_OBJECTCOMMAND_ADDTOGROUP     213
#define ID_FILE_EXPORTSTRINGTABLE       214
#define ID_FILE_IMPORTSTRINGTABLE       215
#define ID_GROUPCOMMAND_ADDTO           216
#define ID_OBJECTCOMMAND_SELECT         217
#define ID_MAP_LAUNCH                   218
#define IDC_EDIT_NAME                   1000
#define IDC_COMBO_RACE                  1002
#define IDC_EDIT_ERR                    1004
#define IDC_STRING_LIST                 1006
#define IDC_BUTTON_NEW                  1007
#define IDC_BUTTON_DELETE               1008
#define IDC_EDIT_VALUE                  1008
#define IDC_BUTTON_EDIT                 1009
#define IDC_EDIT_TAG                    1009
#define IDC_RICHEDIT21                  1010
#define IDC_RICHEDIT_NAME               1010
#define IDC_NAMESTRING                  1010
#define IDC_RICHEDIT                    1010
#define IDC_OBJ_PROPERTIES              1011
#define IDC_BTN_NEWSTRING               1012
#define IDC_EDIT_SCRIPTHANDLE           1013
#define IDC_RADIO_MODIFIED              1014
#define IDC_TABS                        1016
#define IDC_EDIT_HULLMAX                1017
#define IDC_EDIT_SUPPLYPNTS             1018
#define IDC_EDIT_SCRAPVAL               1019
#define IDC_EDIT_DMGVSNONE              1019
#define IDC_EDIT_COMMANDPNTS            1020
#define IDC_EDIT_DMGVSLIGHT             1020
#define IDC_EDIT_SENSORRAD              1021
#define IDC_EDIT_DMGVSMEDIUM            1021
#define IDC_EDIT_CLOAKEDRAD             1022
#define IDC_EDIT_DMGVSHEAVY             1022
#define IDC_EDIT_MAXVELOCITY            1023
#define IDC_COMBO_ARMOR                 1023
#define IDC_EDIT_BASESHIELD             1024
#define IDC_CHECK_SYS1                  1025
#define IDC_CHECK_MODIFIED              1026
#define IDC_BUTTON_NEWSTRING            1028
#define IDC_COMBO_SYSKIT                1029
#define IDC_FLAG_SHIPID                 1030
#define IDC_FLAG_OBJCLASS               1031
#define IDC_FLAG_SHIPTYPE               1032
#define IDC_FLAG_PLAYERID               1033
#define IDC_FLAG_READYWAIT              1034
#define IDC_EDIT_RANGE                  1035
#define IDC_FLAG_ENABLED                1036
#define IDC_COMBO                       1036
#define IDC_COMBO_GROUP                 1037
#define IDC_CHECK_SYS2                  1043
#define IDC_CHECK_SYS3                  1044
#define IDC_CHECK_SYS4                  1045
#define IDC_CHECK_SYS5                  1046
#define IDC_CHECK_SYS6                  1047
#define IDC_CHECK_SYS7                  1048
#define IDC_CHECK_SYS8                  1049
#define IDC_CHECK_SYS9                  1050
#define IDC_CHECK_SYS10                 1051
#define IDC_CHECK_SYS11                 1052
#define IDC_CHECK_SYS12                 1053
#define IDC_CHECK_SYS13                 1054
#define IDC_CHECK_SYS14                 1055
#define IDC_CHECK_SYS15                 1056
#define IDC_CHECK_SYS16                 1057
#define ID_MODE_SYSTEM                  31760
#define ID_MODE_SECTOR                  31761
#define ID_MODE_SCENARIO                31762
#define ID_MODE_CAMPAIGN                31763
#define ID_NEW_SCENARIO                 32771
#define ID_MODE_START                   32772
#define ID_SCENARIO_OPEN                32777
#define IDS_SECTORBAR                   59394
#define IDS_SYSTEMBAR                   59395
#define IDS_ASSETBAR                    59396
#define IDS_ENTITYBAR                   59397
#define IDS_GROUPS                      59398
#define IDS_OUTPUTBAR                   59399

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        219
#define _APS_NEXT_COMMAND_VALUE         32778
#define _APS_NEXT_CONTROL_VALUE         1039
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
