; Listing generated by Microsoft (R) Optimizing Compiler Version 15.00.30729.01 

	TITLE	m:\Archive\Conquest\Code\Libs\Src\DACOM\HeapInst.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMTD
INCLUDELIB OLDNAMES

PUBLIC	?Release@HeapInstance@@UAGKXZ			; HeapInstance::Release
EXTRN	__imp__VirtualFree@12:PROC
; Function compile flags: /Odtp
; File m:\archive\conquest\code\libs\src\dacom\heapinst.cpp
_TEXT	SEGMENT
_this$ = 8						; size = 4
?Release@HeapInstance@@UAGKXZ PROC			; HeapInstance::Release

; 50   : {

	push	ebp
	mov	ebp, esp

; 51   : 	if (dwRefs > 0)

	mov	eax, DWORD PTR _this$[ebp]
	cmp	DWORD PTR [eax+4], 0
	jbe	SHORT $LN3@Release

; 52   : 		dwRefs--;

	mov	ecx, DWORD PTR _this$[ebp]
	mov	edx, DWORD PTR [ecx+4]
	sub	edx, 1
	mov	eax, DWORD PTR _this$[ebp]
	mov	DWORD PTR [eax+4], edx
$LN3@Release:

; 53   : 
; 54   : 	if (dwRefs == 0)

	mov	ecx, DWORD PTR _this$[ebp]
	cmp	DWORD PTR [ecx+4], 0
	jne	SHORT $LN2@Release

; 55   : 	{
; 56   : 		if (pNext)

	mov	edx, DWORD PTR _this$[ebp]
	cmp	DWORD PTR [edx+16], 0
	je	SHORT $LN1@Release

; 57   : 			pNext->Release();

	mov	eax, DWORD PTR _this$[ebp]
	mov	ecx, DWORD PTR [eax+16]
	mov	edx, DWORD PTR _this$[ebp]
	mov	eax, DWORD PTR [edx+16]
	mov	ecx, DWORD PTR [ecx]
	push	eax
	mov	edx, DWORD PTR [ecx+8]
	call	edx
$LN1@Release:

; 58   : 		
; 59   : 		VirtualFree(pHeapBase, 0, MEM_RELEASE);

	push	32768					; 00008000H
	push	0
	mov	eax, DWORD PTR _this$[ebp]
	mov	ecx, DWORD PTR [eax+28]
	push	ecx
	call	DWORD PTR __imp__VirtualFree@12

; 60   : 		//pHeapBase=0;	// we have allocated from within our own heap
; 61   : 		//delete this;
; 62   : 		return 0;

	xor	eax, eax
	jmp	SHORT $LN4@Release
$LN2@Release:

; 63   : 	}
; 64   : 
; 65   : 	return dwRefs;

	mov	edx, DWORD PTR _this$[ebp]
	mov	eax, DWORD PTR [edx+4]
$LN4@Release:

; 66   : }

	pop	ebp
	ret	4
?Release@HeapInstance@@UAGKXZ ENDP			; HeapInstance::Release
_TEXT	ENDS
PUBLIC	?setOwner@BASE_BLOCK@@QAEXK@Z			; BASE_BLOCK::setOwner
PUBLIC	?setMsg@BASE_BLOCK@@QAEXPBD@Z			; BASE_BLOCK::setMsg
PUBLIC	?malloc@HeapInstance@@QAIPAUBASE_BLOCK@@K@Z	; HeapInstance::malloc
PUBLIC	?AllocateMemory@HeapInstance@@UAGPAXKPBD@Z	; HeapInstance::AllocateMemory
; Function compile flags: /Odtp
_TEXT	SEGMENT
_result$ = -4						; size = 4
_this$ = 8						; size = 4
_numBytes$ = 12						; size = 4
_msg$ = 16						; size = 4
?AllocateMemory@HeapInstance@@UAGPAXKPBD@Z PROC		; HeapInstance::AllocateMemory

; 70   : {

	push	ebp
	mov	ebp, esp
	push	ecx

; 71   : 	BASE_BLOCK *result;
; 72   : 
; 73   : 	if ((result = malloc(numBytes)) == 0)

	mov	edx, DWORD PTR _numBytes$[ebp]
	mov	ecx, DWORD PTR _this$[ebp]
	call	?malloc@HeapInstance@@QAIPAUBASE_BLOCK@@K@Z ; HeapInstance::malloc
	mov	DWORD PTR _result$[ebp], eax
	cmp	DWORD PTR _result$[ebp], 0
	jne	SHORT $LN2@AllocateMe

; 74   : 		return result;

	mov	eax, DWORD PTR _result$[ebp]
	jmp	SHORT $LN3@AllocateMe
$LN2@AllocateMe:

; 75   : 
; 76   : 	if ((dwFlags & DAHEAPFLAG_NOMSGS) == 0)

	mov	eax, DWORD PTR _this$[ebp]
	mov	ecx, DWORD PTR [eax+12]
	and	ecx, 16					; 00000010H
	jne	SHORT $LN1@AllocateMe

; 77   : 	{
; 78   : 	  	result->setMsg(msg);

	mov	edx, DWORD PTR _msg$[ebp]
	push	edx
	mov	ecx, DWORD PTR _result$[ebp]
	call	?setMsg@BASE_BLOCK@@QAEXPBD@Z		; BASE_BLOCK::setMsg

; 79   : 	  	result->setOwner(0);

	push	0
	mov	ecx, DWORD PTR _result$[ebp]
	call	?setOwner@BASE_BLOCK@@QAEXK@Z		; BASE_BLOCK::setOwner
$LN1@AllocateMe:

; 80   : 	}
; 81   : 	return (void *) ((char *)result+dwBaseBlockSize);

	mov	eax, DWORD PTR _this$[ebp]
	mov	ecx, DWORD PTR _result$[ebp]
	add	ecx, DWORD PTR [eax+24]
	mov	eax, ecx
$LN3@AllocateMe:

; 82   : }

	mov	esp, ebp
	pop	ebp
	ret	12					; 0000000cH
?AllocateMemory@HeapInstance@@UAGPAXKPBD@Z ENDP		; HeapInstance::AllocateMemory
; Function compile flags: /Odtp
; File m:\archive\conquest\code\libs\src\dacom\baseheap.h
_TEXT	ENDS
;	COMDAT ?setMsg@BASE_BLOCK@@QAEXPBD@Z
_TEXT	SEGMENT
_this$ = -4						; size = 4
__pMsg$ = 8						; size = 4
?setMsg@BASE_BLOCK@@QAEXPBD@Z PROC			; BASE_BLOCK::setMsg, COMDAT
; _this$ = ecx

; 53   : 	{

	push	ebp
	mov	ebp, esp
	push	ecx
	mov	DWORD PTR _this$[ebp], ecx

; 54   : 		pMsg = _pMsg;

	mov	eax, DWORD PTR _this$[ebp]
	mov	ecx, DWORD PTR __pMsg$[ebp]
	mov	DWORD PTR [eax+8], ecx

; 55   : 	}

	mov	esp, ebp
	pop	ebp
	ret	4
?setMsg@BASE_BLOCK@@QAEXPBD@Z ENDP			; BASE_BLOCK::setMsg
; Function compile flags: /Odtp
_TEXT	ENDS
;	COMDAT ?setOwner@BASE_BLOCK@@QAEXK@Z
_TEXT	SEGMENT
_this$ = -4						; size = 4
__pOwner$ = 8						; size = 4
?setOwner@BASE_BLOCK@@QAEXK@Z PROC			; BASE_BLOCK::setOwner, COMDAT
; _this$ = ecx

; 63   : 	{

	push	ebp
	mov	ebp, esp
	push	ecx
	mov	DWORD PTR _this$[ebp], ecx

; 64   : 		pOwner = _pOwner;

	mov	eax, DWORD PTR _this$[ebp]
	mov	ecx, DWORD PTR __pOwner$[ebp]
	mov	DWORD PTR [eax+12], ecx

; 65   : 	}

	mov	esp, ebp
	pop	ebp
	ret	4
?setOwner@BASE_BLOCK@@QAEXK@Z ENDP			; BASE_BLOCK::setOwner
_TEXT	ENDS
PUBLIC	?free@HeapInstance@@QAIHPAUFREE_BLOCK@@@Z	; HeapInstance::free
PUBLIC	?verifyBlock@HeapInstance@@QAEPAUBASE_BLOCK@@PAX@Z ; HeapInstance::verifyBlock
PUBLIC	?ReallocateMemory@HeapInstance@@UAGPAXPAXKPBD@Z	; HeapInstance::ReallocateMemory
EXTRN	_memcpy:PROC
; Function compile flags: /Odtp
; File m:\archive\conquest\code\libs\src\dacom\heapinst.cpp
_TEXT	SEGMENT
tv90 = -12						; size = 4
_result$ = -8						; size = 4
_pBlock$ = -4						; size = 4
_this$ = 8						; size = 4
_allocatedBlock$ = 12					; size = 4
_newSize$ = 16						; size = 4
_msg$ = 20						; size = 4
?ReallocateMemory@HeapInstance@@UAGPAXPAXKPBD@Z PROC	; HeapInstance::ReallocateMemory

; 86   : {

	push	ebp
	mov	ebp, esp
	sub	esp, 12					; 0000000cH

; 87   : 	void * result;
; 88   : 	BASE_BLOCK *pBlock;
; 89   : 
; 90   : 	if ((pBlock = verifyBlock(allocatedBlock)) == 0)

	mov	eax, DWORD PTR _allocatedBlock$[ebp]
	push	eax
	mov	ecx, DWORD PTR _this$[ebp]
	call	?verifyBlock@HeapInstance@@QAEPAUBASE_BLOCK@@PAX@Z ; HeapInstance::verifyBlock
	mov	DWORD PTR _pBlock$[ebp], eax
	cmp	DWORD PTR _pBlock$[ebp], 0
	jne	SHORT $LN5@Reallocate

; 91   : 	{
; 92   : 		result = 0;

	mov	DWORD PTR _result$[ebp], 0
	jmp	SHORT $Done$63517

; 93   : 		goto Done;

	jmp	SHORT $Done$63517
$LN5@Reallocate:

; 94   : 	}
; 95   : 
; 96   : 	if (newSize == 0)

	cmp	DWORD PTR _newSize$[ebp], 0
	jne	SHORT $LN3@Reallocate

; 97   : 	{
; 98   : 		free((FREE_BLOCK *)pBlock);

	mov	edx, DWORD PTR _pBlock$[ebp]
	mov	ecx, DWORD PTR _this$[ebp]
	call	?free@HeapInstance@@QAIHPAUFREE_BLOCK@@@Z ; HeapInstance::free

; 99   : 		result=0;

	mov	DWORD PTR _result$[ebp], 0

; 100  : 	}
; 101  : 	else

	jmp	SHORT $Done$63517
$LN3@Reallocate:

; 102  : 	if ((result = AllocateMemory(newSize, msg)) != 0)

	mov	ecx, DWORD PTR _msg$[ebp]
	push	ecx
	mov	edx, DWORD PTR _newSize$[ebp]
	push	edx
	mov	eax, DWORD PTR _this$[ebp]
	mov	ecx, DWORD PTR [eax]
	mov	edx, DWORD PTR _this$[ebp]
	push	edx
	mov	eax, DWORD PTR [ecx+16]
	call	eax
	mov	DWORD PTR _result$[ebp], eax
	cmp	DWORD PTR _result$[ebp], 0
	je	SHORT $Done$63517

; 103  : 	{
; 104  : 		memcpy(result, allocatedBlock, __min((pBlock->dwSize&~1), newSize));

	mov	ecx, DWORD PTR _pBlock$[ebp]
	mov	edx, DWORD PTR [ecx]
	and	edx, -2					; fffffffeH
	cmp	edx, DWORD PTR _newSize$[ebp]
	jae	SHORT $LN8@Reallocate
	mov	eax, DWORD PTR _pBlock$[ebp]
	mov	ecx, DWORD PTR [eax]
	and	ecx, -2					; fffffffeH
	mov	DWORD PTR tv90[ebp], ecx
	jmp	SHORT $LN9@Reallocate
$LN8@Reallocate:
	mov	edx, DWORD PTR _newSize$[ebp]
	mov	DWORD PTR tv90[ebp], edx
$LN9@Reallocate:
	mov	eax, DWORD PTR tv90[ebp]
	push	eax
	mov	ecx, DWORD PTR _allocatedBlock$[ebp]
	push	ecx
	mov	edx, DWORD PTR _result$[ebp]
	push	edx
	call	_memcpy
	add	esp, 12					; 0000000cH

; 105  : 		free((FREE_BLOCK *)pBlock);

	mov	edx, DWORD PTR _pBlock$[ebp]
	mov	ecx, DWORD PTR _this$[ebp]
	call	?free@HeapInstance@@QAIHPAUFREE_BLOCK@@@Z ; HeapInstance::free
$Done$63517:

; 106  : 	}
; 107  : 
; 108  : Done:
; 109  : 	return result;

	mov	eax, DWORD PTR _result$[ebp]

; 110  : }

	mov	esp, ebp
	pop	ebp
	ret	16					; 00000010H
?ReallocateMemory@HeapInstance@@UAGPAXPAXKPBD@Z ENDP	; HeapInstance::ReallocateMemory
_TEXT	ENDS
PUBLIC	?getUpper@BASE_BLOCK@@QAEPAU1@XZ		; BASE_BLOCK::getUpper
PUBLIC	?getLower@BASE_BLOCK@@QAEPAU1@XZ		; BASE_BLOCK::getLower
EXTRN	?doError@BaseHeap@@QAEJKKK@Z:PROC		; BaseHeap::doError
; Function compile flags: /Odtp
; File m:\archive\conquest\code\libs\src\dacom\baseheap.h
;	COMDAT ?verifyBlock@HeapInstance@@QAEPAUBASE_BLOCK@@PAX@Z
_TEXT	SEGMENT
_this$ = -8						; size = 4
_pBlock$ = -4						; size = 4
__pBlock$ = 8						; size = 4
?verifyBlock@HeapInstance@@QAEPAUBASE_BLOCK@@PAX@Z PROC	; HeapInstance::verifyBlock, COMDAT
; _this$ = ecx

; 329  : {

	push	ebp
	mov	ebp, esp
	sub	esp, 8
	mov	DWORD PTR _this$[ebp], ecx

; 330  : 	BASE_BLOCK *pBlock;
; 331  : 	
; 332  : 	if (_pBlock == 0)

	cmp	DWORD PTR __pBlock$[ebp], 0
	jne	SHORT $LN8@verifyBloc

; 333  : 		return 0;

	xor	eax, eax
	jmp	$LN9@verifyBloc
$LN8@verifyBloc:

; 334  : 		
; 335  : 	pBlock = (BASE_BLOCK *) (((C8 *)_pBlock) - dwBaseBlockSize);

	mov	eax, DWORD PTR _this$[ebp]
	mov	ecx, DWORD PTR __pBlock$[ebp]
	sub	ecx, DWORD PTR [eax+24]
	mov	DWORD PTR _pBlock$[ebp], ecx

; 336  : 	if (dwFlags & DAHEAPFLAG_NOVERIFYPTR)

	mov	edx, DWORD PTR _this$[ebp]
	mov	eax, DWORD PTR [edx+12]
	and	eax, 4
	je	SHORT $LN7@verifyBloc

; 337  : 		return pBlock;

	mov	eax, DWORD PTR _pBlock$[ebp]
	jmp	SHORT $LN9@verifyBloc
$LN7@verifyBloc:

; 338  : 
; 339  : 	// lower block check
; 340  : 	if (pBlock->getLower()->getUpper() != pBlock)

	mov	ecx, DWORD PTR _pBlock$[ebp]
	call	?getLower@BASE_BLOCK@@QAEPAU1@XZ	; BASE_BLOCK::getLower
	mov	ecx, eax
	call	?getUpper@BASE_BLOCK@@QAEPAU1@XZ	; BASE_BLOCK::getUpper
	cmp	eax, DWORD PTR _pBlock$[ebp]
	je	SHORT $LN6@verifyBloc
	jmp	SHORT $Error$63189

; 341  : 		goto Error;

	jmp	SHORT $Error$63189
$LN6@verifyBloc:

; 342  : 	// upper block check
; 343  : 	if (pBlock->getUpper() && pBlock->getUpper()->getLower() != pBlock)

	mov	ecx, DWORD PTR _pBlock$[ebp]
	call	?getUpper@BASE_BLOCK@@QAEPAU1@XZ	; BASE_BLOCK::getUpper
	test	eax, eax
	je	SHORT $LN4@verifyBloc
	mov	ecx, DWORD PTR _pBlock$[ebp]
	call	?getUpper@BASE_BLOCK@@QAEPAU1@XZ	; BASE_BLOCK::getUpper
	mov	ecx, eax
	call	?getLower@BASE_BLOCK@@QAEPAU1@XZ	; BASE_BLOCK::getLower
	cmp	eax, DWORD PTR _pBlock$[ebp]
	je	SHORT $LN4@verifyBloc
	jmp	SHORT $Error$63189

; 344  : 		goto Error;

	jmp	SHORT $Error$63189
$LN4@verifyBloc:

; 345  : 
; 346  : 	return pBlock;

	mov	eax, DWORD PTR _pBlock$[ebp]
	jmp	SHORT $LN9@verifyBloc
$Error$63189:

; 347  : Error:
; 348  : 	if (EnumerateBlocks(0,0) == 0)

	push	0
	push	0
	mov	ecx, DWORD PTR _this$[ebp]
	mov	edx, DWORD PTR [ecx]
	mov	eax, DWORD PTR _this$[ebp]
	push	eax
	mov	ecx, DWORD PTR [edx+32]
	call	ecx
	test	eax, eax
	jne	SHORT $LN2@verifyBloc

; 349  : 		doError(DAHEAP_HEAP_CORRUPTED);

	push	0
	push	0
	push	4
	mov	ecx, DWORD PTR _this$[ebp]
	call	?doError@BaseHeap@@QAEJKKK@Z		; BaseHeap::doError

; 350  : 	else

	jmp	SHORT $LN1@verifyBloc
$LN2@verifyBloc:

; 351  : 		doError(DAHEAP_INVALID_PTR, (DWORD)_pBlock);

	push	0
	mov	edx, DWORD PTR __pBlock$[ebp]
	push	edx
	push	5
	mov	ecx, DWORD PTR _this$[ebp]
	call	?doError@BaseHeap@@QAEJKKK@Z		; BaseHeap::doError
$LN1@verifyBloc:

; 352  : 	return 0;

	xor	eax, eax
$LN9@verifyBloc:

; 353  : }

	mov	esp, ebp
	pop	ebp
	ret	4
?verifyBlock@HeapInstance@@QAEPAUBASE_BLOCK@@PAX@Z ENDP	; HeapInstance::verifyBlock
; Function compile flags: /Odtp
_TEXT	ENDS
;	COMDAT ?getUpper@BASE_BLOCK@@QAEPAU1@XZ
_TEXT	SEGMENT
_this$ = -4						; size = 4
?getUpper@BASE_BLOCK@@QAEPAU1@XZ PROC			; BASE_BLOCK::getUpper, COMDAT
; _this$ = ecx

; 77   : {

	push	ebp
	mov	ebp, esp
	push	ecx
	mov	DWORD PTR _this$[ebp], ecx

; 78   : 	return pUpper;

	mov	eax, DWORD PTR _this$[ebp]
	mov	eax, DWORD PTR [eax+4]

; 79   : }

	mov	esp, ebp
	pop	ebp
	ret	0
?getUpper@BASE_BLOCK@@QAEPAU1@XZ ENDP			; BASE_BLOCK::getUpper
; Function compile flags: /Odtp
_TEXT	ENDS
;	COMDAT ?getLower@BASE_BLOCK@@QAEPAU1@XZ
_TEXT	SEGMENT
_this$ = -4						; size = 4
?getLower@BASE_BLOCK@@QAEPAU1@XZ PROC			; BASE_BLOCK::getLower, COMDAT
; _this$ = ecx

; 82   : {

	push	ebp
	mov	ebp, esp
	push	ecx
	mov	DWORD PTR _this$[ebp], ecx

; 83   : 	return (BASE_BLOCK *) (((C8 *)this) + (dwSize & ~1));

	mov	eax, DWORD PTR _this$[ebp]
	mov	eax, DWORD PTR [eax]
	and	eax, -2					; fffffffeH
	add	eax, DWORD PTR _this$[ebp]

; 84   : }

	mov	esp, ebp
	pop	ebp
	ret	0
?getLower@BASE_BLOCK@@QAEPAU1@XZ ENDP			; BASE_BLOCK::getLower
_TEXT	ENDS
PUBLIC	?FreeMemory@HeapInstance@@UAGJPAX@Z		; HeapInstance::FreeMemory
; Function compile flags: /Odtp
; File m:\archive\conquest\code\libs\src\dacom\heapinst.cpp
_TEXT	SEGMENT
_result$ = -8						; size = 4
_pBlock$ = -4						; size = 4
_this$ = 8						; size = 4
_allocatedBlock$ = 12					; size = 4
?FreeMemory@HeapInstance@@UAGJPAX@Z PROC		; HeapInstance::FreeMemory

; 114  : {

	push	ebp
	mov	ebp, esp
	sub	esp, 8

; 115  : 	BOOL32 result;
; 116  : 	BASE_BLOCK *pBlock;
; 117  : 
; 118  : 	if ((pBlock = verifyBlock(allocatedBlock)) == 0)

	mov	eax, DWORD PTR _allocatedBlock$[ebp]
	push	eax
	mov	ecx, DWORD PTR _this$[ebp]
	call	?verifyBlock@HeapInstance@@QAEPAUBASE_BLOCK@@PAX@Z ; HeapInstance::verifyBlock
	mov	DWORD PTR _pBlock$[ebp], eax
	cmp	DWORD PTR _pBlock$[ebp], 0
	jne	SHORT $LN2@FreeMemory

; 119  : 	{
; 120  : 		result = 0;

	mov	DWORD PTR _result$[ebp], 0
	jmp	SHORT $Done$63531

; 121  : 		goto Done;

	jmp	SHORT $Done$63531
$LN2@FreeMemory:

; 122  : 	}
; 123  : 
; 124  : 	result = free((FREE_BLOCK *)pBlock);

	mov	edx, DWORD PTR _pBlock$[ebp]
	mov	ecx, DWORD PTR _this$[ebp]
	call	?free@HeapInstance@@QAIHPAUFREE_BLOCK@@@Z ; HeapInstance::free
	mov	DWORD PTR _result$[ebp], eax
$Done$63531:

; 125  : 
; 126  : Done:
; 127  : 	return result;

	mov	eax, DWORD PTR _result$[ebp]

; 128  : }

	mov	esp, ebp
	pop	ebp
	ret	8
?FreeMemory@HeapInstance@@UAGJPAX@Z ENDP		; HeapInstance::FreeMemory
_TEXT	ENDS
PUBLIC	?getPrev@FREE_BLOCK@@QAEPAU1@XZ			; FREE_BLOCK::getPrev
PUBLIC	?getNext@FREE_BLOCK@@QAEPAU1@XZ			; FREE_BLOCK::getNext
PUBLIC	?isAllocated@BASE_BLOCK@@QAEHXZ			; BASE_BLOCK::isAllocated
PUBLIC	?EnumerateBlocks@HeapInstance@@UAGJP6GJPAUIHeap@@PAXK1@Z1@Z ; HeapInstance::EnumerateBlocks
; Function compile flags: /Odtp
_TEXT	SEGMENT
_result$ = -12						; size = 4
_dwFlags$ = -8						; size = 4
_pBlock$ = -4						; size = 4
_this$ = 8						; size = 4
_proc$ = 12						; size = 4
_context$ = 16						; size = 4
?EnumerateBlocks@HeapInstance@@UAGJP6GJPAUIHeap@@PAXK1@Z1@Z PROC ; HeapInstance::EnumerateBlocks

; 132  : {

	push	ebp
	mov	ebp, esp
	sub	esp, 12					; 0000000cH

; 133  : 	BOOL32 result=1;

	mov	DWORD PTR _result$[ebp], 1

; 134  : 	DWORD dwFlags;
; 135  : 	FREE_BLOCK *pBlock = (FREE_BLOCK *) pHeapBase;

	mov	eax, DWORD PTR _this$[ebp]
	mov	ecx, DWORD PTR [eax+28]
	mov	DWORD PTR _pBlock$[ebp], ecx
$LN10@EnumerateB:

; 136  : 
; 137  : 	while (result && pBlock->dwSize != 1)

	cmp	DWORD PTR _result$[ebp], 0
	je	$LN9@EnumerateB
	mov	edx, DWORD PTR _pBlock$[ebp]
	cmp	DWORD PTR [edx], 1
	je	$LN9@EnumerateB

; 138  : 	{
; 139  : 		if ((dwFlags = pBlock->isAllocated()) == 0)

	mov	ecx, DWORD PTR _pBlock$[ebp]
	call	?isAllocated@BASE_BLOCK@@QAEHXZ		; BASE_BLOCK::isAllocated
	mov	DWORD PTR _dwFlags$[ebp], eax
	cmp	DWORD PTR _dwFlags$[ebp], 0
	jne	SHORT $LN8@EnumerateB

; 140  : 		{
; 141  : 			// check the free list (circular list)
; 142  : 			if (pBlock->getNext()->getPrev() != pBlock)

	mov	ecx, DWORD PTR _pBlock$[ebp]
	call	?getNext@FREE_BLOCK@@QAEPAU1@XZ		; FREE_BLOCK::getNext
	mov	ecx, eax
	call	?getPrev@FREE_BLOCK@@QAEPAU1@XZ		; FREE_BLOCK::getPrev
	cmp	eax, DWORD PTR _pBlock$[ebp]
	je	SHORT $LN7@EnumerateB

; 143  : 				dwFlags |= DAHEAPFLAG_CORRUPTED_BLOCK;

	mov	eax, DWORD PTR _dwFlags$[ebp]
	or	eax, 2
	mov	DWORD PTR _dwFlags$[ebp], eax
$LN7@EnumerateB:

; 144  : 			if (pBlock->getPrev()->getNext() != pBlock)

	mov	ecx, DWORD PTR _pBlock$[ebp]
	call	?getPrev@FREE_BLOCK@@QAEPAU1@XZ		; FREE_BLOCK::getPrev
	mov	ecx, eax
	call	?getNext@FREE_BLOCK@@QAEPAU1@XZ		; FREE_BLOCK::getNext
	cmp	eax, DWORD PTR _pBlock$[ebp]
	je	SHORT $LN8@EnumerateB

; 145  : 				dwFlags |= DAHEAPFLAG_CORRUPTED_BLOCK;

	mov	ecx, DWORD PTR _dwFlags$[ebp]
	or	ecx, 2
	mov	DWORD PTR _dwFlags$[ebp], ecx
$LN8@EnumerateB:

; 146  : 		}
; 147  : 
; 148  : 		// lower block check
; 149  : 		if (pBlock->getLower()->getUpper() != pBlock)

	mov	ecx, DWORD PTR _pBlock$[ebp]
	call	?getLower@BASE_BLOCK@@QAEPAU1@XZ	; BASE_BLOCK::getLower
	mov	ecx, eax
	call	?getUpper@BASE_BLOCK@@QAEPAU1@XZ	; BASE_BLOCK::getUpper
	cmp	eax, DWORD PTR _pBlock$[ebp]
	je	SHORT $LN5@EnumerateB

; 150  : 			dwFlags |= DAHEAPFLAG_CORRUPTED_BLOCK;

	mov	edx, DWORD PTR _dwFlags$[ebp]
	or	edx, 2
	mov	DWORD PTR _dwFlags$[ebp], edx
$LN5@EnumerateB:

; 151  : 		// upper block check
; 152  : 		if (pBlock->getUpper() && pBlock->getUpper()->getLower() != pBlock)

	mov	ecx, DWORD PTR _pBlock$[ebp]
	call	?getUpper@BASE_BLOCK@@QAEPAU1@XZ	; BASE_BLOCK::getUpper
	test	eax, eax
	je	SHORT $LN4@EnumerateB
	mov	ecx, DWORD PTR _pBlock$[ebp]
	call	?getUpper@BASE_BLOCK@@QAEPAU1@XZ	; BASE_BLOCK::getUpper
	mov	ecx, eax
	call	?getLower@BASE_BLOCK@@QAEPAU1@XZ	; BASE_BLOCK::getLower
	cmp	eax, DWORD PTR _pBlock$[ebp]
	je	SHORT $LN4@EnumerateB

; 153  : 			dwFlags |= DAHEAPFLAG_CORRUPTED_BLOCK;

	mov	eax, DWORD PTR _dwFlags$[ebp]
	or	eax, 2
	mov	DWORD PTR _dwFlags$[ebp], eax
$LN4@EnumerateB:

; 154  : 
; 155  : 		if (proc)

	cmp	DWORD PTR _proc$[ebp], 0
	je	SHORT $LN3@EnumerateB

; 156  : 			result = proc(this, ((char *)pBlock)+dwBaseBlockSize, dwFlags, context);

	mov	ecx, DWORD PTR _context$[ebp]
	push	ecx
	mov	edx, DWORD PTR _dwFlags$[ebp]
	push	edx
	mov	eax, DWORD PTR _this$[ebp]
	mov	ecx, DWORD PTR _pBlock$[ebp]
	add	ecx, DWORD PTR [eax+24]
	push	ecx
	mov	edx, DWORD PTR _this$[ebp]
	push	edx
	call	DWORD PTR _proc$[ebp]
	mov	DWORD PTR _result$[ebp], eax
$LN3@EnumerateB:

; 157  : 
; 158  : 		if (dwFlags & DAHEAPFLAG_CORRUPTED_BLOCK)

	mov	eax, DWORD PTR _dwFlags$[ebp]
	and	eax, 2
	je	SHORT $LN2@EnumerateB

; 159  : 			result=0;

	mov	DWORD PTR _result$[ebp], 0

; 160  : 		else

	jmp	SHORT $LN1@EnumerateB
$LN2@EnumerateB:

; 161  : 			pBlock = (FREE_BLOCK *) pBlock->getLower();

	mov	ecx, DWORD PTR _pBlock$[ebp]
	call	?getLower@BASE_BLOCK@@QAEPAU1@XZ	; BASE_BLOCK::getLower
	mov	DWORD PTR _pBlock$[ebp], eax
$LN1@EnumerateB:

; 162  : 	}

	jmp	$LN10@EnumerateB
$LN9@EnumerateB:

; 163  : 	
; 164  : 	return result;

	mov	eax, DWORD PTR _result$[ebp]

; 165  : }

	mov	esp, ebp
	pop	ebp
	ret	12					; 0000000cH
?EnumerateBlocks@HeapInstance@@UAGJP6GJPAUIHeap@@PAXK1@Z1@Z ENDP ; HeapInstance::EnumerateBlocks
; Function compile flags: /Odtp
; File m:\archive\conquest\code\libs\src\dacom\baseheap.h
_TEXT	ENDS
;	COMDAT ?isAllocated@BASE_BLOCK@@QAEHXZ
_TEXT	SEGMENT
_this$ = -4						; size = 4
?isAllocated@BASE_BLOCK@@QAEHXZ PROC			; BASE_BLOCK::isAllocated, COMDAT
; _this$ = ecx

; 87   : {

	push	ebp
	mov	ebp, esp
	push	ecx
	mov	DWORD PTR _this$[ebp], ecx

; 88   : 	return (dwSize & 1);

	mov	eax, DWORD PTR _this$[ebp]
	mov	eax, DWORD PTR [eax]
	and	eax, 1

; 89   : }

	mov	esp, ebp
	pop	ebp
	ret	0
?isAllocated@BASE_BLOCK@@QAEHXZ ENDP			; BASE_BLOCK::isAllocated
; Function compile flags: /Odtp
_TEXT	ENDS
;	COMDAT ?getPrev@FREE_BLOCK@@QAEPAU1@XZ
_TEXT	SEGMENT
_this$ = -4						; size = 4
?getPrev@FREE_BLOCK@@QAEPAU1@XZ PROC			; FREE_BLOCK::getPrev, COMDAT
; _this$ = ecx

; 92   : {

	push	ebp
	mov	ebp, esp
	push	ecx
	mov	DWORD PTR _this$[ebp], ecx

; 93   : 	return pPrev;

	mov	eax, DWORD PTR _this$[ebp]
	mov	eax, DWORD PTR [eax+8]

; 94   : }

	mov	esp, ebp
	pop	ebp
	ret	0
?getPrev@FREE_BLOCK@@QAEPAU1@XZ ENDP			; FREE_BLOCK::getPrev
; Function compile flags: /Odtp
_TEXT	ENDS
;	COMDAT ?getNext@FREE_BLOCK@@QAEPAU1@XZ
_TEXT	SEGMENT
_this$ = -4						; size = 4
?getNext@FREE_BLOCK@@QAEPAU1@XZ PROC			; FREE_BLOCK::getNext, COMDAT
; _this$ = ecx

; 97   : {

	push	ebp
	mov	ebp, esp
	push	ecx
	mov	DWORD PTR _this$[ebp], ecx

; 98   : 	return pNext;

	mov	eax, DWORD PTR _this$[ebp]
	mov	eax, DWORD PTR [eax+12]

; 99   : }

	mov	esp, ebp
	pop	ebp
	ret	0
?getNext@FREE_BLOCK@@QAEPAU1@XZ ENDP			; FREE_BLOCK::getNext
_TEXT	ENDS
PUBLIC	?GetBlockSize@HeapInstance@@UAGKPAX@Z		; HeapInstance::GetBlockSize
; Function compile flags: /Odtp
; File m:\archive\conquest\code\libs\src\dacom\heapinst.cpp
_TEXT	SEGMENT
_result$ = -8						; size = 4
_pBlock$ = -4						; size = 4
_this$ = 8						; size = 4
_allocatedBlock$ = 12					; size = 4
?GetBlockSize@HeapInstance@@UAGKPAX@Z PROC		; HeapInstance::GetBlockSize

; 169  : {

	push	ebp
	mov	ebp, esp
	sub	esp, 8

; 170  : 	U32 result;
; 171  : 	
; 172  : 	BASE_BLOCK *pBlock;
; 173  : 
; 174  : 	if ((pBlock = verifyBlock(allocatedBlock)) == 0)

	mov	eax, DWORD PTR _allocatedBlock$[ebp]
	push	eax
	mov	ecx, DWORD PTR _this$[ebp]
	call	?verifyBlock@HeapInstance@@QAEPAUBASE_BLOCK@@PAX@Z ; HeapInstance::verifyBlock
	mov	DWORD PTR _pBlock$[ebp], eax
	cmp	DWORD PTR _pBlock$[ebp], 0
	jne	SHORT $LN2@GetBlockSi

; 175  : 		result = 0;

	mov	DWORD PTR _result$[ebp], 0

; 176  : 	else

	jmp	SHORT $LN1@GetBlockSi
$LN2@GetBlockSi:

; 177  : 		result = (pBlock->dwSize - dwBaseBlockSize) & ~1;

	mov	ecx, DWORD PTR _pBlock$[ebp]
	mov	edx, DWORD PTR _this$[ebp]
	mov	eax, DWORD PTR [ecx]
	sub	eax, DWORD PTR [edx+24]
	and	eax, -2					; fffffffeH
	mov	DWORD PTR _result$[ebp], eax
$LN1@GetBlockSi:

; 178  : 
; 179  : 	return result;

	mov	eax, DWORD PTR _result$[ebp]

; 180  : }

	mov	esp, ebp
	pop	ebp
	ret	8
?GetBlockSize@HeapInstance@@UAGKPAX@Z ENDP		; HeapInstance::GetBlockSize
_TEXT	ENDS
PUBLIC	?getMsg@BASE_BLOCK@@QAEPBDXZ			; BASE_BLOCK::getMsg
PUBLIC	?GetBlockMessage@HeapInstance@@UAGPBDPAX@Z	; HeapInstance::GetBlockMessage
; Function compile flags: /Odtp
_TEXT	SEGMENT
_pBlock$ = -4						; size = 4
_this$ = 8						; size = 4
_allocatedBlock$ = 12					; size = 4
?GetBlockMessage@HeapInstance@@UAGPBDPAX@Z PROC		; HeapInstance::GetBlockMessage

; 184  : {

	push	ebp
	mov	ebp, esp
	push	ecx

; 185  : 	BASE_BLOCK *pBlock;
; 186  : 
; 187  : 	if ((pBlock = verifyBlock(allocatedBlock)) != 0)

	mov	eax, DWORD PTR _allocatedBlock$[ebp]
	push	eax
	mov	ecx, DWORD PTR _this$[ebp]
	call	?verifyBlock@HeapInstance@@QAEPAUBASE_BLOCK@@PAX@Z ; HeapInstance::verifyBlock
	mov	DWORD PTR _pBlock$[ebp], eax
	cmp	DWORD PTR _pBlock$[ebp], 0
	je	SHORT $LN2@GetBlockMe

; 188  : 	{
; 189  : 		if (pBlock->isAllocated() && (dwFlags & DAHEAPFLAG_NOMSGS) == 0)

	mov	ecx, DWORD PTR _pBlock$[ebp]
	call	?isAllocated@BASE_BLOCK@@QAEHXZ		; BASE_BLOCK::isAllocated
	test	eax, eax
	je	SHORT $LN2@GetBlockMe
	mov	ecx, DWORD PTR _this$[ebp]
	mov	edx, DWORD PTR [ecx+12]
	and	edx, 16					; 00000010H
	jne	SHORT $LN2@GetBlockMe

; 190  : 			return pBlock->getMsg();

	mov	ecx, DWORD PTR _pBlock$[ebp]
	call	?getMsg@BASE_BLOCK@@QAEPBDXZ		; BASE_BLOCK::getMsg
	jmp	SHORT $LN3@GetBlockMe
$LN2@GetBlockMe:

; 191  : 	}
; 192  : 	return 0;

	xor	eax, eax
$LN3@GetBlockMe:

; 193  : }

	mov	esp, ebp
	pop	ebp
	ret	8
?GetBlockMessage@HeapInstance@@UAGPBDPAX@Z ENDP		; HeapInstance::GetBlockMessage
; Function compile flags: /Odtp
; File m:\archive\conquest\code\libs\src\dacom\baseheap.h
_TEXT	ENDS
;	COMDAT ?getMsg@BASE_BLOCK@@QAEPBDXZ
_TEXT	SEGMENT
_this$ = -4						; size = 4
?getMsg@BASE_BLOCK@@QAEPBDXZ PROC			; BASE_BLOCK::getMsg, COMDAT
; _this$ = ecx

; 48   : 	{

	push	ebp
	mov	ebp, esp
	push	ecx
	mov	DWORD PTR _this$[ebp], ecx

; 49   : 		return pMsg;

	mov	eax, DWORD PTR _this$[ebp]
	mov	eax, DWORD PTR [eax+8]

; 50   : 	}

	mov	esp, ebp
	pop	ebp
	ret	0
?getMsg@BASE_BLOCK@@QAEPBDXZ ENDP			; BASE_BLOCK::getMsg
_TEXT	ENDS
PUBLIC	?SetBlockMessage@HeapInstance@@UAGJPAXPBD@Z	; HeapInstance::SetBlockMessage
; Function compile flags: /Odtp
; File m:\archive\conquest\code\libs\src\dacom\heapinst.cpp
_TEXT	SEGMENT
_pBlock$ = -4						; size = 4
_this$ = 8						; size = 4
_allocatedBlock$ = 12					; size = 4
_msg$ = 16						; size = 4
?SetBlockMessage@HeapInstance@@UAGJPAXPBD@Z PROC	; HeapInstance::SetBlockMessage

; 197  : {

	push	ebp
	mov	ebp, esp
	push	ecx

; 198  : 	BASE_BLOCK *pBlock;
; 199  : 
; 200  : 	if ((pBlock = verifyBlock(allocatedBlock)) != 0)

	mov	eax, DWORD PTR _allocatedBlock$[ebp]
	push	eax
	mov	ecx, DWORD PTR _this$[ebp]
	call	?verifyBlock@HeapInstance@@QAEPAUBASE_BLOCK@@PAX@Z ; HeapInstance::verifyBlock
	mov	DWORD PTR _pBlock$[ebp], eax
	cmp	DWORD PTR _pBlock$[ebp], 0
	je	SHORT $LN2@SetBlockMe

; 201  : 	{
; 202  : 		if (pBlock->isAllocated() && (dwFlags & DAHEAPFLAG_NOMSGS) == 0)

	mov	ecx, DWORD PTR _pBlock$[ebp]
	call	?isAllocated@BASE_BLOCK@@QAEHXZ		; BASE_BLOCK::isAllocated
	test	eax, eax
	je	SHORT $LN1@SetBlockMe
	mov	ecx, DWORD PTR _this$[ebp]
	mov	edx, DWORD PTR [ecx+12]
	and	edx, 16					; 00000010H
	jne	SHORT $LN1@SetBlockMe

; 203  : 			pBlock->setMsg(msg);

	mov	eax, DWORD PTR _msg$[ebp]
	push	eax
	mov	ecx, DWORD PTR _pBlock$[ebp]
	call	?setMsg@BASE_BLOCK@@QAEXPBD@Z		; BASE_BLOCK::setMsg
$LN1@SetBlockMe:

; 204  : 		return 1;

	mov	eax, 1
	jmp	SHORT $LN3@SetBlockMe
$LN2@SetBlockMe:

; 205  : 	}
; 206  : 	return 0;

	xor	eax, eax
$LN3@SetBlockMe:

; 207  : }

	mov	esp, ebp
	pop	ebp
	ret	12					; 0000000cH
?SetBlockMessage@HeapInstance@@UAGJPAXPBD@Z ENDP	; HeapInstance::SetBlockMessage
_TEXT	ENDS
PUBLIC	?DidAlloc@HeapInstance@@UAGJPAX@Z		; HeapInstance::DidAlloc
; Function compile flags: /Odtp
_TEXT	SEGMENT
_this$ = 8						; size = 4
_allocatedBlock$ = 12					; size = 4
?DidAlloc@HeapInstance@@UAGJPAX@Z PROC			; HeapInstance::DidAlloc

; 211  : {

	push	ebp
	mov	ebp, esp

; 212  : 	if (((DWORD)(pHeapBase) > (DWORD)allocatedBlock) ||
; 213  : 			((DWORD)(pHeapBase) + dwHeapSize <= (DWORD)allocatedBlock))

	mov	eax, DWORD PTR _this$[ebp]
	mov	ecx, DWORD PTR [eax+28]
	cmp	ecx, DWORD PTR _allocatedBlock$[ebp]
	ja	SHORT $LN1@DidAlloc
	mov	edx, DWORD PTR _this$[ebp]
	mov	eax, DWORD PTR [edx+28]
	mov	ecx, DWORD PTR _this$[ebp]
	add	eax, DWORD PTR [ecx+32]
	cmp	eax, DWORD PTR _allocatedBlock$[ebp]
	ja	SHORT $LN2@DidAlloc
$LN1@DidAlloc:

; 214  : 	{
; 215  : 		return 0;

	xor	eax, eax
	jmp	SHORT $LN3@DidAlloc
$LN2@DidAlloc:

; 216  : 	}
; 217  : 	return 1;

	mov	eax, 1
$LN3@DidAlloc:

; 218  : }

	pop	ebp
	ret	8
?DidAlloc@HeapInstance@@UAGJPAX@Z ENDP			; HeapInstance::DidAlloc
_TEXT	ENDS
PUBLIC	?GetAvailableMemory@HeapInstance@@UAGKXZ	; HeapInstance::GetAvailableMemory
; Function compile flags: /Odtp
_TEXT	SEGMENT
_result$ = -16						; size = 4
_pBlock$ = -12						; size = 4
_pStart$ = -8						; size = 4
_loops$ = -4						; size = 4
_this$ = 8						; size = 4
?GetAvailableMemory@HeapInstance@@UAGKXZ PROC		; HeapInstance::GetAvailableMemory

; 222  : {

	push	ebp
	mov	ebp, esp
	sub	esp, 16					; 00000010H

; 223  : 	U32 result=0;

	mov	DWORD PTR _result$[ebp], 0

; 224  : 	S32 loops=10000;

	mov	DWORD PTR _loops$[ebp], 10000		; 00002710H

; 225  : 	FREE_BLOCK *pBlock = pFirstFreeBlock;

	mov	eax, DWORD PTR _this$[ebp]
	mov	ecx, DWORD PTR [eax+20]
	mov	DWORD PTR _pBlock$[ebp], ecx

; 226  : 	FREE_BLOCK *pStart = pFirstFreeBlock;

	mov	edx, DWORD PTR _this$[ebp]
	mov	eax, DWORD PTR [edx+20]
	mov	DWORD PTR _pStart$[ebp], eax

; 227  : 
; 228  : 	if (pBlock)

	cmp	DWORD PTR _pBlock$[ebp], 0
	je	SHORT $LN5@GetAvailab
$LN4@GetAvailab:

; 229  : 	do
; 230  : 	{
; 231  : 		pBlock = pBlock->getNext();

	mov	ecx, DWORD PTR _pBlock$[ebp]
	call	?getNext@FREE_BLOCK@@QAEPAU1@XZ		; FREE_BLOCK::getNext
	mov	DWORD PTR _pBlock$[ebp], eax

; 232  : 		result += pBlock->dwSize - dwBaseBlockSize;

	mov	ecx, DWORD PTR _pBlock$[ebp]
	mov	edx, DWORD PTR _this$[ebp]
	mov	eax, DWORD PTR [ecx]
	sub	eax, DWORD PTR [edx+24]
	add	eax, DWORD PTR _result$[ebp]
	mov	DWORD PTR _result$[ebp], eax

; 233  : 		if (--loops <= 0)

	mov	ecx, DWORD PTR _loops$[ebp]
	sub	ecx, 1
	mov	DWORD PTR _loops$[ebp], ecx
	cmp	DWORD PTR _loops$[ebp], 0
	jg	SHORT $LN3@GetAvailab

; 234  : 			break;

	jmp	SHORT $LN5@GetAvailab
$LN3@GetAvailab:

; 235  : 
; 236  : 	} while (pBlock != pStart);

	mov	edx, DWORD PTR _pBlock$[ebp]
	cmp	edx, DWORD PTR _pStart$[ebp]
	jne	SHORT $LN4@GetAvailab
$LN5@GetAvailab:

; 237  : 
; 238  : 	return result;

	mov	eax, DWORD PTR _result$[ebp]

; 239  : }

	mov	esp, ebp
	pop	ebp
	ret	4
?GetAvailableMemory@HeapInstance@@UAGKXZ ENDP		; HeapInstance::GetAvailableMemory
_TEXT	ENDS
PUBLIC	?GetLargestBlock@HeapInstance@@UAGKXZ		; HeapInstance::GetLargestBlock
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv128 = -20						; size = 4
_pStart$63611 = -16					; size = 4
_loops$63612 = -12					; size = 4
_result$ = -8						; size = 4
_pBlock$ = -4						; size = 4
_this$ = 8						; size = 4
?GetLargestBlock@HeapInstance@@UAGKXZ PROC		; HeapInstance::GetLargestBlock

; 243  : {

	push	ebp
	mov	ebp, esp
	sub	esp, 20					; 00000014H

; 244  : 	U32 result=0;

	mov	DWORD PTR _result$[ebp], 0

; 245  : 	FREE_BLOCK *pBlock = pFirstFreeBlock;

	mov	eax, DWORD PTR _this$[ebp]
	mov	ecx, DWORD PTR [eax+20]
	mov	DWORD PTR _pBlock$[ebp], ecx

; 246  : 	
; 247  : 	if (pBlock)

	cmp	DWORD PTR _pBlock$[ebp], 0
	je	$LN7@GetLargest

; 248  : 	{
; 249  : 		if ((dwFlags & DAHEAPFLAG_NOBESTFIT) == 0)

	mov	edx, DWORD PTR _this$[ebp]
	mov	eax, DWORD PTR [edx+12]
	and	eax, 2
	jne	SHORT $LN6@GetLargest

; 250  : 			result = pBlock->getPrev()->dwSize - dwBaseBlockSize;

	mov	ecx, DWORD PTR _pBlock$[ebp]
	call	?getPrev@FREE_BLOCK@@QAEPAU1@XZ		; FREE_BLOCK::getPrev
	mov	ecx, DWORD PTR _this$[ebp]
	mov	edx, DWORD PTR [eax]
	sub	edx, DWORD PTR [ecx+24]
	mov	DWORD PTR _result$[ebp], edx

; 251  : 		else

	jmp	SHORT $LN7@GetLargest
$LN6@GetLargest:

; 252  : 		{
; 253  : 			FREE_BLOCK *pStart = pFirstFreeBlock;

	mov	eax, DWORD PTR _this$[ebp]
	mov	ecx, DWORD PTR [eax+20]
	mov	DWORD PTR _pStart$63611[ebp], ecx

; 254  : 			S32 loops=10000;

	mov	DWORD PTR _loops$63612[ebp], 10000	; 00002710H
$LN4@GetLargest:

; 255  : 			
; 256  : 			do
; 257  : 			{
; 258  : 				pBlock = pBlock->getNext();

	mov	ecx, DWORD PTR _pBlock$[ebp]
	call	?getNext@FREE_BLOCK@@QAEPAU1@XZ		; FREE_BLOCK::getNext
	mov	DWORD PTR _pBlock$[ebp], eax

; 259  : 				result = __max(result, pBlock->dwSize);

	mov	edx, DWORD PTR _pBlock$[ebp]
	mov	eax, DWORD PTR _result$[ebp]
	cmp	eax, DWORD PTR [edx]
	jbe	SHORT $LN10@GetLargest
	mov	ecx, DWORD PTR _result$[ebp]
	mov	DWORD PTR tv128[ebp], ecx
	jmp	SHORT $LN11@GetLargest
$LN10@GetLargest:
	mov	edx, DWORD PTR _pBlock$[ebp]
	mov	eax, DWORD PTR [edx]
	mov	DWORD PTR tv128[ebp], eax
$LN11@GetLargest:
	mov	ecx, DWORD PTR tv128[ebp]
	mov	DWORD PTR _result$[ebp], ecx

; 260  : 				if (--loops <= 0)

	mov	edx, DWORD PTR _loops$63612[ebp]
	sub	edx, 1
	mov	DWORD PTR _loops$63612[ebp], edx
	cmp	DWORD PTR _loops$63612[ebp], 0
	jg	SHORT $LN3@GetLargest

; 261  : 					break;

	jmp	SHORT $LN2@GetLargest
$LN3@GetLargest:

; 262  : 
; 263  : 			} while (pBlock != pStart);

	mov	eax, DWORD PTR _pBlock$[ebp]
	cmp	eax, DWORD PTR _pStart$63611[ebp]
	jne	SHORT $LN4@GetLargest
$LN2@GetLargest:

; 264  : 
; 265  : 			result -= dwBaseBlockSize;

	mov	ecx, DWORD PTR _this$[ebp]
	mov	edx, DWORD PTR _result$[ebp]
	sub	edx, DWORD PTR [ecx+24]
	mov	DWORD PTR _result$[ebp], edx
$LN7@GetLargest:

; 266  : 		}
; 267  : 	}
; 268  : 	
; 269  : 	return result;

	mov	eax, DWORD PTR _result$[ebp]

; 270  : }

	mov	esp, ebp
	pop	ebp
	ret	4
?GetLargestBlock@HeapInstance@@UAGKXZ ENDP		; HeapInstance::GetLargestBlock
_TEXT	ENDS
PUBLIC	?GetHeapSize@HeapInstance@@UAGKXZ		; HeapInstance::GetHeapSize
; Function compile flags: /Odtp
_TEXT	SEGMENT
_this$ = 8						; size = 4
?GetHeapSize@HeapInstance@@UAGKXZ PROC			; HeapInstance::GetHeapSize

; 274  : {

	push	ebp
	mov	ebp, esp

; 275  : 	return dwHeapSize - (dwBaseBlockSize*3) - sizeof(HeapInstance);

	mov	eax, DWORD PTR _this$[ebp]
	mov	ecx, DWORD PTR [eax+24]
	imul	ecx, 3
	mov	edx, DWORD PTR _this$[ebp]
	mov	eax, DWORD PTR [edx+32]
	sub	eax, ecx
	sub	eax, 64					; 00000040H

; 276  : }

	pop	ebp
	ret	4
?GetHeapSize@HeapInstance@@UAGKXZ ENDP			; HeapInstance::GetHeapSize
_TEXT	ENDS
PUBLIC	?SetErrorHandler@HeapInstance@@UAGP6AHUErrorCode@@PBDZZP6AH01ZZ@Z ; HeapInstance::SetErrorHandler
; Function compile flags: /Odtp
_TEXT	SEGMENT
_result$ = -4						; size = 4
_this$ = 8						; size = 4
_proc$ = 12						; size = 4
?SetErrorHandler@HeapInstance@@UAGP6AHUErrorCode@@PBDZZP6AH01ZZ@Z PROC ; HeapInstance::SetErrorHandler

; 280  : {

	push	ebp
	mov	ebp, esp
	push	ecx

; 281  : 	DA_ERROR_HANDLER result = pErrorHandler;

	mov	eax, DWORD PTR _this$[ebp]
	mov	ecx, DWORD PTR [eax+8]
	mov	DWORD PTR _result$[ebp], ecx

; 282  : 
; 283  : 	pErrorHandler = proc;

	mov	edx, DWORD PTR _this$[ebp]
	mov	eax, DWORD PTR _proc$[ebp]
	mov	DWORD PTR [edx+8], eax

; 284  :  	
; 285  : 	return result;

	mov	eax, DWORD PTR _result$[ebp]

; 286  : }

	mov	esp, ebp
	pop	ebp
	ret	8
?SetErrorHandler@HeapInstance@@UAGP6AHUErrorCode@@PBDZZP6AH01ZZ@Z ENDP ; HeapInstance::SetErrorHandler
_TEXT	ENDS
PUBLIC	?GetErrorHandler@HeapInstance@@UAGP6AHUErrorCode@@PBDZZXZ ; HeapInstance::GetErrorHandler
; Function compile flags: /Odtp
_TEXT	SEGMENT
_this$ = 8						; size = 4
?GetErrorHandler@HeapInstance@@UAGP6AHUErrorCode@@PBDZZXZ PROC ; HeapInstance::GetErrorHandler

; 290  : {

	push	ebp
	mov	ebp, esp

; 291  : 	return pErrorHandler;

	mov	eax, DWORD PTR _this$[ebp]
	mov	eax, DWORD PTR [eax+8]

; 292  : }

	pop	ebp
	ret	4
?GetErrorHandler@HeapInstance@@UAGP6AHUErrorCode@@PBDZZXZ ENDP ; HeapInstance::GetErrorHandler
_TEXT	ENDS
PUBLIC	??0ErrorCode@@QAE@W4ErrorKind@@W4SeverityLevel@@@Z ; ErrorCode::ErrorCode
PUBLIC	??_C@_0CE@JBJGEEGD@?$CFs?$CI?$CFd?$CJ?5?3?5FATAL?3Assertion?5failed?3@ ; `string'
PUBLIC	??_C@_0P@KGMHEPGH@?4?2HeapInst?4cpp?$AA@	; `string'
PUBLIC	??_C@_06JMELBMAE@lpDesc?$AA@			; `string'
PUBLIC	?initHeap@HeapInstance@@QAE?AW4GENRESULT@@PAUDAHEAPDESC@@@Z ; HeapInstance::initHeap
EXTRN	_memset:PROC
EXTRN	__imp__InitializeCriticalSection@4:PROC
EXTRN	__imp__VirtualAlloc@16:PROC
EXTRN	_FDUMP:DWORD
;	COMDAT ??_C@_0CE@JBJGEEGD@?$CFs?$CI?$CFd?$CJ?5?3?5FATAL?3Assertion?5failed?3@
CONST	SEGMENT
??_C@_0CE@JBJGEEGD@?$CFs?$CI?$CFd?$CJ?5?3?5FATAL?3Assertion?5failed?3@ DB '%'
	DB	's(%d) : FATAL:Assertion failed: %s', 00H	; `string'
CONST	ENDS
;	COMDAT ??_C@_0P@KGMHEPGH@?4?2HeapInst?4cpp?$AA@
CONST	SEGMENT
??_C@_0P@KGMHEPGH@?4?2HeapInst?4cpp?$AA@ DB '.\HeapInst.cpp', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_06JMELBMAE@lpDesc?$AA@
CONST	SEGMENT
??_C@_06JMELBMAE@lpDesc?$AA@ DB 'lpDesc', 00H		; `string'
; Function compile flags: /Odtp
CONST	ENDS
_TEXT	SEGMENT
tv77 = -24						; size = 4
_this$ = -20						; size = 4
$T63909 = -16						; size = 4
_pEnding$ = -12						; size = 4
_pStart$ = -8						; size = 4
_dwSize$ = -4						; size = 4
_lpDesc$ = 8						; size = 4
?initHeap@HeapInstance@@QAE?AW4GENRESULT@@PAUDAHEAPDESC@@@Z PROC ; HeapInstance::initHeap
; _this$ = ecx

; 296  : {

	push	ebp
	mov	ebp, esp
	sub	esp, 24					; 00000018H
	mov	DWORD PTR _this$[ebp], ecx

; 297  : 	BASE_BLOCK *pEnding;
; 298  : 	FREE_BLOCK *pStart;
; 299  : 	DWORD dwSize;
; 300  : 
; 301  : 	ASSERT(lpDesc);

	cmp	DWORD PTR _lpDesc$[ebp], 0
	jne	SHORT $LN5@initHeap
	push	OFFSET ??_C@_06JMELBMAE@lpDesc?$AA@
	push	301					; 0000012dH
	push	OFFSET ??_C@_0P@KGMHEPGH@?4?2HeapInst?4cpp?$AA@
	push	OFFSET ??_C@_0CE@JBJGEEGD@?$CFs?$CI?$CFd?$CJ?5?3?5FATAL?3Assertion?5failed?3@
	push	0
	push	65540					; 00010004H
	lea	ecx, DWORD PTR $T63909[ebp]
	call	??0ErrorCode@@QAE@W4ErrorKind@@W4SeverityLevel@@@Z ; ErrorCode::ErrorCode
	mov	eax, DWORD PTR [eax]
	push	eax
	call	DWORD PTR _FDUMP
	add	esp, 20					; 00000014H
$LN5@initHeap:

; 302  : 
; 303  : 	dwSize = __max((sizeof(FREE_BLOCK)*4 + sizeof(HeapInstance)), lpDesc->heapSize);

	mov	ecx, DWORD PTR _lpDesc$[ebp]
	cmp	DWORD PTR [ecx+8], 128			; 00000080H
	jae	SHORT $LN8@initHeap
	mov	DWORD PTR tv77[ebp], 128		; 00000080H
	jmp	SHORT $LN9@initHeap
$LN8@initHeap:
	mov	edx, DWORD PTR _lpDesc$[ebp]
	mov	eax, DWORD PTR [edx+8]
	mov	DWORD PTR tv77[ebp], eax
$LN9@initHeap:
	mov	ecx, DWORD PTR tv77[ebp]
	mov	DWORD PTR _dwSize$[ebp], ecx

; 304  : 	dwSize = (dwSize+0xFFF)&~0xFFF;

	mov	edx, DWORD PTR _dwSize$[ebp]
	add	edx, 4095				; 00000fffH
	and	edx, -4096				; fffff000H
	mov	DWORD PTR _dwSize$[ebp], edx

; 305  : 
; 306  : 	if ((long)lpDesc->growSize <= 0)

	mov	eax, DWORD PTR _lpDesc$[ebp]
	cmp	DWORD PTR [eax+16], 0
	jg	SHORT $LN4@initHeap

; 307  : 	{
; 308  : 		if (lpDesc->flags & DAHEAPFLAG_GROWHEAP)

	mov	ecx, DWORD PTR _lpDesc$[ebp]
	mov	edx, DWORD PTR [ecx+12]
	and	edx, 32					; 00000020H
	je	SHORT $LN4@initHeap

; 309  : 			return GR_INVALID_PARMS;

	mov	eax, -2					; fffffffeH
	jmp	$LN6@initHeap
$LN4@initHeap:

; 310  : 	}
; 311  : 	
; 312  : 	if ((pHeapBase = VirtualAlloc(0, dwSize, MEM_COMMIT, PAGE_READWRITE)) == 0)

	push	4
	push	4096					; 00001000H
	mov	eax, DWORD PTR _dwSize$[ebp]
	push	eax
	push	0
	call	DWORD PTR __imp__VirtualAlloc@16
	mov	ecx, DWORD PTR _this$[ebp]
	mov	DWORD PTR [ecx+28], eax
	mov	edx, DWORD PTR _this$[ebp]
	cmp	DWORD PTR [edx+28], 0
	jne	SHORT $LN2@initHeap

; 313  : 	{
; 314  : 		doError(DAHEAP_VALLOC_FAILED, dwSize);

	push	0
	mov	eax, DWORD PTR _dwSize$[ebp]
	push	eax
	push	7
	mov	ecx, DWORD PTR _this$[ebp]
	call	?doError@BaseHeap@@QAEJKKK@Z		; BaseHeap::doError

; 315  : 		return GR_OUT_OF_MEMORY;

	mov	eax, -4					; fffffffcH
	jmp	$LN6@initHeap
$LN2@initHeap:

; 316  : 	}
; 317  : 
; 318  : 	dwHeapSize = dwSize;

	mov	ecx, DWORD PTR _this$[ebp]
	mov	edx, DWORD PTR _dwSize$[ebp]
	mov	DWORD PTR [ecx+32], edx

; 319  : 	dwFlags = lpDesc->flags;

	mov	eax, DWORD PTR _this$[ebp]
	mov	ecx, DWORD PTR _lpDesc$[ebp]
	mov	edx, DWORD PTR [ecx+12]
	mov	DWORD PTR [eax+12], edx

; 320  : 	dwBaseBlockSize = (dwFlags & DAHEAPFLAG_NOMSGS) ? 8 : 16;

	mov	eax, DWORD PTR _this$[ebp]
	mov	ecx, DWORD PTR [eax+12]
	and	ecx, 16					; 00000010H
	neg	ecx
	sbb	ecx, ecx
	and	ecx, -8					; fffffff8H
	add	ecx, 16					; 00000010H
	mov	edx, DWORD PTR _this$[ebp]
	mov	DWORD PTR [edx+24], ecx

; 321  : 	dwGrowSize = lpDesc->growSize;

	mov	eax, DWORD PTR _this$[ebp]
	mov	ecx, DWORD PTR _lpDesc$[ebp]
	mov	edx, DWORD PTR [ecx+16]
	mov	DWORD PTR [eax+36], edx

; 322  : 
; 323  : 	if (dwFlags & DAHEAPFLAG_MULTITHREADED)

	mov	eax, DWORD PTR _this$[ebp]
	mov	ecx, DWORD PTR [eax+12]
	and	ecx, 1
	je	SHORT $LN1@initHeap

; 324  : 		InitializeCriticalSection(&criticalSection);	

	mov	edx, DWORD PTR _this$[ebp]
	add	edx, 40					; 00000028H
	push	edx
	call	DWORD PTR __imp__InitializeCriticalSection@4
$LN1@initHeap:

; 325  : 
; 326  : 	pStart = (FREE_BLOCK *) pHeapBase;

	mov	eax, DWORD PTR _this$[ebp]
	mov	ecx, DWORD PTR [eax+28]
	mov	DWORD PTR _pStart$[ebp], ecx

; 327  : 	pEnding = (BASE_BLOCK *) (((char *)pHeapBase) + dwHeapSize - dwBaseBlockSize);

	mov	edx, DWORD PTR _this$[ebp]
	mov	eax, DWORD PTR [edx+28]
	mov	ecx, DWORD PTR _this$[ebp]
	add	eax, DWORD PTR [ecx+32]
	mov	edx, DWORD PTR _this$[ebp]
	sub	eax, DWORD PTR [edx+24]
	mov	DWORD PTR _pEnding$[ebp], eax

; 328  : 
; 329  : 	//----------------------------------------
; 330  : 	// Initialize heap
; 331  : 	//----------------------------------------
; 332  : 
; 333  : 	pStart->dwSize = (DWORD)pEnding - (DWORD)pStart;

	mov	eax, DWORD PTR _pEnding$[ebp]
	sub	eax, DWORD PTR _pStart$[ebp]
	mov	ecx, DWORD PTR _pStart$[ebp]
	mov	DWORD PTR [ecx], eax

; 334  : 	pStart->pUpper = 0;		// first block in list

	mov	edx, DWORD PTR _pStart$[ebp]
	mov	DWORD PTR [edx+4], 0

; 335  : 	pStart->pPrev = 
; 336  : 	pStart->pNext = pStart;

	mov	eax, DWORD PTR _pStart$[ebp]
	mov	ecx, DWORD PTR _pStart$[ebp]
	mov	DWORD PTR [eax+12], ecx
	mov	edx, DWORD PTR _pStart$[ebp]
	mov	eax, DWORD PTR _pStart$[ebp]
	mov	DWORD PTR [edx+8], eax

; 337  : 	
; 338  : 	pFirstFreeBlock = pStart;

	mov	ecx, DWORD PTR _this$[ebp]
	mov	edx, DWORD PTR _pStart$[ebp]
	mov	DWORD PTR [ecx+20], edx

; 339  : 
; 340  : 	pEnding->dwSize = 1;		// mark as the last block in the heap

	mov	eax, DWORD PTR _pEnding$[ebp]
	mov	DWORD PTR [eax], 1

; 341  : 	pEnding->pUpper = pStart;

	mov	ecx, DWORD PTR _pEnding$[ebp]
	mov	edx, DWORD PTR _pStart$[ebp]
	mov	DWORD PTR [ecx+4], edx

; 342  : 
; 343  : 	// initialize all memory to -1
; 344  : 
; 345  : 	memset(pStart+1, -1, pStart->dwSize - sizeof(FREE_BLOCK));

	mov	eax, DWORD PTR _pStart$[ebp]
	mov	ecx, DWORD PTR [eax]
	sub	ecx, 16					; 00000010H
	push	ecx
	push	-1
	mov	edx, DWORD PTR _pStart$[ebp]
	add	edx, 16					; 00000010H
	push	edx
	call	_memset
	add	esp, 12					; 0000000cH

; 346  : 
; 347  : 	return GR_OK;

	xor	eax, eax
$LN6@initHeap:

; 348  : }

	mov	esp, ebp
	pop	ebp
	ret	4
?initHeap@HeapInstance@@QAE?AW4GENRESULT@@PAUDAHEAPDESC@@@Z ENDP ; HeapInstance::initHeap
; Function compile flags: /Odtp
; File m:\archive\conquest\code\libs\include\fdump.h
_TEXT	ENDS
;	COMDAT ??0ErrorCode@@QAE@W4ErrorKind@@W4SeverityLevel@@@Z
_TEXT	SEGMENT
_this$ = -4						; size = 4
__kind$ = 8						; size = 4
__severity$ = 12					; size = 4
??0ErrorCode@@QAE@W4ErrorKind@@W4SeverityLevel@@@Z PROC	; ErrorCode::ErrorCode, COMDAT
; _this$ = ecx

; 177  : 	ErrorCode (ErrorKind _kind, SeverityLevel _severity)

	push	ebp
	mov	ebp, esp
	push	ecx
	mov	DWORD PTR _this$[ebp], ecx

; 178  : 	{
; 179  : 		severity = _severity;

	mov	eax, DWORD PTR __severity$[ebp]
	and	eax, 15					; 0000000fH
	mov	ecx, DWORD PTR _this$[ebp]
	mov	edx, DWORD PTR [ecx]
	and	edx, -16				; fffffff0H
	or	edx, eax
	mov	eax, DWORD PTR _this$[ebp]
	mov	DWORD PTR [eax], edx

; 180  : 		kind = _kind;

	mov	ecx, DWORD PTR __kind$[ebp]
	and	ecx, 268435455				; 0fffffffH
	shl	ecx, 4
	mov	edx, DWORD PTR _this$[ebp]
	mov	eax, DWORD PTR [edx]
	and	eax, 15					; 0000000fH
	or	eax, ecx
	mov	ecx, DWORD PTR _this$[ebp]
	mov	DWORD PTR [ecx], eax

; 181  : 	}

	mov	eax, DWORD PTR _this$[ebp]
	mov	esp, ebp
	pop	ebp
	ret	8
??0ErrorCode@@QAE@W4ErrorKind@@W4SeverityLevel@@@Z ENDP	; ErrorCode::ErrorCode
_TEXT	ENDS
PUBLIC	?UNLINK@HeapInstance@@QAEXPAUFREE_BLOCK@@@Z	; HeapInstance::UNLINK
PUBLIC	??_C@_06DPHEOBMB@pBlock?$AA@			; `string'
PUBLIC	?sort@HeapInstance@@QAIXPAUFREE_BLOCK@@@Z	; HeapInstance::sort
;	COMDAT ??_C@_06DPHEOBMB@pBlock?$AA@
; File m:\archive\conquest\code\libs\src\dacom\heapinst.cpp
CONST	SEGMENT
??_C@_06DPHEOBMB@pBlock?$AA@ DB 'pBlock', 00H		; `string'
; Function compile flags: /Odtp
CONST	ENDS
_TEXT	SEGMENT
_pBlock$ = -28						; size = 4
_this$ = -24						; size = 4
$T63915 = -20						; size = 4
_pFirst$ = -16						; size = 4
_esi$ = -12						; size = 4
_edi$ = -8						; size = 4
_dwSize$ = -4						; size = 4
?sort@HeapInstance@@QAIXPAUFREE_BLOCK@@@Z PROC		; HeapInstance::sort
; _this$ = ecx
; _pBlock$ = edx

; 353  : {

	push	ebp
	mov	ebp, esp
	sub	esp, 28					; 0000001cH
	mov	DWORD PTR _pBlock$[ebp], edx
	mov	DWORD PTR _this$[ebp], ecx

; 354  : 	ASSERT(pBlock);

	cmp	DWORD PTR _pBlock$[ebp], 0
	jne	SHORT $LN19@sort
	push	OFFSET ??_C@_06DPHEOBMB@pBlock?$AA@
	push	354					; 00000162H
	push	OFFSET ??_C@_0P@KGMHEPGH@?4?2HeapInst?4cpp?$AA@
	push	OFFSET ??_C@_0CE@JBJGEEGD@?$CFs?$CI?$CFd?$CJ?5?3?5FATAL?3Assertion?5failed?3@
	push	0
	push	65540					; 00010004H
	lea	ecx, DWORD PTR $T63915[ebp]
	call	??0ErrorCode@@QAE@W4ErrorKind@@W4SeverityLevel@@@Z ; ErrorCode::ErrorCode
	mov	eax, DWORD PTR [eax]
	push	eax
	call	DWORD PTR _FDUMP
	add	esp, 20					; 00000014H
$LN19@sort:

; 355  : 
; 356  : 	FREE_BLOCK *pFirst = pFirstFreeBlock, *edi, *esi;

	mov	ecx, DWORD PTR _this$[ebp]
	mov	edx, DWORD PTR [ecx+20]
	mov	DWORD PTR _pFirst$[ebp], edx

; 357  : 	DWORD dwSize = pBlock->dwSize;

	mov	eax, DWORD PTR _pBlock$[ebp]
	mov	ecx, DWORD PTR [eax]
	mov	DWORD PTR _dwSize$[ebp], ecx

; 358  : 
; 359  : 	// see if we have any work to do at all
; 360  : 
; 361  : 	edi = pBlock->getNext();

	mov	ecx, DWORD PTR _pBlock$[ebp]
	call	?getNext@FREE_BLOCK@@QAEPAU1@XZ		; FREE_BLOCK::getNext
	mov	DWORD PTR _edi$[ebp], eax

; 362  : 	if (edi == pBlock->getPrev())

	mov	ecx, DWORD PTR _pBlock$[ebp]
	call	?getPrev@FREE_BLOCK@@QAEPAU1@XZ		; FREE_BLOCK::getPrev
	cmp	DWORD PTR _edi$[ebp], eax
	jne	SHORT $LN18@sort

; 363  : 	{
; 364  : 		// one or two members in the list
; 365  : 		if (edi == pBlock)

	mov	edx, DWORD PTR _edi$[ebp]
	cmp	edx, DWORD PTR _pBlock$[ebp]
	jne	SHORT $LN17@sort

; 366  : 			return;	// only member of the list

	jmp	$LN20@sort
$LN17@sort:

; 367  : 		// assume we are the smaller block
; 368  : 		pFirstFreeBlock = pBlock;

	mov	eax, DWORD PTR _this$[ebp]
	mov	ecx, DWORD PTR _pBlock$[ebp]
	mov	DWORD PTR [eax+20], ecx

; 369  : 		if (dwSize >= edi->dwSize)

	mov	edx, DWORD PTR _edi$[ebp]
	mov	eax, DWORD PTR _dwSize$[ebp]
	cmp	eax, DWORD PTR [edx]
	jb	SHORT $LN16@sort

; 370  : 			pFirstFreeBlock = edi;		// oops! 

	mov	ecx, DWORD PTR _this$[ebp]
	mov	edx, DWORD PTR _edi$[ebp]
	mov	DWORD PTR [ecx+20], edx
$LN16@sort:

; 371  : 		return;

	jmp	$LN20@sort
$LN18@sort:

; 372  : 	}
; 373  : 
; 374  : 	// else see if we are not in the correct order
; 375  : 
; 376  : 	if (dwSize <= edi->dwSize || edi == pFirst)

	mov	eax, DWORD PTR _edi$[ebp]
	mov	ecx, DWORD PTR _dwSize$[ebp]
	cmp	ecx, DWORD PTR [eax]
	jbe	SHORT $LN14@sort
	mov	edx, DWORD PTR _edi$[ebp]
	cmp	edx, DWORD PTR _pFirst$[ebp]
	jne	SHORT $LN15@sort
$LN14@sort:

; 377  : 	{
; 378  : 		edi = pBlock->pPrev;

	mov	eax, DWORD PTR _pBlock$[ebp]
	mov	ecx, DWORD PTR [eax+8]
	mov	DWORD PTR _edi$[ebp], ecx

; 379  : 		if (dwSize >= edi->dwSize || pBlock == pFirst)

	mov	edx, DWORD PTR _edi$[ebp]
	mov	eax, DWORD PTR _dwSize$[ebp]
	cmp	eax, DWORD PTR [edx]
	jae	SHORT $LN12@sort
	mov	ecx, DWORD PTR _pBlock$[ebp]
	cmp	ecx, DWORD PTR _pFirst$[ebp]
	jne	SHORT $LN15@sort
$LN12@sort:

; 380  : 			return;

	jmp	$LN20@sort
$LN15@sort:

; 381  : 	}
; 382  : 
; 383  : 	//  else we must unlink our block, saving a pointer to lower neighbor
; 384  : 
; 385  : 	UNLINK(pBlock);

	mov	edx, DWORD PTR _pBlock$[ebp]
	push	edx
	mov	ecx, DWORD PTR _this$[ebp]
	call	?UNLINK@HeapInstance@@QAEXPAUFREE_BLOCK@@@Z ; HeapInstance::UNLINK

; 386  : 
; 387  : 	pFirst = pFirstFreeBlock;

	mov	eax, DWORD PTR _this$[ebp]
	mov	ecx, DWORD PTR [eax+20]
	mov	DWORD PTR _pFirst$[ebp], ecx

; 388  : 
; 389  : 	if (pBlock->pPrev != edi)

	mov	edx, DWORD PTR _pBlock$[ebp]
	mov	eax, DWORD PTR [edx+8]
	cmp	eax, DWORD PTR _edi$[ebp]
	je	SHORT $LN11@sort
$LN10@sort:

; 390  : 	{
; 391  : 		// stop when guy to the right is higher than us, or is the FirstMemBlock
; 392  : 		do
; 393  : 		{
; 394  : 			esi = edi;

	mov	ecx, DWORD PTR _edi$[ebp]
	mov	DWORD PTR _esi$[ebp], ecx

; 395  : 			edi = edi->pNext;

	mov	edx, DWORD PTR _edi$[ebp]
	mov	eax, DWORD PTR [edx+12]
	mov	DWORD PTR _edi$[ebp], eax

; 396  : 		} while (edi != pFirst && dwSize > edi->dwSize);

	mov	ecx, DWORD PTR _edi$[ebp]
	cmp	ecx, DWORD PTR _pFirst$[ebp]
	je	SHORT $LN8@sort
	mov	edx, DWORD PTR _edi$[ebp]
	mov	eax, DWORD PTR _dwSize$[ebp]
	cmp	eax, DWORD PTR [edx]
	ja	SHORT $LN10@sort
$LN8@sort:

; 397  : 	}
; 398  : 	else

	jmp	SHORT $LN6@sort
$LN11@sort:

; 399  : 	{
; 400  : 		//	;stop when guy to the left is lower than us, or we stopped on the FirstMemBlock
; 401  : 		//@@Loop2:
; 402  : 		esi = edi;

	mov	ecx, DWORD PTR _edi$[ebp]
	mov	DWORD PTR _esi$[ebp], ecx
$LN5@sort:

; 403  : 		do
; 404  : 		{
; 405  : 			edi = esi;

	mov	edx, DWORD PTR _esi$[ebp]
	mov	DWORD PTR _edi$[ebp], edx

; 406  : 			esi = esi->pPrev;

	mov	eax, DWORD PTR _esi$[ebp]
	mov	ecx, DWORD PTR [eax+8]
	mov	DWORD PTR _esi$[ebp], ecx

; 407  : 		} while (edi != pFirst && dwSize < esi->dwSize);

	mov	edx, DWORD PTR _edi$[ebp]
	cmp	edx, DWORD PTR _pFirst$[ebp]
	je	SHORT $LN6@sort
	mov	eax, DWORD PTR _esi$[ebp]
	mov	ecx, DWORD PTR _dwSize$[ebp]
	cmp	ecx, DWORD PTR [eax]
	jb	SHORT $LN5@sort
$LN6@sort:

; 408  : 	}
; 409  : 
; 410  : 
; 411  : 	// @@FoundPlace:	; esi-> prev block, edi->next block, ebx -> us
; 412  : 
; 413  : 	pBlock->pPrev = esi;

	mov	edx, DWORD PTR _pBlock$[ebp]
	mov	eax, DWORD PTR _esi$[ebp]
	mov	DWORD PTR [edx+8], eax

; 414  : 	pBlock->pNext = edi;

	mov	ecx, DWORD PTR _pBlock$[ebp]
	mov	edx, DWORD PTR _edi$[ebp]
	mov	DWORD PTR [ecx+12], edx

; 415  : 	esi->pNext = pBlock;

	mov	eax, DWORD PTR _esi$[ebp]
	mov	ecx, DWORD PTR _pBlock$[ebp]
	mov	DWORD PTR [eax+12], ecx

; 416  : 	edi->pPrev = pBlock;

	mov	edx, DWORD PTR _edi$[ebp]
	mov	eax, DWORD PTR _pBlock$[ebp]
	mov	DWORD PTR [edx+8], eax

; 417  : 
; 418  : 	if (dwSize < pFirst->dwSize)		// are we now the smallest block of them all?

	mov	ecx, DWORD PTR _pFirst$[ebp]
	mov	edx, DWORD PTR _dwSize$[ebp]
	cmp	edx, DWORD PTR [ecx]
	jae	SHORT $LN20@sort

; 419  : 		pFirstFreeBlock = pBlock;

	mov	eax, DWORD PTR _this$[ebp]
	mov	ecx, DWORD PTR _pBlock$[ebp]
	mov	DWORD PTR [eax+20], ecx
$LN20@sort:

; 420  : }

	mov	esp, ebp
	pop	ebp
	ret	0
?sort@HeapInstance@@QAIXPAUFREE_BLOCK@@@Z ENDP		; HeapInstance::sort
; Function compile flags: /Odtp
; File m:\archive\conquest\code\libs\src\dacom\baseheap.h
_TEXT	ENDS
;	COMDAT ?UNLINK@HeapInstance@@QAEXPAUFREE_BLOCK@@@Z
_TEXT	SEGMENT
_this$ = -12						; size = 4
_pPrev$ = -8						; size = 4
_pNext$ = -4						; size = 4
_pBlock$ = 8						; size = 4
?UNLINK@HeapInstance@@QAEXPAUFREE_BLOCK@@@Z PROC	; HeapInstance::UNLINK, COMDAT
; _this$ = ecx

; 304  : {

	push	ebp
	mov	ebp, esp
	sub	esp, 12					; 0000000cH
	mov	DWORD PTR _this$[ebp], ecx

; 305  : 	FREE_BLOCK *pPrev, *pNext;
; 306  : 
; 307  : 	if ((pNext = pBlock->getNext()) == pBlock)

	mov	ecx, DWORD PTR _pBlock$[ebp]
	call	?getNext@FREE_BLOCK@@QAEPAU1@XZ		; FREE_BLOCK::getNext
	mov	DWORD PTR _pNext$[ebp], eax
	mov	eax, DWORD PTR _pNext$[ebp]
	cmp	eax, DWORD PTR _pBlock$[ebp]
	jne	SHORT $LN2@UNLINK

; 308  : 	{
; 309  : 		// list is empty
; 310  : 
; 311  : 		pFirstFreeBlock = 0;

	mov	ecx, DWORD PTR _this$[ebp]
	mov	DWORD PTR [ecx+20], 0

; 312  : 		return;

	jmp	SHORT $LN3@UNLINK
$LN2@UNLINK:

; 313  : 	}
; 314  : 
; 315  : 	if (pBlock == pFirstFreeBlock)

	mov	edx, DWORD PTR _this$[ebp]
	mov	eax, DWORD PTR _pBlock$[ebp]
	cmp	eax, DWORD PTR [edx+20]
	jne	SHORT $LN1@UNLINK

; 316  : 		pFirstFreeBlock = pNext;

	mov	ecx, DWORD PTR _this$[ebp]
	mov	edx, DWORD PTR _pNext$[ebp]
	mov	DWORD PTR [ecx+20], edx
$LN1@UNLINK:

; 317  : 
; 318  : 	// unlink the element
; 319  : 
; 320  : 	pPrev = pBlock->getPrev();

	mov	ecx, DWORD PTR _pBlock$[ebp]
	call	?getPrev@FREE_BLOCK@@QAEPAU1@XZ		; FREE_BLOCK::getPrev
	mov	DWORD PTR _pPrev$[ebp], eax

; 321  : 
; 322  : 	pPrev->pNext = pNext;

	mov	eax, DWORD PTR _pPrev$[ebp]
	mov	ecx, DWORD PTR _pNext$[ebp]
	mov	DWORD PTR [eax+12], ecx

; 323  : 	pNext->pPrev = pPrev;

	mov	edx, DWORD PTR _pNext$[ebp]
	mov	eax, DWORD PTR _pPrev$[ebp]
	mov	DWORD PTR [edx+8], eax
$LN3@UNLINK:

; 324  : }	

	mov	esp, ebp
	pop	ebp
	ret	4
?UNLINK@HeapInstance@@QAEXPAUFREE_BLOCK@@@Z ENDP	; HeapInstance::UNLINK
; Function compile flags: /Odtp
; File m:\archive\conquest\code\libs\src\dacom\heapinst.cpp
_TEXT	ENDS
_TEXT	SEGMENT
_dwNumBytes$ = -24					; size = 4
_this$ = -20						; size = 4
_pTmp$63706 = -16					; size = 4
_pBlock$ = -12						; size = 4
_dwRemainder$ = -8					; size = 4
_pStart$ = -4						; size = 4
?malloc@HeapInstance@@QAIPAUBASE_BLOCK@@K@Z PROC	; HeapInstance::malloc
; _this$ = ecx
; _dwNumBytes$ = edx

; 424  : {

	push	ebp
	mov	ebp, esp
	sub	esp, 24					; 00000018H
	mov	DWORD PTR _dwNumBytes$[ebp], edx
	mov	DWORD PTR _this$[ebp], ecx

; 425  : 	FREE_BLOCK *pBlock, *pStart;
; 426  : 	DWORD dwRemainder;
; 427  : 
; 428  : 
; 429  : 	dwNumBytes = (dwNumBytes + dwBaseBlockSize + 7) & ~7;	// enforce quad-word alignment

	mov	eax, DWORD PTR _this$[ebp]
	mov	ecx, DWORD PTR [eax+24]
	mov	edx, DWORD PTR _dwNumBytes$[ebp]
	lea	eax, DWORD PTR [edx+ecx+7]
	and	eax, -8					; fffffff8H
	mov	DWORD PTR _dwNumBytes$[ebp], eax

; 430  : 	//	dwNumBytes = __max(sizeof(FREE_BLOCK), dwNumBytes);		// already ensured
; 431  : 
; 432  : 	// search the free list for available block
; 433  : 
; 434  : 	if ((pBlock = pFirstFreeBlock) == 0)

	mov	ecx, DWORD PTR _this$[ebp]
	mov	edx, DWORD PTR [ecx+20]
	mov	DWORD PTR _pBlock$[ebp], edx
	cmp	DWORD PTR _pBlock$[ebp], 0
	jne	SHORT $LN11@malloc
	jmp	$Error$63693

; 435  : 		goto Error;		// out of memory

	jmp	$Error$63693
$LN11@malloc:

; 436  : 
; 437  : 	pStart = pBlock;	// mark beginning of list

	mov	eax, DWORD PTR _pBlock$[ebp]
	mov	DWORD PTR _pStart$[ebp], eax
$LN9@malloc:

; 438  : 
; 439  : 	do
; 440  : 	{
; 441  : 		if ((long)(dwRemainder = pBlock->dwSize - dwNumBytes) >= 0)

	mov	ecx, DWORD PTR _pBlock$[ebp]
	mov	edx, DWORD PTR [ecx]
	sub	edx, DWORD PTR _dwNumBytes$[ebp]
	mov	DWORD PTR _dwRemainder$[ebp], edx
	js	SHORT $LN8@malloc

; 442  : 			break;		// found a block

	jmp	SHORT $LN7@malloc
$LN8@malloc:

; 443  : 	} while ((pBlock = pBlock->getNext()) != pStart);

	mov	ecx, DWORD PTR _pBlock$[ebp]
	call	?getNext@FREE_BLOCK@@QAEPAU1@XZ		; FREE_BLOCK::getNext
	mov	DWORD PTR _pBlock$[ebp], eax
	mov	eax, DWORD PTR _pBlock$[ebp]
	cmp	eax, DWORD PTR _pStart$[ebp]
	jne	SHORT $LN9@malloc
$LN7@malloc:

; 444  : 
; 445  : 	if ((long)dwRemainder < 0)

	cmp	DWORD PTR _dwRemainder$[ebp], 0
	jge	SHORT $LN5@malloc
	jmp	SHORT $Error$63693

; 446  : 		goto Error;		// out of memory

	jmp	SHORT $Error$63693
$LN5@malloc:

; 447  : 
; 448  : 
; 449  : 	if (dwRemainder < sizeof(FREE_BLOCK)*2)

	cmp	DWORD PTR _dwRemainder$[ebp], 32	; 00000020H
	jae	SHORT $LN3@malloc

; 450  : 	{
; 451  : 		// just unlink the whole block
; 452  : 		UNLINK(pBlock);

	mov	ecx, DWORD PTR _pBlock$[ebp]
	push	ecx
	mov	ecx, DWORD PTR _this$[ebp]
	call	?UNLINK@HeapInstance@@QAEXPAUFREE_BLOCK@@@Z ; HeapInstance::UNLINK

; 453  : 		pBlock->dwSize |= 1;	// mark as allocated

	mov	edx, DWORD PTR _pBlock$[ebp]
	mov	eax, DWORD PTR [edx]
	or	eax, 1
	mov	ecx, DWORD PTR _pBlock$[ebp]
	mov	DWORD PTR [ecx], eax

; 454  : 	}
; 455  : 	else

	jmp	SHORT $LN2@malloc
$LN3@malloc:

; 456  : 	{
; 457  : 		// update the lower block to point to the new block
; 458  : 		BASE_BLOCK *pTmp;
; 459  : 
; 460  : 		pTmp = pBlock->getLower();

	mov	ecx, DWORD PTR _pBlock$[ebp]
	call	?getLower@BASE_BLOCK@@QAEPAU1@XZ	; BASE_BLOCK::getLower
	mov	DWORD PTR _pTmp$63706[ebp], eax

; 461  : 		pBlock->dwSize = dwRemainder;

	mov	edx, DWORD PTR _pBlock$[ebp]
	mov	eax, DWORD PTR _dwRemainder$[ebp]
	mov	DWORD PTR [edx], eax

; 462  : 
; 463  : 		if ((dwFlags & DAHEAPFLAG_NOBESTFIT) == 0)

	mov	ecx, DWORD PTR _this$[ebp]
	mov	edx, DWORD PTR [ecx+12]
	and	edx, 2
	jne	SHORT $LN1@malloc

; 464  : 			sort(pBlock);

	mov	edx, DWORD PTR _pBlock$[ebp]
	mov	ecx, DWORD PTR _this$[ebp]
	call	?sort@HeapInstance@@QAIXPAUFREE_BLOCK@@@Z ; HeapInstance::sort
$LN1@malloc:

; 465  : 
; 466  : 		pTmp->pUpper = pBlock = (FREE_BLOCK *) (((char *)pTmp->pUpper) + dwRemainder);

	mov	eax, DWORD PTR _pTmp$63706[ebp]
	mov	ecx, DWORD PTR [eax+4]
	add	ecx, DWORD PTR _dwRemainder$[ebp]
	mov	DWORD PTR _pBlock$[ebp], ecx
	mov	edx, DWORD PTR _pTmp$63706[ebp]
	mov	eax, DWORD PTR _pBlock$[ebp]
	mov	DWORD PTR [edx+4], eax

; 467  : 
; 468  : 		// pBlock -> new block
; 469  : 		pBlock->dwSize = dwNumBytes + 1;		// mark allocated

	mov	ecx, DWORD PTR _dwNumBytes$[ebp]
	add	ecx, 1
	mov	edx, DWORD PTR _pBlock$[ebp]
	mov	DWORD PTR [edx], ecx

; 470  : 		pBlock->pUpper = (BASE_BLOCK *) (((char *)pBlock) - dwRemainder);

	mov	eax, DWORD PTR _pBlock$[ebp]
	sub	eax, DWORD PTR _dwRemainder$[ebp]
	mov	ecx, DWORD PTR _pBlock$[ebp]
	mov	DWORD PTR [ecx+4], eax
$LN2@malloc:

; 471  : 	}
; 472  : 	
; 473  : 	return pBlock;

	mov	eax, DWORD PTR _pBlock$[ebp]
	jmp	SHORT $LN12@malloc
$Error$63693:

; 474  : 	
; 475  : Error:
; 476  : 	return 0;

	xor	eax, eax
$LN12@malloc:

; 477  : }

	mov	esp, ebp
	pop	ebp
	ret	0
?malloc@HeapInstance@@QAIPAUBASE_BLOCK@@K@Z ENDP	; HeapInstance::malloc
_TEXT	ENDS
PUBLIC	?RELINK@HeapInstance@@QAEXPAUFREE_BLOCK@@@Z	; HeapInstance::RELINK
PUBLIC	?mergeWithLower@HeapInstance@@QAIHPAUBASE_BLOCK@@@Z ; HeapInstance::mergeWithLower
; Function compile flags: /Odtp
_TEXT	SEGMENT
_pBlock$ = -24						; size = 4
_this$ = -20						; size = 4
$T63920 = -16						; size = 4
_pLower$63744 = -12					; size = 4
_pUpper$ = -8						; size = 4
_dwSize$ = -4						; size = 4
?free@HeapInstance@@QAIHPAUFREE_BLOCK@@@Z PROC		; HeapInstance::free
; _this$ = ecx
; _pBlock$ = edx

; 520  : {

	push	ebp
	mov	ebp, esp
	sub	esp, 24					; 00000018H
	mov	DWORD PTR _pBlock$[ebp], edx
	mov	DWORD PTR _this$[ebp], ecx

; 521  : 	ASSERT(pBlock);

	cmp	DWORD PTR _pBlock$[ebp], 0
	jne	SHORT $LN5@free
	push	OFFSET ??_C@_06DPHEOBMB@pBlock?$AA@
	push	521					; 00000209H
	push	OFFSET ??_C@_0P@KGMHEPGH@?4?2HeapInst?4cpp?$AA@
	push	OFFSET ??_C@_0CE@JBJGEEGD@?$CFs?$CI?$CFd?$CJ?5?3?5FATAL?3Assertion?5failed?3@
	push	0
	push	65540					; 00010004H
	lea	ecx, DWORD PTR $T63920[ebp]
	call	??0ErrorCode@@QAE@W4ErrorKind@@W4SeverityLevel@@@Z ; ErrorCode::ErrorCode
	mov	eax, DWORD PTR [eax]
	push	eax
	call	DWORD PTR _FDUMP
	add	esp, 20					; 00000014H
$LN5@free:

; 522  : 
; 523  : 	FREE_BLOCK *pUpper;
; 524  : 	DWORD dwSize;
; 525  : 	
; 526  : 	// merge this block with lower one if possible
; 527  : 	if (mergeWithLower(pBlock) == 0)

	mov	edx, DWORD PTR _pBlock$[ebp]
	mov	ecx, DWORD PTR _this$[ebp]
	call	?mergeWithLower@HeapInstance@@QAIHPAUBASE_BLOCK@@@Z ; HeapInstance::mergeWithLower
	test	eax, eax
	jne	SHORT $LN4@free

; 528  : 		return 0;

	xor	eax, eax
	jmp	SHORT $LN6@free
$LN4@free:

; 529  : 
; 530  : 	// if block above is "free", add our size to it. no relinking is needed
; 531  : 
; 532  : 	if ((pUpper = (FREE_BLOCK *)pBlock->getUpper()) != 0 && 
; 533  : 		((dwSize = pBlock->dwSize + pUpper->dwSize) & 1) != 0)

	mov	ecx, DWORD PTR _pBlock$[ebp]
	call	?getUpper@BASE_BLOCK@@QAEPAU1@XZ	; BASE_BLOCK::getUpper
	mov	DWORD PTR _pUpper$[ebp], eax
	cmp	DWORD PTR _pUpper$[ebp], 0
	je	SHORT $LN3@free
	mov	ecx, DWORD PTR _pBlock$[ebp]
	mov	edx, DWORD PTR [ecx]
	mov	eax, DWORD PTR _pUpper$[ebp]
	add	edx, DWORD PTR [eax]
	mov	DWORD PTR _dwSize$[ebp], edx
	mov	ecx, DWORD PTR _dwSize$[ebp]
	and	ecx, 1
	je	SHORT $LN3@free

; 534  : 	{
; 535  : 		FREE_BLOCK *pLower;
; 536  : 		// just add new size to upper block
; 537  : 		pUpper->dwSize = dwSize-1;		// remove the allocated marker

	mov	edx, DWORD PTR _dwSize$[ebp]
	sub	edx, 1
	mov	eax, DWORD PTR _pUpper$[ebp]
	mov	DWORD PTR [eax], edx

; 538  : 
; 539  : 		// inform lower neighbor of the change
; 540  : 
; 541  : 		pLower = (FREE_BLOCK *) pUpper->getLower();

	mov	ecx, DWORD PTR _pUpper$[ebp]
	call	?getLower@BASE_BLOCK@@QAEPAU1@XZ	; BASE_BLOCK::getLower
	mov	DWORD PTR _pLower$63744[ebp], eax

; 542  : 		pLower->pUpper = pUpper;

	mov	ecx, DWORD PTR _pLower$63744[ebp]
	mov	edx, DWORD PTR _pUpper$[ebp]
	mov	DWORD PTR [ecx+4], edx

; 543  : 
; 544  : 		if ((dwFlags & DAHEAPFLAG_NOBESTFIT) == 0)

	mov	eax, DWORD PTR _this$[ebp]
	mov	ecx, DWORD PTR [eax+12]
	and	ecx, 2
	jne	SHORT $LN2@free

; 545  : 			sort(pUpper);

	mov	edx, DWORD PTR _pUpper$[ebp]
	mov	ecx, DWORD PTR _this$[ebp]
	call	?sort@HeapInstance@@QAIXPAUFREE_BLOCK@@@Z ; HeapInstance::sort
$LN2@free:

; 546  : 	}
; 547  : 	else

	jmp	SHORT $LN1@free
$LN3@free:

; 548  : 	{
; 549  : 		// just relink the block into the list
; 550  : 
; 551  : 		pBlock->dwSize &= ~1;		// remove the allocation marker

	mov	edx, DWORD PTR _pBlock$[ebp]
	mov	eax, DWORD PTR [edx]
	and	eax, -2					; fffffffeH
	mov	ecx, DWORD PTR _pBlock$[ebp]
	mov	DWORD PTR [ecx], eax

; 552  : 		RELINK(pBlock);

	mov	edx, DWORD PTR _pBlock$[ebp]
	push	edx
	mov	ecx, DWORD PTR _this$[ebp]
	call	?RELINK@HeapInstance@@QAEXPAUFREE_BLOCK@@@Z ; HeapInstance::RELINK
$LN1@free:

; 553  : 
; 554  : 	}
; 555  : 	return 1;

	mov	eax, 1
$LN6@free:

; 556  : }

	mov	esp, ebp
	pop	ebp
	ret	0
?free@HeapInstance@@QAIHPAUFREE_BLOCK@@@Z ENDP		; HeapInstance::free
; Function compile flags: /Odtp
; File m:\archive\conquest\code\libs\src\dacom\baseheap.h
_TEXT	ENDS
;	COMDAT ?RELINK@HeapInstance@@QAEXPAUFREE_BLOCK@@@Z
_TEXT	SEGMENT
_this$ = -16						; size = 4
_pTmp$63163 = -12					; size = 4
_dwSize$63164 = -8					; size = 4
_pStart$ = -4						; size = 4
_pBlock$ = 8						; size = 4
?RELINK@HeapInstance@@QAEXPAUFREE_BLOCK@@@Z PROC	; HeapInstance::RELINK, COMDAT
; _this$ = ecx

; 261  : {

	push	ebp
	mov	ebp, esp
	sub	esp, 16					; 00000010H
	mov	DWORD PTR _this$[ebp], ecx

; 262  : 	FREE_BLOCK *pStart;
; 263  : 
; 264  :   	if ((pStart = pFirstFreeBlock) == 0)		

	mov	eax, DWORD PTR _this$[ebp]
	mov	ecx, DWORD PTR [eax+20]
	mov	DWORD PTR _pStart$[ebp], ecx
	cmp	DWORD PTR _pStart$[ebp], 0
	jne	SHORT $LN7@RELINK

; 265  : 	{
; 266  : 		// empty list
; 267  : 		pFirstFreeBlock = pBlock;

	mov	edx, DWORD PTR _this$[ebp]
	mov	eax, DWORD PTR _pBlock$[ebp]
	mov	DWORD PTR [edx+20], eax

; 268  : 		pBlock->pPrev = 
; 269  : 		pBlock->pNext = pBlock;

	mov	ecx, DWORD PTR _pBlock$[ebp]
	mov	edx, DWORD PTR _pBlock$[ebp]
	mov	DWORD PTR [ecx+12], edx
	mov	eax, DWORD PTR _pBlock$[ebp]
	mov	ecx, DWORD PTR _pBlock$[ebp]
	mov	DWORD PTR [eax+8], ecx

; 270  : 		return;

	jmp	$LN8@RELINK
$LN7@RELINK:

; 271  : 	}
; 272  : 
; 273  : 	if ((dwFlags & DAHEAPFLAG_NOBESTFIT) == 0)

	mov	edx, DWORD PTR _this$[ebp]
	mov	eax, DWORD PTR [edx+12]
	and	eax, 2
	jne	SHORT $LN6@RELINK

; 274  : 	{
; 275  : 		FREE_BLOCK *pTmp;
; 276  : 		DWORD dwSize;
; 277  : 
; 278  : 		pTmp = pStart;

	mov	ecx, DWORD PTR _pStart$[ebp]
	mov	DWORD PTR _pTmp$63163[ebp], ecx

; 279  : 		dwSize = pBlock->dwSize;

	mov	edx, DWORD PTR _pBlock$[ebp]
	mov	eax, DWORD PTR [edx]
	mov	DWORD PTR _dwSize$63164[ebp], eax

; 280  : 
; 281  : 		if (dwSize < pStart->dwSize)

	mov	ecx, DWORD PTR _pStart$[ebp]
	mov	edx, DWORD PTR _dwSize$63164[ebp]
	cmp	edx, DWORD PTR [ecx]
	jae	SHORT $LN3@RELINK

; 282  : 			pFirstFreeBlock = pBlock;

	mov	eax, DWORD PTR _this$[ebp]
	mov	ecx, DWORD PTR _pBlock$[ebp]
	mov	DWORD PTR [eax+20], ecx

; 283  : 		else

	jmp	SHORT $LN4@RELINK
$LN3@RELINK:

; 284  : 		{
; 285  : 			while ((pStart = pStart->getNext()) != pTmp)

	mov	ecx, DWORD PTR _pStart$[ebp]
	call	?getNext@FREE_BLOCK@@QAEPAU1@XZ		; FREE_BLOCK::getNext
	mov	DWORD PTR _pStart$[ebp], eax
	mov	edx, DWORD PTR _pStart$[ebp]
	cmp	edx, DWORD PTR _pTmp$63163[ebp]
	je	SHORT $LN4@RELINK

; 286  : 			{
; 287  : 				if (dwSize <= pStart->dwSize)

	mov	eax, DWORD PTR _pStart$[ebp]
	mov	ecx, DWORD PTR _dwSize$63164[ebp]
	cmp	ecx, DWORD PTR [eax]
	ja	SHORT $LN1@RELINK

; 288  : 					break;

	jmp	SHORT $LN4@RELINK
$LN1@RELINK:

; 289  : 			}

	jmp	SHORT $LN3@RELINK
$LN4@RELINK:

; 290  : 		}
; 291  : 		
; 292  : 		pStart = pStart->getPrev();

	mov	ecx, DWORD PTR _pStart$[ebp]
	call	?getPrev@FREE_BLOCK@@QAEPAU1@XZ		; FREE_BLOCK::getPrev
	mov	DWORD PTR _pStart$[ebp], eax
$LN6@RELINK:

; 293  : 	}
; 294  : 
; 295  : 	pBlock->pNext = pStart->pNext;

	mov	edx, DWORD PTR _pBlock$[ebp]
	mov	eax, DWORD PTR _pStart$[ebp]
	mov	ecx, DWORD PTR [eax+12]
	mov	DWORD PTR [edx+12], ecx

; 296  : 	pBlock->pPrev = pStart;

	mov	edx, DWORD PTR _pBlock$[ebp]
	mov	eax, DWORD PTR _pStart$[ebp]
	mov	DWORD PTR [edx+8], eax

; 297  : 	pStart->pNext = pBlock;

	mov	ecx, DWORD PTR _pStart$[ebp]
	mov	edx, DWORD PTR _pBlock$[ebp]
	mov	DWORD PTR [ecx+12], edx

; 298  : 	pBlock->pNext->pPrev = pBlock;

	mov	eax, DWORD PTR _pBlock$[ebp]
	mov	ecx, DWORD PTR [eax+12]
	mov	edx, DWORD PTR _pBlock$[ebp]
	mov	DWORD PTR [ecx+8], edx
$LN8@RELINK:

; 299  : }

	mov	esp, ebp
	pop	ebp
	ret	4
?RELINK@HeapInstance@@QAEXPAUFREE_BLOCK@@@Z ENDP	; HeapInstance::RELINK
; Function compile flags: /Odtp
; File m:\archive\conquest\code\libs\src\dacom\heapinst.cpp
_TEXT	ENDS
;	COMDAT ?mergeWithLower@HeapInstance@@QAIHPAUBASE_BLOCK@@@Z
_TEXT	SEGMENT
_pBlock$ = -24						; size = 4
_this$ = -20						; size = 4
$T63924 = -16						; size = 4
_pNewLower$63731 = -12					; size = 4
_pLower$ = -8						; size = 4
_dwSize$ = -4						; size = 4
?mergeWithLower@HeapInstance@@QAIHPAUBASE_BLOCK@@@Z PROC ; HeapInstance::mergeWithLower, COMDAT
; _this$ = ecx
; _pBlock$ = edx

; 481  : {

	push	ebp
	mov	ebp, esp
	sub	esp, 24					; 00000018H
	mov	DWORD PTR _pBlock$[ebp], edx
	mov	DWORD PTR _this$[ebp], ecx

; 482  : 	ASSERT(pBlock);

	cmp	DWORD PTR _pBlock$[ebp], 0
	jne	SHORT $LN6@mergeWithL
	push	OFFSET ??_C@_06DPHEOBMB@pBlock?$AA@
	push	482					; 000001e2H
	push	OFFSET ??_C@_0P@KGMHEPGH@?4?2HeapInst?4cpp?$AA@
	push	OFFSET ??_C@_0CE@JBJGEEGD@?$CFs?$CI?$CFd?$CJ?5?3?5FATAL?3Assertion?5failed?3@
	push	0
	push	65540					; 00010004H
	lea	ecx, DWORD PTR $T63924[ebp]
	call	??0ErrorCode@@QAE@W4ErrorKind@@W4SeverityLevel@@@Z ; ErrorCode::ErrorCode
	mov	eax, DWORD PTR [eax]
	push	eax
	call	DWORD PTR _FDUMP
	add	esp, 20					; 00000014H
$LN6@mergeWithL:

; 483  : 
; 484  : 	FREE_BLOCK *pLower;
; 485  : 	DWORD dwSize;
; 486  : 
; 487  : 	if (((dwSize = pBlock->dwSize) & 1) == 0)

	mov	ecx, DWORD PTR _pBlock$[ebp]
	mov	edx, DWORD PTR [ecx]
	mov	DWORD PTR _dwSize$[ebp], edx
	mov	eax, DWORD PTR _dwSize$[ebp]
	and	eax, 1
	jne	SHORT $LN5@mergeWithL

; 488  : 	{
; 489  : 		doError(DAHEAP_INVALID_PTR, ((DWORD)pBlock) + dwBaseBlockSize);

	push	0
	mov	ecx, DWORD PTR _this$[ebp]
	mov	edx, DWORD PTR _pBlock$[ebp]
	add	edx, DWORD PTR [ecx+24]
	push	edx
	push	5
	mov	ecx, DWORD PTR _this$[ebp]
	call	?doError@BaseHeap@@QAEJKKK@Z		; BaseHeap::doError

; 490  : 		return 0;

	xor	eax, eax
	jmp	$LN7@mergeWithL
$LN5@mergeWithL:

; 491  : 	}
; 492  : 
; 493  : 	if (dwFlags & DAHEAPFLAG_DEBUGFILL_SNAN)		// includes regular mem fill too

	mov	eax, DWORD PTR _this$[ebp]
	mov	ecx, DWORD PTR [eax+12]
	and	ecx, 192				; 000000c0H
	je	SHORT $LN4@mergeWithL

; 494  : 	{
; 495  : 		if ((dwFlags & DAHEAPFLAG_DEBUGFILL_SNAN) == DAHEAPFLAG_DEBUGFILL_SNAN)

	mov	edx, DWORD PTR _this$[ebp]
	mov	eax, DWORD PTR [edx+12]
	and	eax, 192				; 000000c0H
	cmp	eax, 192				; 000000c0H
	jne	SHORT $LN3@mergeWithL

; 496  : 			snanfill(&pBlock->pMsg, ((dwSize&~1)-daoffsetofmember(BASE_BLOCK,pMsg)) >> 2);

	mov	ecx, DWORD PTR _dwSize$[ebp]
	and	ecx, -2					; fffffffeH
	xor	edx, edx
	add	edx, 8
	sub	ecx, edx
	shr	ecx, 2
	push	ecx
	mov	eax, DWORD PTR _pBlock$[ebp]
	add	eax, 8
	push	eax
	call	?snanfill@@YGXPAXK@Z			; snanfill

; 497  : 		else

	jmp	SHORT $LN4@mergeWithL
$LN3@mergeWithL:

; 498  : 			memset(&pBlock->pMsg, 0xCB, (dwSize&~1)-daoffsetofmember(BASE_BLOCK,pMsg));

	mov	ecx, DWORD PTR _dwSize$[ebp]
	and	ecx, -2					; fffffffeH
	xor	edx, edx
	add	edx, 8
	sub	ecx, edx
	push	ecx
	push	203					; 000000cbH
	mov	eax, DWORD PTR _pBlock$[ebp]
	add	eax, 8
	push	eax
	call	_memset
	add	esp, 12					; 0000000cH
$LN4@mergeWithL:

; 499  : 	}
; 500  : 
; 501  : 	pLower = (FREE_BLOCK *) pBlock->getLower();

	mov	ecx, DWORD PTR _pBlock$[ebp]
	call	?getLower@BASE_BLOCK@@QAEPAU1@XZ	; BASE_BLOCK::getLower
	mov	DWORD PTR _pLower$[ebp], eax

; 502  : 	dwSize += pLower->dwSize;

	mov	ecx, DWORD PTR _pLower$[ebp]
	mov	edx, DWORD PTR _dwSize$[ebp]
	add	edx, DWORD PTR [ecx]
	mov	DWORD PTR _dwSize$[ebp], edx

; 503  : 	
; 504  : 	if ((dwSize & 1) != 0)	// lower block was free

	mov	eax, DWORD PTR _dwSize$[ebp]
	and	eax, 1
	je	SHORT $LN1@mergeWithL

; 505  : 	{
; 506  : 		FREE_BLOCK *pNewLower;
; 507  : 
; 508  : 		pBlock->dwSize = dwSize;

	mov	ecx, DWORD PTR _pBlock$[ebp]
	mov	edx, DWORD PTR _dwSize$[ebp]
	mov	DWORD PTR [ecx], edx

; 509  : 		pNewLower = (FREE_BLOCK *) pBlock->getLower();

	mov	ecx, DWORD PTR _pBlock$[ebp]
	call	?getLower@BASE_BLOCK@@QAEPAU1@XZ	; BASE_BLOCK::getLower
	mov	DWORD PTR _pNewLower$63731[ebp], eax

; 510  : 		pNewLower->pUpper = pBlock;	// update new lower block

	mov	eax, DWORD PTR _pNewLower$63731[ebp]
	mov	ecx, DWORD PTR _pBlock$[ebp]
	mov	DWORD PTR [eax+4], ecx

; 511  : 
; 512  : 		UNLINK(pLower);

	mov	edx, DWORD PTR _pLower$[ebp]
	push	edx
	mov	ecx, DWORD PTR _this$[ebp]
	call	?UNLINK@HeapInstance@@QAEXPAUFREE_BLOCK@@@Z ; HeapInstance::UNLINK
$LN1@mergeWithL:

; 513  : 	}
; 514  : 	
; 515  : 	return 1;

	mov	eax, 1
$LN7@mergeWithL:

; 516  : }

	mov	esp, ebp
	pop	ebp
	ret	0
?mergeWithLower@HeapInstance@@QAIHPAUBASE_BLOCK@@@Z ENDP ; HeapInstance::mergeWithLower
_TEXT	ENDS
PUBLIC	??_C@_07OAAHBBHO@pMemory?$AA@			; `string'
;	COMDAT ??_C@_07OAAHBBHO@pMemory?$AA@
CONST	SEGMENT
??_C@_07OAAHBBHO@pMemory?$AA@ DB 'pMemory', 00H		; `string'
; Function compile flags: /Odtp
CONST	ENDS
_TEXT	SEGMENT
$T63927 = -4						; size = 4
_pMemory$ = 8						; size = 4
_numDwords$ = 12					; size = 4
?snanfill@@YGXPAXK@Z PROC				; snanfill

; 32   : {

	push	ebp
	mov	ebp, esp
	push	ecx
	push	edi

; 33   : 	ASSERT(pMemory);

	cmp	DWORD PTR _pMemory$[ebp], 0
	jne	SHORT $LN1@snanfill
	push	OFFSET ??_C@_07OAAHBBHO@pMemory?$AA@
	push	33					; 00000021H
	push	OFFSET ??_C@_0P@KGMHEPGH@?4?2HeapInst?4cpp?$AA@
	push	OFFSET ??_C@_0CE@JBJGEEGD@?$CFs?$CI?$CFd?$CJ?5?3?5FATAL?3Assertion?5failed?3@
	push	0
	push	65540					; 00010004H
	lea	ecx, DWORD PTR $T63927[ebp]
	call	??0ErrorCode@@QAE@W4ErrorKind@@W4SeverityLevel@@@Z ; ErrorCode::ErrorCode
	mov	eax, DWORD PTR [eax]
	push	eax
	call	DWORD PTR _FDUMP
	add	esp, 20					; 00000014H
$LN1@snanfill:

; 34   : 	__asm {
; 35   : 		mov edi, DWORD PTR pMemory

	mov	edi, DWORD PTR _pMemory$[ebp]

; 36   : 		cld

	cld

; 37   : 		mov ecx, numDwords

	mov	ecx, DWORD PTR _numDwords$[ebp]

; 38   : 		mov eax, 0FFA01006h

	mov	eax, -6287354				; ffa01006H

; 39   : 		rep stosd

	rep	 stosd

; 40   : 	}
; 41   : }

	pop	edi
	mov	esp, ebp
	pop	ebp
	ret	8
?snanfill@@YGXPAXK@Z ENDP				; snanfill
_TEXT	ENDS
PUBLIC	?SetBlockOwner@HeapInstance@@UAGJPAXK@Z		; HeapInstance::SetBlockOwner
; Function compile flags: /Odtp
_TEXT	SEGMENT
_result$ = -8						; size = 4
_pBlock$ = -4						; size = 4
_this$ = 8						; size = 4
_allocatedBlock$ = 12					; size = 4
_owner$ = 16						; size = 4
?SetBlockOwner@HeapInstance@@UAGJPAXK@Z PROC		; HeapInstance::SetBlockOwner

; 560  : {

	push	ebp
	mov	ebp, esp
	sub	esp, 8

; 561  : 	BOOL32 result;
; 562  : 	BASE_BLOCK *pBlock;
; 563  : 
; 564  : 	if ((pBlock = verifyBlock(allocatedBlock)) == 0)

	mov	eax, DWORD PTR _allocatedBlock$[ebp]
	push	eax
	mov	ecx, DWORD PTR _this$[ebp]
	call	?verifyBlock@HeapInstance@@QAEPAUBASE_BLOCK@@PAX@Z ; HeapInstance::verifyBlock
	mov	DWORD PTR _pBlock$[ebp], eax
	cmp	DWORD PTR _pBlock$[ebp], 0
	jne	SHORT $LN3@SetBlockOw

; 565  : 	{
; 566  : 		result = 0;

	mov	DWORD PTR _result$[ebp], 0
	jmp	SHORT $Done$63756

; 567  : 		goto Done;

	jmp	SHORT $Done$63756
$LN3@SetBlockOw:

; 568  : 	}
; 569  : 
; 570  : 	if (pBlock->isAllocated() && (dwFlags & DAHEAPFLAG_NOMSGS) == 0)

	mov	ecx, DWORD PTR _pBlock$[ebp]
	call	?isAllocated@BASE_BLOCK@@QAEHXZ		; BASE_BLOCK::isAllocated
	test	eax, eax
	je	SHORT $LN1@SetBlockOw
	mov	ecx, DWORD PTR _this$[ebp]
	mov	edx, DWORD PTR [ecx+12]
	and	edx, 16					; 00000010H
	jne	SHORT $LN1@SetBlockOw

; 571  : 	  	pBlock->setOwner(owner);

	mov	eax, DWORD PTR _owner$[ebp]
	push	eax
	mov	ecx, DWORD PTR _pBlock$[ebp]
	call	?setOwner@BASE_BLOCK@@QAEXK@Z		; BASE_BLOCK::setOwner
$LN1@SetBlockOw:

; 572  : 
; 573  : 	result=1;

	mov	DWORD PTR _result$[ebp], 1
$Done$63756:

; 574  : 
; 575  : Done:
; 576  : 	return result;

	mov	eax, DWORD PTR _result$[ebp]

; 577  : }

	mov	esp, ebp
	pop	ebp
	ret	12					; 0000000cH
?SetBlockOwner@HeapInstance@@UAGJPAXK@Z ENDP		; HeapInstance::SetBlockOwner
_TEXT	ENDS
PUBLIC	?getOwner@BASE_BLOCK@@QAEKXZ			; BASE_BLOCK::getOwner
PUBLIC	?GetBlockOwner@HeapInstance@@UAGKPAX@Z		; HeapInstance::GetBlockOwner
; Function compile flags: /Odtp
_TEXT	SEGMENT
_result$ = -8						; size = 4
_pBlock$ = -4						; size = 4
_this$ = 8						; size = 4
_allocatedBlock$ = 12					; size = 4
?GetBlockOwner@HeapInstance@@UAGKPAX@Z PROC		; HeapInstance::GetBlockOwner

; 581  : {

	push	ebp
	mov	ebp, esp
	sub	esp, 8

; 582  : 	U32 result=0;

	mov	DWORD PTR _result$[ebp], 0

; 583  : 	BASE_BLOCK *pBlock;
; 584  : 
; 585  : 	if ((pBlock = verifyBlock(allocatedBlock)) == 0)

	mov	eax, DWORD PTR _allocatedBlock$[ebp]
	push	eax
	mov	ecx, DWORD PTR _this$[ebp]
	call	?verifyBlock@HeapInstance@@QAEPAUBASE_BLOCK@@PAX@Z ; HeapInstance::verifyBlock
	mov	DWORD PTR _pBlock$[ebp], eax
	cmp	DWORD PTR _pBlock$[ebp], 0
	jne	SHORT $LN5@GetBlockOw
	jmp	SHORT $Done$63766

; 586  : 		goto Done;

	jmp	SHORT $Done$63766
$LN5@GetBlockOw:

; 587  : 
; 588  : 	if (pBlock->isAllocated())

	mov	ecx, DWORD PTR _pBlock$[ebp]
	call	?isAllocated@BASE_BLOCK@@QAEHXZ		; BASE_BLOCK::isAllocated
	test	eax, eax
	je	SHORT $Done$63766

; 589  : 	{
; 590  : 		if ((dwFlags & DAHEAPFLAG_NOMSGS) == 0)

	mov	ecx, DWORD PTR _this$[ebp]
	mov	edx, DWORD PTR [ecx+12]
	and	edx, 16					; 00000010H
	jne	SHORT $LN2@GetBlockOw

; 591  : 			result = pBlock->getOwner();

	mov	ecx, DWORD PTR _pBlock$[ebp]
	call	?getOwner@BASE_BLOCK@@QAEKXZ		; BASE_BLOCK::getOwner
	mov	DWORD PTR _result$[ebp], eax

; 592  : 		else

	jmp	SHORT $Done$63766
$LN2@GetBlockOw:

; 593  : 			result = 0xFFFFFFFF;		// signal that block is allocated, but we don't know who owns it

	mov	DWORD PTR _result$[ebp], -1
$Done$63766:

; 594  : 	}
; 595  : 
; 596  : Done:
; 597  : 	return result;

	mov	eax, DWORD PTR _result$[ebp]

; 598  : }

	mov	esp, ebp
	pop	ebp
	ret	8
?GetBlockOwner@HeapInstance@@UAGKPAX@Z ENDP		; HeapInstance::GetBlockOwner
; Function compile flags: /Odtp
; File m:\archive\conquest\code\libs\src\dacom\baseheap.h
_TEXT	ENDS
;	COMDAT ?getOwner@BASE_BLOCK@@QAEKXZ
_TEXT	SEGMENT
_this$ = -4						; size = 4
?getOwner@BASE_BLOCK@@QAEKXZ PROC			; BASE_BLOCK::getOwner, COMDAT
; _this$ = ecx

; 58   : 	{

	push	ebp
	mov	ebp, esp
	push	ecx
	mov	DWORD PTR _this$[ebp], ecx

; 59   : 		return pOwner;

	mov	eax, DWORD PTR _this$[ebp]
	mov	eax, DWORD PTR [eax+12]

; 60   : 	}

	mov	esp, ebp
	pop	ebp
	ret	0
?getOwner@BASE_BLOCK@@QAEKXZ ENDP			; BASE_BLOCK::getOwner
_TEXT	ENDS
END
