//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by PrepStub99.rc
//
#define IDS_BUILDNUMBER                 1
#define STR_ILLEGALTOKEN                1
#define STR_NOMEMORY                    2
#define STR_APPTITLE                    3
#define IDCANCEL2                       3
#define IDOK2                           3
#define STR_FILENOTFOUND                4
#define IDCANCEL3                       4
#define STR_CANTOPENSOURCE              5
#define STR_MUSTHAVEOSFLAG              6
#define STR_CANTCREATEFILE              7
#define STR_OUTPUTHEADER                8
#define STR_WIN31_WARNING               9
#define STR_WINNT_WARNING               10
#define STR_CANTLOADDLL                 11
#define STR_WINNT_REQUIRED              12
#define STR_INVALID_SCRIPT              13
#define STR_BUILD_NUMBER                100
#define IDR_MENU1                       101
#define IDC_CURSOR1                     102
#define IDI_ICON1                       103
#define IDM_MENU                        105
#define IDI_SUITEMANAGERICON            113
#define IDI_PREPSTUB98ICON              113
#define IDD_TESTCASEPARAMS              114
#define IDD_ABOUT                       115
#define IDD_SOURCEDIR                   116
#define IDD_VIEWLIST                    117
#define IDD_BUILD_OLD                   118
#define IDD_DIALOG1                     119
#define IDC_SPLITH                      121
#define IDC_SPLITV                      122
#define IDM_COMMAND_ITEM_MENU           123
#define IDB_SPLASH                      125
#define IDI_COMMAND                     126
#define IDD_EDITCOMMAND                 127
#define IDD_DIALOG2                     128
#define ID_TOOLBAR                      129
#define IDB_CHECKBOXES                  131
#define IDB_OS_ICONS                    135
#define IDB_OS_ICONS_MASK               138
#define IDD_DIALOG3                     140
#define IDD_EDITCOMMANDDIALOG           140
#define IDD_BUILDSETTINGS               142
#define IDD_INJECT                      143
#define IDD_INJECTSETUP                 144
#define IDD_PROGRESS                    147
#define IDD_SAVEAS                      148
#define IDD_VERIFICATION                149
#define IDI_FOLDER                      151
#define IDI_NOTEBOOK                    152
#define IDD_STRINGSETTINGS              153
#define IDI_VERIFY                      154
#define IDI_INJECT                      155
#define IDI_STRINGS                     158
#define IDD_CONTEXTHELP                 162
#define IDD_BUILDDIALOG                 163
#define IDD_BUILD                       163
#define IDD_ADVANCEDINJECTSETTINGS      164
#define IDD_FUTURE_EDITCOMMANDDIALOG    165
#define IDM_EMPTY_RECENTLIST            167
#define IDD_PROP_GENERAL                168
#define IDD_PROP_VERIFICATION           169
#define IDD_PROP_TRIALVERSION           170
#define IDD_PROP_STRINGSETTINGS         171
#define IDD_PROP_INJECTSETTINGS         172
#define IDD_PROP_DEFAULTFLAGS           173
#define STR_FILE_FILTER_RC              201
#define STR_FILE_FILTER_BINARY          202
#define STR_FILE_FILTER_SCRIPT          203
#define STR_FILE_FILTER_EXE             204
#define STR_FILE_FILTER_SAVEAS          205
#define STR_FILE_FILTER_DLL             206
#define STR_TEXTOUTPUTHEADER            301
#define STR_SETSOURCEFOLDER             302
#define STR_SETDROPFOLDER               303
#define STR_LOADRULES_FAILED            400
#define STR_LOADHISTORY_FAILED          401
#define STR_BADSCRIPT                   402
#define STR_INITFAILED                  403
#define STR_BINWRITEFAILED              404
#define STR_RCWRITEFAILED               405
#define STR_COMMANDWITHNOFLAGS          406
#define STR_SETUPUPDATESUCCESS          407
#define STR_SETUPUPDATEFAILED           408
#define STR_SAVECHANGES                 409
#define STR_NODYNSECTION                410
#define STR_UPDATELISTFAILED            411
#define STR_CLEARFILELIST               413
#define STR_REPLICATEFAILED             414
#define STR_ADDFILESMESSAGE             415
#define STR_DROPDIREXISTS               416
#define STR_REPARENTEXISTS              417
#define STR_CANNOTCOPYFILE              418
#define STR_CANNOTCREATEDIR             419
#define STR_UNKNOWNRULEACTION           420
#define STR_LOADSTRINGLIST_FAILED       421
#define STR_UPDATESTRINGLISTFAILED      422
#define STR_DUPLICATESTRING             423
#define STR_NODYNSTRINGSECTION          424
#define STR_CREATEDYNSTRINGSECTIONFAILED 425
#define STR_CANCELREPLICATE             426
#define STR_STRINGNOTFOUND              427
#define STR_BADSUBSTSTRING              428
#define STR_CLEARDYNSTRINGLISTFAILED    429
#define STR_GENERICABORT                430
#define STR_BADSETUPFILE                431
#define STR_RENAME_R_U_SURE             432
#define STR_LOADSTATICSTRINGSWARNING    433
#define STR_LOADSTATICSTRINGSFAILED     434
#define STR_FILENOTWRITABLE             435
#define STR_CREATEDROPDIRFAILED         436
#define STR_CREATEREPARENTDIRFAILED     437
#define STR_DROPDIRNOTWRITABLE          438
#define STR_BADSETUPDLLFILE             439
#define STR_UNKNOWNBUILDTYPE            440
#define STR_SWITCHTOISO                 441
#define STR_SWITCHTOLFN                 442
#define STR_CREATEDISKDIRFAILED         443
#define STR_DISKDIREXISTS               444
#define STR_INVALID_DEPARENT_RULE       445
#define STR_CANNOTCOPYTOUNINSTALL       446
#define STR_UNINSTALLEXEEXISTS          447
#define STR_NOMAKECABEXE                448
#define STR_CANNOTCOPYTODLL             449
#define STR_BADACTIONSYNTAX             450
#define STR_MAKECABFAILED               451
#define STR_CABNOTFOUND                 452
#define STR_CANTCOPYTRIALEXE            453
#define STR_CANTINJECTCAB               454
#define STR_BINOPENFAILED               455
#define STR_NO_UPDATE_FILELIST          456
#define STR_SOURCEDIRINVALID            457
#define STR_NO_UPDATE_STRINGLIST        458
#define STR_NO_UPDATE_STATICSTRINGLIST  459
#define STR_MULTIDISK_FILE_NOT_UNIQUE   460
#define STR_BAD_COLORDEPTH              461
#define STR_BADCABFOLDERORDER           462
#define STR_CL_HEADER                   601
#define STR_CL_BUILD_UPDATEANDINJECT    602
#define STR_CL_BUILD_REPLICATE          603
#define STR_CL_BUILD_TRIAL              604
#define STR_CL_USAGE                    605
#define STR_CL_PRESSANY                 606
#define STR_CL_MISSING_FILENAME         607
#define STR_CL_UNKNOWN_PARAM            608
#define STR_CL_MISSING_BINARY           609
#define STR_CL_BUILD_SAVEASBINARY       610
#define IDC_OPEN                        1001
#define IDS_HELP_NOHELP                 1001
#define IDC_PARAM1_TYPE                 1002
#define IDS_HELP_SETUPLOCATION          1002
#define IDC_PARAM1_VALUE                1003
#define IDS_HELP_SETUPDLLLOCATION       1003
#define IDC_PARAM2_TYPE                 1004
#define IDC_PARAM3_TYPE                 1005
#define IDC_PARAM2_VALUE                1006
#define IDC_PARAM4_TYPE                 1007
#define IDC_PARAM5_TYPE                 1008
#define IDC_PARAM6_TYPE                 1009
#define IDC_PARAM3_VALUE                1010
#define IDC_PARAM4_VALUE                1011
#define IDC_PARAM5_VALUE                1012
#define IDC_PARAM6_VALUE                1013
#define IDC_TESTCASENAME                1015
#define IDC_TESTCASEPATH                1016
#define IDC_PARAM1_NAME                 1017
#define IDC_PARAM2_NAME                 1018
#define IDC_PARAM3_NAME                 1019
#define IDC_PARAM4_NAME                 1020
#define IDC_PARAM5_NAME                 1021
#define IDC_PARAM6_NAME                 1022
#define IDC_BUILDNUMBER                 1023
#define IDC_SOURCEDIR                   1024
#define IDC_VIEWLIST                    1026
#define IDC_TAB1                        1028
#define IDC_TREE1                       1029
#define IDC_LIST1                       1030
#define IDC_TASK                        1032
#define IDC_TASK2                       1036
#define IDC_SOURCEPATH                  1037
#define IDC_DROPPATH                    1038
#define IDC_REPARENTDIR                 1039
#define IDC_SETUPLOCATION               1040
#define IDC_ISOCHECK                    1041
#define IDC_SETUPDLLLOCATION            1041
#define IDBUILD                         1042
#define IDC_BTN_SOURCE                  1043
#define IDC_BTN_DROP                    1044
#define IDC_BTN_SETUP                   1045
#define IDB_UPDATE                      1046
#define IDC_BTN_SETUPDLL                1046
#define IDC_CB_WIN98                    1048
#define IDC_CB_NT40                     1049
#define IDC_CB_NT50                     1050
#define IDC_CB_DBCS                     1051
#define IDC_CB_OEM                      1052
#define IDC_CB_FRA                      1053
#define IDC_CB_GER                      1054
#define IDC_CB_JPN                      1055
#define IDC_CB_USA                      1056
#define IDC_CB_APP1                     1057
#define IDC_CB_RTL                      1058
#define IDC_CB_IMEENABLE                1059
#define IDC_CB_IMEON                    1060
#define IDC_CB_WIN95                    1065
#define IDC_CB_SPA                      1066
#define IDC_CB_LOC                      1067
#define IDC_CB_HIST                     1068
#define IDC_TOKEN                       1069
#define IDC_GROUPLIST                   1070
#define IDC_LANG                        1071
#define IDC_LOC                         1072
#define IDC_GROUPS                      1073
#define IDC_GROUPLIST2                  1074
#define IDC_COMBO1                      1078
#define IDC_OS                          1081
#define IDC_PARAMS                      1082
#define IDC_FORMATS                     1083
#define IDC_DONE                        1086
#define IDC_BUILD                       1087
#define IDC_LANG_COMBO                  1089
#define IDC_PROGRESS                    1091
#define IDC_STATUS                      1093
#define IDC_TASKLIST                    1095
#define IDC_LOCALIZATION                1096
#define IDC_LOADSCRIPTSTRINGS           1106
#define IDC_LOADDLLSTRINGS              1107
#define IDC_VERIFYSETTINGS              1108
#define IDC_IGNORESTRINGS               1108
#define IDC_STRINGSETTINGS              1109
#define IDC_REPLICATEFILETREE           1110
#define IDC_INJECTBINARYBLOB            1111
#define IDC_INJECTDYNAMICSTRINGS        1112
#define IDC_INJECTSTATICSTRINGS         1113
#define IDC_TEXT                        1114
#define IDC_BUTTON1                     1116
#define IDC_ADVANCEDINJECTSETTINGS      1116
#define IDC_UPDATEFILELIST              1117
#define IDC_DROPPATHTEXT                1118
#define IDC_REPARENTPATHTEXT            1119
#define IDC_SETUPEXETEXT                1120
#define IDC_DLLLOCATIONTEXT             1121
#define IDC_STATICSTRINGTEXT            1122
#define IDC_BUILDFLAGTEXT               1123
#define IDC_NOTEICON                    1124
#define IDC_RESOURCEANDINJECTTEXT       1125
#define IDC_STATICSTRINGOPTIONSTEXT     1126
#define IDC_VERIFICATIONTEXT            1127
#define IDC_TRIALEXE                    1129
#define IDC_MAKECABEXE                  1130
#define IDC_UNINSTALLEXE                1131
#define IDC_INJECTTEXT                  1132
#define IDC_STRINGTEXT                  1133
#define IDC_VERIFYTEXT1                 1134
#define IDC_VERIFYTEXT2                 1135
#define IDC_VERIFYTITLE                 1136
#define STR_CON_PROGRESS                2001
#define IDM_EXIT                        40001
#define IDM_ABOUT                       40002
#define IDM_ATTACH                      40003
#define IDM_LOADSCRIPT                  40003
#define IDM_CREATE_BINARY               40004
#define IDM_CREATE_RC                   40005
#define IDM_UPDATESETUP                 40006
#define IDM_READFILELIST                40007
#define IDM_VIEWLIST                    40008
#define IDM_LOADRULES                   40009
#define IDM_CREATE_LIST                 40010
#define IDM_SAVE                        40010
#define IDM_LOADHISTORY                 40011
#define IDM_AUTO                        40012
#define IDM_BUILD                       40012
#define IDM_REMOVEDYN                   40013
#define IDM_NEW                         40014
#define IDM_SAVEAS                      40015
#define ID_POPUP_DELETE                 40017
#define ID_POPUP_PROPERTIES             40018
#define IDM_UPDATE                      40019
#define ID_BUTTON40021                  40021
#define ID_BUTTON40022                  40022
#define ID_BUTTON40023                  40023
#define ID_BUTTON40024                  40024
#define ID_BUTTON40025                  40025
#define IDM_CLOSE                       40026
#define IDM_INJECT                      40027
#define IDM_UPDATEFILELIST              40028
#define IDM_BUILDSETTINGS               40029
#define ID_VIEW_OPTIONS                 40033
#define IDM_SHOWCOM                     40034
#define IDM_SHOWREG                     40035
#define IDM_SHOWINT                     40036
#define IDM_SHOWCOLOR                   40037
#define ID_EDIT_SELECTALL               40039
#define DIM_EXPORTBIN                   40045
#define ID_BUILD_EXPORTRESOURCECOMPILERRCFILE 40046
#define IDM_SHOWPROPERTY                40047
#define IDM_LOADSTRINGS                 40048
#define ID_AUTOSIZE                     40049
#define IDM_TESTME                      40050
#define IDM_SAVERC3                     40050
#define IDM_RECENTFILES                 40057
#define IDM_BUILD_TRIAL                 40060

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        174
#define _APS_NEXT_COMMAND_VALUE         40062
#define _APS_NEXT_CONTROL_VALUE         1137
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
