//--------------------------------------------------------------------------//
//                                                                          //
//                                 PCH.CPP                                  //
//                                                                          //
//                  COPYRIGHT (C) 1995 BY ORIGIN SYSTEMS, INC.              //
//                                                                          //
//--------------------------------------------------------------------------//
/*
    $Logfile:   F:/projects/jy/happy/vcs/pch.cpv  $

    $Revision:   1.1  $

    $Date:   08 May 1996 12:13:20  $

    $Author:   JYENAWINE  $
*/			    
//------------------------------- #INCLUDES --------------------------------//
//--------------------------------------------------------------------------//

#include <windows.h>


// This file exists solely for the purpose of creating a pre-compiled header


//------------------------------------------------------------------
/*
    $Log:   F:/projects/jy/happy/vcs/pch.cpv  $
 * 
 *    Rev 1.1   08 May 1996 12:13:20   JYENAWINE
 * new version
 * 
 *    Rev 1.0   03 Jan 1996 12:31:14   JYENAWINE
 * Initial revision.
 * 
 *    Rev 1.0   29 Aug 1995 00:16:54   JYENAWINE
 * Initial revision.
*/   
