; Listing generated by Microsoft (R) Optimizing Compiler Version 19.44.35223.0 

	TITLE	E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\Release\BaseHeap.obj
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRT
INCLUDELIB OLDNAMES

PUBLIC	?QueryInterface@BaseHeap@@UAG?AW4GENRESULT@@PBDPAPAX@Z ; BaseHeap::QueryInterface
PUBLIC	?AddRef@BaseHeap@@UAGKXZ			; BaseHeap::AddRef
PUBLIC	?Release@BaseHeap@@UAGKXZ			; BaseHeap::Release
PUBLIC	?CreateInstance@BaseHeap@@UAG?AW4GENRESULT@@PAUDACOMDESC@@PAPAX@Z ; BaseHeap::CreateInstance
PUBLIC	?AllocateMemory@BaseHeap@@UAGPAXKPBD@Z		; BaseHeap::AllocateMemory
PUBLIC	?ClearAllocateMemory@BaseHeap@@UAGPAXKPBDE@Z	; BaseHeap::ClearAllocateMemory
PUBLIC	?ReallocateMemory@BaseHeap@@UAGPAXPAXKPBD@Z	; BaseHeap::ReallocateMemory
PUBLIC	?FreeMemory@BaseHeap@@UAGJPAX@Z			; BaseHeap::FreeMemory
PUBLIC	?EnumerateBlocks@BaseHeap@@UAGJP6GJPAUIHeap@@PAXK1@Z1@Z ; BaseHeap::EnumerateBlocks
PUBLIC	?GetBlockSize@BaseHeap@@UAGKPAX@Z		; BaseHeap::GetBlockSize
PUBLIC	?GetBlockMessage@BaseHeap@@UAGPBDPAX@Z		; BaseHeap::GetBlockMessage
PUBLIC	?DidAlloc@BaseHeap@@UAGJPAX@Z			; BaseHeap::DidAlloc
PUBLIC	?GetAvailableMemory@BaseHeap@@UAGKXZ		; BaseHeap::GetAvailableMemory
PUBLIC	?GetLargestBlock@BaseHeap@@UAGKXZ		; BaseHeap::GetLargestBlock
PUBLIC	?GetHeapSize@BaseHeap@@UAGKXZ			; BaseHeap::GetHeapSize
PUBLIC	?SetErrorHandler@BaseHeap@@UAGP6AHUErrorCode@@PBDZZP6AH01ZZ@Z ; BaseHeap::SetErrorHandler
PUBLIC	?GetErrorHandler@BaseHeap@@UAGP6AHUErrorCode@@PBDZZXZ ; BaseHeap::GetErrorHandler
PUBLIC	?SetBlockOwner@BaseHeap@@UAGJPAXK@Z		; BaseHeap::SetBlockOwner
PUBLIC	?GetBlockOwner@BaseHeap@@UAGKPAX@Z		; BaseHeap::GetBlockOwner
PUBLIC	?SetBlockMessage@BaseHeap@@UAGJPAXPBD@Z		; BaseHeap::SetBlockMessage
PUBLIC	?HeapMinimize@BaseHeap@@UAGXXZ			; BaseHeap::HeapMinimize
PUBLIC	?GetHeapFlags@BaseHeap@@UAGKXZ			; BaseHeap::GetHeapFlags
PUBLIC	?AddToList@BaseHeap@@QAIHPAUHeapInstance@@@Z	; BaseHeap::AddToList
PUBLIC	?doError@BaseHeap@@QAEJKKK@Z			; BaseHeap::doError
PUBLIC	?AllocateMemory@MTHeapInstance@@UAGPAXKPBD@Z	; MTHeapInstance::AllocateMemory
PUBLIC	?ReallocateMemory@MTHeapInstance@@UAGPAXPAXKPBD@Z ; MTHeapInstance::ReallocateMemory
PUBLIC	?FreeMemory@MTHeapInstance@@UAGJPAX@Z		; MTHeapInstance::FreeMemory
PUBLIC	?EnumerateBlocks@MTHeapInstance@@UAGJP6GJPAUIHeap@@PAXK1@Z1@Z ; MTHeapInstance::EnumerateBlocks
PUBLIC	?GetBlockSize@MTHeapInstance@@UAGKPAX@Z		; MTHeapInstance::GetBlockSize
PUBLIC	?GetBlockMessage@MTHeapInstance@@UAGPBDPAX@Z	; MTHeapInstance::GetBlockMessage
PUBLIC	?DidAlloc@MTHeapInstance@@UAGJPAX@Z		; MTHeapInstance::DidAlloc
PUBLIC	?GetAvailableMemory@MTHeapInstance@@UAGKXZ	; MTHeapInstance::GetAvailableMemory
PUBLIC	?GetLargestBlock@MTHeapInstance@@UAGKXZ		; MTHeapInstance::GetLargestBlock
PUBLIC	?GetHeapSize@MTHeapInstance@@UAGKXZ		; MTHeapInstance::GetHeapSize
PUBLIC	?SetErrorHandler@MTHeapInstance@@UAGP6AHUErrorCode@@PBDZZP6AH01ZZ@Z ; MTHeapInstance::SetErrorHandler
PUBLIC	?GetErrorHandler@MTHeapInstance@@UAGP6AHUErrorCode@@PBDZZXZ ; MTHeapInstance::GetErrorHandler
PUBLIC	?SetBlockOwner@MTHeapInstance@@UAGJPAXK@Z	; MTHeapInstance::SetBlockOwner
PUBLIC	?GetBlockOwner@MTHeapInstance@@UAGKPAX@Z	; MTHeapInstance::GetBlockOwner
PUBLIC	?SetBlockMessage@MTHeapInstance@@UAGJPAXPBD@Z	; MTHeapInstance::SetBlockMessage
PUBLIC	?RegisterHeap@@YAXPAUICOManager@@@Z		; RegisterHeap
PUBLIC	??_7BaseHeap@@6B@				; BaseHeap::`vftable'
PUBLIC	??_7HeapInstance@@6B@				; HeapInstance::`vftable'
PUBLIC	??_7MTHeapInstance@@6B@				; MTHeapInstance::`vftable'
PUBLIC	??_C@_08EMNENPBA@instance@			; `string'
PUBLIC	??_C@_0EA@JPKIKKIB@E?3?2GitHub?2projects?2ConquestFWR?2@ ; `string'
PUBLIC	??_C@_0CE@JBJGEEGD@?$CFs?$CI?$CFd?$CJ?5?3?5FATAL?3Assertion?5failed@ ; `string'
PUBLIC	??_C@_0L@MDPAODCI@descriptor@			; `string'
PUBLIC	??_C@_0BD@BIJEMHFL@Heap?5control?5block@	; `string'
PUBLIC	??_C@_05EHEOJPMF@pHeap@				; `string'
PUBLIC	??_R0?AUIDAComponent@@@8			; IDAComponent `RTTI Type Descriptor'
PUBLIC	??_R3IDAComponent@@8				; IDAComponent::`RTTI Class Hierarchy Descriptor'
PUBLIC	??_R2IDAComponent@@8				; IDAComponent::`RTTI Base Class Array'
PUBLIC	??_R1A@?0A@EA@IDAComponent@@8			; IDAComponent::`RTTI Base Class Descriptor at (0,-1,0,64)'
PUBLIC	??_R0?AUIComponentFactory@@@8			; IComponentFactory `RTTI Type Descriptor'
PUBLIC	??_R3IComponentFactory@@8			; IComponentFactory::`RTTI Class Hierarchy Descriptor'
PUBLIC	??_R2IComponentFactory@@8			; IComponentFactory::`RTTI Base Class Array'
PUBLIC	??_R1A@?0A@EA@IComponentFactory@@8		; IComponentFactory::`RTTI Base Class Descriptor at (0,-1,0,64)'
PUBLIC	??_R0?AUIHeap@@@8				; IHeap `RTTI Type Descriptor'
PUBLIC	??_R3IHeap@@8					; IHeap::`RTTI Class Hierarchy Descriptor'
PUBLIC	??_R2IHeap@@8					; IHeap::`RTTI Base Class Array'
PUBLIC	??_R1A@?0A@EA@IHeap@@8				; IHeap::`RTTI Base Class Descriptor at (0,-1,0,64)'
PUBLIC	??_R4BaseHeap@@6B@				; BaseHeap::`RTTI Complete Object Locator'
PUBLIC	??_R0?AUBaseHeap@@@8				; BaseHeap `RTTI Type Descriptor'
PUBLIC	??_R3BaseHeap@@8				; BaseHeap::`RTTI Class Hierarchy Descriptor'
PUBLIC	??_R2BaseHeap@@8				; BaseHeap::`RTTI Base Class Array'
PUBLIC	??_R1A@?0A@EA@BaseHeap@@8			; BaseHeap::`RTTI Base Class Descriptor at (0,-1,0,64)'
PUBLIC	??_R4HeapInstance@@6B@				; HeapInstance::`RTTI Complete Object Locator'
PUBLIC	??_R0?AUHeapInstance@@@8			; HeapInstance `RTTI Type Descriptor'
PUBLIC	??_R3HeapInstance@@8				; HeapInstance::`RTTI Class Hierarchy Descriptor'
PUBLIC	??_R2HeapInstance@@8				; HeapInstance::`RTTI Base Class Array'
PUBLIC	??_R1A@?0A@EA@HeapInstance@@8			; HeapInstance::`RTTI Base Class Descriptor at (0,-1,0,64)'
PUBLIC	??_R4MTHeapInstance@@6B@			; MTHeapInstance::`RTTI Complete Object Locator'
PUBLIC	??_R0?AUMTHeapInstance@@@8			; MTHeapInstance `RTTI Type Descriptor'
PUBLIC	??_R3MTHeapInstance@@8				; MTHeapInstance::`RTTI Class Hierarchy Descriptor'
PUBLIC	??_R2MTHeapInstance@@8				; MTHeapInstance::`RTTI Base Class Array'
PUBLIC	??_R1A@?0A@EA@MTHeapInstance@@8			; MTHeapInstance::`RTTI Base Class Descriptor at (0,-1,0,64)'
EXTRN	??2@YAPAXI@Z:PROC				; operator new
EXTRN	??3@YAXPAXI@Z:PROC				; operator delete
EXTRN	__imp__InitializeCriticalSection@4:PROC
EXTRN	__imp__EnterCriticalSection@4:PROC
EXTRN	__imp__LeaveCriticalSection@4:PROC
EXTRN	__imp__DeleteCriticalSection@4:PROC
EXTRN	__imp__VirtualFree@12:PROC
EXTRN	__imp__LoadStringA@16:PROC
EXTRN	?malloc_pass_through@BaseHeap@@UAGPAXPBD@Z:PROC	; BaseHeap::malloc_pass_through
EXTRN	?realloc_pass_through@BaseHeap@@UAGPAXPBD@Z:PROC ; BaseHeap::realloc_pass_through
EXTRN	?calloc_pass_through@BaseHeap@@UAGPAXPBD@Z:PROC	; BaseHeap::calloc_pass_through
EXTRN	?Release@HeapInstance@@UAGKXZ:PROC		; HeapInstance::Release
EXTRN	?AllocateMemory@HeapInstance@@UAGPAXKPBD@Z:PROC	; HeapInstance::AllocateMemory
EXTRN	?ReallocateMemory@HeapInstance@@UAGPAXPAXKPBD@Z:PROC ; HeapInstance::ReallocateMemory
EXTRN	?FreeMemory@HeapInstance@@UAGJPAX@Z:PROC	; HeapInstance::FreeMemory
EXTRN	?EnumerateBlocks@HeapInstance@@UAGJP6GJPAUIHeap@@PAXK1@Z1@Z:PROC ; HeapInstance::EnumerateBlocks
EXTRN	?GetBlockSize@HeapInstance@@UAGKPAX@Z:PROC	; HeapInstance::GetBlockSize
EXTRN	?GetBlockMessage@HeapInstance@@UAGPBDPAX@Z:PROC	; HeapInstance::GetBlockMessage
EXTRN	?DidAlloc@HeapInstance@@UAGJPAX@Z:PROC		; HeapInstance::DidAlloc
EXTRN	?GetAvailableMemory@HeapInstance@@UAGKXZ:PROC	; HeapInstance::GetAvailableMemory
EXTRN	?GetLargestBlock@HeapInstance@@UAGKXZ:PROC	; HeapInstance::GetLargestBlock
EXTRN	?GetHeapSize@HeapInstance@@UAGKXZ:PROC		; HeapInstance::GetHeapSize
EXTRN	?SetErrorHandler@HeapInstance@@UAGP6AHUErrorCode@@PBDZZP6AH01ZZ@Z:PROC ; HeapInstance::SetErrorHandler
EXTRN	?GetErrorHandler@HeapInstance@@UAGP6AHUErrorCode@@PBDZZXZ:PROC ; HeapInstance::GetErrorHandler
EXTRN	?SetBlockOwner@HeapInstance@@UAGJPAXK@Z:PROC	; HeapInstance::SetBlockOwner
EXTRN	?GetBlockOwner@HeapInstance@@UAGKPAX@Z:PROC	; HeapInstance::GetBlockOwner
EXTRN	?SetBlockMessage@HeapInstance@@UAGJPAXPBD@Z:PROC ; HeapInstance::SetBlockMessage
EXTRN	?initHeap@HeapInstance@@QAE?AW4GENRESULT@@PAUDAHEAPDESC@@@Z:PROC ; HeapInstance::initHeap
EXTRN	?free@HeapInstance@@QAIHPAUFREE_BLOCK@@@Z:PROC	; HeapInstance::free
EXTRN	@__security_check_cookie@4:PROC
EXTRN	_memcpy:PROC
EXTRN	_memset:PROC
EXTRN	_HEAP:DWORD
EXTRN	_FDUMP:DWORD
EXTRN	?g_pMSHeap@@3PAUIHeap@@A:DWORD			; g_pMSHeap
EXTRN	?hInstance@@3PAUHINSTANCE__@@A:DWORD		; hInstance
EXTRN	??_7type_info@@6B@:QWORD			; type_info::`vftable'
EXTRN	___security_cookie:DWORD
;	COMDAT ??_R1A@?0A@EA@MTHeapInstance@@8
rdata$r	SEGMENT
??_R1A@?0A@EA@MTHeapInstance@@8 DD FLAT:??_R0?AUMTHeapInstance@@@8 ; MTHeapInstance::`RTTI Base Class Descriptor at (0,-1,0,64)'
	DD	05H
	DD	00H
	DD	0ffffffffH
	DD	00H
	DD	040H
	DD	FLAT:??_R3MTHeapInstance@@8
rdata$r	ENDS
;	COMDAT ??_R2MTHeapInstance@@8
rdata$r	SEGMENT
??_R2MTHeapInstance@@8 DD FLAT:??_R1A@?0A@EA@MTHeapInstance@@8 ; MTHeapInstance::`RTTI Base Class Array'
	DD	FLAT:??_R1A@?0A@EA@HeapInstance@@8
	DD	FLAT:??_R1A@?0A@EA@BaseHeap@@8
	DD	FLAT:??_R1A@?0A@EA@IHeap@@8
	DD	FLAT:??_R1A@?0A@EA@IComponentFactory@@8
	DD	FLAT:??_R1A@?0A@EA@IDAComponent@@8
rdata$r	ENDS
;	COMDAT ??_R3MTHeapInstance@@8
rdata$r	SEGMENT
??_R3MTHeapInstance@@8 DD 00H				; MTHeapInstance::`RTTI Class Hierarchy Descriptor'
	DD	00H
	DD	06H
	DD	FLAT:??_R2MTHeapInstance@@8
rdata$r	ENDS
;	COMDAT ??_R0?AUMTHeapInstance@@@8
data$rs	SEGMENT
??_R0?AUMTHeapInstance@@@8 DD FLAT:??_7type_info@@6B@	; MTHeapInstance `RTTI Type Descriptor'
	DD	00H
	DB	'.?AUMTHeapInstance@@', 00H
data$rs	ENDS
;	COMDAT ??_R4MTHeapInstance@@6B@
rdata$r	SEGMENT
??_R4MTHeapInstance@@6B@ DD 00H				; MTHeapInstance::`RTTI Complete Object Locator'
	DD	00H
	DD	00H
	DD	FLAT:??_R0?AUMTHeapInstance@@@8
	DD	FLAT:??_R3MTHeapInstance@@8
rdata$r	ENDS
;	COMDAT ??_R1A@?0A@EA@HeapInstance@@8
rdata$r	SEGMENT
??_R1A@?0A@EA@HeapInstance@@8 DD FLAT:??_R0?AUHeapInstance@@@8 ; HeapInstance::`RTTI Base Class Descriptor at (0,-1,0,64)'
	DD	04H
	DD	00H
	DD	0ffffffffH
	DD	00H
	DD	040H
	DD	FLAT:??_R3HeapInstance@@8
rdata$r	ENDS
;	COMDAT ??_R2HeapInstance@@8
rdata$r	SEGMENT
??_R2HeapInstance@@8 DD FLAT:??_R1A@?0A@EA@HeapInstance@@8 ; HeapInstance::`RTTI Base Class Array'
	DD	FLAT:??_R1A@?0A@EA@BaseHeap@@8
	DD	FLAT:??_R1A@?0A@EA@IHeap@@8
	DD	FLAT:??_R1A@?0A@EA@IComponentFactory@@8
	DD	FLAT:??_R1A@?0A@EA@IDAComponent@@8
rdata$r	ENDS
;	COMDAT ??_R3HeapInstance@@8
rdata$r	SEGMENT
??_R3HeapInstance@@8 DD 00H				; HeapInstance::`RTTI Class Hierarchy Descriptor'
	DD	00H
	DD	05H
	DD	FLAT:??_R2HeapInstance@@8
rdata$r	ENDS
;	COMDAT ??_R0?AUHeapInstance@@@8
data$rs	SEGMENT
??_R0?AUHeapInstance@@@8 DD FLAT:??_7type_info@@6B@	; HeapInstance `RTTI Type Descriptor'
	DD	00H
	DB	'.?AUHeapInstance@@', 00H
data$rs	ENDS
;	COMDAT ??_R4HeapInstance@@6B@
rdata$r	SEGMENT
??_R4HeapInstance@@6B@ DD 00H				; HeapInstance::`RTTI Complete Object Locator'
	DD	00H
	DD	00H
	DD	FLAT:??_R0?AUHeapInstance@@@8
	DD	FLAT:??_R3HeapInstance@@8
rdata$r	ENDS
;	COMDAT ??_R1A@?0A@EA@BaseHeap@@8
rdata$r	SEGMENT
??_R1A@?0A@EA@BaseHeap@@8 DD FLAT:??_R0?AUBaseHeap@@@8	; BaseHeap::`RTTI Base Class Descriptor at (0,-1,0,64)'
	DD	03H
	DD	00H
	DD	0ffffffffH
	DD	00H
	DD	040H
	DD	FLAT:??_R3BaseHeap@@8
rdata$r	ENDS
;	COMDAT ??_R2BaseHeap@@8
rdata$r	SEGMENT
??_R2BaseHeap@@8 DD FLAT:??_R1A@?0A@EA@BaseHeap@@8	; BaseHeap::`RTTI Base Class Array'
	DD	FLAT:??_R1A@?0A@EA@IHeap@@8
	DD	FLAT:??_R1A@?0A@EA@IComponentFactory@@8
	DD	FLAT:??_R1A@?0A@EA@IDAComponent@@8
rdata$r	ENDS
;	COMDAT ??_R3BaseHeap@@8
rdata$r	SEGMENT
??_R3BaseHeap@@8 DD 00H					; BaseHeap::`RTTI Class Hierarchy Descriptor'
	DD	00H
	DD	04H
	DD	FLAT:??_R2BaseHeap@@8
rdata$r	ENDS
;	COMDAT ??_R0?AUBaseHeap@@@8
data$rs	SEGMENT
??_R0?AUBaseHeap@@@8 DD FLAT:??_7type_info@@6B@		; BaseHeap `RTTI Type Descriptor'
	DD	00H
	DB	'.?AUBaseHeap@@', 00H
data$rs	ENDS
;	COMDAT ??_R4BaseHeap@@6B@
rdata$r	SEGMENT
??_R4BaseHeap@@6B@ DD 00H				; BaseHeap::`RTTI Complete Object Locator'
	DD	00H
	DD	00H
	DD	FLAT:??_R0?AUBaseHeap@@@8
	DD	FLAT:??_R3BaseHeap@@8
rdata$r	ENDS
;	COMDAT ??_R1A@?0A@EA@IHeap@@8
rdata$r	SEGMENT
??_R1A@?0A@EA@IHeap@@8 DD FLAT:??_R0?AUIHeap@@@8	; IHeap::`RTTI Base Class Descriptor at (0,-1,0,64)'
	DD	02H
	DD	00H
	DD	0ffffffffH
	DD	00H
	DD	040H
	DD	FLAT:??_R3IHeap@@8
rdata$r	ENDS
;	COMDAT ??_R2IHeap@@8
rdata$r	SEGMENT
??_R2IHeap@@8 DD FLAT:??_R1A@?0A@EA@IHeap@@8		; IHeap::`RTTI Base Class Array'
	DD	FLAT:??_R1A@?0A@EA@IComponentFactory@@8
	DD	FLAT:??_R1A@?0A@EA@IDAComponent@@8
rdata$r	ENDS
;	COMDAT ??_R3IHeap@@8
rdata$r	SEGMENT
??_R3IHeap@@8 DD 00H					; IHeap::`RTTI Class Hierarchy Descriptor'
	DD	00H
	DD	03H
	DD	FLAT:??_R2IHeap@@8
rdata$r	ENDS
;	COMDAT ??_R0?AUIHeap@@@8
data$rs	SEGMENT
??_R0?AUIHeap@@@8 DD FLAT:??_7type_info@@6B@		; IHeap `RTTI Type Descriptor'
	DD	00H
	DB	'.?AUIHeap@@', 00H
data$rs	ENDS
;	COMDAT ??_R1A@?0A@EA@IComponentFactory@@8
rdata$r	SEGMENT
??_R1A@?0A@EA@IComponentFactory@@8 DD FLAT:??_R0?AUIComponentFactory@@@8 ; IComponentFactory::`RTTI Base Class Descriptor at (0,-1,0,64)'
	DD	01H
	DD	00H
	DD	0ffffffffH
	DD	00H
	DD	040H
	DD	FLAT:??_R3IComponentFactory@@8
rdata$r	ENDS
;	COMDAT ??_R2IComponentFactory@@8
rdata$r	SEGMENT
??_R2IComponentFactory@@8 DD FLAT:??_R1A@?0A@EA@IComponentFactory@@8 ; IComponentFactory::`RTTI Base Class Array'
	DD	FLAT:??_R1A@?0A@EA@IDAComponent@@8
rdata$r	ENDS
;	COMDAT ??_R3IComponentFactory@@8
rdata$r	SEGMENT
??_R3IComponentFactory@@8 DD 00H			; IComponentFactory::`RTTI Class Hierarchy Descriptor'
	DD	00H
	DD	02H
	DD	FLAT:??_R2IComponentFactory@@8
rdata$r	ENDS
;	COMDAT ??_R0?AUIComponentFactory@@@8
data$rs	SEGMENT
??_R0?AUIComponentFactory@@@8 DD FLAT:??_7type_info@@6B@ ; IComponentFactory `RTTI Type Descriptor'
	DD	00H
	DB	'.?AUIComponentFactory@@', 00H
data$rs	ENDS
;	COMDAT ??_R1A@?0A@EA@IDAComponent@@8
rdata$r	SEGMENT
??_R1A@?0A@EA@IDAComponent@@8 DD FLAT:??_R0?AUIDAComponent@@@8 ; IDAComponent::`RTTI Base Class Descriptor at (0,-1,0,64)'
	DD	00H
	DD	00H
	DD	0ffffffffH
	DD	00H
	DD	040H
	DD	FLAT:??_R3IDAComponent@@8
rdata$r	ENDS
;	COMDAT ??_R2IDAComponent@@8
rdata$r	SEGMENT
??_R2IDAComponent@@8 DD FLAT:??_R1A@?0A@EA@IDAComponent@@8 ; IDAComponent::`RTTI Base Class Array'
rdata$r	ENDS
;	COMDAT ??_R3IDAComponent@@8
rdata$r	SEGMENT
??_R3IDAComponent@@8 DD 00H				; IDAComponent::`RTTI Class Hierarchy Descriptor'
	DD	00H
	DD	01H
	DD	FLAT:??_R2IDAComponent@@8
rdata$r	ENDS
;	COMDAT ??_R0?AUIDAComponent@@@8
data$rs	SEGMENT
??_R0?AUIDAComponent@@@8 DD FLAT:??_7type_info@@6B@	; IDAComponent `RTTI Type Descriptor'
	DD	00H
	DB	'.?AUIDAComponent@@', 00H
data$rs	ENDS
;	COMDAT ??_C@_05EHEOJPMF@pHeap@
CONST	SEGMENT
??_C@_05EHEOJPMF@pHeap@ DB 'pHeap', 00H			; `string'
CONST	ENDS
;	COMDAT ??_C@_0BD@BIJEMHFL@Heap?5control?5block@
CONST	SEGMENT
??_C@_0BD@BIJEMHFL@Heap?5control?5block@ DB 'Heap control block', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0L@MDPAODCI@descriptor@
CONST	SEGMENT
??_C@_0L@MDPAODCI@descriptor@ DB 'descriptor', 00H	; `string'
CONST	ENDS
;	COMDAT ??_C@_0CE@JBJGEEGD@?$CFs?$CI?$CFd?$CJ?5?3?5FATAL?3Assertion?5failed@
CONST	SEGMENT
??_C@_0CE@JBJGEEGD@?$CFs?$CI?$CFd?$CJ?5?3?5FATAL?3Assertion?5failed@ DB '%'
	DB	's(%d) : FATAL:Assertion failed: %s', 00H	; `string'
CONST	ENDS
;	COMDAT ??_C@_0EA@JPKIKKIB@E?3?2GitHub?2projects?2ConquestFWR?2@
CONST	SEGMENT
??_C@_0EA@JPKIKKIB@E?3?2GitHub?2projects?2ConquestFWR?2@ DB 'E:\GitHub\pr'
	DB	'ojects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.cpp', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_08EMNENPBA@instance@
CONST	SEGMENT
??_C@_08EMNENPBA@instance@ DB 'instance', 00H		; `string'
CONST	ENDS
_DATA	SEGMENT
?interface_name@@3PADA DB 'IHeap', 00H			; interface_name
	ORG $+2
?g_heap@@3UBaseHeap@@A DD FLAT:??_7BaseHeap@@6B@	; g_heap
	DD	01H
	DB	12 DUP(00H)
_DATA	ENDS
;	COMDAT ??_7MTHeapInstance@@6B@
CONST	SEGMENT
??_7MTHeapInstance@@6B@ DD FLAT:??_R4MTHeapInstance@@6B@ ; MTHeapInstance::`vftable'
	DD	FLAT:?QueryInterface@BaseHeap@@UAG?AW4GENRESULT@@PBDPAPAX@Z
	DD	FLAT:?AddRef@BaseHeap@@UAGKXZ
	DD	FLAT:?Release@HeapInstance@@UAGKXZ
	DD	FLAT:?CreateInstance@BaseHeap@@UAG?AW4GENRESULT@@PAUDACOMDESC@@PAPAX@Z
	DD	FLAT:?AllocateMemory@MTHeapInstance@@UAGPAXKPBD@Z
	DD	FLAT:?ClearAllocateMemory@BaseHeap@@UAGPAXKPBDE@Z
	DD	FLAT:?ReallocateMemory@MTHeapInstance@@UAGPAXPAXKPBD@Z
	DD	FLAT:?FreeMemory@MTHeapInstance@@UAGJPAX@Z
	DD	FLAT:?EnumerateBlocks@MTHeapInstance@@UAGJP6GJPAUIHeap@@PAXK1@Z1@Z
	DD	FLAT:?GetBlockSize@MTHeapInstance@@UAGKPAX@Z
	DD	FLAT:?GetBlockMessage@MTHeapInstance@@UAGPBDPAX@Z
	DD	FLAT:?DidAlloc@MTHeapInstance@@UAGJPAX@Z
	DD	FLAT:?GetAvailableMemory@MTHeapInstance@@UAGKXZ
	DD	FLAT:?GetLargestBlock@MTHeapInstance@@UAGKXZ
	DD	FLAT:?GetHeapSize@MTHeapInstance@@UAGKXZ
	DD	FLAT:?SetErrorHandler@MTHeapInstance@@UAGP6AHUErrorCode@@PBDZZP6AH01ZZ@Z
	DD	FLAT:?GetErrorHandler@MTHeapInstance@@UAGP6AHUErrorCode@@PBDZZXZ
	DD	FLAT:?SetBlockOwner@MTHeapInstance@@UAGJPAXK@Z
	DD	FLAT:?GetBlockOwner@MTHeapInstance@@UAGKPAX@Z
	DD	FLAT:?SetBlockMessage@MTHeapInstance@@UAGJPAXPBD@Z
	DD	FLAT:?HeapMinimize@BaseHeap@@UAGXXZ
	DD	FLAT:?GetHeapFlags@BaseHeap@@UAGKXZ
	DD	FLAT:?malloc_pass_through@BaseHeap@@UAGPAXPBD@Z
	DD	FLAT:?realloc_pass_through@BaseHeap@@UAGPAXPBD@Z
	DD	FLAT:?calloc_pass_through@BaseHeap@@UAGPAXPBD@Z
CONST	ENDS
;	COMDAT ??_7HeapInstance@@6B@
CONST	SEGMENT
??_7HeapInstance@@6B@ DD FLAT:??_R4HeapInstance@@6B@	; HeapInstance::`vftable'
	DD	FLAT:?QueryInterface@BaseHeap@@UAG?AW4GENRESULT@@PBDPAPAX@Z
	DD	FLAT:?AddRef@BaseHeap@@UAGKXZ
	DD	FLAT:?Release@HeapInstance@@UAGKXZ
	DD	FLAT:?CreateInstance@BaseHeap@@UAG?AW4GENRESULT@@PAUDACOMDESC@@PAPAX@Z
	DD	FLAT:?AllocateMemory@HeapInstance@@UAGPAXKPBD@Z
	DD	FLAT:?ClearAllocateMemory@BaseHeap@@UAGPAXKPBDE@Z
	DD	FLAT:?ReallocateMemory@HeapInstance@@UAGPAXPAXKPBD@Z
	DD	FLAT:?FreeMemory@HeapInstance@@UAGJPAX@Z
	DD	FLAT:?EnumerateBlocks@HeapInstance@@UAGJP6GJPAUIHeap@@PAXK1@Z1@Z
	DD	FLAT:?GetBlockSize@HeapInstance@@UAGKPAX@Z
	DD	FLAT:?GetBlockMessage@HeapInstance@@UAGPBDPAX@Z
	DD	FLAT:?DidAlloc@HeapInstance@@UAGJPAX@Z
	DD	FLAT:?GetAvailableMemory@HeapInstance@@UAGKXZ
	DD	FLAT:?GetLargestBlock@HeapInstance@@UAGKXZ
	DD	FLAT:?GetHeapSize@HeapInstance@@UAGKXZ
	DD	FLAT:?SetErrorHandler@HeapInstance@@UAGP6AHUErrorCode@@PBDZZP6AH01ZZ@Z
	DD	FLAT:?GetErrorHandler@HeapInstance@@UAGP6AHUErrorCode@@PBDZZXZ
	DD	FLAT:?SetBlockOwner@HeapInstance@@UAGJPAXK@Z
	DD	FLAT:?GetBlockOwner@HeapInstance@@UAGKPAX@Z
	DD	FLAT:?SetBlockMessage@HeapInstance@@UAGJPAXPBD@Z
	DD	FLAT:?HeapMinimize@BaseHeap@@UAGXXZ
	DD	FLAT:?GetHeapFlags@BaseHeap@@UAGKXZ
	DD	FLAT:?malloc_pass_through@BaseHeap@@UAGPAXPBD@Z
	DD	FLAT:?realloc_pass_through@BaseHeap@@UAGPAXPBD@Z
	DD	FLAT:?calloc_pass_through@BaseHeap@@UAGPAXPBD@Z
CONST	ENDS
;	COMDAT ??_7BaseHeap@@6B@
CONST	SEGMENT
??_7BaseHeap@@6B@ DD FLAT:??_R4BaseHeap@@6B@		; BaseHeap::`vftable'
	DD	FLAT:?QueryInterface@BaseHeap@@UAG?AW4GENRESULT@@PBDPAPAX@Z
	DD	FLAT:?AddRef@BaseHeap@@UAGKXZ
	DD	FLAT:?Release@BaseHeap@@UAGKXZ
	DD	FLAT:?CreateInstance@BaseHeap@@UAG?AW4GENRESULT@@PAUDACOMDESC@@PAPAX@Z
	DD	FLAT:?AllocateMemory@BaseHeap@@UAGPAXKPBD@Z
	DD	FLAT:?ClearAllocateMemory@BaseHeap@@UAGPAXKPBDE@Z
	DD	FLAT:?ReallocateMemory@BaseHeap@@UAGPAXPAXKPBD@Z
	DD	FLAT:?FreeMemory@BaseHeap@@UAGJPAX@Z
	DD	FLAT:?EnumerateBlocks@BaseHeap@@UAGJP6GJPAUIHeap@@PAXK1@Z1@Z
	DD	FLAT:?GetBlockSize@BaseHeap@@UAGKPAX@Z
	DD	FLAT:?GetBlockMessage@BaseHeap@@UAGPBDPAX@Z
	DD	FLAT:?DidAlloc@BaseHeap@@UAGJPAX@Z
	DD	FLAT:?GetAvailableMemory@BaseHeap@@UAGKXZ
	DD	FLAT:?GetLargestBlock@BaseHeap@@UAGKXZ
	DD	FLAT:?GetHeapSize@BaseHeap@@UAGKXZ
	DD	FLAT:?SetErrorHandler@BaseHeap@@UAGP6AHUErrorCode@@PBDZZP6AH01ZZ@Z
	DD	FLAT:?GetErrorHandler@BaseHeap@@UAGP6AHUErrorCode@@PBDZZXZ
	DD	FLAT:?SetBlockOwner@BaseHeap@@UAGJPAXK@Z
	DD	FLAT:?GetBlockOwner@BaseHeap@@UAGKPAX@Z
	DD	FLAT:?SetBlockMessage@BaseHeap@@UAGJPAXPBD@Z
	DD	FLAT:?HeapMinimize@BaseHeap@@UAGXXZ
	DD	FLAT:?GetHeapFlags@BaseHeap@@UAGKXZ
	DD	FLAT:?malloc_pass_through@BaseHeap@@UAGPAXPBD@Z
	DD	FLAT:?realloc_pass_through@BaseHeap@@UAGPAXPBD@Z
	DD	FLAT:?calloc_pass_through@BaseHeap@@UAGPAXPBD@Z
CONST	ENDS
; Function compile flags: /Ogtp
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.cpp
;	COMDAT ?RegisterHeap@@YAXPAUICOManager@@@Z
_TEXT	SEGMENT
_pManager$ = 8						; size = 4
?RegisterHeap@@YAXPAUICOManager@@@Z PROC		; RegisterHeap, COMDAT

; 633  : {

	push	ebp
	mov	ebp, esp

; 634  : 	pManager->RegisterComponent(&g_heap, interface_name);

	mov	eax, DWORD PTR _pManager$[ebp]
	push	-2147483648				; 80000000H
	push	OFFSET ?interface_name@@3PADA
	push	OFFSET ?g_heap@@3UBaseHeap@@A
	mov	ecx, DWORD PTR [eax]
	push	eax
	call	DWORD PTR [ecx+16]

; 635  : }

	pop	ebp
	ret	0
?RegisterHeap@@YAXPAUICOManager@@@Z ENDP		; RegisterHeap
_TEXT	ENDS
; Function compile flags: /Ogtp
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.h
;	COMDAT ?SetBlockMessage@MTHeapInstance@@UAGJPAXPBD@Z
_TEXT	SEGMENT
_this$ = 8						; size = 4
_allocatedBlock$ = 12					; size = 4
_msg$ = 16						; size = 4
?SetBlockMessage@MTHeapInstance@@UAGJPAXPBD@Z PROC	; MTHeapInstance::SetBlockMessage, COMDAT

; 479  : 	{

	push	ebp
	mov	ebp, esp
	push	esi

; 480  : 		EnterCriticalSection(&criticalSection);

	mov	esi, DWORD PTR _this$[ebp]
	push	edi
	lea	edi, DWORD PTR [esi+40]
	push	edi
	call	DWORD PTR __imp__EnterCriticalSection@4

; 481  : 		BOOL32 result = HeapInstance::SetBlockMessage(allocatedBlock, msg);

	push	DWORD PTR _msg$[ebp]
	push	DWORD PTR _allocatedBlock$[ebp]
	push	esi
	call	?SetBlockMessage@HeapInstance@@UAGJPAXPBD@Z ; HeapInstance::SetBlockMessage

; 482  : 		LeaveCriticalSection(&criticalSection);

	push	edi
	mov	esi, eax
	call	DWORD PTR __imp__LeaveCriticalSection@4

; 483  : 		return result;

	pop	edi
	mov	eax, esi
	pop	esi

; 484  : 	}

	pop	ebp
	ret	12					; 0000000cH
?SetBlockMessage@MTHeapInstance@@UAGJPAXPBD@Z ENDP	; MTHeapInstance::SetBlockMessage
_TEXT	ENDS
; Function compile flags: /Ogtp
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.h
;	COMDAT ?GetBlockOwner@MTHeapInstance@@UAGKPAX@Z
_TEXT	SEGMENT
_this$ = 8						; size = 4
_allocatedBlock$ = 12					; size = 4
?GetBlockOwner@MTHeapInstance@@UAGKPAX@Z PROC		; MTHeapInstance::GetBlockOwner, COMDAT

; 471  : 	{

	push	ebp
	mov	ebp, esp
	push	esi

; 472  : 		EnterCriticalSection(&criticalSection);

	mov	esi, DWORD PTR _this$[ebp]
	push	edi
	lea	edi, DWORD PTR [esi+40]
	push	edi
	call	DWORD PTR __imp__EnterCriticalSection@4

; 473  : 		U32 result = HeapInstance::GetBlockOwner(allocatedBlock);

	push	DWORD PTR _allocatedBlock$[ebp]
	push	esi
	call	?GetBlockOwner@HeapInstance@@UAGKPAX@Z	; HeapInstance::GetBlockOwner

; 474  : 		LeaveCriticalSection(&criticalSection);

	push	edi
	mov	esi, eax
	call	DWORD PTR __imp__LeaveCriticalSection@4

; 475  : 		return result;

	pop	edi
	mov	eax, esi
	pop	esi

; 476  : 	}

	pop	ebp
	ret	8
?GetBlockOwner@MTHeapInstance@@UAGKPAX@Z ENDP		; MTHeapInstance::GetBlockOwner
_TEXT	ENDS
; Function compile flags: /Ogtp
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.h
;	COMDAT ?SetBlockOwner@MTHeapInstance@@UAGJPAXK@Z
_TEXT	SEGMENT
_this$ = 8						; size = 4
_allocatedBlock$ = 12					; size = 4
_caller$ = 16						; size = 4
?SetBlockOwner@MTHeapInstance@@UAGJPAXK@Z PROC		; MTHeapInstance::SetBlockOwner, COMDAT

; 463  : 	{

	push	ebp
	mov	ebp, esp
	push	esi

; 464  : 		EnterCriticalSection(&criticalSection);

	mov	esi, DWORD PTR _this$[ebp]
	push	edi
	lea	edi, DWORD PTR [esi+40]
	push	edi
	call	DWORD PTR __imp__EnterCriticalSection@4

; 465  : 		BOOL32 result = HeapInstance::SetBlockOwner(allocatedBlock, caller);

	push	DWORD PTR _caller$[ebp]
	push	DWORD PTR _allocatedBlock$[ebp]
	push	esi
	call	?SetBlockOwner@HeapInstance@@UAGJPAXK@Z	; HeapInstance::SetBlockOwner

; 466  : 		LeaveCriticalSection(&criticalSection);

	push	edi
	mov	esi, eax
	call	DWORD PTR __imp__LeaveCriticalSection@4

; 467  : 		return result;

	pop	edi
	mov	eax, esi
	pop	esi

; 468  : 	}

	pop	ebp
	ret	12					; 0000000cH
?SetBlockOwner@MTHeapInstance@@UAGJPAXK@Z ENDP		; MTHeapInstance::SetBlockOwner
_TEXT	ENDS
; Function compile flags: /Ogtp
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.h
;	COMDAT ?GetErrorHandler@MTHeapInstance@@UAGP6AHUErrorCode@@PBDZZXZ
_TEXT	SEGMENT
_this$ = 8						; size = 4
?GetErrorHandler@MTHeapInstance@@UAGP6AHUErrorCode@@PBDZZXZ PROC ; MTHeapInstance::GetErrorHandler, COMDAT

; 455  : 	{

	push	ebp
	mov	ebp, esp
	push	esi

; 456  : 		EnterCriticalSection(&criticalSection);

	mov	esi, DWORD PTR _this$[ebp]
	push	edi
	lea	edi, DWORD PTR [esi+40]
	push	edi
	call	DWORD PTR __imp__EnterCriticalSection@4

; 457  : 		DA_ERROR_HANDLER result = HeapInstance::GetErrorHandler();

	push	esi
	call	?GetErrorHandler@HeapInstance@@UAGP6AHUErrorCode@@PBDZZXZ ; HeapInstance::GetErrorHandler

; 458  : 		LeaveCriticalSection(&criticalSection);

	push	edi
	mov	esi, eax
	call	DWORD PTR __imp__LeaveCriticalSection@4

; 459  : 		return result;

	pop	edi
	mov	eax, esi
	pop	esi

; 460  : 	}

	pop	ebp
	ret	4
?GetErrorHandler@MTHeapInstance@@UAGP6AHUErrorCode@@PBDZZXZ ENDP ; MTHeapInstance::GetErrorHandler
_TEXT	ENDS
; Function compile flags: /Ogtp
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.h
;	COMDAT ?SetErrorHandler@MTHeapInstance@@UAGP6AHUErrorCode@@PBDZZP6AH01ZZ@Z
_TEXT	SEGMENT
_this$ = 8						; size = 4
_proc$ = 12						; size = 4
?SetErrorHandler@MTHeapInstance@@UAGP6AHUErrorCode@@PBDZZP6AH01ZZ@Z PROC ; MTHeapInstance::SetErrorHandler, COMDAT

; 447  : 	{

	push	ebp
	mov	ebp, esp
	push	esi

; 448  : 		EnterCriticalSection(&criticalSection);

	mov	esi, DWORD PTR _this$[ebp]
	push	edi
	lea	edi, DWORD PTR [esi+40]
	push	edi
	call	DWORD PTR __imp__EnterCriticalSection@4

; 449  : 		DA_ERROR_HANDLER result = HeapInstance::SetErrorHandler(proc);

	push	DWORD PTR _proc$[ebp]
	push	esi
	call	?SetErrorHandler@HeapInstance@@UAGP6AHUErrorCode@@PBDZZP6AH01ZZ@Z ; HeapInstance::SetErrorHandler

; 450  : 		LeaveCriticalSection(&criticalSection);

	push	edi
	mov	esi, eax
	call	DWORD PTR __imp__LeaveCriticalSection@4

; 451  : 		return result;

	pop	edi
	mov	eax, esi
	pop	esi

; 452  : 	}

	pop	ebp
	ret	8
?SetErrorHandler@MTHeapInstance@@UAGP6AHUErrorCode@@PBDZZP6AH01ZZ@Z ENDP ; MTHeapInstance::SetErrorHandler
_TEXT	ENDS
; Function compile flags: /Ogtp
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.h
;	COMDAT ?GetHeapSize@MTHeapInstance@@UAGKXZ
_TEXT	SEGMENT
_this$ = 8						; size = 4
?GetHeapSize@MTHeapInstance@@UAGKXZ PROC		; MTHeapInstance::GetHeapSize, COMDAT

; 439  : 	{

	push	ebp
	mov	ebp, esp
	push	esi

; 440  : 		EnterCriticalSection(&criticalSection);

	mov	esi, DWORD PTR _this$[ebp]
	push	edi
	lea	edi, DWORD PTR [esi+40]
	push	edi
	call	DWORD PTR __imp__EnterCriticalSection@4

; 441  : 		U32 result = HeapInstance::GetHeapSize();		// original alloc - overhead

	push	esi
	call	?GetHeapSize@HeapInstance@@UAGKXZ	; HeapInstance::GetHeapSize

; 442  : 		LeaveCriticalSection(&criticalSection);

	push	edi
	mov	esi, eax
	call	DWORD PTR __imp__LeaveCriticalSection@4

; 443  : 		return result;

	pop	edi
	mov	eax, esi
	pop	esi

; 444  : 	}

	pop	ebp
	ret	4
?GetHeapSize@MTHeapInstance@@UAGKXZ ENDP		; MTHeapInstance::GetHeapSize
_TEXT	ENDS
; Function compile flags: /Ogtp
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.h
;	COMDAT ?GetLargestBlock@MTHeapInstance@@UAGKXZ
_TEXT	SEGMENT
_this$ = 8						; size = 4
?GetLargestBlock@MTHeapInstance@@UAGKXZ PROC		; MTHeapInstance::GetLargestBlock, COMDAT

; 431  : 	{

	push	ebp
	mov	ebp, esp
	push	esi

; 432  : 		EnterCriticalSection(&criticalSection);

	mov	esi, DWORD PTR _this$[ebp]
	push	edi
	lea	edi, DWORD PTR [esi+40]
	push	edi
	call	DWORD PTR __imp__EnterCriticalSection@4

; 433  : 		U32 result = HeapInstance::GetLargestBlock();

	push	esi
	call	?GetLargestBlock@HeapInstance@@UAGKXZ	; HeapInstance::GetLargestBlock

; 434  : 		LeaveCriticalSection(&criticalSection);

	push	edi
	mov	esi, eax
	call	DWORD PTR __imp__LeaveCriticalSection@4

; 435  : 		return result;

	pop	edi
	mov	eax, esi
	pop	esi

; 436  : 	}

	pop	ebp
	ret	4
?GetLargestBlock@MTHeapInstance@@UAGKXZ ENDP		; MTHeapInstance::GetLargestBlock
_TEXT	ENDS
; Function compile flags: /Ogtp
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.h
;	COMDAT ?GetAvailableMemory@MTHeapInstance@@UAGKXZ
_TEXT	SEGMENT
_this$ = 8						; size = 4
?GetAvailableMemory@MTHeapInstance@@UAGKXZ PROC		; MTHeapInstance::GetAvailableMemory, COMDAT

; 423  : 	{

	push	ebp
	mov	ebp, esp
	push	esi

; 424  : 		EnterCriticalSection(&criticalSection);

	mov	esi, DWORD PTR _this$[ebp]
	push	edi
	lea	edi, DWORD PTR [esi+40]
	push	edi
	call	DWORD PTR __imp__EnterCriticalSection@4

; 425  : 		U32 result = HeapInstance::GetAvailableMemory();

	push	esi
	call	?GetAvailableMemory@HeapInstance@@UAGKXZ ; HeapInstance::GetAvailableMemory

; 426  : 		LeaveCriticalSection(&criticalSection);

	push	edi
	mov	esi, eax
	call	DWORD PTR __imp__LeaveCriticalSection@4

; 427  : 		return result;

	pop	edi
	mov	eax, esi
	pop	esi

; 428  : 	}

	pop	ebp
	ret	4
?GetAvailableMemory@MTHeapInstance@@UAGKXZ ENDP		; MTHeapInstance::GetAvailableMemory
_TEXT	ENDS
; Function compile flags: /Ogtp
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.h
;	COMDAT ?DidAlloc@MTHeapInstance@@UAGJPAX@Z
_TEXT	SEGMENT
_this$ = 8						; size = 4
_allocatedBlock$ = 12					; size = 4
?DidAlloc@MTHeapInstance@@UAGJPAX@Z PROC		; MTHeapInstance::DidAlloc, COMDAT

; 415  : 	{

	push	ebp
	mov	ebp, esp
	push	esi

; 416  : 		EnterCriticalSection(&criticalSection);

	mov	esi, DWORD PTR _this$[ebp]
	push	edi
	lea	edi, DWORD PTR [esi+40]
	push	edi
	call	DWORD PTR __imp__EnterCriticalSection@4

; 417  : 		BOOL32 result = HeapInstance::DidAlloc(allocatedBlock);

	push	DWORD PTR _allocatedBlock$[ebp]
	push	esi
	call	?DidAlloc@HeapInstance@@UAGJPAX@Z	; HeapInstance::DidAlloc

; 418  : 		LeaveCriticalSection(&criticalSection);

	push	edi
	mov	esi, eax
	call	DWORD PTR __imp__LeaveCriticalSection@4

; 419  : 		return result;

	pop	edi
	mov	eax, esi
	pop	esi

; 420  : 	}

	pop	ebp
	ret	8
?DidAlloc@MTHeapInstance@@UAGJPAX@Z ENDP		; MTHeapInstance::DidAlloc
_TEXT	ENDS
; Function compile flags: /Ogtp
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.h
;	COMDAT ?GetBlockMessage@MTHeapInstance@@UAGPBDPAX@Z
_TEXT	SEGMENT
_this$ = 8						; size = 4
_allocatedBlock$ = 12					; size = 4
?GetBlockMessage@MTHeapInstance@@UAGPBDPAX@Z PROC	; MTHeapInstance::GetBlockMessage, COMDAT

; 407  : 	{

	push	ebp
	mov	ebp, esp
	push	esi

; 408  : 		EnterCriticalSection(&criticalSection);

	mov	esi, DWORD PTR _this$[ebp]
	push	edi
	lea	edi, DWORD PTR [esi+40]
	push	edi
	call	DWORD PTR __imp__EnterCriticalSection@4

; 409  : 		const C8 * result = HeapInstance::GetBlockMessage(allocatedBlock);

	push	DWORD PTR _allocatedBlock$[ebp]
	push	esi
	call	?GetBlockMessage@HeapInstance@@UAGPBDPAX@Z ; HeapInstance::GetBlockMessage

; 410  : 		LeaveCriticalSection(&criticalSection);

	push	edi
	mov	esi, eax
	call	DWORD PTR __imp__LeaveCriticalSection@4

; 411  : 		return result;

	pop	edi
	mov	eax, esi
	pop	esi

; 412  : 	}

	pop	ebp
	ret	8
?GetBlockMessage@MTHeapInstance@@UAGPBDPAX@Z ENDP	; MTHeapInstance::GetBlockMessage
_TEXT	ENDS
; Function compile flags: /Ogtp
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.h
;	COMDAT ?GetBlockSize@MTHeapInstance@@UAGKPAX@Z
_TEXT	SEGMENT
_this$ = 8						; size = 4
_allocatedBlock$ = 12					; size = 4
?GetBlockSize@MTHeapInstance@@UAGKPAX@Z PROC		; MTHeapInstance::GetBlockSize, COMDAT

; 399  : 	{

	push	ebp
	mov	ebp, esp
	push	esi

; 400  : 		EnterCriticalSection(&criticalSection);

	mov	esi, DWORD PTR _this$[ebp]
	push	edi
	lea	edi, DWORD PTR [esi+40]
	push	edi
	call	DWORD PTR __imp__EnterCriticalSection@4

; 401  : 		U32 result = HeapInstance::GetBlockSize(allocatedBlock);

	push	DWORD PTR _allocatedBlock$[ebp]
	push	esi
	call	?GetBlockSize@HeapInstance@@UAGKPAX@Z	; HeapInstance::GetBlockSize

; 402  : 		LeaveCriticalSection(&criticalSection);

	push	edi
	mov	esi, eax
	call	DWORD PTR __imp__LeaveCriticalSection@4

; 403  : 		return result;

	pop	edi
	mov	eax, esi
	pop	esi

; 404  : 	}

	pop	ebp
	ret	8
?GetBlockSize@MTHeapInstance@@UAGKPAX@Z ENDP		; MTHeapInstance::GetBlockSize
_TEXT	ENDS
; Function compile flags: /Ogtp
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.h
;	COMDAT ?EnumerateBlocks@MTHeapInstance@@UAGJP6GJPAUIHeap@@PAXK1@Z1@Z
_TEXT	SEGMENT
_this$ = 8						; size = 4
_proc$ = 12						; size = 4
_context$ = 16						; size = 4
?EnumerateBlocks@MTHeapInstance@@UAGJP6GJPAUIHeap@@PAXK1@Z1@Z PROC ; MTHeapInstance::EnumerateBlocks, COMDAT

; 391  : 	{

	push	ebp
	mov	ebp, esp
	push	esi

; 392  : 		EnterCriticalSection(&criticalSection);

	mov	esi, DWORD PTR _this$[ebp]
	push	edi
	lea	edi, DWORD PTR [esi+40]
	push	edi
	call	DWORD PTR __imp__EnterCriticalSection@4

; 393  : 		BOOL32 result = HeapInstance::EnumerateBlocks(proc, context);

	push	DWORD PTR _context$[ebp]
	push	DWORD PTR _proc$[ebp]
	push	esi
	call	?EnumerateBlocks@HeapInstance@@UAGJP6GJPAUIHeap@@PAXK1@Z1@Z ; HeapInstance::EnumerateBlocks

; 394  : 		LeaveCriticalSection(&criticalSection);

	push	edi
	mov	esi, eax
	call	DWORD PTR __imp__LeaveCriticalSection@4

; 395  : 		return result;

	pop	edi
	mov	eax, esi
	pop	esi

; 396  : 	}

	pop	ebp
	ret	12					; 0000000cH
?EnumerateBlocks@MTHeapInstance@@UAGJP6GJPAUIHeap@@PAXK1@Z1@Z ENDP ; MTHeapInstance::EnumerateBlocks
_TEXT	ENDS
; Function compile flags: /Ogtp
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.h
;	COMDAT ?FreeMemory@MTHeapInstance@@UAGJPAX@Z
_TEXT	SEGMENT
_this$ = 8						; size = 4
_allocatedBlock$ = 12					; size = 4
?FreeMemory@MTHeapInstance@@UAGJPAX@Z PROC		; MTHeapInstance::FreeMemory, COMDAT

; 379  : 	{

	push	ebp
	mov	ebp, esp

; 380  : 		if (allocatedBlock)

	cmp	DWORD PTR _allocatedBlock$[ebp], 0
	je	SHORT $LN2@FreeMemory

; 381  : 		{
; 382  : 			EnterCriticalSection(&criticalSection);

	push	esi
	mov	esi, DWORD PTR _this$[ebp]
	push	edi
	lea	edi, DWORD PTR [esi+40]
	push	edi
	call	DWORD PTR __imp__EnterCriticalSection@4

; 383  : 			BOOL32 result = HeapInstance::FreeMemory(allocatedBlock);

	push	DWORD PTR _allocatedBlock$[ebp]
	push	esi
	call	?FreeMemory@HeapInstance@@UAGJPAX@Z	; HeapInstance::FreeMemory

; 384  : 			LeaveCriticalSection(&criticalSection);

	push	edi
	mov	esi, eax
	call	DWORD PTR __imp__LeaveCriticalSection@4

; 385  : 			return result;

	pop	edi
	mov	eax, esi
	pop	esi

; 388  : 	}

	pop	ebp
	ret	8
$LN2@FreeMemory:

; 386  : 		}
; 387  : 		return 0;

	xor	eax, eax

; 388  : 	}

	pop	ebp
	ret	8
?FreeMemory@MTHeapInstance@@UAGJPAX@Z ENDP		; MTHeapInstance::FreeMemory
_TEXT	ENDS
; Function compile flags: /Ogtp
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.h
;	COMDAT ?ReallocateMemory@MTHeapInstance@@UAGPAXPAXKPBD@Z
_TEXT	SEGMENT
_this$ = 8						; size = 4
_prevBlock$ = 12					; size = 4
_newSize$ = 16						; size = 4
_msg$ = 20						; size = 4
?ReallocateMemory@MTHeapInstance@@UAGPAXPAXKPBD@Z PROC	; MTHeapInstance::ReallocateMemory, COMDAT

; 371  : 	{

	push	ebp
	mov	ebp, esp
	push	esi

; 372  : 		EnterCriticalSection(&criticalSection);

	mov	esi, DWORD PTR _this$[ebp]
	push	edi
	lea	edi, DWORD PTR [esi+40]
	push	edi
	call	DWORD PTR __imp__EnterCriticalSection@4

; 373  : 		void * result = HeapInstance::ReallocateMemory(prevBlock, newSize, msg);

	push	DWORD PTR _msg$[ebp]
	push	DWORD PTR _newSize$[ebp]
	push	DWORD PTR _prevBlock$[ebp]
	push	esi
	call	?ReallocateMemory@HeapInstance@@UAGPAXPAXKPBD@Z ; HeapInstance::ReallocateMemory

; 374  : 		LeaveCriticalSection(&criticalSection);

	push	edi
	mov	esi, eax
	call	DWORD PTR __imp__LeaveCriticalSection@4

; 375  : 		return result;

	pop	edi
	mov	eax, esi
	pop	esi

; 376  : 	}

	pop	ebp
	ret	16					; 00000010H
?ReallocateMemory@MTHeapInstance@@UAGPAXPAXKPBD@Z ENDP	; MTHeapInstance::ReallocateMemory
_TEXT	ENDS
; Function compile flags: /Ogtp
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.h
;	COMDAT ?AllocateMemory@MTHeapInstance@@UAGPAXKPBD@Z
_TEXT	SEGMENT
_this$ = 8						; size = 4
_numBytes$ = 12						; size = 4
_msg$ = 16						; size = 4
?AllocateMemory@MTHeapInstance@@UAGPAXKPBD@Z PROC	; MTHeapInstance::AllocateMemory, COMDAT

; 363  : 	{

	push	ebp
	mov	ebp, esp
	push	esi

; 364  : 		EnterCriticalSection(&criticalSection);

	mov	esi, DWORD PTR _this$[ebp]
	push	edi
	lea	edi, DWORD PTR [esi+40]
	push	edi
	call	DWORD PTR __imp__EnterCriticalSection@4

; 365  : 		void * result = HeapInstance::AllocateMemory(numBytes, msg);

	push	DWORD PTR _msg$[ebp]
	push	DWORD PTR _numBytes$[ebp]
	push	esi
	call	?AllocateMemory@HeapInstance@@UAGPAXKPBD@Z ; HeapInstance::AllocateMemory

; 366  : 		LeaveCriticalSection(&criticalSection);

	push	edi
	mov	esi, eax
	call	DWORD PTR __imp__LeaveCriticalSection@4

; 367  : 		return result;

	pop	edi
	mov	eax, esi
	pop	esi

; 368  : 	}

	pop	ebp
	ret	12					; 0000000cH
?AllocateMemory@MTHeapInstance@@UAGPAXKPBD@Z ENDP	; MTHeapInstance::AllocateMemory
_TEXT	ENDS
; Function compile flags: /Ogtp
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.cpp
;	COMDAT ?doError@BaseHeap@@QAEJKKK@Z
_TEXT	SEGMENT
_buffer$ = -132						; size = 128
__$ArrayPad$ = -4					; size = 4
_dwErrorNum$ = 8					; size = 4
_dwNum1$ = 12						; size = 4
_dwNum2$ = 16						; size = 4
?doError@BaseHeap@@QAEJKKK@Z PROC			; BaseHeap::doError, COMDAT
; _this$ = ecx

; 486  : {

	push	ebp
	mov	ebp, esp
	sub	esp, 132				; 00000084H
	mov	eax, DWORD PTR ___security_cookie
	xor	eax, ebp
	mov	DWORD PTR __$ArrayPad$[ebp], eax
	push	edi
	mov	edi, ecx

; 487  : 	char buffer[128];
; 488  : 	BOOL32 result = 0;
; 489  : 
; 490  : 	if (pErrorHandler)

	cmp	DWORD PTR [edi+8], 0
	je	$LN15@doError

; 491  : 	{
; 492  : 		LoadString(hInstance, dwErrorNum, buffer, sizeof(buffer));

	push	esi
	mov	esi, DWORD PTR _dwErrorNum$[ebp]
	lea	eax, DWORD PTR _buffer$[ebp]
	push	128					; 00000080H
	push	eax
	push	esi
	push	DWORD PTR ?hInstance@@3PAUHINSTANCE__@@A ; hInstance
	call	DWORD PTR __imp__LoadStringA@16

; 493  :  		if (dwErrorNum == DAHEAP_VALLOC_FAILED)

	cmp	esi, 7
	jne	SHORT $LN3@doError

; 494  : 		{
; 495  : 			result = pErrorHandler(ErrorCode(ERR_MEMORY, SEV_WARNING),

	push	DWORD PTR _dwNum2$[ebp]
	lea	eax, DWORD PTR _buffer$[ebp]
	push	DWORD PTR _dwNum1$[ebp]
	push	esi
	push	edi
	push	eax
	push	1048610					; 00100022H
$LN21@doError:

; 506  : 								   buffer,
; 507  : 								   this,
; 508  : 								   dwErrorNum,
; 509  : 								   dwNum1,
; 510  : 								   dwNum2);
; 511  : 		}
; 512  : 		else
; 513  : 		{
; 514  : 			result = pErrorHandler(ErrorCode(ERR_MEMORY, SEV_FATAL),

	mov	eax, DWORD PTR [edi+8]
	call	eax
	add	esp, 24					; 00000018H
	pop	esi
	pop	edi

; 515  : 								   buffer,
; 516  : 								   this,
; 517  : 								   dwErrorNum,
; 518  : 								   dwNum1,
; 519  : 								   dwNum2);
; 520  : 		}
; 521  : 	}
; 522  : 
; 523  : 	return result;
; 524  : }

	mov	ecx, DWORD PTR __$ArrayPad$[ebp]
	xor	ecx, ebp
	call	@__security_check_cookie@4
	mov	esp, ebp
	pop	ebp
	ret	12					; 0000000cH
$LN3@doError:

; 496  : 								   buffer,
; 497  : 								   this,
; 498  : 								   dwErrorNum,
; 499  : 								   dwNum1,
; 500  : 								   dwNum2);
; 501  : 		}
; 502  : 		else
; 503  :  		if (dwErrorNum == DAHEAP_HEAP_EXPANDING || dwErrorNum == DAHEAP_ALLOC_ZERO)

	cmp	esi, 6
	je	SHORT $LN7@doError
	cmp	esi, 2
	je	SHORT $LN7@doError

; 506  : 								   buffer,
; 507  : 								   this,
; 508  : 								   dwErrorNum,
; 509  : 								   dwNum1,
; 510  : 								   dwNum2);
; 511  : 		}
; 512  : 		else
; 513  : 		{
; 514  : 			result = pErrorHandler(ErrorCode(ERR_MEMORY, SEV_FATAL),

	push	DWORD PTR _dwNum2$[ebp]
	lea	eax, DWORD PTR _buffer$[ebp]
	push	DWORD PTR _dwNum1$[ebp]
	push	esi
	push	edi
	push	eax
	push	1048608					; 00100020H
	jmp	SHORT $LN21@doError
$LN7@doError:

; 504  : 		{
; 505  : 			result = pErrorHandler(ErrorCode(ERR_MEMORY, SEV_TRACE_2),

	push	DWORD PTR _dwNum2$[ebp]
	lea	eax, DWORD PTR _buffer$[ebp]
	push	DWORD PTR _dwNum1$[ebp]
	push	esi
	push	edi
	push	eax
	push	1048613					; 00100025H
	jmp	SHORT $LN21@doError
$LN15@doError:

; 515  : 								   buffer,
; 516  : 								   this,
; 517  : 								   dwErrorNum,
; 518  : 								   dwNum1,
; 519  : 								   dwNum2);
; 520  : 		}
; 521  : 	}
; 522  : 
; 523  : 	return result;
; 524  : }

	mov	ecx, DWORD PTR __$ArrayPad$[ebp]
	xor	eax, eax
	xor	ecx, ebp
	pop	edi
	call	@__security_check_cookie@4
	mov	esp, ebp
	pop	ebp
	ret	12					; 0000000cH
?doError@BaseHeap@@QAEJKKK@Z ENDP			; BaseHeap::doError
_TEXT	ENDS
; Function compile flags: /Ogtp
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.cpp
;	COMDAT ?AddToList@BaseHeap@@QAIHPAUHeapInstance@@@Z
_TEXT	SEGMENT
?AddToList@BaseHeap@@QAIHPAUHeapInstance@@@Z PROC	; BaseHeap::AddToList, COMDAT
; _this$ = ecx
; _pHeap$ = edx

; 180  : {

	push	esi
	push	edi
	mov	edi, edx
	mov	esi, ecx

; 181  : 	ASSERT(pHeap);

	test	edi, edi
	jne	SHORT $LN2@AddToList
	push	OFFSET ??_C@_05EHEOJPMF@pHeap@
	push	181					; 000000b5H
	push	OFFSET ??_C@_0EA@JPKIKKIB@E?3?2GitHub?2projects?2ConquestFWR?2@
	push	OFFSET ??_C@_0CE@JBJGEEGD@?$CFs?$CI?$CFd?$CJ?5?3?5FATAL?3Assertion?5failed@
	push	1048640					; 00100040H
	call	DWORD PTR _FDUMP
	add	esp, 20					; 00000014H
$LN2@AddToList:

; 182  : 
; 183  : 	BOOL result=0;
; 184  : 
; 185  : 	if (pHeapList==0)

	mov	eax, DWORD PTR [esi+16]
	test	eax, eax
	jne	SHORT $LN3@AddToList

; 186  : 	{
; 187  : 		if (this == &g_heap)

	cmp	esi, OFFSET ?g_heap@@3UBaseHeap@@A
	jne	SHORT $LN4@AddToList

; 188  : 			HEAP = this;

	mov	DWORD PTR _HEAP, esi

; 194  : 		pHeapList = pHeap;
; 195  : 	}
; 196  : 
; 197  : 	pHeap->SetErrorHandler(pErrorHandler);		// propogate error handler to new heap

	mov	DWORD PTR [esi+16], edi
	push	DWORD PTR [esi+8]
	mov	eax, DWORD PTR [edi]
	push	edi
	call	DWORD PTR [eax+60]

; 198  : 	
; 199  : 	return result;

	pop	edi
	xor	eax, eax
	pop	esi

; 200  : }

	ret	0
$LN3@AddToList:

; 189  : 		pHeapList = pHeap;
; 190  : 	}
; 191  : 	else
; 192  : 	{
; 193  : 		pHeap->pNext = pHeapList;

	mov	DWORD PTR [edi+16], eax
$LN4@AddToList:

; 194  : 		pHeapList = pHeap;
; 195  : 	}
; 196  : 
; 197  : 	pHeap->SetErrorHandler(pErrorHandler);		// propogate error handler to new heap

	mov	DWORD PTR [esi+16], edi
	push	DWORD PTR [esi+8]
	mov	eax, DWORD PTR [edi]
	push	edi
	call	DWORD PTR [eax+60]

; 198  : 	
; 199  : 	return result;

	pop	edi
	xor	eax, eax
	pop	esi

; 200  : }

	ret	0
?AddToList@BaseHeap@@QAIHPAUHeapInstance@@@Z ENDP	; BaseHeap::AddToList
_TEXT	ENDS
; Function compile flags: /Ogtp
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.cpp
;	COMDAT ?GetHeapFlags@BaseHeap@@UAGKXZ
_TEXT	SEGMENT
_this$ = 8						; size = 4
?GetHeapFlags@BaseHeap@@UAGKXZ PROC			; BaseHeap::GetHeapFlags, COMDAT

; 590  : {

	push	ebp
	mov	ebp, esp

; 591  : 	return (pHeapList) ? pHeapList->dwFlags : dwFlags;

	mov	eax, DWORD PTR _this$[ebp]
	mov	ecx, DWORD PTR [eax+16]
	test	ecx, ecx
	je	SHORT $LN3@GetHeapFla
	mov	eax, DWORD PTR [ecx+12]

; 592  : }

	pop	ebp
	ret	4
$LN3@GetHeapFla:

; 591  : 	return (pHeapList) ? pHeapList->dwFlags : dwFlags;

	mov	eax, DWORD PTR [eax+12]

; 592  : }

	pop	ebp
	ret	4
?GetHeapFlags@BaseHeap@@UAGKXZ ENDP			; BaseHeap::GetHeapFlags
_TEXT	ENDS
; Function compile flags: /Ogtp
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.cpp
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.h
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.cpp
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.h
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.cpp
;	COMDAT ?HeapMinimize@BaseHeap@@UAGXXZ
_TEXT	SEGMENT
_this$ = 8						; size = 4
?HeapMinimize@BaseHeap@@UAGXXZ PROC			; BaseHeap::HeapMinimize, COMDAT

; 556  : {

	push	ebp
	mov	ebp, esp

; 557  : 	HeapInstance *pList=pHeapList, *prev=0;

	mov	edx, DWORD PTR _this$[ebp]
	push	ebx
	push	esi
	xor	ebx, ebx
	mov	esi, DWORD PTR [edx+16]

; 558  : 
; 559  : 	if (pList)

	test	esi, esi
	je	SHORT $LN3@HeapMinimi

; 560  : 	while (pList->pNext)		// don't deallocate the initial heap

	cmp	DWORD PTR [esi+16], ebx
	je	SHORT $LN3@HeapMinimi
	push	edi
$LL2@HeapMinimi:
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.h

; 88   : 	return (dwSize & 1);

	mov	ecx, DWORD PTR [esi+28]
	mov	eax, DWORD PTR [ecx]
	test	al, 1
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.cpp

; 563  : 		if (((BASE_BLOCK *)pList->pHeapBase)->isAllocated() == 0 &&

	jne	SHORT $LN5@HeapMinimi
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.h

; 83   : 	return (BASE_BLOCK *) (((C8 *)this) + (dwSize & ~1));

	and	eax, -2					; fffffffeH
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.cpp

; 563  : 		if (((BASE_BLOCK *)pList->pHeapBase)->isAllocated() == 0 &&

	add	eax, DWORD PTR [esi+24]
	add	eax, ecx
	cmp	eax, esi
	jne	SHORT $LN5@HeapMinimi

; 564  : 			(((DWORD)((BASE_BLOCK *)pList->pHeapBase)->getLower()) + pList->dwBaseBlockSize) == (DWORD) pList)
; 565  : 		{
; 566  : 			HeapInstance *pTmp;
; 567  : 
; 568  : 			if (prev)

	mov	edi, DWORD PTR [esi+16]
	test	ebx, ebx
	je	SHORT $LN7@HeapMinimi

; 569  : 				pTmp = prev->pNext = pList->pNext;

	mov	DWORD PTR [ebx+16], edi
	jmp	SHORT $LN8@HeapMinimi
$LN7@HeapMinimi:

; 570  : 			else
; 571  : 				pTmp = pHeapList = pList->pNext;

	mov	DWORD PTR [edx+16], edi
$LN8@HeapMinimi:

; 572  : 
; 573  : 			if (pList->dwFlags & DAHEAPFLAG_MULTITHREADED)

	test	BYTE PTR [esi+12], 1
	je	SHORT $LN9@HeapMinimi

; 574  : 				DeleteCriticalSection(&pList->criticalSection);		

	lea	eax, DWORD PTR [esi+40]
	push	eax
	call	DWORD PTR __imp__DeleteCriticalSection@4
$LN9@HeapMinimi:

; 575  : 
; 576  : 			VirtualFree(pList->pHeapBase, 0, MEM_RELEASE);			// actually frees the instance too

	push	32768					; 00008000H
	push	0
	push	DWORD PTR [esi+28]
	call	DWORD PTR __imp__VirtualFree@12

; 577  : 
; 578  : 			pList = pTmp;
; 579  : 		}

	mov	edx, DWORD PTR _this$[ebp]
	mov	esi, edi
	jmp	SHORT $LN6@HeapMinimi
$LN5@HeapMinimi:

; 580  : 		else
; 581  : 		{
; 582  : 			prev = pList;

	mov	ebx, esi

; 583  : 			pList = pList->pNext;

	mov	esi, DWORD PTR [esi+16]
$LN6@HeapMinimi:

; 560  : 	while (pList->pNext)		// don't deallocate the initial heap

	cmp	DWORD PTR [esi+16], 0
	jne	SHORT $LL2@HeapMinimi
	pop	edi
$LN3@HeapMinimi:
	pop	esi

; 584  : 		}
; 585  : 	}
; 586  : }

	pop	ebx
	pop	ebp
	ret	4
?HeapMinimize@BaseHeap@@UAGXXZ ENDP			; BaseHeap::HeapMinimize
_TEXT	ENDS
; Function compile flags: /Ogtp
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.cpp
;	COMDAT ?SetBlockMessage@BaseHeap@@UAGJPAXPBD@Z
_TEXT	SEGMENT
_this$ = 8						; size = 4
_allocatedBlock$ = 12					; size = 4
_msg$ = 16						; size = 4
?SetBlockMessage@BaseHeap@@UAGJPAXPBD@Z PROC		; BaseHeap::SetBlockMessage, COMDAT

; 388  : {

	push	ebp
	mov	ebp, esp

; 207  : 	for (pList=pHeapList; pList; pList=pList->pNext)

	mov	eax, DWORD PTR _this$[ebp]
	mov	edx, DWORD PTR _allocatedBlock$[ebp]
	mov	eax, DWORD PTR [eax+16]
	test	eax, eax
	je	SHORT $LN2@SetBlockMe
$LL8@SetBlockMe:

; 208  : 	{
; 209  : 		// single comparison range check
; 210  : 		DWORD pos = (DWORD)baseAddress - (DWORD)pList->pHeapBase;

	mov	ecx, edx
	sub	ecx, DWORD PTR [eax+28]

; 211  : 		if (pos < pList->dwHeapSize)

	cmp	ecx, DWORD PTR [eax+32]
	jb	SHORT $LN16@SetBlockMe

; 207  : 	for (pList=pHeapList; pList; pList=pList->pNext)

	mov	eax, DWORD PTR [eax+16]
	test	eax, eax
	jne	SHORT $LL8@SetBlockMe
$LN2@SetBlockMe:

; 394  : 	else
; 395  : 		result = g_pMSHeap->SetBlockMessage(allocatedBlock, msg);

	mov	eax, DWORD PTR ?g_pMSHeap@@3PAUIHeap@@A	; g_pMSHeap
	mov	ecx, DWORD PTR [eax]
	mov	DWORD PTR _allocatedBlock$[ebp], edx
	mov	DWORD PTR _this$[ebp], eax

; 396  : 
; 397  : 	return result;
; 398  : }

	pop	ebp

; 394  : 	else
; 395  : 		result = g_pMSHeap->SetBlockMessage(allocatedBlock, msg);

	jmp	DWORD PTR [ecx+76]
$LN16@SetBlockMe:

; 389  : 	BaseHeap *pHeap = FindTheHeap(allocatedBlock);
; 390  : 	BOOL32 result;
; 391  : 
; 392  : 	if (pHeap)
; 393  : 		result = pHeap->SetBlockMessage(allocatedBlock, msg);

	mov	ecx, DWORD PTR [eax]
	mov	DWORD PTR _allocatedBlock$[ebp], edx
	mov	DWORD PTR _this$[ebp], eax

; 396  : 
; 397  : 	return result;
; 398  : }

	pop	ebp

; 389  : 	BaseHeap *pHeap = FindTheHeap(allocatedBlock);
; 390  : 	BOOL32 result;
; 391  : 
; 392  : 	if (pHeap)
; 393  : 		result = pHeap->SetBlockMessage(allocatedBlock, msg);

	jmp	DWORD PTR [ecx+76]
?SetBlockMessage@BaseHeap@@UAGJPAXPBD@Z ENDP		; BaseHeap::SetBlockMessage
_TEXT	ENDS
; Function compile flags: /Ogtp
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.cpp
;	COMDAT ?GetBlockOwner@BaseHeap@@UAGKPAX@Z
_TEXT	SEGMENT
_this$ = 8						; size = 4
_allocatedBlock$ = 12					; size = 4
?GetBlockOwner@BaseHeap@@UAGKPAX@Z PROC			; BaseHeap::GetBlockOwner, COMDAT

; 542  : {

	push	ebp
	mov	ebp, esp

; 207  : 	for (pList=pHeapList; pList; pList=pList->pNext)

	mov	eax, DWORD PTR _this$[ebp]
	mov	edx, DWORD PTR _allocatedBlock$[ebp]
	mov	eax, DWORD PTR [eax+16]
	test	eax, eax
	je	SHORT $LN2@GetBlockOw
$LL8@GetBlockOw:

; 208  : 	{
; 209  : 		// single comparison range check
; 210  : 		DWORD pos = (DWORD)baseAddress - (DWORD)pList->pHeapBase;

	mov	ecx, edx
	sub	ecx, DWORD PTR [eax+28]

; 211  : 		if (pos < pList->dwHeapSize)

	cmp	ecx, DWORD PTR [eax+32]
	jb	SHORT $LN16@GetBlockOw

; 207  : 	for (pList=pHeapList; pList; pList=pList->pNext)

	mov	eax, DWORD PTR [eax+16]
	test	eax, eax
	jne	SHORT $LL8@GetBlockOw
$LN2@GetBlockOw:

; 548  : 	else
; 549  : 		result = g_pMSHeap->GetBlockOwner(allocatedBlock);

	mov	eax, DWORD PTR ?g_pMSHeap@@3PAUIHeap@@A	; g_pMSHeap
	mov	ecx, DWORD PTR [eax]
	mov	DWORD PTR _allocatedBlock$[ebp], edx
	mov	DWORD PTR _this$[ebp], eax

; 550  : 
; 551  : 	return result;
; 552  : }

	pop	ebp

; 548  : 	else
; 549  : 		result = g_pMSHeap->GetBlockOwner(allocatedBlock);

	jmp	DWORD PTR [ecx+72]
$LN16@GetBlockOw:

; 543  : 	U32 result;
; 544  : 	BaseHeap *pHeap = FindTheHeap(allocatedBlock);
; 545  : 
; 546  : 	if (pHeap)
; 547  : 		result = pHeap->GetBlockOwner(allocatedBlock);

	mov	ecx, DWORD PTR [eax]
	mov	DWORD PTR _allocatedBlock$[ebp], edx
	mov	DWORD PTR _this$[ebp], eax

; 550  : 
; 551  : 	return result;
; 552  : }

	pop	ebp

; 543  : 	U32 result;
; 544  : 	BaseHeap *pHeap = FindTheHeap(allocatedBlock);
; 545  : 
; 546  : 	if (pHeap)
; 547  : 		result = pHeap->GetBlockOwner(allocatedBlock);

	jmp	DWORD PTR [ecx+72]
?GetBlockOwner@BaseHeap@@UAGKPAX@Z ENDP			; BaseHeap::GetBlockOwner
_TEXT	ENDS
; Function compile flags: /Ogtp
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.cpp
;	COMDAT ?SetBlockOwner@BaseHeap@@UAGJPAXK@Z
_TEXT	SEGMENT
_this$ = 8						; size = 4
_allocatedBlock$ = 12					; size = 4
_owner$ = 16						; size = 4
?SetBlockOwner@BaseHeap@@UAGJPAXK@Z PROC		; BaseHeap::SetBlockOwner, COMDAT

; 528  : {

	push	ebp
	mov	ebp, esp

; 207  : 	for (pList=pHeapList; pList; pList=pList->pNext)

	mov	eax, DWORD PTR _this$[ebp]
	mov	edx, DWORD PTR _allocatedBlock$[ebp]
	mov	eax, DWORD PTR [eax+16]
	test	eax, eax
	je	SHORT $LN2@SetBlockOw
$LL8@SetBlockOw:

; 208  : 	{
; 209  : 		// single comparison range check
; 210  : 		DWORD pos = (DWORD)baseAddress - (DWORD)pList->pHeapBase;

	mov	ecx, edx
	sub	ecx, DWORD PTR [eax+28]

; 211  : 		if (pos < pList->dwHeapSize)

	cmp	ecx, DWORD PTR [eax+32]
	jb	SHORT $LN16@SetBlockOw

; 207  : 	for (pList=pHeapList; pList; pList=pList->pNext)

	mov	eax, DWORD PTR [eax+16]
	test	eax, eax
	jne	SHORT $LL8@SetBlockOw
$LN2@SetBlockOw:

; 534  : 	else
; 535  : 		result = g_pMSHeap->SetBlockOwner(allocatedBlock, owner);

	mov	eax, DWORD PTR ?g_pMSHeap@@3PAUIHeap@@A	; g_pMSHeap
	mov	ecx, DWORD PTR [eax]
	mov	DWORD PTR _allocatedBlock$[ebp], edx
	mov	DWORD PTR _this$[ebp], eax

; 536  : 
; 537  : 	return result;
; 538  : }

	pop	ebp

; 534  : 	else
; 535  : 		result = g_pMSHeap->SetBlockOwner(allocatedBlock, owner);

	jmp	DWORD PTR [ecx+68]
$LN16@SetBlockOw:

; 529  : 	BOOL32 result;
; 530  : 	BaseHeap *pHeap = FindTheHeap(allocatedBlock);
; 531  : 
; 532  : 	if (pHeap)
; 533  : 		result = pHeap->SetBlockOwner(allocatedBlock, owner);

	mov	ecx, DWORD PTR [eax]
	mov	DWORD PTR _allocatedBlock$[ebp], edx
	mov	DWORD PTR _this$[ebp], eax

; 536  : 
; 537  : 	return result;
; 538  : }

	pop	ebp

; 529  : 	BOOL32 result;
; 530  : 	BaseHeap *pHeap = FindTheHeap(allocatedBlock);
; 531  : 
; 532  : 	if (pHeap)
; 533  : 		result = pHeap->SetBlockOwner(allocatedBlock, owner);

	jmp	DWORD PTR [ecx+68]
?SetBlockOwner@BaseHeap@@UAGJPAXK@Z ENDP		; BaseHeap::SetBlockOwner
_TEXT	ENDS
; Function compile flags: /Ogtp
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.cpp
;	COMDAT ?GetErrorHandler@BaseHeap@@UAGP6AHUErrorCode@@PBDZZXZ
_TEXT	SEGMENT
_this$ = 8						; size = 4
?GetErrorHandler@BaseHeap@@UAGP6AHUErrorCode@@PBDZZXZ PROC ; BaseHeap::GetErrorHandler, COMDAT

; 480  : {

	push	ebp
	mov	ebp, esp

; 481  : 	return pErrorHandler;

	mov	eax, DWORD PTR _this$[ebp]
	mov	eax, DWORD PTR [eax+8]

; 482  : }

	pop	ebp
	ret	4
?GetErrorHandler@BaseHeap@@UAGP6AHUErrorCode@@PBDZZXZ ENDP ; BaseHeap::GetErrorHandler
_TEXT	ENDS
; Function compile flags: /Ogtp
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.cpp
;	COMDAT ?SetErrorHandler@BaseHeap@@UAGP6AHUErrorCode@@PBDZZP6AH01ZZ@Z
_TEXT	SEGMENT
_this$ = 8						; size = 4
_proc$ = 12						; size = 4
?SetErrorHandler@BaseHeap@@UAGP6AHUErrorCode@@PBDZZP6AH01ZZ@Z PROC ; BaseHeap::SetErrorHandler, COMDAT

; 461  : {

	push	ebp
	mov	ebp, esp
	push	ebx
	push	esi

; 462  : 	DA_ERROR_HANDLER result = pErrorHandler;

	mov	esi, DWORD PTR _this$[ebp]
	push	edi

; 463  : 	HeapInstance *pList;
; 464  : 
; 465  : 	pErrorHandler = proc;

	mov	edi, DWORD PTR _proc$[ebp]
	mov	ebx, DWORD PTR [esi+8]
	mov	DWORD PTR [esi+8], edi

; 466  :  	
; 467  : 	if ((pList = pHeapList) != 0)

	mov	esi, DWORD PTR [esi+16]
	test	esi, esi
	je	SHORT $LN10@SetErrorHa
	npad	7
$LL4@SetErrorHa:

; 468  : 	do
; 469  : 	{
; 470  : 		pList->SetErrorHandler(proc);

	mov	ecx, DWORD PTR [esi]
	push	edi
	push	esi
	call	DWORD PTR [ecx+60]

; 471  : 		pList = pList->pNext;

	mov	esi, DWORD PTR [esi+16]

; 472  : 
; 473  : 	} while (pList != 0);

	test	esi, esi
	jne	SHORT $LL4@SetErrorHa
$LN10@SetErrorHa:
	pop	edi

; 474  : 	
; 475  : 	return result;
; 476  : }

	pop	esi
	mov	eax, ebx
	pop	ebx
	pop	ebp
	ret	8
?SetErrorHandler@BaseHeap@@UAGP6AHUErrorCode@@PBDZZP6AH01ZZ@Z ENDP ; BaseHeap::SetErrorHandler
_TEXT	ENDS
; Function compile flags: /Ogtp
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.cpp
;	COMDAT ?GetHeapSize@BaseHeap@@UAGKXZ
_TEXT	SEGMENT
_this$ = 8						; size = 4
?GetHeapSize@BaseHeap@@UAGKXZ PROC			; BaseHeap::GetHeapSize, COMDAT

; 444  : {

	push	ebp
	mov	ebp, esp
	push	esi

; 445  : 	U32 result=0;
; 446  : 	HeapInstance *pList;
; 447  : 	
; 448  : 	if ((pList = pHeapList) != 0)

	mov	esi, DWORD PTR _this$[ebp]
	push	edi
	xor	edi, edi
	mov	esi, DWORD PTR [esi+16]
	test	esi, esi
	je	SHORT $LN10@GetHeapSiz
$LL4@GetHeapSiz:

; 449  : 	do
; 450  : 	{
; 451  : 		result += pList->GetHeapSize();

	mov	ecx, DWORD PTR [esi]
	push	esi
	call	DWORD PTR [ecx+56]

; 452  : 		pList = pList->pNext;

	mov	esi, DWORD PTR [esi+16]
	add	edi, eax

; 453  : 
; 454  : 	} while (pList != 0);

	test	esi, esi
	jne	SHORT $LL4@GetHeapSiz
$LN10@GetHeapSiz:

; 455  : 
; 456  : 	return result;
; 457  : }

	mov	eax, edi
	pop	edi
	pop	esi
	pop	ebp
	ret	4
?GetHeapSize@BaseHeap@@UAGKXZ ENDP			; BaseHeap::GetHeapSize
_TEXT	ENDS
; Function compile flags: /Ogtp
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.cpp
;	COMDAT ?GetLargestBlock@BaseHeap@@UAGKXZ
_TEXT	SEGMENT
_this$ = 8						; size = 4
?GetLargestBlock@BaseHeap@@UAGKXZ PROC			; BaseHeap::GetLargestBlock, COMDAT

; 425  : {

	push	ebp
	mov	ebp, esp
	push	esi

; 426  : 	U32 result=0, tmp;
; 427  : 	HeapInstance *pList;
; 428  : 	
; 429  : 	if ((pList = pHeapList) != 0)

	mov	esi, DWORD PTR _this$[ebp]
	push	edi
	xor	edi, edi
	mov	esi, DWORD PTR [esi+16]
	test	esi, esi
	je	SHORT $LN10@GetLargest
$LL4@GetLargest:

; 430  : 	do
; 431  : 	{
; 432  : 		tmp = pList->GetLargestBlock();

	mov	eax, DWORD PTR [esi]
	push	esi
	call	DWORD PTR [eax+52]

; 433  : 		result = __max(result, tmp);
; 434  : 
; 435  : 		pList = pList->pNext;

	mov	esi, DWORD PTR [esi+16]
	cmp	edi, eax
	cmova	eax, edi
	mov	edi, eax

; 436  : 
; 437  : 	} while (pList != 0);

	test	esi, esi
	jne	SHORT $LL4@GetLargest
$LN10@GetLargest:

; 438  : 
; 439  : 	return result;
; 440  : }

	mov	eax, edi
	pop	edi
	pop	esi
	pop	ebp
	ret	4
?GetLargestBlock@BaseHeap@@UAGKXZ ENDP			; BaseHeap::GetLargestBlock
_TEXT	ENDS
; Function compile flags: /Ogtp
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.cpp
;	COMDAT ?GetAvailableMemory@BaseHeap@@UAGKXZ
_TEXT	SEGMENT
_this$ = 8						; size = 4
?GetAvailableMemory@BaseHeap@@UAGKXZ PROC		; BaseHeap::GetAvailableMemory, COMDAT

; 408  : {

	push	ebp
	mov	ebp, esp
	push	esi

; 409  : 	U32 result=0;
; 410  : 	HeapInstance *pList;
; 411  : 	
; 412  : 	if ((pList = pHeapList) != 0)

	mov	esi, DWORD PTR _this$[ebp]
	push	edi
	xor	edi, edi
	mov	esi, DWORD PTR [esi+16]
	test	esi, esi
	je	SHORT $LN10@GetAvailab
$LL4@GetAvailab:

; 413  : 	do
; 414  : 	{
; 415  : 		result += pList->GetAvailableMemory();

	mov	ecx, DWORD PTR [esi]
	push	esi
	call	DWORD PTR [ecx+48]

; 416  : 		pList = pList->pNext;

	mov	esi, DWORD PTR [esi+16]
	add	edi, eax

; 417  : 
; 418  : 	} while (pList != 0);

	test	esi, esi
	jne	SHORT $LL4@GetAvailab
$LN10@GetAvailab:

; 419  : 
; 420  : 	return result;
; 421  : }

	mov	eax, edi
	pop	edi
	pop	esi
	pop	ebp
	ret	4
?GetAvailableMemory@BaseHeap@@UAGKXZ ENDP		; BaseHeap::GetAvailableMemory
_TEXT	ENDS
; Function compile flags: /Ogtp
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.cpp
;	COMDAT ?DidAlloc@BaseHeap@@UAGJPAX@Z
_TEXT	SEGMENT
_this$ = 8						; size = 4
_allocatedBlock$ = 12					; size = 4
?DidAlloc@BaseHeap@@UAGJPAX@Z PROC			; BaseHeap::DidAlloc, COMDAT

; 402  : {

	push	ebp
	mov	ebp, esp

; 207  : 	for (pList=pHeapList; pList; pList=pList->pNext)

	mov	ecx, DWORD PTR _this$[ebp]
	mov	ecx, DWORD PTR [ecx+16]
	test	ecx, ecx
	je	SHORT $LN10@DidAlloc
	mov	edx, DWORD PTR _allocatedBlock$[ebp]
$LL6@DidAlloc:

; 208  : 	{
; 209  : 		// single comparison range check
; 210  : 		DWORD pos = (DWORD)baseAddress - (DWORD)pList->pHeapBase;

	mov	eax, edx
	sub	eax, DWORD PTR [ecx+28]

; 211  : 		if (pos < pList->dwHeapSize)

	cmp	eax, DWORD PTR [ecx+32]
	jb	SHORT $LN10@DidAlloc

; 207  : 	for (pList=pHeapList; pList; pList=pList->pNext)

	mov	ecx, DWORD PTR [ecx+16]
	test	ecx, ecx
	jne	SHORT $LL6@DidAlloc
$LN10@DidAlloc:

; 403  : 	return (FindTheHeap(allocatedBlock) != 0);

	xor	eax, eax
	test	ecx, ecx
	setne	al

; 404  : }

	pop	ebp
	ret	8
?DidAlloc@BaseHeap@@UAGJPAX@Z ENDP			; BaseHeap::DidAlloc
_TEXT	ENDS
; Function compile flags: /Ogtp
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.cpp
;	COMDAT ?GetBlockMessage@BaseHeap@@UAGPBDPAX@Z
_TEXT	SEGMENT
_this$ = 8						; size = 4
_allocatedBlock$ = 12					; size = 4
?GetBlockMessage@BaseHeap@@UAGPBDPAX@Z PROC		; BaseHeap::GetBlockMessage, COMDAT

; 374  : {

	push	ebp
	mov	ebp, esp

; 207  : 	for (pList=pHeapList; pList; pList=pList->pNext)

	mov	eax, DWORD PTR _this$[ebp]
	mov	edx, DWORD PTR _allocatedBlock$[ebp]
	mov	eax, DWORD PTR [eax+16]
	test	eax, eax
	je	SHORT $LN2@GetBlockMe
$LL8@GetBlockMe:

; 208  : 	{
; 209  : 		// single comparison range check
; 210  : 		DWORD pos = (DWORD)baseAddress - (DWORD)pList->pHeapBase;

	mov	ecx, edx
	sub	ecx, DWORD PTR [eax+28]

; 211  : 		if (pos < pList->dwHeapSize)

	cmp	ecx, DWORD PTR [eax+32]
	jb	SHORT $LN16@GetBlockMe

; 207  : 	for (pList=pHeapList; pList; pList=pList->pNext)

	mov	eax, DWORD PTR [eax+16]
	test	eax, eax
	jne	SHORT $LL8@GetBlockMe
$LN2@GetBlockMe:

; 380  : 	else
; 381  : 		result = g_pMSHeap->GetBlockMessage(allocatedBlock);

	mov	eax, DWORD PTR ?g_pMSHeap@@3PAUIHeap@@A	; g_pMSHeap
	mov	ecx, DWORD PTR [eax]
	mov	DWORD PTR _allocatedBlock$[ebp], edx
	mov	DWORD PTR _this$[ebp], eax

; 382  : 
; 383  : 	return result;
; 384  : }

	pop	ebp

; 380  : 	else
; 381  : 		result = g_pMSHeap->GetBlockMessage(allocatedBlock);

	jmp	DWORD PTR [ecx+40]
$LN16@GetBlockMe:

; 375  : 	BaseHeap *pHeap = FindTheHeap(allocatedBlock);
; 376  : 	const char *result;
; 377  : 
; 378  : 	if (pHeap)
; 379  : 		result = pHeap->GetBlockMessage(allocatedBlock);

	mov	ecx, DWORD PTR [eax]
	mov	DWORD PTR _allocatedBlock$[ebp], edx
	mov	DWORD PTR _this$[ebp], eax

; 382  : 
; 383  : 	return result;
; 384  : }

	pop	ebp

; 375  : 	BaseHeap *pHeap = FindTheHeap(allocatedBlock);
; 376  : 	const char *result;
; 377  : 
; 378  : 	if (pHeap)
; 379  : 		result = pHeap->GetBlockMessage(allocatedBlock);

	jmp	DWORD PTR [ecx+40]
?GetBlockMessage@BaseHeap@@UAGPBDPAX@Z ENDP		; BaseHeap::GetBlockMessage
_TEXT	ENDS
; Function compile flags: /Ogtp
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.cpp
;	COMDAT ?GetBlockSize@BaseHeap@@UAGKPAX@Z
_TEXT	SEGMENT
_this$ = 8						; size = 4
_allocatedBlock$ = 12					; size = 4
?GetBlockSize@BaseHeap@@UAGKPAX@Z PROC			; BaseHeap::GetBlockSize, COMDAT

; 360  : {

	push	ebp
	mov	ebp, esp

; 207  : 	for (pList=pHeapList; pList; pList=pList->pNext)

	mov	eax, DWORD PTR _this$[ebp]
	mov	edx, DWORD PTR _allocatedBlock$[ebp]
	mov	eax, DWORD PTR [eax+16]
	test	eax, eax
	je	SHORT $LN2@GetBlockSi
$LL8@GetBlockSi:

; 208  : 	{
; 209  : 		// single comparison range check
; 210  : 		DWORD pos = (DWORD)baseAddress - (DWORD)pList->pHeapBase;

	mov	ecx, edx
	sub	ecx, DWORD PTR [eax+28]

; 211  : 		if (pos < pList->dwHeapSize)

	cmp	ecx, DWORD PTR [eax+32]
	jb	SHORT $LN16@GetBlockSi

; 207  : 	for (pList=pHeapList; pList; pList=pList->pNext)

	mov	eax, DWORD PTR [eax+16]
	test	eax, eax
	jne	SHORT $LL8@GetBlockSi
$LN2@GetBlockSi:

; 366  : 	else
; 367  : 		result = g_pMSHeap->GetBlockSize(allocatedBlock);

	mov	eax, DWORD PTR ?g_pMSHeap@@3PAUIHeap@@A	; g_pMSHeap
	mov	ecx, DWORD PTR [eax]
	mov	DWORD PTR _allocatedBlock$[ebp], edx
	mov	DWORD PTR _this$[ebp], eax

; 368  : 
; 369  : 	return result;
; 370  : }

	pop	ebp

; 366  : 	else
; 367  : 		result = g_pMSHeap->GetBlockSize(allocatedBlock);

	jmp	DWORD PTR [ecx+36]
$LN16@GetBlockSi:

; 361  : 	HeapInstance *pHeap = FindTheHeap(allocatedBlock);
; 362  : 	U32 result;
; 363  : 
; 364  : 	if (pHeap)
; 365  : 		result = pHeap->GetBlockSize(allocatedBlock);

	mov	ecx, DWORD PTR [eax]
	mov	DWORD PTR _allocatedBlock$[ebp], edx
	mov	DWORD PTR _this$[ebp], eax

; 368  : 
; 369  : 	return result;
; 370  : }

	pop	ebp

; 361  : 	HeapInstance *pHeap = FindTheHeap(allocatedBlock);
; 362  : 	U32 result;
; 363  : 
; 364  : 	if (pHeap)
; 365  : 		result = pHeap->GetBlockSize(allocatedBlock);

	jmp	DWORD PTR [ecx+36]
?GetBlockSize@BaseHeap@@UAGKPAX@Z ENDP			; BaseHeap::GetBlockSize
_TEXT	ENDS
; Function compile flags: /Ogtp
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.cpp
;	COMDAT ?EnumerateBlocks@BaseHeap@@UAGJP6GJPAUIHeap@@PAXK1@Z1@Z
_TEXT	SEGMENT
_this$ = 8						; size = 4
_proc$ = 12						; size = 4
_context$ = 16						; size = 4
?EnumerateBlocks@BaseHeap@@UAGJP6GJPAUIHeap@@PAXK1@Z1@Z PROC ; BaseHeap::EnumerateBlocks, COMDAT

; 345  : {

	push	ebp
	mov	ebp, esp
	push	esi

; 346  : 	HeapInstance *pHeap = pHeapList;

	mov	esi, DWORD PTR _this$[ebp]

; 347  : 	BOOL32 result=1;

	mov	eax, 1
	mov	esi, DWORD PTR [esi+16]

; 348  : 
; 349  : 	while (pHeap && result)

	test	esi, esi
	je	SHORT $LN3@EnumerateB
	push	ebx
	mov	ebx, DWORD PTR _proc$[ebp]
	push	edi
	mov	edi, DWORD PTR _context$[ebp]
	npad	5
$LL2@EnumerateB:
	test	eax, eax
	je	SHORT $LN14@EnumerateB

; 350  : 	{
; 351  : 		result = pHeap->EnumerateBlocks(proc, context);

	mov	eax, DWORD PTR [esi]
	push	edi
	push	ebx
	push	esi
	call	DWORD PTR [eax+32]

; 352  : 		pHeap = pHeap->pNext;

	mov	esi, DWORD PTR [esi+16]
	test	esi, esi
	jne	SHORT $LL2@EnumerateB
$LN14@EnumerateB:
	pop	edi
	pop	ebx
$LN3@EnumerateB:
	pop	esi

; 353  : 	}
; 354  : 
; 355  : 	return result;
; 356  : }

	pop	ebp
	ret	12					; 0000000cH
?EnumerateBlocks@BaseHeap@@UAGJP6GJPAUIHeap@@PAXK1@Z1@Z ENDP ; BaseHeap::EnumerateBlocks
_TEXT	ENDS
; Function compile flags: /Ogtp
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.cpp
;	COMDAT ?FreeMemory@BaseHeap@@UAGJPAX@Z
_TEXT	SEGMENT
_this$ = 8						; size = 4
_allocatedBlock$ = 12					; size = 4
?FreeMemory@BaseHeap@@UAGJPAX@Z PROC			; BaseHeap::FreeMemory, COMDAT

; 327  : {

	push	ebp
	mov	ebp, esp

; 328  : 	BOOL32 result;
; 329  : 	
; 330  : 	if ((result = U32(allocatedBlock)) != 0)

	mov	edx, DWORD PTR _allocatedBlock$[ebp]
	test	edx, edx
	je	SHORT $LN18@FreeMemory

; 207  : 	for (pList=pHeapList; pList; pList=pList->pNext)

	mov	eax, DWORD PTR _this$[ebp]
	mov	eax, DWORD PTR [eax+16]
	test	eax, eax
	je	SHORT $LN3@FreeMemory
$LL9@FreeMemory:

; 208  : 	{
; 209  : 		// single comparison range check
; 210  : 		DWORD pos = (DWORD)baseAddress - (DWORD)pList->pHeapBase;

	mov	ecx, edx
	sub	ecx, DWORD PTR [eax+28]

; 211  : 		if (pos < pList->dwHeapSize)

	cmp	ecx, DWORD PTR [eax+32]
	jb	SHORT $LN17@FreeMemory

; 207  : 	for (pList=pHeapList; pList; pList=pList->pNext)

	mov	eax, DWORD PTR [eax+16]
	test	eax, eax
	jne	SHORT $LL9@FreeMemory
$LN3@FreeMemory:

; 336  : 		else
; 337  : 			result = g_pMSHeap->FreeMemory(allocatedBlock);

	mov	eax, DWORD PTR ?g_pMSHeap@@3PAUIHeap@@A	; g_pMSHeap
	mov	ecx, DWORD PTR [eax]
	mov	DWORD PTR _allocatedBlock$[ebp], edx
	mov	DWORD PTR _this$[ebp], eax

; 341  : }

	pop	ebp

; 336  : 		else
; 337  : 			result = g_pMSHeap->FreeMemory(allocatedBlock);

	jmp	DWORD PTR [ecx+28]
$LN17@FreeMemory:

; 331  : 	{
; 332  : 		BaseHeap *pHeap = FindTheHeap(allocatedBlock);
; 333  : 
; 334  : 		if (pHeap)
; 335  : 			result = pHeap->FreeMemory(allocatedBlock);

	mov	ecx, DWORD PTR [eax]
	mov	DWORD PTR _allocatedBlock$[ebp], edx
	mov	DWORD PTR _this$[ebp], eax

; 341  : }

	pop	ebp

; 331  : 	{
; 332  : 		BaseHeap *pHeap = FindTheHeap(allocatedBlock);
; 333  : 
; 334  : 		if (pHeap)
; 335  : 			result = pHeap->FreeMemory(allocatedBlock);

	jmp	DWORD PTR [ecx+28]
$LN18@FreeMemory:

; 338  : 	}
; 339  : 
; 340  : 	return result;

	mov	eax, edx

; 341  : }

	pop	ebp
	ret	8
?FreeMemory@BaseHeap@@UAGJPAX@Z ENDP			; BaseHeap::FreeMemory
_TEXT	ENDS
; Function compile flags: /Ogtp
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.cpp
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.h
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.cpp
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.h
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.cpp
;	COMDAT ?ReallocateMemory@BaseHeap@@UAGPAXPAXKPBD@Z
_TEXT	SEGMENT
_this$ = 8						; size = 4
_allocatedBlock$ = 12					; size = 4
_newSize$ = 16						; size = 4
_msg$ = 20						; size = 4
_result$1$ = 20						; size = 4
?ReallocateMemory@BaseHeap@@UAGPAXPAXKPBD@Z PROC	; BaseHeap::ReallocateMemory, COMDAT

; 289  : {

	push	ebp
	mov	ebp, esp
	push	ebx

; 290  : 	if (allocatedBlock == 0)

	mov	ebx, DWORD PTR _allocatedBlock$[ebp]
	test	ebx, ebx
	jne	SHORT $LN2@Reallocate

; 291  : 		return AllocateMemory(newSize, msg);

	mov	eax, DWORD PTR _this$[ebp]
	push	DWORD PTR _msg$[ebp]
	push	DWORD PTR _newSize$[ebp]
	mov	ecx, DWORD PTR [eax]
	push	eax
	call	DWORD PTR [ecx+16]
	pop	ebx

; 323  : }

	pop	ebp
	ret	16					; 00000010H
$LN2@Reallocate:
	push	esi

; 207  : 	for (pList=pHeapList; pList; pList=pList->pNext)

	mov	esi, DWORD PTR _this$[ebp]
	push	edi
	mov	esi, DWORD PTR [esi+16]
	test	esi, esi
	je	SHORT $LN3@Reallocate
	npad	5
$LL17@Reallocate:

; 208  : 	{
; 209  : 		// single comparison range check
; 210  : 		DWORD pos = (DWORD)baseAddress - (DWORD)pList->pHeapBase;

	mov	eax, ebx
	sub	eax, DWORD PTR [esi+28]

; 211  : 		if (pos < pList->dwHeapSize)

	cmp	eax, DWORD PTR [esi+32]
	jb	SHORT $LN40@Reallocate

; 207  : 	for (pList=pHeapList; pList; pList=pList->pNext)

	mov	esi, DWORD PTR [esi+16]
	test	esi, esi
	jne	SHORT $LL17@Reallocate
$LN3@Reallocate:

; 316  : 	else
; 317  : 	{
; 318  : 		result = g_pMSHeap->ReallocateMemory(allocatedBlock, newSize, msg);

	push	DWORD PTR _msg$[ebp]
	mov	eax, DWORD PTR ?g_pMSHeap@@3PAUIHeap@@A	; g_pMSHeap
	push	DWORD PTR _newSize$[ebp]
	push	ebx
	mov	ecx, DWORD PTR [eax]
	push	eax
	call	DWORD PTR [ecx+24]
	mov	ecx, eax
$Done$52:

; 322  : 	return result;

	pop	edi
	pop	esi
	mov	eax, ecx
	pop	ebx

; 323  : }

	pop	ebp
	ret	16					; 00000010H
$LN40@Reallocate:

; 292  : 
; 293  : 	HeapInstance *pHeap = FindTheHeap(allocatedBlock);
; 294  : 	void * result;
; 295  : 
; 296  : 	if (pHeap)
; 297  : 	{
; 298  : 		if ((result = pHeap->ReallocateMemory(allocatedBlock, newSize, msg)) == 0)

	push	DWORD PTR _msg$[ebp]
	mov	edi, DWORD PTR _newSize$[ebp]
	mov	eax, DWORD PTR [esi]
	push	edi
	push	ebx
	push	esi
	call	DWORD PTR [eax+24]
	mov	ecx, eax
	test	ecx, ecx
	jne	SHORT $Done$52

; 299  : 		{
; 300  : 			BASE_BLOCK *pBlock;
; 301  : 
; 302  : 			if (newSize == 0)

	test	edi, edi
	je	SHORT $Done$52
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.h

; 335  : 	pBlock = (BASE_BLOCK *) (((C8 *)_pBlock) - dwBaseBlockSize);

	mov	edi, ebx
	sub	edi, DWORD PTR [esi+24]

; 336  : 	if (dwFlags & DAHEAPFLAG_NOVERIFYPTR)

	test	BYTE PTR [esi+12], 4
	jne	SHORT $LN25@Reallocate

; 83   : 	return (BASE_BLOCK *) (((C8 *)this) + (dwSize & ~1));

	mov	eax, DWORD PTR [edi]
	and	eax, -2					; fffffffeH

; 340  : 	if (pBlock->getLower()->getUpper() != pBlock)

	cmp	DWORD PTR [eax+edi+4], edi
	jne	SHORT $Error$53

; 341  : 		goto Error;
; 342  : 	// upper block check
; 343  : 	if (pBlock->getUpper() && pBlock->getUpper()->getLower() != pBlock)

	mov	ecx, DWORD PTR [edi+4]
	test	ecx, ecx
	je	SHORT $LN25@Reallocate

; 83   : 	return (BASE_BLOCK *) (((C8 *)this) + (dwSize & ~1));

	mov	eax, DWORD PTR [ecx]
	and	eax, -2					; fffffffeH
	add	eax, ecx

; 343  : 	if (pBlock->getUpper() && pBlock->getUpper()->getLower() != pBlock)

	cmp	eax, edi
	jne	SHORT $Error$53
$LN25@Reallocate:
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.cpp

; 304  : 			if ((pBlock = pHeap->verifyBlock(allocatedBlock)) == 0)

	test	edi, edi
	je	SHORT $LN39@Reallocate

; 305  : 			{
; 306  : 				result = 0;
; 307  : 				goto Done;
; 308  : 			}
; 309  : 			if ((result = AllocateMemory(newSize, msg)) != 0)

	mov	ecx, DWORD PTR _this$[ebp]
	push	DWORD PTR _msg$[ebp]
	push	DWORD PTR _newSize$[ebp]
	mov	eax, DWORD PTR [ecx]
	push	ecx
	call	DWORD PTR [eax+16]
	mov	ecx, eax
	mov	DWORD PTR _result$1$[ebp], ecx
	test	ecx, ecx
	je	SHORT $Done$52

; 310  : 			{
; 311  : 				memcpy(result, allocatedBlock, __min((pBlock->dwSize&~1), newSize));

	mov	eax, DWORD PTR [edi]
	mov	edx, DWORD PTR _newSize$[ebp]
	and	eax, -2					; fffffffeH
	cmp	eax, edx
	cmovb	edx, eax
	push	edx
	push	ebx
	push	ecx
	call	_memcpy
	add	esp, 12					; 0000000cH

; 312  : 				pHeap->free((FREE_BLOCK *)pBlock);

	mov	edx, edi
	mov	ecx, esi
	call	?free@HeapInstance@@QAIHPAUFREE_BLOCK@@@Z ; HeapInstance::free

; 313  : 			}
; 314  : 		}
; 315  : 	}

	mov	ecx, DWORD PTR _result$1$[ebp]

; 322  : 	return result;

	mov	eax, ecx
	pop	edi
	pop	esi
	pop	ebx

; 323  : }

	pop	ebp
	ret	16					; 00000010H
$Error$53:
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.h

; 348  : 	if (EnumerateBlocks(0,0) == 0)

	mov	eax, DWORD PTR [esi]
	push	0
	push	0
	push	esi
	call	DWORD PTR [eax+32]

; 349  : 		doError(DAHEAP_HEAP_CORRUPTED);
; 350  : 	else
; 351  : 		doError(DAHEAP_INVALID_PTR, (DWORD)_pBlock);
; 352  : 	return 0;

	xor	ecx, ecx
	test	eax, eax
	push	0
	cmovne	ecx, ebx
	push	ecx
	xor	ecx, ecx
	test	eax, eax
	setne	cl
	add	ecx, 4
	push	ecx
	mov	ecx, esi
	call	?doError@BaseHeap@@QAEJKKK@Z		; BaseHeap::doError
$LN39@Reallocate:
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.cpp

; 322  : 	return result;

	pop	edi
	xor	ecx, ecx
	pop	esi
	mov	eax, ecx
	pop	ebx

; 323  : }

	pop	ebp
	ret	16					; 00000010H
?ReallocateMemory@BaseHeap@@UAGPAXPAXKPBD@Z ENDP	; BaseHeap::ReallocateMemory
_TEXT	ENDS
; Function compile flags: /Ogtp
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.cpp
;	COMDAT ?ClearAllocateMemory@BaseHeap@@UAGPAXKPBDE@Z
_TEXT	SEGMENT
_this$ = 8						; size = 4
_numBytes$ = 12						; size = 4
_msg$ = 16						; size = 4
_initChar$ = 20						; size = 1
?ClearAllocateMemory@BaseHeap@@UAGPAXKPBDE@Z PROC	; BaseHeap::ClearAllocateMemory, COMDAT

; 278  : {

	push	ebp
	mov	ebp, esp

; 279  : 	void * result;
; 280  : 
; 281  : 	if ((result = AllocateMemory(numBytes, msg)) != 0)

	mov	eax, DWORD PTR _this$[ebp]
	push	esi
	push	DWORD PTR _msg$[ebp]
	push	DWORD PTR _numBytes$[ebp]
	mov	ecx, DWORD PTR [eax]
	push	eax
	call	DWORD PTR [ecx+16]
	mov	esi, eax
	test	esi, esi
	je	SHORT $LN2@ClearAlloc

; 282  : 		memset(result, initChar, numBytes);

	push	DWORD PTR _numBytes$[ebp]
	movzx	ecx, BYTE PTR _initChar$[ebp]
	push	ecx
	push	esi
	call	_memset
	add	esp, 12					; 0000000cH

; 283  : 
; 284  : 	return result;

	mov	eax, esi
$LN2@ClearAlloc:
	pop	esi

; 285  : }

	pop	ebp
	ret	16					; 00000010H
?ClearAllocateMemory@BaseHeap@@UAGPAXKPBDE@Z ENDP	; BaseHeap::ClearAllocateMemory
_TEXT	ENDS
; Function compile flags: /Ogtp
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.cpp
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Include\HeapObj.h
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.cpp
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Include\HeapObj.h
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Include\DACOM.h
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Include\HeapObj.h
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.cpp
;	COMDAT ?AllocateMemory@BaseHeap@@UAGPAXKPBD@Z
_TEXT	SEGMENT
_desc$1 = -24						; size = 20
_result$1$ = -4						; size = 4
_this$ = 8						; size = 4
_pHeap$2 = 8						; size = 4
_numBytes$ = 12						; size = 4
_msg$ = 16						; size = 4
?AllocateMemory@BaseHeap@@UAGPAXKPBD@Z PROC		; BaseHeap::AllocateMemory, COMDAT

; 219  : {

	push	ebp
	mov	ebp, esp
	sub	esp, 24					; 00000018H
	push	ebx
	push	esi
	push	edi

; 220  : 	void * result=0;
; 221  : 	HeapInstance *pList;
; 222  : 	
; 223  : 	if (numBytes == 0)

	mov	edi, DWORD PTR _numBytes$[ebp]
	xor	esi, esi
	mov	DWORD PTR _result$1$[ebp], esi
	test	edi, edi
	jne	SHORT $LN45@AllocateMe

; 224  : 	{
; 225  : 		doError(DAHEAP_ALLOC_ZERO);

	mov	ecx, DWORD PTR _this$[ebp]
	push	edi
	push	edi
	push	2
	call	?doError@BaseHeap@@QAEJKKK@Z		; BaseHeap::doError
	pop	edi

; 270  : 	}
; 271  : 
; 272  : Done:
; 273  : 	return result;
; 274  : }

	pop	esi
	xor	eax, eax
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	12					; 0000000cH
$LN45@AllocateMe:

; 226  : 		goto Done;
; 227  : 	}
; 228  : 	if ((long)numBytes < 0)

	jns	SHORT $LN7@AllocateMe

; 229  : 	{
; 230  : 		doError(DAHEAP_OVERFLOW, numBytes);

	mov	ecx, DWORD PTR _this$[ebp]
	push	0
	push	edi
	push	3
	call	?doError@BaseHeap@@QAEJKKK@Z		; BaseHeap::doError
	pop	edi

; 270  : 	}
; 271  : 
; 272  : Done:
; 273  : 	return result;
; 274  : }

	pop	esi
	xor	eax, eax
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	12					; 0000000cH
$LN7@AllocateMe:

; 231  : 		goto Done;
; 232  : 	}
; 233  : 
; 234  : 	if ((pList = pHeapList) != 0)

	mov	ebx, DWORD PTR _this$[ebp]
	mov	esi, DWORD PTR [ebx+16]
	test	esi, esi
	je	SHORT $LN32@AllocateMe
$LL4@AllocateMe:

; 235  : 	do
; 236  : 	{
; 237  : 		if ((result = pList->AllocateMemory(numBytes, msg)) != 0)

	push	DWORD PTR _msg$[ebp]
	mov	eax, DWORD PTR [esi]
	push	edi
	push	esi
	call	DWORD PTR [eax+16]
	mov	DWORD PTR _result$1$[ebp], eax
	test	eax, eax
	jne	$Done$47

; 238  : 			goto Done;
; 239  : 		pList = pList->pNext;

	mov	esi, DWORD PTR [esi+16]

; 240  : 
; 241  : 	} while (pList != 0);

	test	esi, esi
	jne	SHORT $LL4@AllocateMe
$LN32@AllocateMe:

; 242  : 
; 243  : 	if (result == 0)
; 244  : 	{
; 245  : 		if (pHeapList && (pHeapList->dwFlags & DAHEAPFLAG_GROWHEAP))

	mov	ecx, DWORD PTR [ebx+16]
	test	ecx, ecx
	je	$LN15@AllocateMe
	mov	edx, DWORD PTR [ecx+12]
	test	dl, 32					; 00000020H
	je	$LN15@AllocateMe
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Include\HeapObj.h

; 97   : 		heapSize = 

	mov	DWORD PTR _desc$1[ebp+16], 0
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.cpp

; 251  : 			desc.heapSize = __max(desc.growSize, numBytes + sizeof(FREE_BLOCK)*4 + sizeof(HeapInstance));

	lea	eax, DWORD PTR [edi+128]
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Include\HeapObj.h

; 97   : 		heapSize = 

	mov	DWORD PTR _desc$1[ebp+12], 0
	mov	DWORD PTR _desc$1[ebp+8], 0
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Include\DACOM.h

; 444  : 		interface_name = _interface_name;

	mov	DWORD PTR _desc$1[ebp+4], OFFSET ?interface_name@@3PADA
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Include\HeapObj.h

; 100  : 		size = sizeof(*this);

	mov	DWORD PTR _desc$1[ebp], 20		; 00000014H
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.cpp

; 250  : 			desc.growSize = pHeapList->dwGrowSize;

	mov	ecx, DWORD PTR [ecx+36]

; 251  : 			desc.heapSize = __max(desc.growSize, numBytes + sizeof(FREE_BLOCK)*4 + sizeof(HeapInstance));

	cmp	ecx, eax
	mov	DWORD PTR _desc$1[ebp+16], ecx
	cmova	eax, ecx

; 252  : 			desc.flags = pHeapList->dwFlags;

	mov	DWORD PTR _desc$1[ebp+12], edx

; 253  : 
; 254  : 			if (CreateInstance(&desc, (void **)&pHeap) == GR_OK)

	lea	ecx, DWORD PTR _pHeap$2[ebp]
	mov	DWORD PTR _desc$1[ebp+8], eax
	mov	eax, DWORD PTR [ebx]
	push	ecx
	lea	ecx, DWORD PTR _desc$1[ebp]
	push	ecx
	push	ebx
	call	DWORD PTR [eax+12]
	test	eax, eax
	jne	SHORT $LN15@AllocateMe

; 255  : 			{
; 256  : 				result = pHeap->pHeapList->AllocateMemory(numBytes, msg);

	mov	eax, DWORD PTR _pHeap$2[ebp]
	push	DWORD PTR _msg$[ebp]
	push	edi
	mov	eax, DWORD PTR [eax+16]
	push	eax
	mov	ecx, DWORD PTR [eax]
	call	DWORD PTR [ecx+16]
	mov	esi, eax

; 257  : 				pHeap->Release();		// remove the extra reference

	mov	eax, DWORD PTR _pHeap$2[ebp]
	push	eax
	mov	DWORD PTR _result$1$[ebp], esi
	mov	ecx, DWORD PTR [eax]
	call	DWORD PTR [ecx+8]

; 258  : 				if (result != 0)

	test	esi, esi
	je	SHORT $LN15@AllocateMe

; 259  : 				{
; 260  : 					if( (pHeapList->dwFlags & DAHEAPFLAG_NOHEAPEXPANDMSG) == 0 )

	mov	eax, DWORD PTR [ebx+16]
	test	DWORD PTR [eax+12], 256			; 00000100H
	jne	SHORT $LN34@AllocateMe

; 261  : 					{
; 262  : 						doError(DAHEAP_HEAP_EXPANDING, desc.heapSize);	  // actually just a warning

	push	0
	push	DWORD PTR _desc$1[ebp+8]
	mov	ecx, ebx
	push	6
	call	?doError@BaseHeap@@QAEJKKK@Z		; BaseHeap::doError
$LN34@AllocateMe:

; 263  : 					}
; 264  : 					goto Done;
; 265  : 				}
; 266  : 			}
; 267  : 		}
; 268  : 		if (doError(DAHEAP_OUT_OF_MEMORY, numBytes, GetLargestBlock()))

	mov	eax, DWORD PTR _result$1$[ebp]
$Done$47:
	pop	edi

; 270  : 	}
; 271  : 
; 272  : Done:
; 273  : 	return result;
; 274  : }

	pop	esi
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	12					; 0000000cH
$LN15@AllocateMe:

; 263  : 					}
; 264  : 					goto Done;
; 265  : 				}
; 266  : 			}
; 267  : 		}
; 268  : 		if (doError(DAHEAP_OUT_OF_MEMORY, numBytes, GetLargestBlock()))

	mov	eax, DWORD PTR [ebx]
	push	ebx
	call	DWORD PTR [eax+52]
	push	eax
	push	edi
	push	1
	mov	ecx, ebx
	call	?doError@BaseHeap@@QAEJKKK@Z		; BaseHeap::doError
	test	eax, eax
	je	SHORT $LN34@AllocateMe

; 269  : 			return AllocateMemory(numBytes, msg);

	push	DWORD PTR _msg$[ebp]
	mov	eax, DWORD PTR [ebx]
	push	edi
	push	ebx
	call	DWORD PTR [eax+16]
	pop	edi

; 270  : 	}
; 271  : 
; 272  : Done:
; 273  : 	return result;
; 274  : }

	pop	esi
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	12					; 0000000cH
?AllocateMemory@BaseHeap@@UAGPAXKPBD@Z ENDP		; BaseHeap::AllocateMemory
_TEXT	ENDS
; Function compile flags: /Ogtp
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.cpp
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.h
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.cpp
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.h
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.cpp
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.h
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.cpp
;	COMDAT ?CreateInstance@BaseHeap@@UAG?AW4GENRESULT@@PAUDACOMDESC@@PAPAX@Z
_TEXT	SEGMENT
_stheap$ = -132						; size = 64
_mtheap$ = -68						; size = 64
$T1 = -4						; size = 4
_heap$1$ = -4						; size = 4
_this$ = 8						; size = 4
_result$1$ = 8						; size = 4
_descriptor$ = 12					; size = 4
_instance$ = 16						; size = 4
?CreateInstance@BaseHeap@@UAG?AW4GENRESULT@@PAUDACOMDESC@@PAPAX@Z PROC ; BaseHeap::CreateInstance, COMDAT

; 59   : {

	push	ebp
	mov	ebp, esp
	sub	esp, 132				; 00000084H

; 60   : 	ASSERT(instance);

	cmp	DWORD PTR _instance$[ebp], 0
	jne	SHORT $LN2@CreateInst
	push	OFFSET ??_C@_08EMNENPBA@instance@
	push	60					; 0000003cH
	push	OFFSET ??_C@_0EA@JPKIKKIB@E?3?2GitHub?2projects?2ConquestFWR?2@
	push	OFFSET ??_C@_0CE@JBJGEEGD@?$CFs?$CI?$CFd?$CJ?5?3?5FATAL?3Assertion?5failed@
	push	1048640					; 00100040H
	call	DWORD PTR _FDUMP
	add	esp, 20					; 00000014H
$LN2@CreateInst:

; 61   : 	ASSERT(descriptor);

	push	ebx
	mov	ebx, DWORD PTR _descriptor$[ebp]
	push	esi
	push	edi
	test	ebx, ebx
	jne	SHORT $LN3@CreateInst
	push	OFFSET ??_C@_0L@MDPAODCI@descriptor@
	push	61					; 0000003dH
	push	OFFSET ??_C@_0EA@JPKIKKIB@E?3?2GitHub?2projects?2ConquestFWR?2@
	push	OFFSET ??_C@_0CE@JBJGEEGD@?$CFs?$CI?$CFd?$CJ?5?3?5FATAL?3Assertion?5failed@
	push	1048640					; 00100040H
	call	DWORD PTR _FDUMP
	add	esp, 20					; 00000014H
$LN3@CreateInst:
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.h

; 198  : 		memset(((C8 *) this)+sizeof(BaseHeap), 0, sizeof(*this)-sizeof(BaseHeap));

	push	44					; 0000002cH
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.cpp

; 65   : 	HeapInstance *pNewHeap = NULL;

	xor	esi, esi
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.h

; 197  : 	{

	mov	DWORD PTR _stheap$[ebp], OFFSET ??_7HeapInstance@@6B@
	xorps	xmm0, xmm0

; 198  : 		memset(((C8 *) this)+sizeof(BaseHeap), 0, sizeof(*this)-sizeof(BaseHeap));

	lea	eax, DWORD PTR _stheap$[ebp+20]
	push	esi

; 116  : 		memset(((C8 *) this)+sizeof(DWORD), 0, sizeof(*this)-sizeof(DWORD));

	movups	XMMWORD PTR _stheap$[ebp+4], xmm0

; 198  : 		memset(((C8 *) this)+sizeof(BaseHeap), 0, sizeof(*this)-sizeof(BaseHeap));

	push	eax

; 117  : 		dwRefs=1;

	mov	DWORD PTR _stheap$[ebp+4], 1

; 198  : 		memset(((C8 *) this)+sizeof(BaseHeap), 0, sizeof(*this)-sizeof(BaseHeap));

	call	_memset
	push	44					; 0000002cH
	xorps	xmm0, xmm0
	lea	eax, DWORD PTR _mtheap$[ebp+20]
	push	esi

; 116  : 		memset(((C8 *) this)+sizeof(DWORD), 0, sizeof(*this)-sizeof(DWORD));

	movups	XMMWORD PTR _mtheap$[ebp+4], xmm0

; 198  : 		memset(((C8 *) this)+sizeof(BaseHeap), 0, sizeof(*this)-sizeof(BaseHeap));

	push	eax

; 117  : 		dwRefs=1;

	mov	DWORD PTR _mtheap$[ebp+4], 1

; 198  : 		memset(((C8 *) this)+sizeof(BaseHeap), 0, sizeof(*this)-sizeof(BaseHeap));

	call	_memset
	add	esp, 24					; 00000018H
	mov	DWORD PTR _mtheap$[ebp], OFFSET ??_7MTHeapInstance@@6B@
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.cpp

; 68   : 	HeapInstance & heap = (lpInfo->flags & DAHEAPFLAG_MULTITHREADED) ? *static_cast<HeapInstance *>(&mtheap) : stheap;

	test	BYTE PTR [ebx+12], 1
	lea	edi, DWORD PTR _mtheap$[ebp]
	lea	eax, DWORD PTR _stheap$[ebp]
	cmove	edi, eax

; 69   : 
; 70   : 	//
; 71   : 	// If unsupported interface requested, fail call
; 72   : 	//
; 73   : 
; 74   : 	if ((lpInfo->size != sizeof(*lpInfo)) || 

	cmp	DWORD PTR [ebx], 20			; 00000014H
	mov	DWORD PTR _heap$1$[ebp], edi
	jne	$LN5@CreateInst
	mov	eax, DWORD PTR [ebx+4]
	mov	ecx, OFFSET ?interface_name@@3PADA
$LL38@CreateInst:
	mov	dl, BYTE PTR [eax]
	cmp	dl, BYTE PTR [ecx]
	jne	SHORT $LN39@CreateInst
	test	dl, dl
	je	SHORT $LN40@CreateInst
	mov	dl, BYTE PTR [eax+1]
	cmp	dl, BYTE PTR [ecx+1]
	jne	SHORT $LN39@CreateInst
	add	eax, 2
	add	ecx, 2
	test	dl, dl
	jne	SHORT $LL38@CreateInst
$LN40@CreateInst:
	xor	eax, eax
	jmp	SHORT $LN41@CreateInst
$LN39@CreateInst:
	sbb	eax, eax
	or	eax, 1
$LN41@CreateInst:
	test	eax, eax
	jne	$LN5@CreateInst

; 78   : 		goto Done;
; 79   : 	}
; 80   : 
; 81   : 
; 82   : 
; 83   : 	heap.pErrorHandler = pErrorHandler;		// propogate error handler to new heap

	mov	ebx, DWORD PTR _this$[ebp]

; 84   : 	
; 85   : 	if ((result = heap.initHeap(lpInfo)) == GR_OK)

	mov	ecx, edi
	push	DWORD PTR _descriptor$[ebp]
	mov	eax, DWORD PTR [ebx+8]
	mov	DWORD PTR [edi+8], eax
	call	?initHeap@HeapInstance@@QAE?AW4GENRESULT@@PAUDAHEAPDESC@@@Z ; HeapInstance::initHeap
	mov	edi, eax
	mov	DWORD PTR _result$1$[ebp], edi
	test	edi, edi
	jne	$Done$58

; 86   : 	{
; 87   : 		if ((pNewHeap = (HeapInstance *) heap.AllocateMemory(sizeof(HeapInstance), "Heap control block")) == 0)

	mov	ecx, DWORD PTR _heap$1$[ebp]
	push	OFFSET ??_C@_0BD@BIJEMHFL@Heap?5control?5block@
	push	64					; 00000040H
	push	ecx
	mov	eax, DWORD PTR [ecx]
	call	DWORD PTR [eax+16]
	mov	esi, eax
	test	esi, esi
	je	$LN56@CreateInst

; 88   : 		{
; 89   : 			result = GR_OUT_OF_MEMORY;
; 90   : 			goto Done;
; 91   : 		}
; 92   : 	
; 93   : 		memcpy(pNewHeap, &heap, sizeof(HeapInstance));

	mov	eax, DWORD PTR _heap$1$[ebp]
	movups	xmm0, XMMWORD PTR [eax]
	movups	XMMWORD PTR [esi], xmm0
	movups	xmm0, XMMWORD PTR [eax+16]
	movups	XMMWORD PTR [esi+16], xmm0
	movups	xmm0, XMMWORD PTR [eax+32]
	movups	XMMWORD PTR [esi+32], xmm0
	movups	xmm0, XMMWORD PTR [eax+48]
	movups	XMMWORD PTR [esi+48], xmm0

; 94   : 		if (pNewHeap->dwFlags & DAHEAPFLAG_MULTITHREADED)

	test	BYTE PTR [esi+12], 1
	je	SHORT $LN10@CreateInst

; 95   : 		{
; 96   : 			// move criticalsection to the new location
; 97   : 			DeleteCriticalSection(&heap.criticalSection);

	add	eax, 40					; 00000028H
	push	eax
	call	DWORD PTR __imp__DeleteCriticalSection@4

; 98   : 			InitializeCriticalSection(&pNewHeap->criticalSection);	

	lea	eax, DWORD PTR [esi+40]
	push	eax
	call	DWORD PTR __imp__InitializeCriticalSection@4
$LN10@CreateInst:

; 99   : 		}
; 100  : 		
; 101  : 		// successfully created the heap, now add it to a list
; 102  : 		if (((dwFlags ^ lpInfo->flags) & DAHEAPFLAG_PRIVATE) == 0)

	mov	eax, DWORD PTR _descriptor$[ebp]
	mov	ecx, DWORD PTR [ebx+12]
	mov	eax, DWORD PTR [eax+12]
	xor	eax, ecx
	test	al, 8
	jne	SHORT $LN11@CreateInst

; 103  : 		{
; 104  : 			// adding to the size of an existing heap
; 105  : 			AddToList(pNewHeap);

	mov	edx, esi
	mov	ecx, ebx
	call	?AddToList@BaseHeap@@QAIHPAUHeapInstance@@@Z ; BaseHeap::AddToList

; 106  : 			AddRef();

	mov	eax, DWORD PTR [ebx]
	push	ebx
	call	DWORD PTR [eax+4]

; 135  : 			pNewHeap = (HeapInstance *) &g_heap;
; 136  : 		}
; 137  : 	}
; 138  : 
; 139  : Done:
; 140  : 	*instance = pNewHeap;

	mov	eax, DWORD PTR _instance$[ebp]
	mov	esi, ebx
	mov	DWORD PTR [eax], esi

; 141  : 
; 142  : 	return result;

	mov	eax, edi
	pop	edi
	pop	esi
	pop	ebx

; 143  : }

	mov	esp, ebp
	pop	ebp
	ret	12					; 0000000cH
$LN11@CreateInst:

; 107  : 			pNewHeap = (HeapInstance *) this;
; 108  : 		}
; 109  : 		else
; 110  : 		if ((dwFlags & DAHEAPFLAG_PRIVATE) == 0)

	test	cl, 8
	jne	SHORT $LN13@CreateInst

; 111  : 		{
; 112  : 			// we are public, creating a private heap
; 113  : 			BaseHeap *pNewBase;
; 114  : 
; 115  : 			if ((pNewBase = new BaseHeap) == 0)

	push	20					; 00000014H
	call	??2@YAPAXI@Z				; operator new
	mov	edi, eax
	add	esp, 4
	mov	DWORD PTR $T1[ebp], edi
	test	edi, edi
	je	SHORT $LN37@CreateInst
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.h

; 115  : 	{

	mov	DWORD PTR [edi], OFFSET ??_7BaseHeap@@6B@
	xorps	xmm0, xmm0

; 116  : 		memset(((C8 *) this)+sizeof(DWORD), 0, sizeof(*this)-sizeof(DWORD));

	movups	XMMWORD PTR [edi+4], xmm0

; 117  : 		dwRefs=1;

	mov	DWORD PTR [edi+4], 1
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.cpp

; 125  : 			pNewBase->AddToList(pNewHeap);

	mov	edx, esi
	mov	eax, DWORD PTR [ebx+8]
	mov	ecx, edi
	mov	DWORD PTR [edi+8], eax
	mov	eax, DWORD PTR _descriptor$[ebp]
	mov	eax, DWORD PTR [eax+12]
	mov	DWORD PTR [edi+12], eax
	call	?AddToList@BaseHeap@@QAIHPAUHeapInstance@@@Z ; BaseHeap::AddToList

; 135  : 			pNewHeap = (HeapInstance *) &g_heap;
; 136  : 		}
; 137  : 	}
; 138  : 
; 139  : Done:
; 140  : 	*instance = pNewHeap;

	mov	eax, DWORD PTR _instance$[ebp]
	mov	esi, edi
	mov	edi, DWORD PTR _result$1$[ebp]
	mov	DWORD PTR [eax], esi

; 141  : 
; 142  : 	return result;

	mov	eax, edi
	pop	edi
	pop	esi
	pop	ebx

; 143  : }

	mov	esp, ebp
	pop	ebp
	ret	12					; 0000000cH
$LN37@CreateInst:

; 116  : 			{
; 117  : 				pNewHeap->Release();

	mov	eax, DWORD PTR [esi]
	push	esi
	call	DWORD PTR [eax+8]

; 118  : 				pNewHeap = 0;

	xor	esi, esi
$LN56@CreateInst:

; 135  : 			pNewHeap = (HeapInstance *) &g_heap;
; 136  : 		}
; 137  : 	}
; 138  : 
; 139  : Done:
; 140  : 	*instance = pNewHeap;

	mov	eax, DWORD PTR _instance$[ebp]
	mov	edi, -4					; fffffffcH
	mov	DWORD PTR [eax], esi

; 141  : 
; 142  : 	return result;

	mov	eax, edi
	pop	edi
	pop	esi
	pop	ebx

; 143  : }

	mov	esp, ebp
	pop	ebp
	ret	12					; 0000000cH
$LN13@CreateInst:

; 126  : 
; 127  : 			pNewHeap = (HeapInstance *) pNewBase;
; 128  : 		}
; 129  : 		else
; 130  : 		{
; 131  : 			// we are private, creating a public heap
; 132  : 
; 133  : 			g_heap.AddToList(pNewHeap);

	mov	edx, esi
	mov	ecx, OFFSET ?g_heap@@3UBaseHeap@@A
	call	?AddToList@BaseHeap@@QAIHPAUHeapInstance@@@Z ; BaseHeap::AddToList

; 134  : 			g_heap.AddRef();

	push	OFFSET ?g_heap@@3UBaseHeap@@A
	call	?AddRef@BaseHeap@@UAGKXZ		; BaseHeap::AddRef

; 135  : 			pNewHeap = (HeapInstance *) &g_heap;
; 136  : 		}
; 137  : 	}
; 138  : 
; 139  : Done:
; 140  : 	*instance = pNewHeap;

	mov	eax, DWORD PTR _instance$[ebp]
	mov	esi, OFFSET ?g_heap@@3UBaseHeap@@A
	mov	DWORD PTR [eax], esi

; 141  : 
; 142  : 	return result;

	mov	eax, edi
	pop	edi
	pop	esi
	pop	ebx

; 143  : }

	mov	esp, ebp
	pop	ebp
	ret	12					; 0000000cH
$LN5@CreateInst:

; 75   : 		strcmp(lpInfo->interface_name, interface_name))
; 76   : 	{
; 77   : 		result = GR_INTERFACE_UNSUPPORTED;

	mov	edi, -3					; fffffffdH
$Done$58:

; 135  : 			pNewHeap = (HeapInstance *) &g_heap;
; 136  : 		}
; 137  : 	}
; 138  : 
; 139  : Done:
; 140  : 	*instance = pNewHeap;

	mov	eax, DWORD PTR _instance$[ebp]
	mov	DWORD PTR [eax], esi

; 141  : 
; 142  : 	return result;

	mov	eax, edi
	pop	edi
	pop	esi
	pop	ebx

; 143  : }

	mov	esp, ebp
	pop	ebp
	ret	12					; 0000000cH
?CreateInstance@BaseHeap@@UAG?AW4GENRESULT@@PAUDACOMDESC@@PAPAX@Z ENDP ; BaseHeap::CreateInstance
_TEXT	ENDS
; Function compile flags: /Ogtp
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.cpp
;	COMDAT ?Release@BaseHeap@@UAGKXZ
_TEXT	SEGMENT
_this$ = 8						; size = 4
?Release@BaseHeap@@UAGKXZ PROC				; BaseHeap::Release, COMDAT

; 154  : {

	push	ebp
	mov	ebp, esp
	push	esi

; 155  : 	if (dwFlags & DAHEAPFLAG_PRIVATE)

	mov	esi, DWORD PTR _this$[ebp]
	test	BYTE PTR [esi+12], 8
	mov	eax, DWORD PTR [esi+4]
	je	SHORT $LN2@Release

; 156  : 	{
; 157  : 		if (dwRefs > 0)

	test	eax, eax
	je	SHORT $LN15@Release

; 158  : 			dwRefs--;

	dec	eax
	mov	DWORD PTR [esi+4], eax

; 159  : 
; 160  : 		if (dwRefs == 0)

	test	eax, eax
	jne	SHORT $LN1@Release
$LN15@Release:

; 161  : 		{
; 162  : 			if (pHeapList)

	mov	ecx, DWORD PTR [esi+16]
	test	ecx, ecx
	je	SHORT $LN6@Release

; 163  : 				pHeapList->Release();

	mov	eax, DWORD PTR [ecx]
	push	ecx
	call	DWORD PTR [eax+8]
$LN6@Release:

; 164  : 			pHeapList=0;
; 165  : 			delete this;

	push	20					; 00000014H
	push	esi
	mov	DWORD PTR [esi+16], 0
	call	??3@YAXPAXI@Z				; operator delete
	add	esp, 8

; 166  : 			return 0;

	xor	eax, eax
	pop	esi

; 173  : 	}
; 174  : 
; 175  : 	return dwRefs;
; 176  : }

	pop	ebp
	ret	4
$LN2@Release:

; 167  : 		}
; 168  : 	}
; 169  : 	else
; 170  : 	{
; 171  : 		if (dwRefs > 1)

	cmp	eax, 1
	jbe	SHORT $LN1@Release

; 172  : 			dwRefs--;

	dec	eax
	mov	DWORD PTR [esi+4], eax
$LN1@Release:
	pop	esi

; 173  : 	}
; 174  : 
; 175  : 	return dwRefs;
; 176  : }

	pop	ebp
	ret	4
?Release@BaseHeap@@UAGKXZ ENDP				; BaseHeap::Release
_TEXT	ENDS
; Function compile flags: /Ogtp
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.cpp
;	COMDAT ?AddRef@BaseHeap@@UAGKXZ
_TEXT	SEGMENT
_this$ = 8						; size = 4
?AddRef@BaseHeap@@UAGKXZ PROC				; BaseHeap::AddRef, COMDAT

; 147  : {

	push	ebp
	mov	ebp, esp

; 148  : 	dwRefs++;

	mov	ecx, DWORD PTR _this$[ebp]
	mov	eax, DWORD PTR [ecx+4]
	inc	eax
	mov	DWORD PTR [ecx+4], eax

; 149  : 	return dwRefs;
; 150  : }

	pop	ebp
	ret	4
?AddRef@BaseHeap@@UAGKXZ ENDP				; BaseHeap::AddRef
_TEXT	ENDS
; Function compile flags: /Ogtp
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.cpp
;	COMDAT ?QueryInterface@BaseHeap@@UAG?AW4GENRESULT@@PBDPAPAX@Z
_TEXT	SEGMENT
_this$ = 8						; size = 4
_interface_name$ = 12					; size = 4
_instance$ = 16						; size = 4
?QueryInterface@BaseHeap@@UAG?AW4GENRESULT@@PBDPAPAX@Z PROC ; BaseHeap::QueryInterface, COMDAT

; 50   : {

	push	ebp
	mov	ebp, esp
	push	esi

; 51   : 	ASSERT(instance);

	mov	esi, DWORD PTR _instance$[ebp]
	test	esi, esi
	jne	SHORT $LN6@QueryInter
	push	OFFSET ??_C@_08EMNENPBA@instance@
	push	51					; 00000033H
	push	OFFSET ??_C@_0EA@JPKIKKIB@E?3?2GitHub?2projects?2ConquestFWR?2@
	push	OFFSET ??_C@_0CE@JBJGEEGD@?$CFs?$CI?$CFd?$CJ?5?3?5FATAL?3Assertion?5failed@
	push	1048640					; 00100040H
	call	DWORD PTR _FDUMP
	add	esp, 20					; 00000014H
$LN6@QueryInter:

; 52   : 
; 53   : 	*instance = 0;
; 54   : 	return GR_INTERFACE_UNSUPPORTED;
; 55   : }

	mov	DWORD PTR [esi], 0
	mov	eax, -3					; fffffffdH
	pop	esi
	pop	ebp
	ret	12					; 0000000cH
?QueryInterface@BaseHeap@@UAG?AW4GENRESULT@@PBDPAPAX@Z ENDP ; BaseHeap::QueryInterface
_TEXT	ENDS
END
