; Listing generated by Microsoft (R) Optimizing Compiler Version 15.00.30729.01 

	TITLE	m:\Archive\Conquest\Code\Libs\Src\DACOM\BaseHeap.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRT
INCLUDELIB OLDNAMES

_DATA	SEGMENT
_interface_name DB 'IHeap', 00H
_DATA	ENDS
PUBLIC	??0DACOMDESC@@QAE@PBD@Z				; DACOMDESC::DACOMDESC
; Function compile flags: /Ogtpy
; File m:\archive\conquest\code\libs\include\dacom.h
;	COMDAT ??0DACOMDESC@@QAE@PBD@Z
_TEXT	SEGMENT
__interface_name$ = 8					; size = 4
??0DACOMDESC@@QAE@PBD@Z PROC				; DACOMDESC::DACOMDESC, COMDAT
; _this$ = ecx

; 441  : 	DACOMDESC (const C8 * _interface_name = 0)

	mov	eax, ecx

; 442  : 	{
; 443  : 		size = sizeof(*this);
; 444  : 		interface_name = _interface_name;

	mov	ecx, DWORD PTR __interface_name$[esp-4]
	mov	DWORD PTR [eax], 8
	mov	DWORD PTR [eax+4], ecx

; 445  : 	}

	ret	4
??0DACOMDESC@@QAE@PBD@Z ENDP				; DACOMDESC::DACOMDESC
_TEXT	ENDS
PUBLIC	??0DAHEAPDESC@@QAE@PBD@Z			; DAHEAPDESC::DAHEAPDESC
; Function compile flags: /Ogtpy
; File m:\archive\conquest\code\libs\include\heapobj.h
;	COMDAT ??0DAHEAPDESC@@QAE@PBD@Z
_TEXT	SEGMENT
__interfaceName$ = 8					; size = 4
??0DAHEAPDESC@@QAE@PBD@Z PROC				; DAHEAPDESC::DAHEAPDESC, COMDAT
; _this$ = ecx

; 96   : 	{

	mov	eax, ecx
	mov	ecx, DWORD PTR __interfaceName$[esp-4]
	mov	DWORD PTR [eax+4], ecx

; 97   : 		heapSize = 
; 98   : 		flags = 
; 99   : 		growSize = 0;

	xor	ecx, ecx
	mov	DWORD PTR [eax+16], ecx
	mov	DWORD PTR [eax+12], ecx
	mov	DWORD PTR [eax+8], ecx

; 100  : 		size = sizeof(*this);

	mov	DWORD PTR [eax], 20			; 00000014H

; 101  : 	};

	ret	4
??0DAHEAPDESC@@QAE@PBD@Z ENDP				; DAHEAPDESC::DAHEAPDESC
_TEXT	ENDS
PUBLIC	?getUpper@BASE_BLOCK@@QAEPAU1@XZ		; BASE_BLOCK::getUpper
; Function compile flags: /Ogtpy
; File m:\archive\conquest\code\libs\src\dacom\baseheap.h
;	COMDAT ?getUpper@BASE_BLOCK@@QAEPAU1@XZ
_TEXT	SEGMENT
?getUpper@BASE_BLOCK@@QAEPAU1@XZ PROC			; BASE_BLOCK::getUpper, COMDAT
; _this$ = ecx

; 78   : 	return pUpper;

	mov	eax, DWORD PTR [ecx+4]

; 79   : }

	ret	0
?getUpper@BASE_BLOCK@@QAEPAU1@XZ ENDP			; BASE_BLOCK::getUpper
_TEXT	ENDS
PUBLIC	?getLower@BASE_BLOCK@@QAEPAU1@XZ		; BASE_BLOCK::getLower
; Function compile flags: /Ogtpy
;	COMDAT ?getLower@BASE_BLOCK@@QAEPAU1@XZ
_TEXT	SEGMENT
?getLower@BASE_BLOCK@@QAEPAU1@XZ PROC			; BASE_BLOCK::getLower, COMDAT
; _this$ = ecx

; 83   : 	return (BASE_BLOCK *) (((C8 *)this) + (dwSize & ~1));

	mov	eax, DWORD PTR [ecx]
	and	eax, -2					; fffffffeH
	add	eax, ecx

; 84   : }

	ret	0
?getLower@BASE_BLOCK@@QAEPAU1@XZ ENDP			; BASE_BLOCK::getLower
_TEXT	ENDS
PUBLIC	?isAllocated@BASE_BLOCK@@QAEHXZ			; BASE_BLOCK::isAllocated
; Function compile flags: /Ogtpy
;	COMDAT ?isAllocated@BASE_BLOCK@@QAEHXZ
_TEXT	SEGMENT
?isAllocated@BASE_BLOCK@@QAEHXZ PROC			; BASE_BLOCK::isAllocated, COMDAT
; _this$ = ecx

; 88   : 	return (dwSize & 1);

	mov	eax, DWORD PTR [ecx]
	and	eax, 1

; 89   : }

	ret	0
?isAllocated@BASE_BLOCK@@QAEHXZ ENDP			; BASE_BLOCK::isAllocated
_TEXT	ENDS
PUBLIC	??0IDAComponent@@QAE@XZ				; IDAComponent::IDAComponent
; Function compile flags: /Ogtpy
;	COMDAT ??0IDAComponent@@QAE@XZ
_TEXT	SEGMENT
??0IDAComponent@@QAE@XZ PROC				; IDAComponent::IDAComponent, COMDAT
; _this$ = ecx
	mov	eax, ecx
	ret	0
??0IDAComponent@@QAE@XZ ENDP				; IDAComponent::IDAComponent
_TEXT	ENDS
PUBLIC	??0ErrorCode@@QAE@W4ErrorKind@@W4SeverityLevel@@@Z ; ErrorCode::ErrorCode
; Function compile flags: /Ogtpy
; File m:\archive\conquest\code\libs\include\fdump.h
;	COMDAT ??0ErrorCode@@QAE@W4ErrorKind@@W4SeverityLevel@@@Z
_TEXT	SEGMENT
__kind$ = 8						; size = 4
__severity$ = 12					; size = 4
??0ErrorCode@@QAE@W4ErrorKind@@W4SeverityLevel@@@Z PROC	; ErrorCode::ErrorCode, COMDAT
; _this$ = ecx

; 178  : 	{
; 179  : 		severity = _severity;
; 180  : 		kind = _kind;

	mov	edx, DWORD PTR __severity$[esp-4]
	mov	eax, ecx
	mov	ecx, DWORD PTR __kind$[esp-4]
	shl	ecx, 4
	and	edx, 15					; 0000000fH
	or	ecx, edx
	mov	DWORD PTR [eax], ecx

; 181  : 	}

	ret	8
??0ErrorCode@@QAE@W4ErrorKind@@W4SeverityLevel@@@Z ENDP	; ErrorCode::ErrorCode
_TEXT	ENDS
PUBLIC	??_C@_0CE@JBJGEEGD@?$CFs?$CI?$CFd?$CJ?5?3?5FATAL?3Assertion?5failed?3@ ; `string'
PUBLIC	??_C@_0P@IJECOCHM@?4?2BaseHeap?4cpp?$AA@	; `string'
PUBLIC	??_C@_08EMNENPBA@instance?$AA@			; `string'
PUBLIC	?QueryInterface@BaseHeap@@UAG?AW4GENRESULT@@PBDPAPAX@Z ; BaseHeap::QueryInterface
EXTRN	_FDUMP:DWORD
;	COMDAT ??_C@_0CE@JBJGEEGD@?$CFs?$CI?$CFd?$CJ?5?3?5FATAL?3Assertion?5failed?3@
CONST	SEGMENT
??_C@_0CE@JBJGEEGD@?$CFs?$CI?$CFd?$CJ?5?3?5FATAL?3Assertion?5failed?3@ DB '%'
	DB	's(%d) : FATAL:Assertion failed: %s', 00H	; `string'
CONST	ENDS
;	COMDAT ??_C@_0P@IJECOCHM@?4?2BaseHeap?4cpp?$AA@
CONST	SEGMENT
??_C@_0P@IJECOCHM@?4?2BaseHeap?4cpp?$AA@ DB '.\BaseHeap.cpp', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_08EMNENPBA@instance?$AA@
CONST	SEGMENT
??_C@_08EMNENPBA@instance?$AA@ DB 'instance', 00H	; `string'
; Function compile flags: /Ogtpy
; File m:\archive\conquest\code\libs\src\dacom\baseheap.cpp
CONST	ENDS
;	COMDAT ?QueryInterface@BaseHeap@@UAG?AW4GENRESULT@@PBDPAPAX@Z
_TEXT	SEGMENT
_this$ = 8						; size = 4
_interface_name$ = 12					; size = 4
_instance$ = 16						; size = 4
?QueryInterface@BaseHeap@@UAG?AW4GENRESULT@@PBDPAPAX@Z PROC ; BaseHeap::QueryInterface, COMDAT

; 50   : {

	push	esi

; 51   : 	ASSERT(instance);

	mov	esi, DWORD PTR _instance$[esp]
	test	esi, esi
	jne	SHORT $LN6@QueryInter
	push	OFFSET ??_C@_08EMNENPBA@instance?$AA@
	push	51					; 00000033H
	push	OFFSET ??_C@_0P@IJECOCHM@?4?2BaseHeap?4cpp?$AA@
	mov	eax, 1048640				; 00100040H
	push	OFFSET ??_C@_0CE@JBJGEEGD@?$CFs?$CI?$CFd?$CJ?5?3?5FATAL?3Assertion?5failed?3@
	push	eax
	call	DWORD PTR _FDUMP
	add	esp, 20					; 00000014H
$LN6@QueryInter:

; 52   : 
; 53   : 	*instance = 0;

	mov	DWORD PTR [esi], 0

; 54   : 	return GR_INTERFACE_UNSUPPORTED;

	mov	eax, -3					; fffffffdH
	pop	esi

; 55   : }

	ret	12					; 0000000cH
?QueryInterface@BaseHeap@@UAG?AW4GENRESULT@@PBDPAPAX@Z ENDP ; BaseHeap::QueryInterface
_TEXT	ENDS
PUBLIC	?AddRef@BaseHeap@@UAGKXZ			; BaseHeap::AddRef
; Function compile flags: /Ogtpy
;	COMDAT ?AddRef@BaseHeap@@UAGKXZ
_TEXT	SEGMENT
_this$ = 8						; size = 4
?AddRef@BaseHeap@@UAGKXZ PROC				; BaseHeap::AddRef, COMDAT

; 148  : 	dwRefs++;

	mov	eax, DWORD PTR _this$[esp-4]
	inc	DWORD PTR [eax+4]

; 149  : 	return dwRefs;

	mov	eax, DWORD PTR [eax+4]

; 150  : }

	ret	4
?AddRef@BaseHeap@@UAGKXZ ENDP				; BaseHeap::AddRef
_TEXT	ENDS
PUBLIC	?Release@BaseHeap@@UAGKXZ			; BaseHeap::Release
EXTRN	??3@YAXPAX@Z:PROC				; operator delete
; Function compile flags: /Ogtpy
;	COMDAT ?Release@BaseHeap@@UAGKXZ
_TEXT	SEGMENT
_this$ = 8						; size = 4
?Release@BaseHeap@@UAGKXZ PROC				; BaseHeap::Release, COMDAT

; 154  : {

	push	esi

; 155  : 	if (dwFlags & DAHEAPFLAG_PRIVATE)

	mov	esi, DWORD PTR _this$[esp]
	test	BYTE PTR [esi+12], 8

; 156  : 	{
; 157  : 		if (dwRefs > 0)

	mov	eax, DWORD PTR [esi+4]
	je	SHORT $LN6@Release
	test	eax, eax
	jbe	SHORT $LN5@Release

; 158  : 			dwRefs--;

	dec	eax
	mov	DWORD PTR [esi+4], eax
$LN5@Release:

; 159  : 
; 160  : 		if (dwRefs == 0)

	cmp	DWORD PTR [esi+4], 0
	jne	SHORT $LN1@Release

; 161  : 		{
; 162  : 			if (pHeapList)

	mov	eax, DWORD PTR [esi+16]
	test	eax, eax
	je	SHORT $LN3@Release

; 163  : 				pHeapList->Release();

	mov	ecx, DWORD PTR [eax]
	mov	edx, DWORD PTR [ecx+8]
	push	eax
	call	edx
$LN3@Release:

; 164  : 			pHeapList=0;
; 165  : 			delete this;

	push	esi
	mov	DWORD PTR [esi+16], 0
	call	??3@YAXPAX@Z				; operator delete
	add	esp, 4

; 166  : 			return 0;

	xor	eax, eax
	pop	esi

; 176  : }

	ret	4
$LN6@Release:

; 167  : 		}
; 168  : 	}
; 169  : 	else
; 170  : 	{
; 171  : 		if (dwRefs > 1)

	cmp	eax, 1
	jbe	SHORT $LN1@Release

; 172  : 			dwRefs--;

	dec	eax
	mov	DWORD PTR [esi+4], eax
$LN1@Release:

; 173  : 	}
; 174  : 
; 175  : 	return dwRefs;

	mov	eax, DWORD PTR [esi+4]
	pop	esi

; 176  : }

	ret	4
?Release@BaseHeap@@UAGKXZ ENDP				; BaseHeap::Release
_TEXT	ENDS
PUBLIC	??_C@_05EHEOJPMF@pHeap?$AA@			; `string'
PUBLIC	?AddToList@BaseHeap@@QAIHPAUHeapInstance@@@Z	; BaseHeap::AddToList
EXTRN	_HEAP:DWORD
;	COMDAT ??_C@_05EHEOJPMF@pHeap?$AA@
; File m:\archive\conquest\code\libs\include\fdump.h
CONST	SEGMENT
??_C@_05EHEOJPMF@pHeap?$AA@ DB 'pHeap', 00H		; `string'
; Function compile flags: /Ogtpy
; File m:\archive\conquest\code\libs\src\dacom\baseheap.cpp
CONST	ENDS
;	COMDAT ?AddToList@BaseHeap@@QAIHPAUHeapInstance@@@Z
_TEXT	SEGMENT
?AddToList@BaseHeap@@QAIHPAUHeapInstance@@@Z PROC	; BaseHeap::AddToList, COMDAT
; _this$ = ecx
; _pHeap$ = edx

; 180  : {

	push	esi
	mov	esi, edx
	push	edi
	mov	edi, ecx

; 181  : 	ASSERT(pHeap);

	test	esi, esi
	jne	SHORT $LN4@AddToList
	push	OFFSET ??_C@_05EHEOJPMF@pHeap?$AA@
	push	181					; 000000b5H
	push	OFFSET ??_C@_0P@IJECOCHM@?4?2BaseHeap?4cpp?$AA@
	mov	eax, 1048640				; 00100040H
	push	OFFSET ??_C@_0CE@JBJGEEGD@?$CFs?$CI?$CFd?$CJ?5?3?5FATAL?3Assertion?5failed?3@
	push	eax
	call	DWORD PTR _FDUMP
	add	esp, 20					; 00000014H
$LN4@AddToList:

; 182  : 
; 183  : 	BOOL result=0;
; 184  : 
; 185  : 	if (pHeapList==0)

	mov	eax, DWORD PTR [edi+16]
	test	eax, eax
	jne	SHORT $LN3@AddToList

; 186  : 	{
; 187  : 		if (this == &g_heap)

	cmp	edi, OFFSET _g_heap
	jne	SHORT $LN2@AddToList

; 188  : 			HEAP = this;

	mov	DWORD PTR _HEAP, edi

; 194  : 		pHeapList = pHeap;
; 195  : 	}
; 196  : 
; 197  : 	pHeap->SetErrorHandler(pErrorHandler);		// propogate error handler to new heap

	mov	ecx, DWORD PTR [edi+8]
	mov	DWORD PTR [edi+16], esi
	mov	eax, DWORD PTR [esi]
	mov	edx, DWORD PTR [eax+60]
	push	ecx
	push	esi
	call	edx
	pop	edi

; 198  : 	
; 199  : 	return result;

	xor	eax, eax
	pop	esi

; 200  : }

	ret	0
$LN3@AddToList:

; 189  : 		pHeapList = pHeap;
; 190  : 	}
; 191  : 	else
; 192  : 	{
; 193  : 		pHeap->pNext = pHeapList;

	mov	DWORD PTR [esi+16], eax
$LN2@AddToList:

; 194  : 		pHeapList = pHeap;
; 195  : 	}
; 196  : 
; 197  : 	pHeap->SetErrorHandler(pErrorHandler);		// propogate error handler to new heap

	mov	ecx, DWORD PTR [edi+8]
	mov	DWORD PTR [edi+16], esi
	mov	eax, DWORD PTR [esi]
	mov	edx, DWORD PTR [eax+60]
	push	ecx
	push	esi
	call	edx
	pop	edi

; 198  : 	
; 199  : 	return result;

	xor	eax, eax
	pop	esi

; 200  : }

	ret	0
?AddToList@BaseHeap@@QAIHPAUHeapInstance@@@Z ENDP	; BaseHeap::AddToList
_TEXT	ENDS
PUBLIC	?FindTheHeap@BaseHeap@@QAIPAUHeapInstance@@PAX@Z ; BaseHeap::FindTheHeap
; Function compile flags: /Ogtpy
;	COMDAT ?FindTheHeap@BaseHeap@@QAIPAUHeapInstance@@PAX@Z
_TEXT	SEGMENT
?FindTheHeap@BaseHeap@@QAIPAUHeapInstance@@PAX@Z PROC	; BaseHeap::FindTheHeap, COMDAT
; _this$ = ecx
; _baseAddress$ = edx

; 205  : 	HeapInstance *pList;
; 206  : 
; 207  : 	for (pList=pHeapList; pList; pList=pList->pNext)

	mov	eax, DWORD PTR [ecx+16]
	test	eax, eax
	je	SHORT $LN8@FindTheHea
$LL4@FindTheHea:

; 208  : 	{
; 209  : 		// single comparison range check
; 210  : 		DWORD pos = (DWORD)baseAddress - (DWORD)pList->pHeapBase;

	mov	ecx, edx
	sub	ecx, DWORD PTR [eax+28]

; 211  : 		if (pos < pList->dwHeapSize)

	cmp	ecx, DWORD PTR [eax+32]
	jb	SHORT $LN8@FindTheHea
	mov	eax, DWORD PTR [eax+16]
	test	eax, eax
	jne	SHORT $LL4@FindTheHea
$LN8@FindTheHea:

; 212  : 			break;
; 213  : 	}
; 214  : 	return pList;
; 215  : }

	ret	0
?FindTheHeap@BaseHeap@@QAIPAUHeapInstance@@PAX@Z ENDP	; BaseHeap::FindTheHeap
_TEXT	ENDS
PUBLIC	?ClearAllocateMemory@BaseHeap@@UAGPAXKPBDE@Z	; BaseHeap::ClearAllocateMemory
EXTRN	_memset:PROC
; Function compile flags: /Ogtpy
;	COMDAT ?ClearAllocateMemory@BaseHeap@@UAGPAXKPBDE@Z
_TEXT	SEGMENT
_this$ = 8						; size = 4
_numBytes$ = 12						; size = 4
_msg$ = 16						; size = 4
_initChar$ = 20						; size = 1
?ClearAllocateMemory@BaseHeap@@UAGPAXKPBDE@Z PROC	; BaseHeap::ClearAllocateMemory, COMDAT

; 279  : 	void * result;
; 280  : 
; 281  : 	if ((result = AllocateMemory(numBytes, msg)) != 0)

	mov	edx, DWORD PTR _msg$[esp-4]
	mov	eax, DWORD PTR _this$[esp-4]
	mov	ecx, DWORD PTR [eax]
	push	esi
	push	edi
	mov	edi, DWORD PTR _numBytes$[esp+4]
	push	edx
	push	edi
	push	eax
	mov	eax, DWORD PTR [ecx+16]
	call	eax
	mov	esi, eax
	test	esi, esi
	je	SHORT $LN1@ClearAlloc

; 282  : 		memset(result, initChar, numBytes);

	movzx	ecx, BYTE PTR _initChar$[esp+4]
	push	edi
	push	ecx
	push	esi
	call	_memset
	add	esp, 12					; 0000000cH

; 283  : 
; 284  : 	return result;

	mov	eax, esi
$LN1@ClearAlloc:
	pop	edi
	pop	esi

; 285  : }

	ret	16					; 00000010H
?ClearAllocateMemory@BaseHeap@@UAGPAXKPBDE@Z ENDP	; BaseHeap::ClearAllocateMemory
_TEXT	ENDS
PUBLIC	?FreeMemory@BaseHeap@@UAGJPAX@Z			; BaseHeap::FreeMemory
EXTRN	?g_pMSHeap@@3PAUIHeap@@A:DWORD			; g_pMSHeap
; Function compile flags: /Ogtpy
;	COMDAT ?FreeMemory@BaseHeap@@UAGJPAX@Z
_TEXT	SEGMENT
_this$ = 8						; size = 4
_allocatedBlock$ = 12					; size = 4
?FreeMemory@BaseHeap@@UAGJPAX@Z PROC			; BaseHeap::FreeMemory, COMDAT

; 328  : 	BOOL32 result;
; 329  : 	
; 330  : 	if ((result = U32(allocatedBlock)) != 0)

	mov	eax, DWORD PTR _allocatedBlock$[esp-4]
	test	eax, eax
	je	SHORT $LN15@FreeMemory

; 331  : 	{
; 332  : 		BaseHeap *pHeap = FindTheHeap(allocatedBlock);

	mov	ecx, DWORD PTR _this$[esp-4]
	mov	ecx, DWORD PTR [ecx+16]
	test	ecx, ecx
	je	SHORT $LN2@FreeMemory
$LL9@FreeMemory:
	mov	edx, eax
	sub	edx, DWORD PTR [ecx+28]
	cmp	edx, DWORD PTR [ecx+32]
	jb	SHORT $LN13@FreeMemory
	mov	ecx, DWORD PTR [ecx+16]
	test	ecx, ecx
	jne	SHORT $LL9@FreeMemory
$LN2@FreeMemory:

; 336  : 		else
; 337  : 			result = g_pMSHeap->FreeMemory(allocatedBlock);

	mov	ecx, DWORD PTR ?g_pMSHeap@@3PAUIHeap@@A	; g_pMSHeap
	mov	edx, DWORD PTR [ecx]
	mov	DWORD PTR _allocatedBlock$[esp-4], eax
	mov	DWORD PTR _this$[esp-4], ecx
	mov	eax, DWORD PTR [edx+28]
	jmp	eax
$LN13@FreeMemory:

; 333  : 
; 334  : 		if (pHeap)

	test	ecx, ecx
	je	SHORT $LN2@FreeMemory

; 335  : 			result = pHeap->FreeMemory(allocatedBlock);

	mov	edx, DWORD PTR [ecx]
	mov	DWORD PTR _allocatedBlock$[esp-4], eax
	mov	DWORD PTR _this$[esp-4], ecx
	mov	eax, DWORD PTR [edx+28]
	jmp	eax
$LN15@FreeMemory:

; 338  : 	}
; 339  : 
; 340  : 	return result;
; 341  : }

	ret	8
?FreeMemory@BaseHeap@@UAGJPAX@Z ENDP			; BaseHeap::FreeMemory
_TEXT	ENDS
PUBLIC	?EnumerateBlocks@BaseHeap@@UAGJP6GJPAUIHeap@@PAXK1@Z1@Z ; BaseHeap::EnumerateBlocks
; Function compile flags: /Ogtpy
;	COMDAT ?EnumerateBlocks@BaseHeap@@UAGJP6GJPAUIHeap@@PAXK1@Z1@Z
_TEXT	SEGMENT
_this$ = 8						; size = 4
_proc$ = 12						; size = 4
_context$ = 16						; size = 4
?EnumerateBlocks@BaseHeap@@UAGJP6GJPAUIHeap@@PAXK1@Z1@Z PROC ; BaseHeap::EnumerateBlocks, COMDAT

; 346  : 	HeapInstance *pHeap = pHeapList;

	mov	eax, DWORD PTR _this$[esp-4]
	push	esi
	mov	esi, DWORD PTR [eax+16]

; 347  : 	BOOL32 result=1;

	mov	eax, 1

; 348  : 
; 349  : 	while (pHeap && result)

	test	esi, esi
	je	SHORT $LN1@EnumerateB
	push	ebx
	mov	ebx, DWORD PTR _proc$[esp+4]
	push	edi
	mov	edi, DWORD PTR _context$[esp+8]
	npad	5
$LL2@EnumerateB:
	test	eax, eax
	je	SHORT $LN9@EnumerateB

; 350  : 	{
; 351  : 		result = pHeap->EnumerateBlocks(proc, context);

	mov	ecx, DWORD PTR [esi]
	mov	edx, DWORD PTR [ecx+32]
	push	edi
	push	ebx
	push	esi
	call	edx

; 352  : 		pHeap = pHeap->pNext;

	mov	esi, DWORD PTR [esi+16]
	test	esi, esi
	jne	SHORT $LL2@EnumerateB
$LN9@EnumerateB:
	pop	edi
	pop	ebx
$LN1@EnumerateB:
	pop	esi

; 353  : 	}
; 354  : 
; 355  : 	return result;
; 356  : }

	ret	12					; 0000000cH
?EnumerateBlocks@BaseHeap@@UAGJP6GJPAUIHeap@@PAXK1@Z1@Z ENDP ; BaseHeap::EnumerateBlocks
_TEXT	ENDS
PUBLIC	?GetBlockSize@BaseHeap@@UAGKPAX@Z		; BaseHeap::GetBlockSize
; Function compile flags: /Ogtpy
;	COMDAT ?GetBlockSize@BaseHeap@@UAGKPAX@Z
_TEXT	SEGMENT
_this$ = 8						; size = 4
_allocatedBlock$ = 12					; size = 4
?GetBlockSize@BaseHeap@@UAGKPAX@Z PROC			; BaseHeap::GetBlockSize, COMDAT

; 361  : 	HeapInstance *pHeap = FindTheHeap(allocatedBlock);

	mov	eax, DWORD PTR _this$[esp-4]
	mov	eax, DWORD PTR [eax+16]
	mov	ecx, DWORD PTR _allocatedBlock$[esp-4]
	test	eax, eax
	je	SHORT $LN2@GetBlockSi
	npad	1
$LL8@GetBlockSi:
	mov	edx, ecx
	sub	edx, DWORD PTR [eax+28]
	cmp	edx, DWORD PTR [eax+32]
	jb	SHORT $LN12@GetBlockSi
	mov	eax, DWORD PTR [eax+16]
	test	eax, eax
	jne	SHORT $LL8@GetBlockSi
$LN2@GetBlockSi:

; 366  : 	else
; 367  : 		result = g_pMSHeap->GetBlockSize(allocatedBlock);

	mov	eax, DWORD PTR ?g_pMSHeap@@3PAUIHeap@@A	; g_pMSHeap
	mov	edx, DWORD PTR [eax]
	mov	DWORD PTR _allocatedBlock$[esp-4], ecx
	mov	DWORD PTR _this$[esp-4], eax
	mov	eax, DWORD PTR [edx+36]
	jmp	eax
$LN12@GetBlockSi:

; 362  : 	U32 result;
; 363  : 
; 364  : 	if (pHeap)

	test	eax, eax
	je	SHORT $LN2@GetBlockSi

; 365  : 		result = pHeap->GetBlockSize(allocatedBlock);

	mov	edx, DWORD PTR [eax]
	mov	DWORD PTR _allocatedBlock$[esp-4], ecx
	mov	DWORD PTR _this$[esp-4], eax
	mov	eax, DWORD PTR [edx+36]
	jmp	eax
?GetBlockSize@BaseHeap@@UAGKPAX@Z ENDP			; BaseHeap::GetBlockSize
_TEXT	ENDS
PUBLIC	?GetBlockMessage@BaseHeap@@UAGPBDPAX@Z		; BaseHeap::GetBlockMessage
; Function compile flags: /Ogtpy
;	COMDAT ?GetBlockMessage@BaseHeap@@UAGPBDPAX@Z
_TEXT	SEGMENT
_this$ = 8						; size = 4
_allocatedBlock$ = 12					; size = 4
?GetBlockMessage@BaseHeap@@UAGPBDPAX@Z PROC		; BaseHeap::GetBlockMessage, COMDAT

; 375  : 	BaseHeap *pHeap = FindTheHeap(allocatedBlock);

	mov	eax, DWORD PTR _this$[esp-4]
	mov	eax, DWORD PTR [eax+16]
	mov	ecx, DWORD PTR _allocatedBlock$[esp-4]
	test	eax, eax
	je	SHORT $LN2@GetBlockMe
	npad	1
$LL8@GetBlockMe:
	mov	edx, ecx
	sub	edx, DWORD PTR [eax+28]
	cmp	edx, DWORD PTR [eax+32]
	jb	SHORT $LN12@GetBlockMe
	mov	eax, DWORD PTR [eax+16]
	test	eax, eax
	jne	SHORT $LL8@GetBlockMe
$LN2@GetBlockMe:

; 380  : 	else
; 381  : 		result = g_pMSHeap->GetBlockMessage(allocatedBlock);

	mov	eax, DWORD PTR ?g_pMSHeap@@3PAUIHeap@@A	; g_pMSHeap
	mov	edx, DWORD PTR [eax]
	mov	DWORD PTR _allocatedBlock$[esp-4], ecx
	mov	DWORD PTR _this$[esp-4], eax
	mov	eax, DWORD PTR [edx+40]
	jmp	eax
$LN12@GetBlockMe:

; 376  : 	const char *result;
; 377  : 
; 378  : 	if (pHeap)

	test	eax, eax
	je	SHORT $LN2@GetBlockMe

; 379  : 		result = pHeap->GetBlockMessage(allocatedBlock);

	mov	edx, DWORD PTR [eax]
	mov	DWORD PTR _allocatedBlock$[esp-4], ecx
	mov	DWORD PTR _this$[esp-4], eax
	mov	eax, DWORD PTR [edx+40]
	jmp	eax
?GetBlockMessage@BaseHeap@@UAGPBDPAX@Z ENDP		; BaseHeap::GetBlockMessage
_TEXT	ENDS
PUBLIC	?SetBlockMessage@BaseHeap@@UAGJPAXPBD@Z		; BaseHeap::SetBlockMessage
; Function compile flags: /Ogtpy
;	COMDAT ?SetBlockMessage@BaseHeap@@UAGJPAXPBD@Z
_TEXT	SEGMENT
_this$ = 8						; size = 4
_allocatedBlock$ = 12					; size = 4
_msg$ = 16						; size = 4
?SetBlockMessage@BaseHeap@@UAGJPAXPBD@Z PROC		; BaseHeap::SetBlockMessage, COMDAT

; 389  : 	BaseHeap *pHeap = FindTheHeap(allocatedBlock);

	mov	eax, DWORD PTR _this$[esp-4]
	mov	eax, DWORD PTR [eax+16]
	mov	ecx, DWORD PTR _allocatedBlock$[esp-4]
	push	esi
	test	eax, eax
	je	SHORT $LN2@SetBlockMe
$LL8@SetBlockMe:
	mov	edx, ecx
	sub	edx, DWORD PTR [eax+28]
	cmp	edx, DWORD PTR [eax+32]
	jb	SHORT $LN12@SetBlockMe
	mov	eax, DWORD PTR [eax+16]
	test	eax, eax
	jne	SHORT $LL8@SetBlockMe

; 390  : 	BOOL32 result;
; 391  : 
; 392  : 	if (pHeap)

	jmp	SHORT $LN2@SetBlockMe
$LN12@SetBlockMe:
	test	eax, eax

; 393  : 		result = pHeap->SetBlockMessage(allocatedBlock, msg);
; 394  : 	else

	jne	SHORT $LN14@SetBlockMe
$LN2@SetBlockMe:

; 395  : 		result = g_pMSHeap->SetBlockMessage(allocatedBlock, msg);

	mov	eax, DWORD PTR ?g_pMSHeap@@3PAUIHeap@@A	; g_pMSHeap
$LN14@SetBlockMe:
	mov	esi, DWORD PTR _msg$[esp]
	mov	edx, DWORD PTR [eax]
	push	esi
	push	ecx
	push	eax
	mov	eax, DWORD PTR [edx+76]
	call	eax
	pop	esi

; 396  : 
; 397  : 	return result;
; 398  : }

	ret	12					; 0000000cH
?SetBlockMessage@BaseHeap@@UAGJPAXPBD@Z ENDP		; BaseHeap::SetBlockMessage
_TEXT	ENDS
PUBLIC	?DidAlloc@BaseHeap@@UAGJPAX@Z			; BaseHeap::DidAlloc
; Function compile flags: /Ogtpy
;	COMDAT ?DidAlloc@BaseHeap@@UAGJPAX@Z
_TEXT	SEGMENT
_this$ = 8						; size = 4
_allocatedBlock$ = 12					; size = 4
?DidAlloc@BaseHeap@@UAGJPAX@Z PROC			; BaseHeap::DidAlloc, COMDAT

; 403  : 	return (FindTheHeap(allocatedBlock) != 0);

	mov	eax, DWORD PTR _this$[esp-4]
	mov	eax, DWORD PTR [eax+16]
	test	eax, eax
	je	SHORT $LN10@DidAlloc
	mov	ecx, DWORD PTR _allocatedBlock$[esp-4]
	npad	1
$LL6@DidAlloc:
	mov	edx, ecx
	sub	edx, DWORD PTR [eax+28]
	cmp	edx, DWORD PTR [eax+32]
	jb	SHORT $LN10@DidAlloc
	mov	eax, DWORD PTR [eax+16]
	test	eax, eax
	jne	SHORT $LL6@DidAlloc
$LN10@DidAlloc:
	xor	ecx, ecx
	test	eax, eax
	setne	cl
	mov	eax, ecx

; 404  : }

	ret	8
?DidAlloc@BaseHeap@@UAGJPAX@Z ENDP			; BaseHeap::DidAlloc
_TEXT	ENDS
PUBLIC	?GetAvailableMemory@BaseHeap@@UAGKXZ		; BaseHeap::GetAvailableMemory
; Function compile flags: /Ogtpy
;	COMDAT ?GetAvailableMemory@BaseHeap@@UAGKXZ
_TEXT	SEGMENT
_this$ = 8						; size = 4
?GetAvailableMemory@BaseHeap@@UAGKXZ PROC		; BaseHeap::GetAvailableMemory, COMDAT

; 409  : 	U32 result=0;
; 410  : 	HeapInstance *pList;
; 411  : 	
; 412  : 	if ((pList = pHeapList) != 0)

	mov	eax, DWORD PTR _this$[esp-4]
	push	esi
	mov	esi, DWORD PTR [eax+16]
	push	edi
	xor	edi, edi
	test	esi, esi
	je	SHORT $LN8@GetAvailab
	npad	1
$LL3@GetAvailab:

; 413  : 	do
; 414  : 	{
; 415  : 		result += pList->GetAvailableMemory();

	mov	ecx, DWORD PTR [esi]
	mov	edx, DWORD PTR [ecx+48]
	push	esi
	call	edx

; 416  : 		pList = pList->pNext;

	mov	esi, DWORD PTR [esi+16]
	add	edi, eax

; 417  : 
; 418  : 	} while (pList != 0);

	test	esi, esi
	jne	SHORT $LL3@GetAvailab
$LN8@GetAvailab:

; 419  : 
; 420  : 	return result;

	mov	eax, edi
	pop	edi
	pop	esi

; 421  : }

	ret	4
?GetAvailableMemory@BaseHeap@@UAGKXZ ENDP		; BaseHeap::GetAvailableMemory
_TEXT	ENDS
PUBLIC	?GetLargestBlock@BaseHeap@@UAGKXZ		; BaseHeap::GetLargestBlock
; Function compile flags: /Ogtpy
;	COMDAT ?GetLargestBlock@BaseHeap@@UAGKXZ
_TEXT	SEGMENT
_this$ = 8						; size = 4
?GetLargestBlock@BaseHeap@@UAGKXZ PROC			; BaseHeap::GetLargestBlock, COMDAT

; 426  : 	U32 result=0, tmp;
; 427  : 	HeapInstance *pList;
; 428  : 	
; 429  : 	if ((pList = pHeapList) != 0)

	mov	eax, DWORD PTR _this$[esp-4]
	push	esi
	mov	esi, DWORD PTR [eax+16]
	push	edi
	xor	edi, edi
	test	esi, esi
	je	SHORT $LN10@GetLargest
	npad	1
$LL3@GetLargest:

; 430  : 	do
; 431  : 	{
; 432  : 		tmp = pList->GetLargestBlock();

	mov	ecx, DWORD PTR [esi]
	mov	edx, DWORD PTR [ecx+52]
	push	esi
	call	edx

; 433  : 		result = __max(result, tmp);

	cmp	edi, eax
	ja	SHORT $LN8@GetLargest
	mov	edi, eax
$LN8@GetLargest:

; 434  : 
; 435  : 		pList = pList->pNext;

	mov	esi, DWORD PTR [esi+16]

; 436  : 
; 437  : 	} while (pList != 0);

	test	esi, esi
	jne	SHORT $LL3@GetLargest
$LN10@GetLargest:

; 438  : 
; 439  : 	return result;

	mov	eax, edi
	pop	edi
	pop	esi

; 440  : }

	ret	4
?GetLargestBlock@BaseHeap@@UAGKXZ ENDP			; BaseHeap::GetLargestBlock
_TEXT	ENDS
PUBLIC	?GetHeapSize@BaseHeap@@UAGKXZ			; BaseHeap::GetHeapSize
; Function compile flags: /Ogtpy
;	COMDAT ?GetHeapSize@BaseHeap@@UAGKXZ
_TEXT	SEGMENT
_this$ = 8						; size = 4
?GetHeapSize@BaseHeap@@UAGKXZ PROC			; BaseHeap::GetHeapSize, COMDAT

; 445  : 	U32 result=0;
; 446  : 	HeapInstance *pList;
; 447  : 	
; 448  : 	if ((pList = pHeapList) != 0)

	mov	eax, DWORD PTR _this$[esp-4]
	push	esi
	mov	esi, DWORD PTR [eax+16]
	push	edi
	xor	edi, edi
	test	esi, esi
	je	SHORT $LN8@GetHeapSiz
	npad	1
$LL3@GetHeapSiz:

; 449  : 	do
; 450  : 	{
; 451  : 		result += pList->GetHeapSize();

	mov	ecx, DWORD PTR [esi]
	mov	edx, DWORD PTR [ecx+56]
	push	esi
	call	edx

; 452  : 		pList = pList->pNext;

	mov	esi, DWORD PTR [esi+16]
	add	edi, eax

; 453  : 
; 454  : 	} while (pList != 0);

	test	esi, esi
	jne	SHORT $LL3@GetHeapSiz
$LN8@GetHeapSiz:

; 455  : 
; 456  : 	return result;

	mov	eax, edi
	pop	edi
	pop	esi

; 457  : }

	ret	4
?GetHeapSize@BaseHeap@@UAGKXZ ENDP			; BaseHeap::GetHeapSize
_TEXT	ENDS
PUBLIC	?SetErrorHandler@BaseHeap@@UAGP6AHUErrorCode@@PBDZZP6AH01ZZ@Z ; BaseHeap::SetErrorHandler
; Function compile flags: /Ogtpy
;	COMDAT ?SetErrorHandler@BaseHeap@@UAGP6AHUErrorCode@@PBDZZP6AH01ZZ@Z
_TEXT	SEGMENT
_this$ = 8						; size = 4
_proc$ = 12						; size = 4
?SetErrorHandler@BaseHeap@@UAGP6AHUErrorCode@@PBDZZP6AH01ZZ@Z PROC ; BaseHeap::SetErrorHandler, COMDAT

; 462  : 	DA_ERROR_HANDLER result = pErrorHandler;

	mov	eax, DWORD PTR _this$[esp-4]
	push	ebx
	mov	ebx, DWORD PTR [eax+8]
	push	esi

; 463  : 	HeapInstance *pList;
; 464  : 
; 465  : 	pErrorHandler = proc;
; 466  :  	
; 467  : 	if ((pList = pHeapList) != 0)

	mov	esi, DWORD PTR [eax+16]
	push	edi
	mov	edi, DWORD PTR _proc$[esp+8]
	mov	DWORD PTR [eax+8], edi
	test	esi, esi
	je	SHORT $LN8@SetErrorHa
$LL3@SetErrorHa:

; 468  : 	do
; 469  : 	{
; 470  : 		pList->SetErrorHandler(proc);

	mov	eax, DWORD PTR [esi]
	mov	ecx, DWORD PTR [eax+60]
	push	edi
	push	esi
	call	ecx

; 471  : 		pList = pList->pNext;

	mov	esi, DWORD PTR [esi+16]

; 472  : 
; 473  : 	} while (pList != 0);

	test	esi, esi
	jne	SHORT $LL3@SetErrorHa
$LN8@SetErrorHa:
	pop	edi
	pop	esi

; 474  : 	
; 475  : 	return result;

	mov	eax, ebx
	pop	ebx

; 476  : }

	ret	8
?SetErrorHandler@BaseHeap@@UAGP6AHUErrorCode@@PBDZZP6AH01ZZ@Z ENDP ; BaseHeap::SetErrorHandler
_TEXT	ENDS
PUBLIC	?GetErrorHandler@BaseHeap@@UAGP6AHUErrorCode@@PBDZZXZ ; BaseHeap::GetErrorHandler
; Function compile flags: /Ogtpy
;	COMDAT ?GetErrorHandler@BaseHeap@@UAGP6AHUErrorCode@@PBDZZXZ
_TEXT	SEGMENT
_this$ = 8						; size = 4
?GetErrorHandler@BaseHeap@@UAGP6AHUErrorCode@@PBDZZXZ PROC ; BaseHeap::GetErrorHandler, COMDAT

; 481  : 	return pErrorHandler;

	mov	eax, DWORD PTR _this$[esp-4]
	mov	eax, DWORD PTR [eax+8]

; 482  : }

	ret	4
?GetErrorHandler@BaseHeap@@UAGP6AHUErrorCode@@PBDZZXZ ENDP ; BaseHeap::GetErrorHandler
_TEXT	ENDS
PUBLIC	__$ArrayPad$
PUBLIC	?doError@BaseHeap@@QAEJKKK@Z			; BaseHeap::doError
EXTRN	__imp__LoadStringA@16:PROC
EXTRN	?hInstance@@3PAUHINSTANCE__@@A:DWORD		; hInstance
EXTRN	___security_cookie:DWORD
EXTRN	@__security_check_cookie@4:PROC
; Function compile flags: /Ogtpy
;	COMDAT ?doError@BaseHeap@@QAEJKKK@Z
_TEXT	SEGMENT
_buffer$ = -132						; size = 128
__$ArrayPad$ = -4					; size = 4
_dwErrorNum$ = 8					; size = 4
_dwNum1$ = 12						; size = 4
_dwNum2$ = 16						; size = 4
?doError@BaseHeap@@QAEJKKK@Z PROC			; BaseHeap::doError, COMDAT
; _this$ = ecx

; 486  : {

	sub	esp, 132				; 00000084H
	mov	eax, DWORD PTR ___security_cookie
	xor	eax, esp
	mov	DWORD PTR __$ArrayPad$[esp+132], eax
	push	esi
	mov	esi, ecx

; 487  : 	char buffer[128];
; 488  : 	BOOL32 result = 0;

	xor	eax, eax

; 489  : 
; 490  : 	if (pErrorHandler)

	cmp	DWORD PTR [esi+8], eax
	je	SHORT $LN1@doError

; 491  : 	{
; 492  : 		LoadString(hInstance, dwErrorNum, buffer, sizeof(buffer));

	mov	ecx, DWORD PTR ?hInstance@@3PAUHINSTANCE__@@A ; hInstance
	push	edi
	mov	edi, DWORD PTR _dwErrorNum$[esp+136]
	push	128					; 00000080H
	lea	eax, DWORD PTR _buffer$[esp+144]
	push	eax
	push	edi
	push	ecx
	call	DWORD PTR __imp__LoadStringA@16

; 493  :  		if (dwErrorNum == DAHEAP_VALLOC_FAILED)

	cmp	edi, 7
	jne	SHORT $LN5@doError

; 494  : 		{
; 495  : 			result = pErrorHandler(ErrorCode(ERR_MEMORY, SEV_WARNING),
; 496  : 								   buffer,
; 497  : 								   this,
; 498  : 								   dwErrorNum,
; 499  : 								   dwNum1,
; 500  : 								   dwNum2);

	mov	edx, DWORD PTR _dwNum2$[esp+136]
	mov	ecx, DWORD PTR _dwNum1$[esp+136]
	push	edx
	push	ecx
	push	edi
	push	esi
	lea	edx, DWORD PTR _buffer$[esp+156]
	mov	eax, 1048610				; 00100022H
	push	edx
	push	eax
	mov	eax, DWORD PTR [esi+8]
	call	eax

; 501  : 		}
; 502  : 		else

	jmp	SHORT $LN17@doError
$LN5@doError:

; 503  :  		if (dwErrorNum == DAHEAP_HEAP_EXPANDING || dwErrorNum == DAHEAP_ALLOC_ZERO)

	cmp	edi, 6
	je	SHORT $LN2@doError

; 511  : 		}
; 512  : 		else
; 513  : 		{
; 514  : 			result = pErrorHandler(ErrorCode(ERR_MEMORY, SEV_FATAL),
; 515  : 								   buffer,
; 516  : 								   this,
; 517  : 								   dwErrorNum,
; 518  : 								   dwNum1,
; 519  : 								   dwNum2);

	mov	eax, 1048608				; 00100020H
	cmp	edi, 2
	jne	SHORT $LN18@doError
$LN2@doError:

; 504  : 		{
; 505  : 			result = pErrorHandler(ErrorCode(ERR_MEMORY, SEV_TRACE_2),
; 506  : 								   buffer,
; 507  : 								   this,
; 508  : 								   dwErrorNum,
; 509  : 								   dwNum1,
; 510  : 								   dwNum2);

	mov	eax, 1048613				; 00100025H
$LN18@doError:
	mov	ecx, DWORD PTR _dwNum2$[esp+136]
	mov	edx, DWORD PTR _dwNum1$[esp+136]
	push	ecx
	push	edx
	mov	edx, DWORD PTR [esi+8]
	push	edi
	push	esi
	lea	ecx, DWORD PTR _buffer$[esp+156]
	push	ecx
	push	eax
	call	edx
$LN17@doError:
	add	esp, 24					; 00000018H
	pop	edi
$LN1@doError:

; 520  : 		}
; 521  : 	}
; 522  : 
; 523  : 	return result;
; 524  : }

	mov	ecx, DWORD PTR __$ArrayPad$[esp+136]
	pop	esi
	xor	ecx, esp
	call	@__security_check_cookie@4
	add	esp, 132				; 00000084H
	ret	12					; 0000000cH
?doError@BaseHeap@@QAEJKKK@Z ENDP			; BaseHeap::doError
_TEXT	ENDS
PUBLIC	?SetBlockOwner@BaseHeap@@UAGJPAXK@Z		; BaseHeap::SetBlockOwner
; Function compile flags: /Ogtpy
;	COMDAT ?SetBlockOwner@BaseHeap@@UAGJPAXK@Z
_TEXT	SEGMENT
_this$ = 8						; size = 4
_allocatedBlock$ = 12					; size = 4
_owner$ = 16						; size = 4
?SetBlockOwner@BaseHeap@@UAGJPAXK@Z PROC		; BaseHeap::SetBlockOwner, COMDAT

; 529  : 	BOOL32 result;
; 530  : 	BaseHeap *pHeap = FindTheHeap(allocatedBlock);

	mov	eax, DWORD PTR _this$[esp-4]
	mov	eax, DWORD PTR [eax+16]
	mov	ecx, DWORD PTR _allocatedBlock$[esp-4]
	push	esi
	test	eax, eax
	je	SHORT $LN2@SetBlockOw
$LL8@SetBlockOw:
	mov	edx, ecx
	sub	edx, DWORD PTR [eax+28]
	cmp	edx, DWORD PTR [eax+32]
	jb	SHORT $LN12@SetBlockOw
	mov	eax, DWORD PTR [eax+16]
	test	eax, eax
	jne	SHORT $LL8@SetBlockOw

; 531  : 
; 532  : 	if (pHeap)

	jmp	SHORT $LN2@SetBlockOw
$LN12@SetBlockOw:
	test	eax, eax

; 533  : 		result = pHeap->SetBlockOwner(allocatedBlock, owner);
; 534  : 	else

	jne	SHORT $LN14@SetBlockOw
$LN2@SetBlockOw:

; 535  : 		result = g_pMSHeap->SetBlockOwner(allocatedBlock, owner);

	mov	eax, DWORD PTR ?g_pMSHeap@@3PAUIHeap@@A	; g_pMSHeap
$LN14@SetBlockOw:
	mov	esi, DWORD PTR _owner$[esp]
	mov	edx, DWORD PTR [eax]
	push	esi
	push	ecx
	push	eax
	mov	eax, DWORD PTR [edx+68]
	call	eax
	pop	esi

; 536  : 
; 537  : 	return result;
; 538  : }

	ret	12					; 0000000cH
?SetBlockOwner@BaseHeap@@UAGJPAXK@Z ENDP		; BaseHeap::SetBlockOwner
_TEXT	ENDS
PUBLIC	?GetBlockOwner@BaseHeap@@UAGKPAX@Z		; BaseHeap::GetBlockOwner
; Function compile flags: /Ogtpy
;	COMDAT ?GetBlockOwner@BaseHeap@@UAGKPAX@Z
_TEXT	SEGMENT
_this$ = 8						; size = 4
_allocatedBlock$ = 12					; size = 4
?GetBlockOwner@BaseHeap@@UAGKPAX@Z PROC			; BaseHeap::GetBlockOwner, COMDAT

; 543  : 	U32 result;
; 544  : 	BaseHeap *pHeap = FindTheHeap(allocatedBlock);

	mov	eax, DWORD PTR _this$[esp-4]
	mov	eax, DWORD PTR [eax+16]
	mov	ecx, DWORD PTR _allocatedBlock$[esp-4]
	test	eax, eax
	je	SHORT $LN2@GetBlockOw
	npad	1
$LL8@GetBlockOw:
	mov	edx, ecx
	sub	edx, DWORD PTR [eax+28]
	cmp	edx, DWORD PTR [eax+32]
	jb	SHORT $LN12@GetBlockOw
	mov	eax, DWORD PTR [eax+16]
	test	eax, eax
	jne	SHORT $LL8@GetBlockOw
$LN2@GetBlockOw:

; 548  : 	else
; 549  : 		result = g_pMSHeap->GetBlockOwner(allocatedBlock);

	mov	eax, DWORD PTR ?g_pMSHeap@@3PAUIHeap@@A	; g_pMSHeap
	mov	edx, DWORD PTR [eax]
	mov	DWORD PTR _allocatedBlock$[esp-4], ecx
	mov	DWORD PTR _this$[esp-4], eax
	mov	eax, DWORD PTR [edx+72]
	jmp	eax
$LN12@GetBlockOw:

; 545  : 
; 546  : 	if (pHeap)

	test	eax, eax
	je	SHORT $LN2@GetBlockOw

; 547  : 		result = pHeap->GetBlockOwner(allocatedBlock);

	mov	edx, DWORD PTR [eax]
	mov	DWORD PTR _allocatedBlock$[esp-4], ecx
	mov	DWORD PTR _this$[esp-4], eax
	mov	eax, DWORD PTR [edx+72]
	jmp	eax
?GetBlockOwner@BaseHeap@@UAGKPAX@Z ENDP			; BaseHeap::GetBlockOwner
_TEXT	ENDS
PUBLIC	?HeapMinimize@BaseHeap@@UAGXXZ			; BaseHeap::HeapMinimize
EXTRN	__imp__DeleteCriticalSection@4:PROC
EXTRN	__imp__VirtualFree@12:PROC
; Function compile flags: /Ogtpy
;	COMDAT ?HeapMinimize@BaseHeap@@UAGXXZ
_TEXT	SEGMENT
_this$ = 8						; size = 4
?HeapMinimize@BaseHeap@@UAGXXZ PROC			; BaseHeap::HeapMinimize, COMDAT

; 557  : 	HeapInstance *pList=pHeapList, *prev=0;

	mov	eax, DWORD PTR _this$[esp-4]
	push	ebp
	push	esi
	mov	esi, DWORD PTR [eax+16]
	xor	ebp, ebp

; 558  : 
; 559  : 	if (pList)

	test	esi, esi
	je	SHORT $LN6@HeapMinimi

; 560  : 	while (pList->pNext)		// don't deallocate the initial heap

	mov	eax, DWORD PTR [esi+16]
	test	eax, eax
	je	SHORT $LN6@HeapMinimi
	push	ebx
	mov	ebx, DWORD PTR __imp__VirtualFree@12
	push	edi
	npad	2
$LL7@HeapMinimi:

; 561  : 	{
; 562  : 		// if only allocated block is the control block, free it.
; 563  : 		if (((BASE_BLOCK *)pList->pHeapBase)->isAllocated() == 0 &&
; 564  : 			(((DWORD)((BASE_BLOCK *)pList->pHeapBase)->getLower()) + pList->dwBaseBlockSize) == (DWORD) pList)

	mov	ecx, DWORD PTR [esi+28]
	test	BYTE PTR [ecx], 1
	jne	SHORT $LN5@HeapMinimi
	mov	edx, DWORD PTR [ecx]
	and	edx, -2					; fffffffeH
	add	edx, DWORD PTR [esi+24]
	add	edx, ecx
	cmp	edx, esi
	jne	SHORT $LN5@HeapMinimi

; 565  : 		{
; 566  : 			HeapInstance *pTmp;
; 567  : 
; 568  : 			if (prev)
; 569  : 				pTmp = prev->pNext = pList->pNext;

	mov	edi, eax
	test	ebp, ebp
	je	SHORT $LN4@HeapMinimi
	mov	DWORD PTR [ebp+16], eax

; 570  : 			else

	jmp	SHORT $LN3@HeapMinimi
$LN4@HeapMinimi:

; 571  : 				pTmp = pHeapList = pList->pNext;

	mov	ecx, DWORD PTR _this$[esp+12]
	mov	DWORD PTR [ecx+16], eax
$LN3@HeapMinimi:

; 572  : 
; 573  : 			if (pList->dwFlags & DAHEAPFLAG_MULTITHREADED)

	test	BYTE PTR [esi+12], 1
	je	SHORT $LN2@HeapMinimi

; 574  : 				DeleteCriticalSection(&pList->criticalSection);		

	lea	edx, DWORD PTR [esi+40]
	push	edx
	call	DWORD PTR __imp__DeleteCriticalSection@4
$LN2@HeapMinimi:

; 575  : 
; 576  : 			VirtualFree(pList->pHeapBase, 0, MEM_RELEASE);			// actually frees the instance too

	mov	eax, DWORD PTR [esi+28]
	push	32768					; 00008000H
	push	0
	push	eax
	call	ebx

; 577  : 
; 578  : 			pList = pTmp;

	mov	esi, edi

; 579  : 		}
; 580  : 		else

	jmp	SHORT $LN1@HeapMinimi
$LN5@HeapMinimi:

; 581  : 		{
; 582  : 			prev = pList;

	mov	ebp, esi

; 583  : 			pList = pList->pNext;

	mov	esi, eax
$LN1@HeapMinimi:
	mov	eax, DWORD PTR [esi+16]
	test	eax, eax
	jne	SHORT $LL7@HeapMinimi
	pop	edi
	pop	ebx
$LN6@HeapMinimi:
	pop	esi
	pop	ebp

; 584  : 		}
; 585  : 	}
; 586  : }

	ret	4
?HeapMinimize@BaseHeap@@UAGXXZ ENDP			; BaseHeap::HeapMinimize
_TEXT	ENDS
PUBLIC	?GetHeapFlags@BaseHeap@@UAGKXZ			; BaseHeap::GetHeapFlags
; Function compile flags: /Ogtpy
;	COMDAT ?GetHeapFlags@BaseHeap@@UAGKXZ
_TEXT	SEGMENT
_this$ = 8						; size = 4
?GetHeapFlags@BaseHeap@@UAGKXZ PROC			; BaseHeap::GetHeapFlags, COMDAT

; 591  : 	return (pHeapList) ? pHeapList->dwFlags : dwFlags;

	mov	ecx, DWORD PTR _this$[esp-4]
	mov	eax, DWORD PTR [ecx+16]
	test	eax, eax
	je	SHORT $LN3@GetHeapFla
	mov	eax, DWORD PTR [eax+12]

; 592  : }

	ret	4
$LN3@GetHeapFla:

; 591  : 	return (pHeapList) ? pHeapList->dwFlags : dwFlags;

	mov	eax, DWORD PTR [ecx+12]

; 592  : }

	ret	4
?GetHeapFlags@BaseHeap@@UAGKXZ ENDP			; BaseHeap::GetHeapFlags
_TEXT	ENDS
PUBLIC	?RegisterHeap@@YAXPAUICOManager@@@Z		; RegisterHeap
; Function compile flags: /Ogtpy
;	COMDAT ?RegisterHeap@@YAXPAUICOManager@@@Z
_TEXT	SEGMENT
_pManager$ = 8						; size = 4
?RegisterHeap@@YAXPAUICOManager@@@Z PROC		; RegisterHeap, COMDAT

; 634  : 	pManager->RegisterComponent(&g_heap, interface_name);

	mov	eax, DWORD PTR _pManager$[esp-4]
	mov	ecx, DWORD PTR [eax]
	mov	edx, DWORD PTR [ecx+16]
	push	-2147483648				; 80000000H
	push	OFFSET _interface_name
	push	OFFSET _g_heap
	push	eax
	call	edx

; 635  : }

	ret	0
?RegisterHeap@@YAXPAUICOManager@@@Z ENDP		; RegisterHeap
_TEXT	ENDS
PUBLIC	??0IComponentFactory@@QAE@XZ			; IComponentFactory::IComponentFactory
; Function compile flags: /Ogtpy
;	COMDAT ??0IComponentFactory@@QAE@XZ
_TEXT	SEGMENT
??0IComponentFactory@@QAE@XZ PROC			; IComponentFactory::IComponentFactory, COMDAT
; _this$ = ecx
	mov	eax, ecx
	ret	0
??0IComponentFactory@@QAE@XZ ENDP			; IComponentFactory::IComponentFactory
_TEXT	ENDS
PUBLIC	?verifyBlock@HeapInstance@@QAEPAUBASE_BLOCK@@PAX@Z ; HeapInstance::verifyBlock
; Function compile flags: /Ogtpy
; File m:\archive\conquest\code\libs\src\dacom\baseheap.h
;	COMDAT ?verifyBlock@HeapInstance@@QAEPAUBASE_BLOCK@@PAX@Z
_TEXT	SEGMENT
__pBlock$ = 8						; size = 4
?verifyBlock@HeapInstance@@QAEPAUBASE_BLOCK@@PAX@Z PROC	; HeapInstance::verifyBlock, COMDAT
; _this$ = ecx

; 329  : {

	push	esi
	push	edi

; 330  : 	BASE_BLOCK *pBlock;
; 331  : 	
; 332  : 	if (_pBlock == 0)

	mov	edi, DWORD PTR __pBlock$[esp+4]
	mov	esi, ecx
	test	edi, edi

; 333  : 		return 0;

	je	SHORT $LN22@verifyBloc

; 334  : 		
; 335  : 	pBlock = (BASE_BLOCK *) (((C8 *)_pBlock) - dwBaseBlockSize);

	mov	eax, edi
	sub	eax, DWORD PTR [esi+24]

; 336  : 	if (dwFlags & DAHEAPFLAG_NOVERIFYPTR)

	test	BYTE PTR [esi+12], 4

; 337  : 		return pBlock;

	jne	SHORT $LN9@verifyBloc

; 338  : 
; 339  : 	// lower block check
; 340  : 	if (pBlock->getLower()->getUpper() != pBlock)

	mov	ecx, DWORD PTR [eax]
	and	ecx, -2					; fffffffeH
	cmp	DWORD PTR [ecx+eax+4], eax
	jne	SHORT $Error$63197

; 341  : 		goto Error;
; 342  : 	// upper block check
; 343  : 	if (pBlock->getUpper() && pBlock->getUpper()->getLower() != pBlock)

	mov	ecx, DWORD PTR [eax+4]
	test	ecx, ecx
	je	SHORT $LN9@verifyBloc
	mov	edx, DWORD PTR [ecx]
	and	edx, -2					; fffffffeH
	add	edx, ecx
	cmp	edx, eax
	je	SHORT $LN9@verifyBloc
$Error$63197:

; 344  : 		goto Error;
; 345  : 
; 346  : 	return pBlock;
; 347  : Error:
; 348  : 	if (EnumerateBlocks(0,0) == 0)

	mov	eax, DWORD PTR [esi]
	mov	ecx, DWORD PTR [eax+32]
	push	0
	push	0
	push	esi
	call	ecx

; 349  : 		doError(DAHEAP_HEAP_CORRUPTED);

	push	0
	mov	ecx, esi
	test	eax, eax
	jne	SHORT $LN2@verifyBloc
	push	eax
	push	4

; 350  : 	else
; 351  : 		doError(DAHEAP_INVALID_PTR, (DWORD)_pBlock);

	call	?doError@BaseHeap@@QAEJKKK@Z		; BaseHeap::doError
	pop	edi

; 352  : 	return 0;

	xor	eax, eax
	pop	esi

; 353  : }

	ret	4
$LN2@verifyBloc:

; 350  : 	else
; 351  : 		doError(DAHEAP_INVALID_PTR, (DWORD)_pBlock);

	push	edi
	push	5
	call	?doError@BaseHeap@@QAEJKKK@Z		; BaseHeap::doError
$LN22@verifyBloc:

; 352  : 	return 0;

	xor	eax, eax
$LN9@verifyBloc:
	pop	edi
	pop	esi

; 353  : }

	ret	4
?verifyBlock@HeapInstance@@QAEPAUBASE_BLOCK@@PAX@Z ENDP	; HeapInstance::verifyBlock
_TEXT	ENDS
PUBLIC	?AllocateMemory@BaseHeap@@UAGPAXKPBD@Z		; BaseHeap::AllocateMemory
; Function compile flags: /Ogtpy
; File m:\archive\conquest\code\libs\src\dacom\baseheap.cpp
;	COMDAT ?AllocateMemory@BaseHeap@@UAGPAXKPBD@Z
_TEXT	SEGMENT
_desc$63491 = -20					; size = 20
_pHeap$63492 = 8					; size = 4
_this$ = 8						; size = 4
_numBytes$ = 12						; size = 4
_msg$ = 16						; size = 4
?AllocateMemory@BaseHeap@@UAGPAXKPBD@Z PROC		; BaseHeap::AllocateMemory, COMDAT

; 219  : {

	sub	esp, 20					; 00000014H
	push	ebx
	push	ebp
	push	esi
	push	edi

; 220  : 	void * result=0;
; 221  : 	HeapInstance *pList;
; 222  : 	
; 223  : 	if (numBytes == 0)

	mov	edi, DWORD PTR _numBytes$[esp+32]
	xor	ebx, ebx
	test	edi, edi
	jne	SHORT $LN30@AllocateMe

; 224  : 	{
; 225  : 		doError(DAHEAP_ALLOC_ZERO);

	mov	ecx, DWORD PTR _this$[esp+32]
	push	edi
	push	edi
	push	2

; 229  : 	{
; 230  : 		doError(DAHEAP_OVERFLOW, numBytes);

	call	?doError@BaseHeap@@QAEJKKK@Z		; BaseHeap::doError
$Done$63478:
	pop	edi
	pop	esi
	pop	ebp

; 270  : 	}
; 271  : 
; 272  : Done:
; 273  : 	return result;

	mov	eax, ebx
	pop	ebx

; 274  : }

	add	esp, 20					; 00000014H
	ret	12					; 0000000cH
$LN30@AllocateMe:

; 226  : 		goto Done;
; 227  : 	}
; 228  : 	if ((long)numBytes < 0)

	jge	SHORT $LN15@AllocateMe
	mov	ecx, DWORD PTR _this$[esp+32]

; 229  : 	{
; 230  : 		doError(DAHEAP_OVERFLOW, numBytes);

	push	0
	push	edi
	push	3
	call	?doError@BaseHeap@@QAEJKKK@Z		; BaseHeap::doError
	pop	edi
	pop	esi
	pop	ebp

; 270  : 	}
; 271  : 
; 272  : Done:
; 273  : 	return result;

	mov	eax, ebx
	pop	ebx

; 274  : }

	add	esp, 20					; 00000014H
	ret	12					; 0000000cH
$LN15@AllocateMe:

; 231  : 		goto Done;
; 232  : 	}
; 233  : 
; 234  : 	if ((pList = pHeapList) != 0)

	mov	ebp, DWORD PTR _this$[esp+32]
	mov	esi, DWORD PTR [ebp+16]
	xor	ecx, ecx
	cmp	esi, ecx
	je	SHORT $LN10@AllocateMe
$LL12@AllocateMe:

; 235  : 	do
; 236  : 	{
; 237  : 		if ((result = pList->AllocateMemory(numBytes, msg)) != 0)

	mov	ecx, DWORD PTR _msg$[esp+32]
	mov	eax, DWORD PTR [esi]
	mov	edx, DWORD PTR [eax+16]
	push	ecx
	push	edi
	push	esi
	call	edx
	mov	ebx, eax
	test	ebx, ebx
	jne	SHORT $Done$63478

; 238  : 			goto Done;
; 239  : 		pList = pList->pNext;

	mov	esi, DWORD PTR [esi+16]

; 240  : 
; 241  : 	} while (pList != 0);

	test	esi, esi
	jne	SHORT $LL12@AllocateMe
	xor	ecx, ecx
$LN10@AllocateMe:

; 242  : 
; 243  : 	if (result == 0)
; 244  : 	{
; 245  : 		if (pHeapList && (pHeapList->dwFlags & DAHEAPFLAG_GROWHEAP))

	mov	eax, DWORD PTR [ebp+16]
	cmp	eax, ecx
	je	$LN29@AllocateMe
	test	BYTE PTR [eax+12], 32			; 00000020H
	je	$LN29@AllocateMe

; 246  : 		{
; 247  : 			DAHEAPDESC desc(interface_name);

	mov	DWORD PTR _desc$63491[esp+52], ecx
	mov	DWORD PTR _desc$63491[esp+44], ecx
	mov	DWORD PTR _desc$63491[esp+40], OFFSET _interface_name
	mov	DWORD PTR _desc$63491[esp+48], ecx
	mov	DWORD PTR _desc$63491[esp+36], 20	; 00000014H

; 248  : 			BaseHeap * pHeap;
; 249  : 
; 250  : 			desc.growSize = pHeapList->dwGrowSize;

	mov	ecx, DWORD PTR [eax+36]

; 251  : 			desc.heapSize = __max(desc.growSize, numBytes + sizeof(FREE_BLOCK)*4 + sizeof(HeapInstance));

	lea	edx, DWORD PTR [edi+128]
	mov	DWORD PTR _desc$63491[esp+52], ecx
	mov	DWORD PTR _desc$63491[esp+44], ecx
	cmp	ecx, edx
	ja	SHORT $LN21@AllocateMe
	mov	DWORD PTR _desc$63491[esp+44], edx
$LN21@AllocateMe:

; 252  : 			desc.flags = pHeapList->dwFlags;

	mov	eax, DWORD PTR [eax+12]

; 253  : 
; 254  : 			if (CreateInstance(&desc, (void **)&pHeap) == GR_OK)

	mov	ecx, DWORD PTR [ebp]
	mov	ecx, DWORD PTR [ecx+12]
	lea	edx, DWORD PTR _pHeap$63492[esp+32]
	mov	DWORD PTR _desc$63491[esp+48], eax
	push	edx
	lea	eax, DWORD PTR _desc$63491[esp+40]
	push	eax
	push	ebp
	call	ecx
	test	eax, eax
	jne	SHORT $LN29@AllocateMe

; 255  : 			{
; 256  : 				result = pHeap->pHeapList->AllocateMemory(numBytes, msg);

	mov	edx, DWORD PTR _pHeap$63492[esp+32]
	mov	eax, DWORD PTR [edx+16]
	mov	edx, DWORD PTR _msg$[esp+32]
	mov	ecx, DWORD PTR [eax]
	push	edx
	push	edi
	push	eax
	mov	eax, DWORD PTR [ecx+16]
	call	eax
	mov	ebx, eax

; 257  : 				pHeap->Release();		// remove the extra reference

	mov	eax, DWORD PTR _pHeap$63492[esp+32]
	mov	ecx, DWORD PTR [eax]
	mov	edx, DWORD PTR [ecx+8]
	push	eax
	call	edx

; 258  : 				if (result != 0)

	test	ebx, ebx
	je	SHORT $LN29@AllocateMe

; 259  : 				{
; 260  : 					if( (pHeapList->dwFlags & DAHEAPFLAG_NOHEAPEXPANDMSG) == 0 )

	mov	eax, DWORD PTR [ebp+16]
	test	DWORD PTR [eax+12], 256			; 00000100H
	jne	$Done$63478

; 261  : 					{
; 262  : 						doError(DAHEAP_HEAP_EXPANDING, desc.heapSize);	  // actually just a warning

	mov	ecx, DWORD PTR _desc$63491[esp+44]
	push	0
	push	ecx
	push	6
	mov	ecx, ebp
	call	?doError@BaseHeap@@QAEJKKK@Z		; BaseHeap::doError
	pop	edi
	pop	esi
	pop	ebp

; 270  : 	}
; 271  : 
; 272  : Done:
; 273  : 	return result;

	mov	eax, ebx
	pop	ebx

; 274  : }

	add	esp, 20					; 00000014H
	ret	12					; 0000000cH
$LN29@AllocateMe:

; 263  : 					}
; 264  : 					goto Done;
; 265  : 				}
; 266  : 			}
; 267  : 		}
; 268  : 		if (doError(DAHEAP_OUT_OF_MEMORY, numBytes, GetLargestBlock()))

	mov	edx, DWORD PTR [ebp]
	mov	eax, DWORD PTR [edx+52]
	push	ebp
	call	eax
	push	eax
	push	edi
	push	1
	mov	ecx, ebp
	call	?doError@BaseHeap@@QAEJKKK@Z		; BaseHeap::doError
	test	eax, eax
	je	$Done$63478

; 269  : 			return AllocateMemory(numBytes, msg);

	mov	edx, DWORD PTR _msg$[esp+32]
	mov	ecx, DWORD PTR [ebp]
	mov	eax, DWORD PTR [ecx+16]
	push	edx
	push	edi
	push	ebp
	call	eax
	pop	edi
	pop	esi
	pop	ebp
	pop	ebx

; 274  : }

	add	esp, 20					; 00000014H
	ret	12					; 0000000cH
?AllocateMemory@BaseHeap@@UAGPAXKPBD@Z ENDP		; BaseHeap::AllocateMemory
_TEXT	ENDS
PUBLIC	?ReallocateMemory@BaseHeap@@UAGPAXPAXKPBD@Z	; BaseHeap::ReallocateMemory
EXTRN	?free@HeapInstance@@QAIHPAUFREE_BLOCK@@@Z:PROC	; HeapInstance::free
EXTRN	_memcpy:PROC
; Function compile flags: /Ogtpy
;	COMDAT ?ReallocateMemory@BaseHeap@@UAGPAXPAXKPBD@Z
_TEXT	SEGMENT
_this$ = 8						; size = 4
_allocatedBlock$ = 12					; size = 4
_pBlock$63522 = 16					; size = 4
_newSize$ = 16						; size = 4
_msg$ = 20						; size = 4
?ReallocateMemory@BaseHeap@@UAGPAXPAXKPBD@Z PROC	; BaseHeap::ReallocateMemory, COMDAT

; 289  : {

	push	ebp

; 290  : 	if (allocatedBlock == 0)

	mov	ebp, DWORD PTR _allocatedBlock$[esp]
	test	ebp, ebp
	jne	SHORT $LN9@Reallocate

; 291  : 		return AllocateMemory(newSize, msg);

	mov	edx, DWORD PTR _msg$[esp]
	mov	eax, DWORD PTR _this$[esp]
	mov	ecx, DWORD PTR [eax]
	push	edx
	mov	edx, DWORD PTR _newSize$[esp+4]
	push	edx
	push	eax
	mov	eax, DWORD PTR [ecx+16]
	call	eax
	pop	ebp

; 323  : }

	ret	16					; 00000010H
$LN9@Reallocate:

; 292  : 
; 293  : 	HeapInstance *pHeap = FindTheHeap(allocatedBlock);

	mov	ecx, DWORD PTR _this$[esp]
	push	ebx
	push	esi
	mov	esi, DWORD PTR [ecx+16]
	push	edi
	test	esi, esi
	je	SHORT $LN8@Reallocate
$LL17@Reallocate:
	mov	edx, ebp
	sub	edx, DWORD PTR [esi+28]
	cmp	edx, DWORD PTR [esi+32]
	jb	SHORT $LN21@Reallocate
	mov	esi, DWORD PTR [esi+16]
	test	esi, esi
	jne	SHORT $LL17@Reallocate
$LN8@Reallocate:

; 313  : 			}
; 314  : 		}
; 315  : 	}
; 316  : 	else
; 317  : 	{
; 318  : 		result = g_pMSHeap->ReallocateMemory(allocatedBlock, newSize, msg);

	mov	ecx, DWORD PTR _msg$[esp+12]
	mov	eax, DWORD PTR ?g_pMSHeap@@3PAUIHeap@@A	; g_pMSHeap
	mov	edx, DWORD PTR [eax]
	mov	edx, DWORD PTR [edx+24]
	push	ecx
	mov	ecx, DWORD PTR _newSize$[esp+16]
	push	ecx
	push	ebp
	push	eax
	call	edx
	mov	edi, eax
$Done$63524:

; 319  : 	}
; 320  : 
; 321  : Done:
; 322  : 	return result;

	mov	eax, edi
	pop	edi
	pop	esi
	pop	ebx
	pop	ebp

; 323  : }

	ret	16					; 00000010H
$LN21@Reallocate:

; 294  : 	void * result;
; 295  : 
; 296  : 	if (pHeap)

	test	esi, esi
	je	SHORT $LN8@Reallocate

; 297  : 	{
; 298  : 		if ((result = pHeap->ReallocateMemory(allocatedBlock, newSize, msg)) == 0)

	mov	ecx, DWORD PTR _msg$[esp+12]
	mov	ebx, DWORD PTR _newSize$[esp+12]
	mov	eax, DWORD PTR [esi]
	mov	edx, DWORD PTR [eax+24]
	push	ecx
	push	ebx
	push	ebp
	push	esi
	call	edx
	mov	edi, eax
	test	edi, edi
	jne	SHORT $Done$63524

; 299  : 		{
; 300  : 			BASE_BLOCK *pBlock;
; 301  : 
; 302  : 			if (newSize == 0)

	test	ebx, ebx
	je	SHORT $Done$63524

; 303  : 				goto Done;		// already handled
; 304  : 			if ((pBlock = pHeap->verifyBlock(allocatedBlock)) == 0)

	push	ebp
	mov	ecx, esi
	call	?verifyBlock@HeapInstance@@QAEPAUBASE_BLOCK@@PAX@Z ; HeapInstance::verifyBlock
	mov	DWORD PTR _pBlock$63522[esp+12], eax
	test	eax, eax
	jne	SHORT $LN4@Reallocate

; 319  : 	}
; 320  : 
; 321  : Done:
; 322  : 	return result;

	mov	eax, edi
	pop	edi
	pop	esi
	pop	ebx
	pop	ebp

; 323  : }

	ret	16					; 00000010H
$LN4@Reallocate:

; 305  : 			{
; 306  : 				result = 0;
; 307  : 				goto Done;
; 308  : 			}
; 309  : 			if ((result = AllocateMemory(newSize, msg)) != 0)

	mov	edx, DWORD PTR _msg$[esp+12]
	mov	eax, DWORD PTR _this$[esp+12]
	mov	ecx, DWORD PTR [eax]
	push	edx
	push	ebx
	push	eax
	mov	eax, DWORD PTR [ecx+16]
	call	eax
	mov	edi, eax
	test	edi, edi
	je	SHORT $Done$63524

; 310  : 			{
; 311  : 				memcpy(result, allocatedBlock, __min((pBlock->dwSize&~1), newSize));

	mov	ecx, DWORD PTR _pBlock$63522[esp+12]
	mov	eax, DWORD PTR [ecx]
	and	eax, -2					; fffffffeH
	cmp	eax, ebx
	jb	SHORT $LN13@Reallocate
	mov	eax, ebx
$LN13@Reallocate:
	push	eax
	push	ebp
	push	edi
	call	_memcpy

; 312  : 				pHeap->free((FREE_BLOCK *)pBlock);

	mov	edx, DWORD PTR _pBlock$63522[esp+24]
	add	esp, 12					; 0000000cH
	mov	ecx, esi
	call	?free@HeapInstance@@QAIHPAUFREE_BLOCK@@@Z ; HeapInstance::free

; 319  : 	}
; 320  : 
; 321  : Done:
; 322  : 	return result;

	mov	eax, edi
	pop	edi
	pop	esi
	pop	ebx
	pop	ebp

; 323  : }

	ret	16					; 00000010H
?ReallocateMemory@BaseHeap@@UAGPAXPAXKPBD@Z ENDP	; BaseHeap::ReallocateMemory
_TEXT	ENDS
PUBLIC	??0IHeap@@QAE@XZ				; IHeap::IHeap
; Function compile flags: /Ogtpy
;	COMDAT ??0IHeap@@QAE@XZ
_TEXT	SEGMENT
??0IHeap@@QAE@XZ PROC					; IHeap::IHeap, COMDAT
; _this$ = ecx
	mov	eax, ecx
	ret	0
??0IHeap@@QAE@XZ ENDP					; IHeap::IHeap
_TEXT	ENDS
PUBLIC	??_7BaseHeap@@6B@				; BaseHeap::`vftable'
PUBLIC	??0BaseHeap@@QAE@XZ				; BaseHeap::BaseHeap
PUBLIC	??_R4BaseHeap@@6B@				; BaseHeap::`RTTI Complete Object Locator'
PUBLIC	??_R0?AUBaseHeap@@@8				; BaseHeap `RTTI Type Descriptor'
PUBLIC	??_R3BaseHeap@@8				; BaseHeap::`RTTI Class Hierarchy Descriptor'
PUBLIC	??_R2BaseHeap@@8				; BaseHeap::`RTTI Base Class Array'
PUBLIC	??_R1A@?0A@EA@BaseHeap@@8			; BaseHeap::`RTTI Base Class Descriptor at (0,-1,0,64)'
PUBLIC	??_R1A@?0A@EA@IHeap@@8				; IHeap::`RTTI Base Class Descriptor at (0,-1,0,64)'
PUBLIC	??_R0?AUIHeap@@@8				; IHeap `RTTI Type Descriptor'
PUBLIC	??_R3IHeap@@8					; IHeap::`RTTI Class Hierarchy Descriptor'
PUBLIC	??_R2IHeap@@8					; IHeap::`RTTI Base Class Array'
PUBLIC	??_R1A@?0A@EA@IComponentFactory@@8		; IComponentFactory::`RTTI Base Class Descriptor at (0,-1,0,64)'
PUBLIC	??_R0?AUIComponentFactory@@@8			; IComponentFactory `RTTI Type Descriptor'
PUBLIC	??_R3IComponentFactory@@8			; IComponentFactory::`RTTI Class Hierarchy Descriptor'
PUBLIC	??_R2IComponentFactory@@8			; IComponentFactory::`RTTI Base Class Array'
PUBLIC	??_R1A@?0A@EA@IDAComponent@@8			; IDAComponent::`RTTI Base Class Descriptor at (0,-1,0,64)'
PUBLIC	??_R0?AUIDAComponent@@@8			; IDAComponent `RTTI Type Descriptor'
PUBLIC	??_R3IDAComponent@@8				; IDAComponent::`RTTI Class Hierarchy Descriptor'
PUBLIC	??_R2IDAComponent@@8				; IDAComponent::`RTTI Base Class Array'
PUBLIC	?CreateInstance@BaseHeap@@UAG?AW4GENRESULT@@PAUDACOMDESC@@PAPAX@Z ; BaseHeap::CreateInstance
EXTRN	??_7type_info@@6B@:QWORD			; type_info::`vftable'
EXTRN	?malloc_pass_through@BaseHeap@@UAGPAXPBD@Z:PROC	; BaseHeap::malloc_pass_through
EXTRN	?realloc_pass_through@BaseHeap@@UAGPAXPBD@Z:PROC ; BaseHeap::realloc_pass_through
EXTRN	?calloc_pass_through@BaseHeap@@UAGPAXPBD@Z:PROC	; BaseHeap::calloc_pass_through
;	COMDAT ??_R2IDAComponent@@8
; File m:\archive\conquest\code\libs\src\dacom\baseheap.h
rdata$r	SEGMENT
??_R2IDAComponent@@8 DD FLAT:??_R1A@?0A@EA@IDAComponent@@8 ; IDAComponent::`RTTI Base Class Array'
rdata$r	ENDS
;	COMDAT ??_R3IDAComponent@@8
rdata$r	SEGMENT
??_R3IDAComponent@@8 DD 00H				; IDAComponent::`RTTI Class Hierarchy Descriptor'
	DD	00H
	DD	01H
	DD	FLAT:??_R2IDAComponent@@8
rdata$r	ENDS
;	COMDAT ??_R0?AUIDAComponent@@@8
_DATA	SEGMENT
??_R0?AUIDAComponent@@@8 DD FLAT:??_7type_info@@6B@	; IDAComponent `RTTI Type Descriptor'
	DD	00H
	DB	'.?AUIDAComponent@@', 00H
_DATA	ENDS
;	COMDAT ??_R1A@?0A@EA@IDAComponent@@8
rdata$r	SEGMENT
??_R1A@?0A@EA@IDAComponent@@8 DD FLAT:??_R0?AUIDAComponent@@@8 ; IDAComponent::`RTTI Base Class Descriptor at (0,-1,0,64)'
	DD	00H
	DD	00H
	DD	0ffffffffH
	DD	00H
	DD	040H
	DD	FLAT:??_R3IDAComponent@@8
rdata$r	ENDS
;	COMDAT ??_R2IComponentFactory@@8
rdata$r	SEGMENT
??_R2IComponentFactory@@8 DD FLAT:??_R1A@?0A@EA@IComponentFactory@@8 ; IComponentFactory::`RTTI Base Class Array'
	DD	FLAT:??_R1A@?0A@EA@IDAComponent@@8
rdata$r	ENDS
;	COMDAT ??_R3IComponentFactory@@8
rdata$r	SEGMENT
??_R3IComponentFactory@@8 DD 00H			; IComponentFactory::`RTTI Class Hierarchy Descriptor'
	DD	00H
	DD	02H
	DD	FLAT:??_R2IComponentFactory@@8
rdata$r	ENDS
;	COMDAT ??_R0?AUIComponentFactory@@@8
_DATA	SEGMENT
??_R0?AUIComponentFactory@@@8 DD FLAT:??_7type_info@@6B@ ; IComponentFactory `RTTI Type Descriptor'
	DD	00H
	DB	'.?AUIComponentFactory@@', 00H
_DATA	ENDS
;	COMDAT ??_R1A@?0A@EA@IComponentFactory@@8
rdata$r	SEGMENT
??_R1A@?0A@EA@IComponentFactory@@8 DD FLAT:??_R0?AUIComponentFactory@@@8 ; IComponentFactory::`RTTI Base Class Descriptor at (0,-1,0,64)'
	DD	01H
	DD	00H
	DD	0ffffffffH
	DD	00H
	DD	040H
	DD	FLAT:??_R3IComponentFactory@@8
rdata$r	ENDS
;	COMDAT ??_R2IHeap@@8
rdata$r	SEGMENT
??_R2IHeap@@8 DD FLAT:??_R1A@?0A@EA@IHeap@@8		; IHeap::`RTTI Base Class Array'
	DD	FLAT:??_R1A@?0A@EA@IComponentFactory@@8
	DD	FLAT:??_R1A@?0A@EA@IDAComponent@@8
rdata$r	ENDS
;	COMDAT ??_R3IHeap@@8
rdata$r	SEGMENT
??_R3IHeap@@8 DD 00H					; IHeap::`RTTI Class Hierarchy Descriptor'
	DD	00H
	DD	03H
	DD	FLAT:??_R2IHeap@@8
rdata$r	ENDS
;	COMDAT ??_R0?AUIHeap@@@8
_DATA	SEGMENT
??_R0?AUIHeap@@@8 DD FLAT:??_7type_info@@6B@		; IHeap `RTTI Type Descriptor'
	DD	00H
	DB	'.?AUIHeap@@', 00H
_DATA	ENDS
;	COMDAT ??_R1A@?0A@EA@IHeap@@8
rdata$r	SEGMENT
??_R1A@?0A@EA@IHeap@@8 DD FLAT:??_R0?AUIHeap@@@8	; IHeap::`RTTI Base Class Descriptor at (0,-1,0,64)'
	DD	02H
	DD	00H
	DD	0ffffffffH
	DD	00H
	DD	040H
	DD	FLAT:??_R3IHeap@@8
rdata$r	ENDS
;	COMDAT ??_R1A@?0A@EA@BaseHeap@@8
rdata$r	SEGMENT
??_R1A@?0A@EA@BaseHeap@@8 DD FLAT:??_R0?AUBaseHeap@@@8	; BaseHeap::`RTTI Base Class Descriptor at (0,-1,0,64)'
	DD	03H
	DD	00H
	DD	0ffffffffH
	DD	00H
	DD	040H
	DD	FLAT:??_R3BaseHeap@@8
rdata$r	ENDS
;	COMDAT ??_R2BaseHeap@@8
rdata$r	SEGMENT
??_R2BaseHeap@@8 DD FLAT:??_R1A@?0A@EA@BaseHeap@@8	; BaseHeap::`RTTI Base Class Array'
	DD	FLAT:??_R1A@?0A@EA@IHeap@@8
	DD	FLAT:??_R1A@?0A@EA@IComponentFactory@@8
	DD	FLAT:??_R1A@?0A@EA@IDAComponent@@8
rdata$r	ENDS
;	COMDAT ??_R3BaseHeap@@8
rdata$r	SEGMENT
??_R3BaseHeap@@8 DD 00H					; BaseHeap::`RTTI Class Hierarchy Descriptor'
	DD	00H
	DD	04H
	DD	FLAT:??_R2BaseHeap@@8
rdata$r	ENDS
;	COMDAT ??_R0?AUBaseHeap@@@8
_DATA	SEGMENT
??_R0?AUBaseHeap@@@8 DD FLAT:??_7type_info@@6B@		; BaseHeap `RTTI Type Descriptor'
	DD	00H
	DB	'.?AUBaseHeap@@', 00H
_DATA	ENDS
;	COMDAT ??_R4BaseHeap@@6B@
rdata$r	SEGMENT
??_R4BaseHeap@@6B@ DD 00H				; BaseHeap::`RTTI Complete Object Locator'
	DD	00H
	DD	00H
	DD	FLAT:??_R0?AUBaseHeap@@@8
	DD	FLAT:??_R3BaseHeap@@8
rdata$r	ENDS
;	COMDAT ??_7BaseHeap@@6B@
CONST	SEGMENT
??_7BaseHeap@@6B@ DD FLAT:??_R4BaseHeap@@6B@		; BaseHeap::`vftable'
	DD	FLAT:?QueryInterface@BaseHeap@@UAG?AW4GENRESULT@@PBDPAPAX@Z
	DD	FLAT:?AddRef@BaseHeap@@UAGKXZ
	DD	FLAT:?Release@BaseHeap@@UAGKXZ
	DD	FLAT:?CreateInstance@BaseHeap@@UAG?AW4GENRESULT@@PAUDACOMDESC@@PAPAX@Z
	DD	FLAT:?AllocateMemory@BaseHeap@@UAGPAXKPBD@Z
	DD	FLAT:?ClearAllocateMemory@BaseHeap@@UAGPAXKPBDE@Z
	DD	FLAT:?ReallocateMemory@BaseHeap@@UAGPAXPAXKPBD@Z
	DD	FLAT:?FreeMemory@BaseHeap@@UAGJPAX@Z
	DD	FLAT:?EnumerateBlocks@BaseHeap@@UAGJP6GJPAUIHeap@@PAXK1@Z1@Z
	DD	FLAT:?GetBlockSize@BaseHeap@@UAGKPAX@Z
	DD	FLAT:?GetBlockMessage@BaseHeap@@UAGPBDPAX@Z
	DD	FLAT:?DidAlloc@BaseHeap@@UAGJPAX@Z
	DD	FLAT:?GetAvailableMemory@BaseHeap@@UAGKXZ
	DD	FLAT:?GetLargestBlock@BaseHeap@@UAGKXZ
	DD	FLAT:?GetHeapSize@BaseHeap@@UAGKXZ
	DD	FLAT:?SetErrorHandler@BaseHeap@@UAGP6AHUErrorCode@@PBDZZP6AH01ZZ@Z
	DD	FLAT:?GetErrorHandler@BaseHeap@@UAGP6AHUErrorCode@@PBDZZXZ
	DD	FLAT:?SetBlockOwner@BaseHeap@@UAGJPAXK@Z
	DD	FLAT:?GetBlockOwner@BaseHeap@@UAGKPAX@Z
	DD	FLAT:?SetBlockMessage@BaseHeap@@UAGJPAXPBD@Z
	DD	FLAT:?HeapMinimize@BaseHeap@@UAGXXZ
	DD	FLAT:?GetHeapFlags@BaseHeap@@UAGKXZ
	DD	FLAT:?malloc_pass_through@BaseHeap@@UAGPAXPBD@Z
	DD	FLAT:?realloc_pass_through@BaseHeap@@UAGPAXPBD@Z
	DD	FLAT:?calloc_pass_through@BaseHeap@@UAGPAXPBD@Z
; Function compile flags: /Ogtpy
CONST	ENDS
;	COMDAT ??0BaseHeap@@QAE@XZ
_TEXT	SEGMENT
??0BaseHeap@@QAE@XZ PROC				; BaseHeap::BaseHeap, COMDAT
; _this$ = ecx

; 114  : 	BaseHeap (void)

	mov	eax, ecx

; 115  : 	{
; 116  : 		memset(((C8 *) this)+sizeof(DWORD), 0, sizeof(*this)-sizeof(DWORD));

	xor	ecx, ecx
	mov	DWORD PTR [eax], OFFSET ??_7BaseHeap@@6B@
	mov	DWORD PTR [eax+8], ecx
	mov	DWORD PTR [eax+12], ecx
	mov	DWORD PTR [eax+16], ecx

; 117  : 		dwRefs=1;

	mov	DWORD PTR [eax+4], 1

; 118  : 	}

	ret	0
??0BaseHeap@@QAE@XZ ENDP				; BaseHeap::BaseHeap
_TEXT	ENDS
PUBLIC	??_7HeapInstance@@6B@				; HeapInstance::`vftable'
PUBLIC	??0HeapInstance@@QAE@XZ				; HeapInstance::HeapInstance
PUBLIC	??_R4HeapInstance@@6B@				; HeapInstance::`RTTI Complete Object Locator'
PUBLIC	??_R0?AUHeapInstance@@@8			; HeapInstance `RTTI Type Descriptor'
PUBLIC	??_R3HeapInstance@@8				; HeapInstance::`RTTI Class Hierarchy Descriptor'
PUBLIC	??_R2HeapInstance@@8				; HeapInstance::`RTTI Base Class Array'
PUBLIC	??_R1A@?0A@EA@HeapInstance@@8			; HeapInstance::`RTTI Base Class Descriptor at (0,-1,0,64)'
EXTRN	?Release@HeapInstance@@UAGKXZ:PROC		; HeapInstance::Release
EXTRN	?AllocateMemory@HeapInstance@@UAGPAXKPBD@Z:PROC	; HeapInstance::AllocateMemory
EXTRN	?ReallocateMemory@HeapInstance@@UAGPAXPAXKPBD@Z:PROC ; HeapInstance::ReallocateMemory
EXTRN	?FreeMemory@HeapInstance@@UAGJPAX@Z:PROC	; HeapInstance::FreeMemory
EXTRN	?EnumerateBlocks@HeapInstance@@UAGJP6GJPAUIHeap@@PAXK1@Z1@Z:PROC ; HeapInstance::EnumerateBlocks
EXTRN	?GetBlockSize@HeapInstance@@UAGKPAX@Z:PROC	; HeapInstance::GetBlockSize
EXTRN	?GetBlockMessage@HeapInstance@@UAGPBDPAX@Z:PROC	; HeapInstance::GetBlockMessage
EXTRN	?DidAlloc@HeapInstance@@UAGJPAX@Z:PROC		; HeapInstance::DidAlloc
EXTRN	?GetAvailableMemory@HeapInstance@@UAGKXZ:PROC	; HeapInstance::GetAvailableMemory
EXTRN	?GetLargestBlock@HeapInstance@@UAGKXZ:PROC	; HeapInstance::GetLargestBlock
EXTRN	?GetHeapSize@HeapInstance@@UAGKXZ:PROC		; HeapInstance::GetHeapSize
EXTRN	?SetErrorHandler@HeapInstance@@UAGP6AHUErrorCode@@PBDZZP6AH01ZZ@Z:PROC ; HeapInstance::SetErrorHandler
EXTRN	?GetErrorHandler@HeapInstance@@UAGP6AHUErrorCode@@PBDZZXZ:PROC ; HeapInstance::GetErrorHandler
EXTRN	?SetBlockOwner@HeapInstance@@UAGJPAXK@Z:PROC	; HeapInstance::SetBlockOwner
EXTRN	?GetBlockOwner@HeapInstance@@UAGKPAX@Z:PROC	; HeapInstance::GetBlockOwner
EXTRN	?SetBlockMessage@HeapInstance@@UAGJPAXPBD@Z:PROC ; HeapInstance::SetBlockMessage
;	COMDAT ??_R1A@?0A@EA@HeapInstance@@8
rdata$r	SEGMENT
??_R1A@?0A@EA@HeapInstance@@8 DD FLAT:??_R0?AUHeapInstance@@@8 ; HeapInstance::`RTTI Base Class Descriptor at (0,-1,0,64)'
	DD	04H
	DD	00H
	DD	0ffffffffH
	DD	00H
	DD	040H
	DD	FLAT:??_R3HeapInstance@@8
rdata$r	ENDS
;	COMDAT ??_R2HeapInstance@@8
rdata$r	SEGMENT
??_R2HeapInstance@@8 DD FLAT:??_R1A@?0A@EA@HeapInstance@@8 ; HeapInstance::`RTTI Base Class Array'
	DD	FLAT:??_R1A@?0A@EA@BaseHeap@@8
	DD	FLAT:??_R1A@?0A@EA@IHeap@@8
	DD	FLAT:??_R1A@?0A@EA@IComponentFactory@@8
	DD	FLAT:??_R1A@?0A@EA@IDAComponent@@8
rdata$r	ENDS
;	COMDAT ??_R3HeapInstance@@8
rdata$r	SEGMENT
??_R3HeapInstance@@8 DD 00H				; HeapInstance::`RTTI Class Hierarchy Descriptor'
	DD	00H
	DD	05H
	DD	FLAT:??_R2HeapInstance@@8
rdata$r	ENDS
;	COMDAT ??_R0?AUHeapInstance@@@8
_DATA	SEGMENT
??_R0?AUHeapInstance@@@8 DD FLAT:??_7type_info@@6B@	; HeapInstance `RTTI Type Descriptor'
	DD	00H
	DB	'.?AUHeapInstance@@', 00H
_DATA	ENDS
;	COMDAT ??_R4HeapInstance@@6B@
rdata$r	SEGMENT
??_R4HeapInstance@@6B@ DD 00H				; HeapInstance::`RTTI Complete Object Locator'
	DD	00H
	DD	00H
	DD	FLAT:??_R0?AUHeapInstance@@@8
	DD	FLAT:??_R3HeapInstance@@8
rdata$r	ENDS
;	COMDAT ??_7HeapInstance@@6B@
CONST	SEGMENT
??_7HeapInstance@@6B@ DD FLAT:??_R4HeapInstance@@6B@	; HeapInstance::`vftable'
	DD	FLAT:?QueryInterface@BaseHeap@@UAG?AW4GENRESULT@@PBDPAPAX@Z
	DD	FLAT:?AddRef@BaseHeap@@UAGKXZ
	DD	FLAT:?Release@HeapInstance@@UAGKXZ
	DD	FLAT:?CreateInstance@BaseHeap@@UAG?AW4GENRESULT@@PAUDACOMDESC@@PAPAX@Z
	DD	FLAT:?AllocateMemory@HeapInstance@@UAGPAXKPBD@Z
	DD	FLAT:?ClearAllocateMemory@BaseHeap@@UAGPAXKPBDE@Z
	DD	FLAT:?ReallocateMemory@HeapInstance@@UAGPAXPAXKPBD@Z
	DD	FLAT:?FreeMemory@HeapInstance@@UAGJPAX@Z
	DD	FLAT:?EnumerateBlocks@HeapInstance@@UAGJP6GJPAUIHeap@@PAXK1@Z1@Z
	DD	FLAT:?GetBlockSize@HeapInstance@@UAGKPAX@Z
	DD	FLAT:?GetBlockMessage@HeapInstance@@UAGPBDPAX@Z
	DD	FLAT:?DidAlloc@HeapInstance@@UAGJPAX@Z
	DD	FLAT:?GetAvailableMemory@HeapInstance@@UAGKXZ
	DD	FLAT:?GetLargestBlock@HeapInstance@@UAGKXZ
	DD	FLAT:?GetHeapSize@HeapInstance@@UAGKXZ
	DD	FLAT:?SetErrorHandler@HeapInstance@@UAGP6AHUErrorCode@@PBDZZP6AH01ZZ@Z
	DD	FLAT:?GetErrorHandler@HeapInstance@@UAGP6AHUErrorCode@@PBDZZXZ
	DD	FLAT:?SetBlockOwner@HeapInstance@@UAGJPAXK@Z
	DD	FLAT:?GetBlockOwner@HeapInstance@@UAGKPAX@Z
	DD	FLAT:?SetBlockMessage@HeapInstance@@UAGJPAXPBD@Z
	DD	FLAT:?HeapMinimize@BaseHeap@@UAGXXZ
	DD	FLAT:?GetHeapFlags@BaseHeap@@UAGKXZ
	DD	FLAT:?malloc_pass_through@BaseHeap@@UAGPAXPBD@Z
	DD	FLAT:?realloc_pass_through@BaseHeap@@UAGPAXPBD@Z
	DD	FLAT:?calloc_pass_through@BaseHeap@@UAGPAXPBD@Z
; Function compile flags: /Ogtpy
CONST	ENDS
;	COMDAT ??0HeapInstance@@QAE@XZ
_TEXT	SEGMENT
??0HeapInstance@@QAE@XZ PROC				; HeapInstance::HeapInstance, COMDAT
; _this$ = ecx

; 196  : 	HeapInstance (void)

	xor	eax, eax
	push	esi
	mov	esi, ecx
	mov	DWORD PTR [esi+8], eax
	mov	DWORD PTR [esi+12], eax
	mov	DWORD PTR [esi+16], eax

; 197  : 	{
; 198  : 		memset(((C8 *) this)+sizeof(BaseHeap), 0, sizeof(*this)-sizeof(BaseHeap));

	push	44					; 0000002cH
	push	eax
	lea	eax, DWORD PTR [esi+20]
	push	eax
	mov	DWORD PTR [esi+4], 1
	mov	DWORD PTR [esi], OFFSET ??_7HeapInstance@@6B@
	call	_memset
	add	esp, 12					; 0000000cH

; 199  : 	}

	mov	eax, esi
	pop	esi
	ret	0
??0HeapInstance@@QAE@XZ ENDP				; HeapInstance::HeapInstance
_TEXT	ENDS
PUBLIC	??_7MTHeapInstance@@6B@				; MTHeapInstance::`vftable'
PUBLIC	??0MTHeapInstance@@QAE@XZ			; MTHeapInstance::MTHeapInstance
PUBLIC	??_R4MTHeapInstance@@6B@			; MTHeapInstance::`RTTI Complete Object Locator'
PUBLIC	??_R0?AUMTHeapInstance@@@8			; MTHeapInstance `RTTI Type Descriptor'
PUBLIC	??_R3MTHeapInstance@@8				; MTHeapInstance::`RTTI Class Hierarchy Descriptor'
PUBLIC	??_R2MTHeapInstance@@8				; MTHeapInstance::`RTTI Base Class Array'
PUBLIC	??_R1A@?0A@EA@MTHeapInstance@@8			; MTHeapInstance::`RTTI Base Class Descriptor at (0,-1,0,64)'
PUBLIC	?AllocateMemory@MTHeapInstance@@UAGPAXKPBD@Z	; MTHeapInstance::AllocateMemory
PUBLIC	?ReallocateMemory@MTHeapInstance@@UAGPAXPAXKPBD@Z ; MTHeapInstance::ReallocateMemory
PUBLIC	?FreeMemory@MTHeapInstance@@UAGJPAX@Z		; MTHeapInstance::FreeMemory
PUBLIC	?EnumerateBlocks@MTHeapInstance@@UAGJP6GJPAUIHeap@@PAXK1@Z1@Z ; MTHeapInstance::EnumerateBlocks
PUBLIC	?GetBlockSize@MTHeapInstance@@UAGKPAX@Z		; MTHeapInstance::GetBlockSize
PUBLIC	?GetBlockMessage@MTHeapInstance@@UAGPBDPAX@Z	; MTHeapInstance::GetBlockMessage
PUBLIC	?DidAlloc@MTHeapInstance@@UAGJPAX@Z		; MTHeapInstance::DidAlloc
PUBLIC	?GetAvailableMemory@MTHeapInstance@@UAGKXZ	; MTHeapInstance::GetAvailableMemory
PUBLIC	?GetLargestBlock@MTHeapInstance@@UAGKXZ		; MTHeapInstance::GetLargestBlock
PUBLIC	?GetHeapSize@MTHeapInstance@@UAGKXZ		; MTHeapInstance::GetHeapSize
PUBLIC	?SetErrorHandler@MTHeapInstance@@UAGP6AHUErrorCode@@PBDZZP6AH01ZZ@Z ; MTHeapInstance::SetErrorHandler
PUBLIC	?GetErrorHandler@MTHeapInstance@@UAGP6AHUErrorCode@@PBDZZXZ ; MTHeapInstance::GetErrorHandler
PUBLIC	?SetBlockOwner@MTHeapInstance@@UAGJPAXK@Z	; MTHeapInstance::SetBlockOwner
PUBLIC	?GetBlockOwner@MTHeapInstance@@UAGKPAX@Z	; MTHeapInstance::GetBlockOwner
PUBLIC	?SetBlockMessage@MTHeapInstance@@UAGJPAXPBD@Z	; MTHeapInstance::SetBlockMessage
;	COMDAT ??_R1A@?0A@EA@MTHeapInstance@@8
rdata$r	SEGMENT
??_R1A@?0A@EA@MTHeapInstance@@8 DD FLAT:??_R0?AUMTHeapInstance@@@8 ; MTHeapInstance::`RTTI Base Class Descriptor at (0,-1,0,64)'
	DD	05H
	DD	00H
	DD	0ffffffffH
	DD	00H
	DD	040H
	DD	FLAT:??_R3MTHeapInstance@@8
rdata$r	ENDS
;	COMDAT ??_R2MTHeapInstance@@8
rdata$r	SEGMENT
??_R2MTHeapInstance@@8 DD FLAT:??_R1A@?0A@EA@MTHeapInstance@@8 ; MTHeapInstance::`RTTI Base Class Array'
	DD	FLAT:??_R1A@?0A@EA@HeapInstance@@8
	DD	FLAT:??_R1A@?0A@EA@BaseHeap@@8
	DD	FLAT:??_R1A@?0A@EA@IHeap@@8
	DD	FLAT:??_R1A@?0A@EA@IComponentFactory@@8
	DD	FLAT:??_R1A@?0A@EA@IDAComponent@@8
rdata$r	ENDS
;	COMDAT ??_R3MTHeapInstance@@8
rdata$r	SEGMENT
??_R3MTHeapInstance@@8 DD 00H				; MTHeapInstance::`RTTI Class Hierarchy Descriptor'
	DD	00H
	DD	06H
	DD	FLAT:??_R2MTHeapInstance@@8
rdata$r	ENDS
;	COMDAT ??_R0?AUMTHeapInstance@@@8
_DATA	SEGMENT
??_R0?AUMTHeapInstance@@@8 DD FLAT:??_7type_info@@6B@	; MTHeapInstance `RTTI Type Descriptor'
	DD	00H
	DB	'.?AUMTHeapInstance@@', 00H
_DATA	ENDS
;	COMDAT ??_R4MTHeapInstance@@6B@
rdata$r	SEGMENT
??_R4MTHeapInstance@@6B@ DD 00H				; MTHeapInstance::`RTTI Complete Object Locator'
	DD	00H
	DD	00H
	DD	FLAT:??_R0?AUMTHeapInstance@@@8
	DD	FLAT:??_R3MTHeapInstance@@8
rdata$r	ENDS
;	COMDAT ??_7MTHeapInstance@@6B@
CONST	SEGMENT
??_7MTHeapInstance@@6B@ DD FLAT:??_R4MTHeapInstance@@6B@ ; MTHeapInstance::`vftable'
	DD	FLAT:?QueryInterface@BaseHeap@@UAG?AW4GENRESULT@@PBDPAPAX@Z
	DD	FLAT:?AddRef@BaseHeap@@UAGKXZ
	DD	FLAT:?Release@HeapInstance@@UAGKXZ
	DD	FLAT:?CreateInstance@BaseHeap@@UAG?AW4GENRESULT@@PAUDACOMDESC@@PAPAX@Z
	DD	FLAT:?AllocateMemory@MTHeapInstance@@UAGPAXKPBD@Z
	DD	FLAT:?ClearAllocateMemory@BaseHeap@@UAGPAXKPBDE@Z
	DD	FLAT:?ReallocateMemory@MTHeapInstance@@UAGPAXPAXKPBD@Z
	DD	FLAT:?FreeMemory@MTHeapInstance@@UAGJPAX@Z
	DD	FLAT:?EnumerateBlocks@MTHeapInstance@@UAGJP6GJPAUIHeap@@PAXK1@Z1@Z
	DD	FLAT:?GetBlockSize@MTHeapInstance@@UAGKPAX@Z
	DD	FLAT:?GetBlockMessage@MTHeapInstance@@UAGPBDPAX@Z
	DD	FLAT:?DidAlloc@MTHeapInstance@@UAGJPAX@Z
	DD	FLAT:?GetAvailableMemory@MTHeapInstance@@UAGKXZ
	DD	FLAT:?GetLargestBlock@MTHeapInstance@@UAGKXZ
	DD	FLAT:?GetHeapSize@MTHeapInstance@@UAGKXZ
	DD	FLAT:?SetErrorHandler@MTHeapInstance@@UAGP6AHUErrorCode@@PBDZZP6AH01ZZ@Z
	DD	FLAT:?GetErrorHandler@MTHeapInstance@@UAGP6AHUErrorCode@@PBDZZXZ
	DD	FLAT:?SetBlockOwner@MTHeapInstance@@UAGJPAXK@Z
	DD	FLAT:?GetBlockOwner@MTHeapInstance@@UAGKPAX@Z
	DD	FLAT:?SetBlockMessage@MTHeapInstance@@UAGJPAXPBD@Z
	DD	FLAT:?HeapMinimize@BaseHeap@@UAGXXZ
	DD	FLAT:?GetHeapFlags@BaseHeap@@UAGKXZ
	DD	FLAT:?malloc_pass_through@BaseHeap@@UAGPAXPBD@Z
	DD	FLAT:?realloc_pass_through@BaseHeap@@UAGPAXPBD@Z
	DD	FLAT:?calloc_pass_through@BaseHeap@@UAGPAXPBD@Z
; Function compile flags: /Ogtpy
CONST	ENDS
;	COMDAT ??0MTHeapInstance@@QAE@XZ
_TEXT	SEGMENT
??0MTHeapInstance@@QAE@XZ PROC				; MTHeapInstance::MTHeapInstance, COMDAT
; _this$ = ecx
	xor	eax, eax
	push	esi
	mov	esi, ecx
	mov	DWORD PTR [esi+8], eax
	mov	DWORD PTR [esi+12], eax
	push	44					; 0000002cH
	mov	DWORD PTR [esi+16], eax
	push	eax
	lea	eax, DWORD PTR [esi+20]
	push	eax
	mov	DWORD PTR [esi+4], 1
	call	_memset
	add	esp, 12					; 0000000cH
	mov	DWORD PTR [esi], OFFSET ??_7MTHeapInstance@@6B@
	mov	eax, esi
	pop	esi
	ret	0
??0MTHeapInstance@@QAE@XZ ENDP				; MTHeapInstance::MTHeapInstance
_TEXT	ENDS
EXTRN	__imp__LeaveCriticalSection@4:PROC
EXTRN	__imp__EnterCriticalSection@4:PROC
; Function compile flags: /Ogtpy
;	COMDAT ?AllocateMemory@MTHeapInstance@@UAGPAXKPBD@Z
_TEXT	SEGMENT
_this$ = 8						; size = 4
_numBytes$ = 12						; size = 4
_msg$ = 16						; size = 4
?AllocateMemory@MTHeapInstance@@UAGPAXKPBD@Z PROC	; MTHeapInstance::AllocateMemory, COMDAT

; 363  : 	{

	push	esi
	push	edi

; 364  : 		EnterCriticalSection(&criticalSection);

	mov	edi, DWORD PTR _this$[esp+4]
	lea	esi, DWORD PTR [edi+40]
	push	esi
	call	DWORD PTR __imp__EnterCriticalSection@4

; 365  : 		void * result = HeapInstance::AllocateMemory(numBytes, msg);

	mov	eax, DWORD PTR _msg$[esp+4]
	mov	ecx, DWORD PTR _numBytes$[esp+4]
	push	eax
	push	ecx
	push	edi
	call	?AllocateMemory@HeapInstance@@UAGPAXKPBD@Z ; HeapInstance::AllocateMemory

; 366  : 		LeaveCriticalSection(&criticalSection);

	push	esi
	mov	edi, eax
	call	DWORD PTR __imp__LeaveCriticalSection@4

; 367  : 		return result;

	mov	eax, edi
	pop	edi
	pop	esi

; 368  : 	}

	ret	12					; 0000000cH
?AllocateMemory@MTHeapInstance@@UAGPAXKPBD@Z ENDP	; MTHeapInstance::AllocateMemory
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?ReallocateMemory@MTHeapInstance@@UAGPAXPAXKPBD@Z
_TEXT	SEGMENT
_this$ = 8						; size = 4
_prevBlock$ = 12					; size = 4
_newSize$ = 16						; size = 4
_msg$ = 20						; size = 4
?ReallocateMemory@MTHeapInstance@@UAGPAXPAXKPBD@Z PROC	; MTHeapInstance::ReallocateMemory, COMDAT

; 371  : 	{

	push	esi
	push	edi

; 372  : 		EnterCriticalSection(&criticalSection);

	mov	edi, DWORD PTR _this$[esp+4]
	lea	esi, DWORD PTR [edi+40]
	push	esi
	call	DWORD PTR __imp__EnterCriticalSection@4

; 373  : 		void * result = HeapInstance::ReallocateMemory(prevBlock, newSize, msg);

	mov	eax, DWORD PTR _msg$[esp+4]
	mov	ecx, DWORD PTR _newSize$[esp+4]
	mov	edx, DWORD PTR _prevBlock$[esp+4]
	push	eax
	push	ecx
	push	edx
	push	edi
	call	?ReallocateMemory@HeapInstance@@UAGPAXPAXKPBD@Z ; HeapInstance::ReallocateMemory

; 374  : 		LeaveCriticalSection(&criticalSection);

	push	esi
	mov	edi, eax
	call	DWORD PTR __imp__LeaveCriticalSection@4

; 375  : 		return result;

	mov	eax, edi
	pop	edi
	pop	esi

; 376  : 	}

	ret	16					; 00000010H
?ReallocateMemory@MTHeapInstance@@UAGPAXPAXKPBD@Z ENDP	; MTHeapInstance::ReallocateMemory
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?FreeMemory@MTHeapInstance@@UAGJPAX@Z
_TEXT	SEGMENT
_this$ = 8						; size = 4
_allocatedBlock$ = 12					; size = 4
?FreeMemory@MTHeapInstance@@UAGJPAX@Z PROC		; MTHeapInstance::FreeMemory, COMDAT

; 379  : 	{

	push	ebx

; 380  : 		if (allocatedBlock)

	mov	ebx, DWORD PTR _allocatedBlock$[esp]
	test	ebx, ebx
	je	SHORT $LN1@FreeMemory@2
	push	esi
	push	edi

; 381  : 		{
; 382  : 			EnterCriticalSection(&criticalSection);

	mov	edi, DWORD PTR _this$[esp+8]
	lea	esi, DWORD PTR [edi+40]
	push	esi
	call	DWORD PTR __imp__EnterCriticalSection@4

; 383  : 			BOOL32 result = HeapInstance::FreeMemory(allocatedBlock);

	push	ebx
	push	edi
	call	?FreeMemory@HeapInstance@@UAGJPAX@Z	; HeapInstance::FreeMemory

; 384  : 			LeaveCriticalSection(&criticalSection);

	push	esi
	mov	edi, eax
	call	DWORD PTR __imp__LeaveCriticalSection@4

; 385  : 			return result;

	mov	eax, edi
	pop	edi
	pop	esi
	pop	ebx

; 388  : 	}

	ret	8
$LN1@FreeMemory@2:

; 386  : 		}
; 387  : 		return 0;

	xor	eax, eax
	pop	ebx

; 388  : 	}

	ret	8
?FreeMemory@MTHeapInstance@@UAGJPAX@Z ENDP		; MTHeapInstance::FreeMemory
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?EnumerateBlocks@MTHeapInstance@@UAGJP6GJPAUIHeap@@PAXK1@Z1@Z
_TEXT	SEGMENT
_this$ = 8						; size = 4
_proc$ = 12						; size = 4
_context$ = 16						; size = 4
?EnumerateBlocks@MTHeapInstance@@UAGJP6GJPAUIHeap@@PAXK1@Z1@Z PROC ; MTHeapInstance::EnumerateBlocks, COMDAT

; 391  : 	{

	push	esi
	push	edi

; 392  : 		EnterCriticalSection(&criticalSection);

	mov	edi, DWORD PTR _this$[esp+4]
	lea	esi, DWORD PTR [edi+40]
	push	esi
	call	DWORD PTR __imp__EnterCriticalSection@4

; 393  : 		BOOL32 result = HeapInstance::EnumerateBlocks(proc, context);

	mov	eax, DWORD PTR _context$[esp+4]
	mov	ecx, DWORD PTR _proc$[esp+4]
	push	eax
	push	ecx
	push	edi
	call	?EnumerateBlocks@HeapInstance@@UAGJP6GJPAUIHeap@@PAXK1@Z1@Z ; HeapInstance::EnumerateBlocks

; 394  : 		LeaveCriticalSection(&criticalSection);

	push	esi
	mov	edi, eax
	call	DWORD PTR __imp__LeaveCriticalSection@4

; 395  : 		return result;

	mov	eax, edi
	pop	edi
	pop	esi

; 396  : 	}

	ret	12					; 0000000cH
?EnumerateBlocks@MTHeapInstance@@UAGJP6GJPAUIHeap@@PAXK1@Z1@Z ENDP ; MTHeapInstance::EnumerateBlocks
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?GetBlockSize@MTHeapInstance@@UAGKPAX@Z
_TEXT	SEGMENT
_this$ = 8						; size = 4
_allocatedBlock$ = 12					; size = 4
?GetBlockSize@MTHeapInstance@@UAGKPAX@Z PROC		; MTHeapInstance::GetBlockSize, COMDAT

; 399  : 	{

	push	esi
	push	edi

; 400  : 		EnterCriticalSection(&criticalSection);

	mov	edi, DWORD PTR _this$[esp+4]
	lea	esi, DWORD PTR [edi+40]
	push	esi
	call	DWORD PTR __imp__EnterCriticalSection@4

; 401  : 		U32 result = HeapInstance::GetBlockSize(allocatedBlock);

	mov	eax, DWORD PTR _allocatedBlock$[esp+4]
	push	eax
	push	edi
	call	?GetBlockSize@HeapInstance@@UAGKPAX@Z	; HeapInstance::GetBlockSize

; 402  : 		LeaveCriticalSection(&criticalSection);

	push	esi
	mov	edi, eax
	call	DWORD PTR __imp__LeaveCriticalSection@4

; 403  : 		return result;

	mov	eax, edi
	pop	edi
	pop	esi

; 404  : 	}

	ret	8
?GetBlockSize@MTHeapInstance@@UAGKPAX@Z ENDP		; MTHeapInstance::GetBlockSize
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?GetBlockMessage@MTHeapInstance@@UAGPBDPAX@Z
_TEXT	SEGMENT
_this$ = 8						; size = 4
_allocatedBlock$ = 12					; size = 4
?GetBlockMessage@MTHeapInstance@@UAGPBDPAX@Z PROC	; MTHeapInstance::GetBlockMessage, COMDAT

; 407  : 	{

	push	esi
	push	edi

; 408  : 		EnterCriticalSection(&criticalSection);

	mov	edi, DWORD PTR _this$[esp+4]
	lea	esi, DWORD PTR [edi+40]
	push	esi
	call	DWORD PTR __imp__EnterCriticalSection@4

; 409  : 		const C8 * result = HeapInstance::GetBlockMessage(allocatedBlock);

	mov	eax, DWORD PTR _allocatedBlock$[esp+4]
	push	eax
	push	edi
	call	?GetBlockMessage@HeapInstance@@UAGPBDPAX@Z ; HeapInstance::GetBlockMessage

; 410  : 		LeaveCriticalSection(&criticalSection);

	push	esi
	mov	edi, eax
	call	DWORD PTR __imp__LeaveCriticalSection@4

; 411  : 		return result;

	mov	eax, edi
	pop	edi
	pop	esi

; 412  : 	}

	ret	8
?GetBlockMessage@MTHeapInstance@@UAGPBDPAX@Z ENDP	; MTHeapInstance::GetBlockMessage
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?DidAlloc@MTHeapInstance@@UAGJPAX@Z
_TEXT	SEGMENT
_this$ = 8						; size = 4
_allocatedBlock$ = 12					; size = 4
?DidAlloc@MTHeapInstance@@UAGJPAX@Z PROC		; MTHeapInstance::DidAlloc, COMDAT

; 415  : 	{

	push	esi
	push	edi

; 416  : 		EnterCriticalSection(&criticalSection);

	mov	edi, DWORD PTR _this$[esp+4]
	lea	esi, DWORD PTR [edi+40]
	push	esi
	call	DWORD PTR __imp__EnterCriticalSection@4

; 417  : 		BOOL32 result = HeapInstance::DidAlloc(allocatedBlock);

	mov	eax, DWORD PTR _allocatedBlock$[esp+4]
	push	eax
	push	edi
	call	?DidAlloc@HeapInstance@@UAGJPAX@Z	; HeapInstance::DidAlloc

; 418  : 		LeaveCriticalSection(&criticalSection);

	push	esi
	mov	edi, eax
	call	DWORD PTR __imp__LeaveCriticalSection@4

; 419  : 		return result;

	mov	eax, edi
	pop	edi
	pop	esi

; 420  : 	}

	ret	8
?DidAlloc@MTHeapInstance@@UAGJPAX@Z ENDP		; MTHeapInstance::DidAlloc
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?GetAvailableMemory@MTHeapInstance@@UAGKXZ
_TEXT	SEGMENT
_this$ = 8						; size = 4
?GetAvailableMemory@MTHeapInstance@@UAGKXZ PROC		; MTHeapInstance::GetAvailableMemory, COMDAT

; 423  : 	{

	push	esi
	push	edi

; 424  : 		EnterCriticalSection(&criticalSection);

	mov	edi, DWORD PTR _this$[esp+4]
	lea	esi, DWORD PTR [edi+40]
	push	esi
	call	DWORD PTR __imp__EnterCriticalSection@4

; 425  : 		U32 result = HeapInstance::GetAvailableMemory();

	push	edi
	call	?GetAvailableMemory@HeapInstance@@UAGKXZ ; HeapInstance::GetAvailableMemory

; 426  : 		LeaveCriticalSection(&criticalSection);

	push	esi
	mov	edi, eax
	call	DWORD PTR __imp__LeaveCriticalSection@4

; 427  : 		return result;

	mov	eax, edi
	pop	edi
	pop	esi

; 428  : 	}

	ret	4
?GetAvailableMemory@MTHeapInstance@@UAGKXZ ENDP		; MTHeapInstance::GetAvailableMemory
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?GetLargestBlock@MTHeapInstance@@UAGKXZ
_TEXT	SEGMENT
_this$ = 8						; size = 4
?GetLargestBlock@MTHeapInstance@@UAGKXZ PROC		; MTHeapInstance::GetLargestBlock, COMDAT

; 431  : 	{

	push	esi
	push	edi

; 432  : 		EnterCriticalSection(&criticalSection);

	mov	edi, DWORD PTR _this$[esp+4]
	lea	esi, DWORD PTR [edi+40]
	push	esi
	call	DWORD PTR __imp__EnterCriticalSection@4

; 433  : 		U32 result = HeapInstance::GetLargestBlock();

	push	edi
	call	?GetLargestBlock@HeapInstance@@UAGKXZ	; HeapInstance::GetLargestBlock

; 434  : 		LeaveCriticalSection(&criticalSection);

	push	esi
	mov	edi, eax
	call	DWORD PTR __imp__LeaveCriticalSection@4

; 435  : 		return result;

	mov	eax, edi
	pop	edi
	pop	esi

; 436  : 	}

	ret	4
?GetLargestBlock@MTHeapInstance@@UAGKXZ ENDP		; MTHeapInstance::GetLargestBlock
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?GetHeapSize@MTHeapInstance@@UAGKXZ
_TEXT	SEGMENT
_this$ = 8						; size = 4
?GetHeapSize@MTHeapInstance@@UAGKXZ PROC		; MTHeapInstance::GetHeapSize, COMDAT

; 439  : 	{

	push	esi
	push	edi

; 440  : 		EnterCriticalSection(&criticalSection);

	mov	edi, DWORD PTR _this$[esp+4]
	lea	esi, DWORD PTR [edi+40]
	push	esi
	call	DWORD PTR __imp__EnterCriticalSection@4

; 441  : 		U32 result = HeapInstance::GetHeapSize();		// original alloc - overhead

	push	edi
	call	?GetHeapSize@HeapInstance@@UAGKXZ	; HeapInstance::GetHeapSize

; 442  : 		LeaveCriticalSection(&criticalSection);

	push	esi
	mov	edi, eax
	call	DWORD PTR __imp__LeaveCriticalSection@4

; 443  : 		return result;

	mov	eax, edi
	pop	edi
	pop	esi

; 444  : 	}

	ret	4
?GetHeapSize@MTHeapInstance@@UAGKXZ ENDP		; MTHeapInstance::GetHeapSize
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?SetErrorHandler@MTHeapInstance@@UAGP6AHUErrorCode@@PBDZZP6AH01ZZ@Z
_TEXT	SEGMENT
_this$ = 8						; size = 4
_proc$ = 12						; size = 4
?SetErrorHandler@MTHeapInstance@@UAGP6AHUErrorCode@@PBDZZP6AH01ZZ@Z PROC ; MTHeapInstance::SetErrorHandler, COMDAT

; 447  : 	{

	push	esi
	push	edi

; 448  : 		EnterCriticalSection(&criticalSection);

	mov	edi, DWORD PTR _this$[esp+4]
	lea	esi, DWORD PTR [edi+40]
	push	esi
	call	DWORD PTR __imp__EnterCriticalSection@4

; 449  : 		DA_ERROR_HANDLER result = HeapInstance::SetErrorHandler(proc);

	mov	eax, DWORD PTR _proc$[esp+4]
	push	eax
	push	edi
	call	?SetErrorHandler@HeapInstance@@UAGP6AHUErrorCode@@PBDZZP6AH01ZZ@Z ; HeapInstance::SetErrorHandler

; 450  : 		LeaveCriticalSection(&criticalSection);

	push	esi
	mov	edi, eax
	call	DWORD PTR __imp__LeaveCriticalSection@4

; 451  : 		return result;

	mov	eax, edi
	pop	edi
	pop	esi

; 452  : 	}

	ret	8
?SetErrorHandler@MTHeapInstance@@UAGP6AHUErrorCode@@PBDZZP6AH01ZZ@Z ENDP ; MTHeapInstance::SetErrorHandler
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?GetErrorHandler@MTHeapInstance@@UAGP6AHUErrorCode@@PBDZZXZ
_TEXT	SEGMENT
_this$ = 8						; size = 4
?GetErrorHandler@MTHeapInstance@@UAGP6AHUErrorCode@@PBDZZXZ PROC ; MTHeapInstance::GetErrorHandler, COMDAT

; 455  : 	{

	push	esi
	push	edi

; 456  : 		EnterCriticalSection(&criticalSection);

	mov	edi, DWORD PTR _this$[esp+4]
	lea	esi, DWORD PTR [edi+40]
	push	esi
	call	DWORD PTR __imp__EnterCriticalSection@4

; 457  : 		DA_ERROR_HANDLER result = HeapInstance::GetErrorHandler();

	push	edi
	call	?GetErrorHandler@HeapInstance@@UAGP6AHUErrorCode@@PBDZZXZ ; HeapInstance::GetErrorHandler

; 458  : 		LeaveCriticalSection(&criticalSection);

	push	esi
	mov	edi, eax
	call	DWORD PTR __imp__LeaveCriticalSection@4

; 459  : 		return result;

	mov	eax, edi
	pop	edi
	pop	esi

; 460  : 	}

	ret	4
?GetErrorHandler@MTHeapInstance@@UAGP6AHUErrorCode@@PBDZZXZ ENDP ; MTHeapInstance::GetErrorHandler
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?SetBlockOwner@MTHeapInstance@@UAGJPAXK@Z
_TEXT	SEGMENT
_this$ = 8						; size = 4
_allocatedBlock$ = 12					; size = 4
_caller$ = 16						; size = 4
?SetBlockOwner@MTHeapInstance@@UAGJPAXK@Z PROC		; MTHeapInstance::SetBlockOwner, COMDAT

; 463  : 	{

	push	esi
	push	edi

; 464  : 		EnterCriticalSection(&criticalSection);

	mov	edi, DWORD PTR _this$[esp+4]
	lea	esi, DWORD PTR [edi+40]
	push	esi
	call	DWORD PTR __imp__EnterCriticalSection@4

; 465  : 		BOOL32 result = HeapInstance::SetBlockOwner(allocatedBlock, caller);

	mov	eax, DWORD PTR _caller$[esp+4]
	mov	ecx, DWORD PTR _allocatedBlock$[esp+4]
	push	eax
	push	ecx
	push	edi
	call	?SetBlockOwner@HeapInstance@@UAGJPAXK@Z	; HeapInstance::SetBlockOwner

; 466  : 		LeaveCriticalSection(&criticalSection);

	push	esi
	mov	edi, eax
	call	DWORD PTR __imp__LeaveCriticalSection@4

; 467  : 		return result;

	mov	eax, edi
	pop	edi
	pop	esi

; 468  : 	}

	ret	12					; 0000000cH
?SetBlockOwner@MTHeapInstance@@UAGJPAXK@Z ENDP		; MTHeapInstance::SetBlockOwner
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?GetBlockOwner@MTHeapInstance@@UAGKPAX@Z
_TEXT	SEGMENT
_this$ = 8						; size = 4
_allocatedBlock$ = 12					; size = 4
?GetBlockOwner@MTHeapInstance@@UAGKPAX@Z PROC		; MTHeapInstance::GetBlockOwner, COMDAT

; 471  : 	{

	push	esi
	push	edi

; 472  : 		EnterCriticalSection(&criticalSection);

	mov	edi, DWORD PTR _this$[esp+4]
	lea	esi, DWORD PTR [edi+40]
	push	esi
	call	DWORD PTR __imp__EnterCriticalSection@4

; 473  : 		U32 result = HeapInstance::GetBlockOwner(allocatedBlock);

	mov	eax, DWORD PTR _allocatedBlock$[esp+4]
	push	eax
	push	edi
	call	?GetBlockOwner@HeapInstance@@UAGKPAX@Z	; HeapInstance::GetBlockOwner

; 474  : 		LeaveCriticalSection(&criticalSection);

	push	esi
	mov	edi, eax
	call	DWORD PTR __imp__LeaveCriticalSection@4

; 475  : 		return result;

	mov	eax, edi
	pop	edi
	pop	esi

; 476  : 	}

	ret	8
?GetBlockOwner@MTHeapInstance@@UAGKPAX@Z ENDP		; MTHeapInstance::GetBlockOwner
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?SetBlockMessage@MTHeapInstance@@UAGJPAXPBD@Z
_TEXT	SEGMENT
_this$ = 8						; size = 4
_allocatedBlock$ = 12					; size = 4
_msg$ = 16						; size = 4
?SetBlockMessage@MTHeapInstance@@UAGJPAXPBD@Z PROC	; MTHeapInstance::SetBlockMessage, COMDAT

; 479  : 	{

	push	esi
	push	edi

; 480  : 		EnterCriticalSection(&criticalSection);

	mov	edi, DWORD PTR _this$[esp+4]
	lea	esi, DWORD PTR [edi+40]
	push	esi
	call	DWORD PTR __imp__EnterCriticalSection@4

; 481  : 		BOOL32 result = HeapInstance::SetBlockMessage(allocatedBlock, msg);

	mov	eax, DWORD PTR _msg$[esp+4]
	mov	ecx, DWORD PTR _allocatedBlock$[esp+4]
	push	eax
	push	ecx
	push	edi
	call	?SetBlockMessage@HeapInstance@@UAGJPAXPBD@Z ; HeapInstance::SetBlockMessage

; 482  : 		LeaveCriticalSection(&criticalSection);

	push	esi
	mov	edi, eax
	call	DWORD PTR __imp__LeaveCriticalSection@4

; 483  : 		return result;

	mov	eax, edi
	pop	edi
	pop	esi

; 484  : 	}

	ret	12					; 0000000cH
?SetBlockMessage@MTHeapInstance@@UAGJPAXPBD@Z ENDP	; MTHeapInstance::SetBlockMessage
_TEXT	ENDS
PUBLIC	??_C@_0BD@BIJEMHFL@Heap?5control?5block?$AA@	; `string'
PUBLIC	??_C@_0L@MDPAODCI@descriptor?$AA@		; `string'
EXTRN	??2@YAPAXI@Z:PROC				; operator new
EXTRN	__imp__InitializeCriticalSection@4:PROC
EXTRN	?initHeap@HeapInstance@@QAE?AW4GENRESULT@@PAUDAHEAPDESC@@@Z:PROC ; HeapInstance::initHeap
;	COMDAT ??_C@_0BD@BIJEMHFL@Heap?5control?5block?$AA@
CONST	SEGMENT
??_C@_0BD@BIJEMHFL@Heap?5control?5block?$AA@ DB 'Heap control block', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0L@MDPAODCI@descriptor?$AA@
CONST	SEGMENT
??_C@_0L@MDPAODCI@descriptor?$AA@ DB 'descriptor', 00H	; `string'
; Function compile flags: /Ogtpy
; File m:\archive\conquest\code\libs\src\dacom\baseheap.cpp
CONST	ENDS
;	COMDAT ?CreateInstance@BaseHeap@@UAG?AW4GENRESULT@@PAUDACOMDESC@@PAPAX@Z
_TEXT	SEGMENT
_result$ = -136						; size = 4
$T64234 = -132						; size = 4
_mtheap$ = -128						; size = 64
_stheap$ = -64						; size = 64
_this$ = 8						; size = 4
_descriptor$ = 12					; size = 4
_instance$ = 16						; size = 4
?CreateInstance@BaseHeap@@UAG?AW4GENRESULT@@PAUDACOMDESC@@PAPAX@Z PROC ; BaseHeap::CreateInstance, COMDAT

; 59   : {

	sub	esp, 136				; 00000088H

; 60   : 	ASSERT(instance);

	cmp	DWORD PTR _instance$[esp+132], 0
	jne	SHORT $LN15@CreateInst
	push	OFFSET ??_C@_08EMNENPBA@instance?$AA@
	push	60					; 0000003cH
	push	OFFSET ??_C@_0P@IJECOCHM@?4?2BaseHeap?4cpp?$AA@
	mov	eax, 1048640				; 00100040H
	push	OFFSET ??_C@_0CE@JBJGEEGD@?$CFs?$CI?$CFd?$CJ?5?3?5FATAL?3Assertion?5failed?3@
	push	eax
	call	DWORD PTR _FDUMP
	add	esp, 20					; 00000014H
$LN15@CreateInst:
	push	ebx
	push	ebp
	push	esi
	push	edi

; 61   : 	ASSERT(descriptor);

	mov	edi, DWORD PTR _descriptor$[esp+148]
	test	edi, edi
	jne	SHORT $LN14@CreateInst
	push	OFFSET ??_C@_0L@MDPAODCI@descriptor?$AA@
	push	61					; 0000003dH
	push	OFFSET ??_C@_0P@IJECOCHM@?4?2BaseHeap?4cpp?$AA@
	mov	eax, 1048640				; 00100040H
	push	OFFSET ??_C@_0CE@JBJGEEGD@?$CFs?$CI?$CFd?$CJ?5?3?5FATAL?3Assertion?5failed?3@
	push	eax
	call	DWORD PTR _FDUMP
	add	esp, 20					; 00000014H
$LN14@CreateInst:

; 62   : 
; 63   : 	DAHEAPDESC *lpInfo = (DAHEAPDESC *) descriptor;
; 64   : 	GENRESULT result = GR_OK;
; 65   : 	HeapInstance *pNewHeap = NULL;
; 66   : 	HeapInstance stheap;		// single threaded heap

	xor	eax, eax
	push	44					; 0000002cH
	mov	DWORD PTR _stheap$[esp+160], eax
	push	eax
	mov	DWORD PTR _stheap$[esp+168], eax
	mov	DWORD PTR _stheap$[esp+172], eax
	mov	DWORD PTR _stheap$[esp+176], eax
	lea	eax, DWORD PTR _stheap$[esp+180]
	mov	esi, 1
	push	eax
	xor	ebp, ebp
	mov	DWORD PTR _stheap$[esp+168], esi
	mov	DWORD PTR _stheap$[esp+164], OFFSET ??_7HeapInstance@@6B@
	call	_memset

; 67   : 	MTHeapInstance mtheap;		// multi threaded heap

	xor	eax, eax
	push	44					; 0000002cH
	push	eax
	lea	ecx, DWORD PTR _mtheap$[esp+192]
	mov	DWORD PTR _mtheap$[esp+176], eax
	push	ecx
	mov	DWORD PTR _mtheap$[esp+184], eax
	mov	DWORD PTR _mtheap$[esp+188], eax
	mov	DWORD PTR _mtheap$[esp+192], eax
	mov	DWORD PTR _mtheap$[esp+180], esi
	call	_memset
	add	esp, 24					; 00000018H

; 68   : 	HeapInstance & heap = (lpInfo->flags & DAHEAPFLAG_MULTITHREADED) ? *static_cast<HeapInstance *>(&mtheap) : stheap;

	test	BYTE PTR [edi+12], 1
	mov	DWORD PTR _mtheap$[esp+152], OFFSET ??_7MTHeapInstance@@6B@
	je	SHORT $LN18@CreateInst
	lea	esi, DWORD PTR _mtheap$[esp+152]
	mov	DWORD PTR $T64234[esp+152], esi
	jmp	SHORT $LN19@CreateInst
$LN18@CreateInst:
	lea	edx, DWORD PTR _stheap$[esp+152]
	mov	DWORD PTR $T64234[esp+152], edx
	mov	esi, edx
$LN19@CreateInst:

; 69   : 
; 70   : 	//
; 71   : 	// If unsupported interface requested, fail call
; 72   : 	//
; 73   : 
; 74   : 	if ((lpInfo->size != sizeof(*lpInfo)) || 
; 75   : 		strcmp(lpInfo->interface_name, interface_name))

	cmp	DWORD PTR [edi], 20			; 00000014H
	jne	$LN12@CreateInst
	mov	eax, DWORD PTR [edi+4]
	mov	ecx, OFFSET _interface_name
	npad	6
$LL38@CreateInst:
	mov	dl, BYTE PTR [eax]
	cmp	dl, BYTE PTR [ecx]
	jne	SHORT $LN39@CreateInst
	test	dl, dl
	je	SHORT $LN40@CreateInst
	mov	dl, BYTE PTR [eax+1]
	cmp	dl, BYTE PTR [ecx+1]
	jne	SHORT $LN39@CreateInst
	add	eax, 2
	add	ecx, 2
	test	dl, dl
	jne	SHORT $LL38@CreateInst
$LN40@CreateInst:
	xor	eax, eax
	jmp	SHORT $LN41@CreateInst
$LN39@CreateInst:
	sbb	eax, eax
	sbb	eax, -1
$LN41@CreateInst:
	test	eax, eax
	jne	$LN12@CreateInst

; 78   : 		goto Done;
; 79   : 	}
; 80   : 
; 81   : 
; 82   : 
; 83   : 	heap.pErrorHandler = pErrorHandler;		// propogate error handler to new heap

	mov	ebx, DWORD PTR _this$[esp+148]
	mov	eax, DWORD PTR [ebx+8]

; 84   : 	
; 85   : 	if ((result = heap.initHeap(lpInfo)) == GR_OK)

	push	edi
	mov	ecx, esi
	mov	DWORD PTR [esi+8], eax
	call	?initHeap@HeapInstance@@QAE?AW4GENRESULT@@PAUDAHEAPDESC@@@Z ; HeapInstance::initHeap
	mov	DWORD PTR _result$[esp+152], eax
	test	eax, eax
	jne	$Done$63406

; 86   : 	{
; 87   : 		if ((pNewHeap = (HeapInstance *) heap.AllocateMemory(sizeof(HeapInstance), "Heap control block")) == 0)

	mov	ecx, DWORD PTR [esi]
	mov	edx, DWORD PTR [ecx+16]
	push	OFFSET ??_C@_0BD@BIJEMHFL@Heap?5control?5block?$AA@
	push	64					; 00000040H
	push	esi
	call	edx
	mov	ebp, eax
	test	ebp, ebp

; 88   : 		{
; 89   : 			result = GR_OUT_OF_MEMORY;
; 90   : 			goto Done;

	je	SHORT $LN43@CreateInst

; 91   : 		}
; 92   : 	
; 93   : 		memcpy(pNewHeap, &heap, sizeof(HeapInstance));

	mov	ecx, 16					; 00000010H
	mov	edi, ebp
	rep movsd

; 94   : 		if (pNewHeap->dwFlags & DAHEAPFLAG_MULTITHREADED)

	test	BYTE PTR [ebp+12], 1
	je	SHORT $LN7@CreateInst

; 95   : 		{
; 96   : 			// move criticalsection to the new location
; 97   : 			DeleteCriticalSection(&heap.criticalSection);

	mov	eax, DWORD PTR $T64234[esp+152]
	add	eax, 40					; 00000028H
	push	eax
	call	DWORD PTR __imp__DeleteCriticalSection@4

; 98   : 			InitializeCriticalSection(&pNewHeap->criticalSection);	

	lea	ecx, DWORD PTR [ebp+40]
	push	ecx
	call	DWORD PTR __imp__InitializeCriticalSection@4
$LN7@CreateInst:

; 99   : 		}
; 100  : 		
; 101  : 		// successfully created the heap, now add it to a list
; 102  : 		if (((dwFlags ^ lpInfo->flags) & DAHEAPFLAG_PRIVATE) == 0)

	mov	edi, DWORD PTR _descriptor$[esp+148]
	mov	eax, DWORD PTR [ebx+12]
	mov	edx, DWORD PTR [edi+12]
	xor	edx, eax
	test	dl, 8
	jne	SHORT $LN6@CreateInst

; 103  : 		{
; 104  : 			// adding to the size of an existing heap
; 105  : 			AddToList(pNewHeap);

	mov	edx, ebp
	mov	ecx, ebx
	call	?AddToList@BaseHeap@@QAIHPAUHeapInstance@@@Z ; BaseHeap::AddToList

; 106  : 			AddRef();

	mov	eax, DWORD PTR [ebx]
	mov	ecx, DWORD PTR [eax+4]
	push	ebx
	call	ecx

; 107  : 			pNewHeap = (HeapInstance *) this;

	mov	ebp, ebx

; 108  : 		}
; 109  : 		else

	jmp	SHORT $Done$63406
$LN6@CreateInst:

; 110  : 		if ((dwFlags & DAHEAPFLAG_PRIVATE) == 0)

	test	al, 8
	jne	SHORT $LN4@CreateInst

; 111  : 		{
; 112  : 			// we are public, creating a private heap
; 113  : 			BaseHeap *pNewBase;
; 114  : 
; 115  : 			if ((pNewBase = new BaseHeap) == 0)

	push	20					; 00000014H
	call	??2@YAPAXI@Z				; operator new
	add	esp, 4
	test	eax, eax
	je	SHORT $LN37@CreateInst
	mov	ecx, eax
	call	??0BaseHeap@@QAE@XZ			; BaseHeap::BaseHeap
	mov	esi, eax
	test	esi, esi
	jne	SHORT $LN3@CreateInst
$LN37@CreateInst:

; 116  : 			{
; 117  : 				pNewHeap->Release();

	mov	edx, DWORD PTR [ebp]
	mov	eax, DWORD PTR [edx+8]
	push	ebp
	call	eax

; 118  : 				pNewHeap = 0;

	xor	ebp, ebp
$LN43@CreateInst:

; 119  : 				result = GR_OUT_OF_MEMORY;

	mov	DWORD PTR _result$[esp+152], -4		; fffffffcH

; 120  : 				goto Done;

	jmp	SHORT $Done$63406
$LN3@CreateInst:

; 121  : 			}
; 122  : 
; 123  : 			pNewBase->pErrorHandler = pErrorHandler;

	mov	ecx, DWORD PTR [ebx+8]
	mov	DWORD PTR [esi+8], ecx

; 124  : 			pNewBase->dwFlags = lpInfo->flags;

	mov	edx, DWORD PTR [edi+12]
	mov	DWORD PTR [esi+12], edx

; 125  : 			pNewBase->AddToList(pNewHeap);

	mov	edx, ebp
	mov	ecx, esi
	call	?AddToList@BaseHeap@@QAIHPAUHeapInstance@@@Z ; BaseHeap::AddToList

; 126  : 
; 127  : 			pNewHeap = (HeapInstance *) pNewBase;

	mov	ebp, esi

; 128  : 		}
; 129  : 		else

	jmp	SHORT $Done$63406
$LN4@CreateInst:

; 130  : 		{
; 131  : 			// we are private, creating a public heap
; 132  : 
; 133  : 			g_heap.AddToList(pNewHeap);

	mov	edx, ebp
	mov	ecx, OFFSET _g_heap
	call	?AddToList@BaseHeap@@QAIHPAUHeapInstance@@@Z ; BaseHeap::AddToList

; 134  : 			g_heap.AddRef();

	push	OFFSET _g_heap
	call	?AddRef@BaseHeap@@UAGKXZ		; BaseHeap::AddRef

; 135  : 			pNewHeap = (HeapInstance *) &g_heap;

	mov	ebp, OFFSET _g_heap
	jmp	SHORT $Done$63406
$LN12@CreateInst:

; 76   : 	{
; 77   : 		result = GR_INTERFACE_UNSUPPORTED;

	mov	DWORD PTR _result$[esp+152], -3		; fffffffdH
$Done$63406:

; 136  : 		}
; 137  : 	}
; 138  : 
; 139  : Done:
; 140  : 	*instance = pNewHeap;

	mov	eax, DWORD PTR _instance$[esp+148]
	pop	edi
	pop	esi
	mov	DWORD PTR [eax], ebp

; 141  : 
; 142  : 	return result;

	mov	eax, DWORD PTR _result$[esp+144]
	pop	ebp
	pop	ebx

; 143  : }

	add	esp, 136				; 00000088H
	ret	12					; 0000000cH
?CreateInstance@BaseHeap@@UAG?AW4GENRESULT@@PAUDACOMDESC@@PAPAX@Z ENDP ; BaseHeap::CreateInstance
_TEXT	ENDS
_DATA	SEGMENT
	ORG $+2
_g_heap	DD	FLAT:??_7BaseHeap@@6B@
	DD	01H
	DB	12 DUP(00H)
_DATA	ENDS
END
