; Listing generated by Microsoft (R) Optimizing Compiler Version 19.44.35223.0 

	TITLE	E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\Release\HeapInst.obj
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRT
INCLUDELIB OLDNAMES

PUBLIC	?Release@HeapInstance@@UAGKXZ			; HeapInstance::Release
PUBLIC	?AllocateMemory@HeapInstance@@UAGPAXKPBD@Z	; HeapInstance::AllocateMemory
PUBLIC	?ReallocateMemory@HeapInstance@@UAGPAXPAXKPBD@Z	; HeapInstance::ReallocateMemory
PUBLIC	?FreeMemory@HeapInstance@@UAGJPAX@Z		; HeapInstance::FreeMemory
PUBLIC	?EnumerateBlocks@HeapInstance@@UAGJP6GJPAUIHeap@@PAXK1@Z1@Z ; HeapInstance::EnumerateBlocks
PUBLIC	?GetBlockSize@HeapInstance@@UAGKPAX@Z		; HeapInstance::GetBlockSize
PUBLIC	?GetBlockMessage@HeapInstance@@UAGPBDPAX@Z	; HeapInstance::GetBlockMessage
PUBLIC	?DidAlloc@HeapInstance@@UAGJPAX@Z		; HeapInstance::DidAlloc
PUBLIC	?GetAvailableMemory@HeapInstance@@UAGKXZ	; HeapInstance::GetAvailableMemory
PUBLIC	?GetLargestBlock@HeapInstance@@UAGKXZ		; HeapInstance::GetLargestBlock
PUBLIC	?GetHeapSize@HeapInstance@@UAGKXZ		; HeapInstance::GetHeapSize
PUBLIC	?SetErrorHandler@HeapInstance@@UAGP6AHUErrorCode@@PBDZZP6AH01ZZ@Z ; HeapInstance::SetErrorHandler
PUBLIC	?GetErrorHandler@HeapInstance@@UAGP6AHUErrorCode@@PBDZZXZ ; HeapInstance::GetErrorHandler
PUBLIC	?SetBlockOwner@HeapInstance@@UAGJPAXK@Z		; HeapInstance::SetBlockOwner
PUBLIC	?GetBlockOwner@HeapInstance@@UAGKPAX@Z		; HeapInstance::GetBlockOwner
PUBLIC	?SetBlockMessage@HeapInstance@@UAGJPAXPBD@Z	; HeapInstance::SetBlockMessage
PUBLIC	?initHeap@HeapInstance@@QAE?AW4GENRESULT@@PAUDAHEAPDESC@@@Z ; HeapInstance::initHeap
PUBLIC	?sort@HeapInstance@@QAIXPAUFREE_BLOCK@@@Z	; HeapInstance::sort
PUBLIC	?malloc@HeapInstance@@QAIPAUBASE_BLOCK@@K@Z	; HeapInstance::malloc
PUBLIC	?free@HeapInstance@@QAIHPAUFREE_BLOCK@@@Z	; HeapInstance::free
PUBLIC	??_C@_07OAAHBBHO@pMemory@			; `string'
PUBLIC	??_C@_0EA@LACNAHJK@E?3?2GitHub?2projects?2ConquestFWR?2@ ; `string'
PUBLIC	??_C@_0CE@JBJGEEGD@?$CFs?$CI?$CFd?$CJ?5?3?5FATAL?3Assertion?5failed@ ; `string'
PUBLIC	??_C@_06JMELBMAE@lpDesc@			; `string'
PUBLIC	??_C@_06DPHEOBMB@pBlock@			; `string'
EXTRN	__imp__InitializeCriticalSection@4:PROC
EXTRN	__imp__VirtualAlloc@16:PROC
EXTRN	__imp__VirtualFree@12:PROC
EXTRN	?doError@BaseHeap@@QAEJKKK@Z:PROC		; BaseHeap::doError
EXTRN	_memcpy:PROC
EXTRN	_memset:PROC
EXTRN	_FDUMP:DWORD
;	COMDAT ??_C@_06DPHEOBMB@pBlock@
CONST	SEGMENT
??_C@_06DPHEOBMB@pBlock@ DB 'pBlock', 00H		; `string'
CONST	ENDS
;	COMDAT ??_C@_06JMELBMAE@lpDesc@
CONST	SEGMENT
??_C@_06JMELBMAE@lpDesc@ DB 'lpDesc', 00H		; `string'
CONST	ENDS
;	COMDAT ??_C@_0CE@JBJGEEGD@?$CFs?$CI?$CFd?$CJ?5?3?5FATAL?3Assertion?5failed@
CONST	SEGMENT
??_C@_0CE@JBJGEEGD@?$CFs?$CI?$CFd?$CJ?5?3?5FATAL?3Assertion?5failed@ DB '%'
	DB	's(%d) : FATAL:Assertion failed: %s', 00H	; `string'
CONST	ENDS
;	COMDAT ??_C@_0EA@LACNAHJK@E?3?2GitHub?2projects?2ConquestFWR?2@
CONST	SEGMENT
??_C@_0EA@LACNAHJK@E?3?2GitHub?2projects?2ConquestFWR?2@ DB 'E:\GitHub\pr'
	DB	'ojects\ConquestFWR\Code\Libs\Src\DACOM\HeapInst.cpp', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_07OAAHBBHO@pMemory@
CONST	SEGMENT
??_C@_07OAAHBBHO@pMemory@ DB 'pMemory', 00H		; `string'
CONST	ENDS
; Function compile flags: /Ogtp
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\HeapInst.cpp
;	COMDAT ?snanfill@@YGXPAXK@Z
_TEXT	SEGMENT
_pMemory$ = 8						; size = 4
_numDwords$ = 12					; size = 4
?snanfill@@YGXPAXK@Z PROC				; snanfill, COMDAT

; 32   : {

	push	ebp
	mov	ebp, esp

; 33   : 	ASSERT(pMemory);

	cmp	DWORD PTR _pMemory$[ebp], 0
	jne	SHORT $LN2@snanfill
	push	OFFSET ??_C@_07OAAHBBHO@pMemory@
	push	33					; 00000021H
	push	OFFSET ??_C@_0EA@LACNAHJK@E?3?2GitHub?2projects?2ConquestFWR?2@
	push	OFFSET ??_C@_0CE@JBJGEEGD@?$CFs?$CI?$CFd?$CJ?5?3?5FATAL?3Assertion?5failed@
	push	1048640					; 00100040H
	call	DWORD PTR _FDUMP
	add	esp, 20					; 00000014H
$LN2@snanfill:

; 34   : 	__asm {

	push	edi

; 35   : 		mov edi, DWORD PTR pMemory

	mov	edi, DWORD PTR _pMemory$[ebp]

; 36   : 		cld

	cld

; 37   : 		mov ecx, numDwords

	mov	ecx, DWORD PTR _numDwords$[ebp]

; 38   : 		mov eax, 0FFA01006h

	mov	eax, -6287354				; ffa01006H

; 39   : 		rep stosd

	rep	 stosd

; 34   : 	__asm {

	pop	edi

; 40   : 	}
; 41   : }

	pop	ebp
	ret	8
?snanfill@@YGXPAXK@Z ENDP				; snanfill
_TEXT	ENDS
; Function compile flags: /Ogtp
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\HeapInst.cpp
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.h
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\HeapInst.cpp
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.h
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\HeapInst.cpp
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.h
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\HeapInst.cpp
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.h
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\HeapInst.cpp
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.h
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\HeapInst.cpp
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.h
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\HeapInst.cpp
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.h
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\HeapInst.cpp
;	COMDAT ?free@HeapInstance@@QAIHPAUFREE_BLOCK@@@Z
_TEXT	SEGMENT
?free@HeapInstance@@QAIHPAUFREE_BLOCK@@@Z PROC		; HeapInstance::free, COMDAT
; _this$ = ecx
; _pBlock$ = edx

; 520  : {

	push	ebx
	push	esi
	mov	esi, edx
	push	edi
	mov	edi, ecx

; 521  : 	ASSERT(pBlock);

	test	esi, esi
	jne	SHORT $LN11@free
	push	OFFSET ??_C@_06DPHEOBMB@pBlock@
	push	521					; 00000209H
	push	OFFSET ??_C@_0EA@LACNAHJK@E?3?2GitHub?2projects?2ConquestFWR?2@
	push	OFFSET ??_C@_0CE@JBJGEEGD@?$CFs?$CI?$CFd?$CJ?5?3?5FATAL?3Assertion?5failed@
	push	1048640					; 00100040H
	call	DWORD PTR _FDUMP

; 482  : 	ASSERT(pBlock);

	push	OFFSET ??_C@_06DPHEOBMB@pBlock@
	push	482					; 000001e2H
	push	OFFSET ??_C@_0EA@LACNAHJK@E?3?2GitHub?2projects?2ConquestFWR?2@
	push	OFFSET ??_C@_0CE@JBJGEEGD@?$CFs?$CI?$CFd?$CJ?5?3?5FATAL?3Assertion?5failed@
	push	1048640					; 00100040H
	call	DWORD PTR _FDUMP
	add	esp, 40					; 00000028H
$LN11@free:

; 483  : 
; 484  : 	FREE_BLOCK *pLower;
; 485  : 	DWORD dwSize;
; 486  : 
; 487  : 	if (((dwSize = pBlock->dwSize) & 1) == 0)

	mov	ebx, DWORD PTR [esi]
	test	bl, 1
	jne	SHORT $LN12@free

; 488  : 	{
; 489  : 		doError(DAHEAP_INVALID_PTR, ((DWORD)pBlock) + dwBaseBlockSize);

	mov	eax, DWORD PTR [edi+24]
	mov	ecx, edi
	push	0
	add	eax, esi
	push	eax
	push	5
	call	?doError@BaseHeap@@QAEJKKK@Z		; BaseHeap::doError
	pop	edi

; 556  : }

	pop	esi
	xor	eax, eax
	pop	ebx
	ret	0
$LN12@free:

; 493  : 	if (dwFlags & DAHEAPFLAG_DEBUGFILL_SNAN)		// includes regular mem fill too

	mov	eax, DWORD PTR [edi+12]
	and	eax, 192				; 000000c0H
	je	SHORT $LN15@free

; 494  : 	{
; 495  : 		if ((dwFlags & DAHEAPFLAG_DEBUGFILL_SNAN) == DAHEAPFLAG_DEBUGFILL_SNAN)

	lea	ecx, DWORD PTR [esi+8]
	cmp	eax, 192				; 000000c0H
	jne	SHORT $LN14@free

; 496  : 			snanfill(&pBlock->pMsg, ((dwSize&~1)-daoffsetofmember(BASE_BLOCK,pMsg)) >> 2);

	lea	eax, DWORD PTR [ebx-8]
	shr	eax, 2
	push	eax
	push	ecx
	call	?snanfill@@YGXPAXK@Z			; snanfill
	jmp	SHORT $LN15@free
$LN14@free:

; 497  : 		else
; 498  : 			memset(&pBlock->pMsg, 0xCB, (dwSize&~1)-daoffsetofmember(BASE_BLOCK,pMsg));

	mov	eax, ebx
	and	eax, -2					; fffffffeH
	sub	eax, 8
	push	eax
	push	203					; 000000cbH
	push	ecx
	call	_memset
	add	esp, 12					; 0000000cH
$LN15@free:
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.h

; 83   : 	return (BASE_BLOCK *) (((C8 *)this) + (dwSize & ~1));

	mov	eax, DWORD PTR [esi]
	and	eax, -2					; fffffffeH
	add	eax, esi
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\HeapInst.cpp

; 502  : 	dwSize += pLower->dwSize;

	add	ebx, DWORD PTR [eax]

; 503  : 	
; 504  : 	if ((dwSize & 1) != 0)	// lower block was free

	test	bl, 1
	je	SHORT $LN24@free

; 505  : 	{
; 506  : 		FREE_BLOCK *pNewLower;
; 507  : 
; 508  : 		pBlock->dwSize = dwSize;

	mov	DWORD PTR [esi], ebx
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.h

; 83   : 	return (BASE_BLOCK *) (((C8 *)this) + (dwSize & ~1));

	and	ebx, -2					; fffffffeH
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\HeapInst.cpp

; 510  : 		pNewLower->pUpper = pBlock;	// update new lower block

	mov	DWORD PTR [ebx+esi+4], esi
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.h

; 307  : 	if ((pNext = pBlock->getNext()) == pBlock)

	mov	ecx, DWORD PTR [eax+12]
	cmp	ecx, eax
	jne	SHORT $LN25@free

; 308  : 	{
; 309  : 		// list is empty
; 310  : 
; 311  : 		pFirstFreeBlock = 0;

	mov	DWORD PTR [edi+20], 0

; 312  : 		return;

	jmp	SHORT $LN24@free
$LN25@free:

; 313  : 	}
; 314  : 
; 315  : 	if (pBlock == pFirstFreeBlock)

	cmp	eax, DWORD PTR [edi+20]
	jne	SHORT $LN26@free

; 316  : 		pFirstFreeBlock = pNext;

	mov	DWORD PTR [edi+20], ecx
$LN26@free:

; 317  : 
; 318  : 	// unlink the element
; 319  : 
; 320  : 	pPrev = pBlock->getPrev();

	mov	eax, DWORD PTR [eax+8]

; 321  : 
; 322  : 	pPrev->pNext = pNext;

	mov	DWORD PTR [eax+12], ecx

; 323  : 	pNext->pPrev = pPrev;

	mov	DWORD PTR [ecx+8], eax
$LN24@free:
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\HeapInst.cpp

; 532  : 	if ((pUpper = (FREE_BLOCK *)pBlock->getUpper()) != 0 && 

	mov	edx, DWORD PTR [esi+4]
	test	edx, edx
	je	SHORT $LN44@free
	mov	eax, DWORD PTR [edx]
	add	eax, DWORD PTR [esi]
	test	al, 1
	je	SHORT $LN44@free

; 533  : 		((dwSize = pBlock->dwSize + pUpper->dwSize) & 1) != 0)
; 534  : 	{
; 535  : 		FREE_BLOCK *pLower;
; 536  : 		// just add new size to upper block
; 537  : 		pUpper->dwSize = dwSize-1;		// remove the allocated marker

	dec	eax
	mov	DWORD PTR [edx], eax
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.h

; 83   : 	return (BASE_BLOCK *) (((C8 *)this) + (dwSize & ~1));

	and	eax, -2					; fffffffeH
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\HeapInst.cpp

; 542  : 		pLower->pUpper = pUpper;

	mov	DWORD PTR [eax+edx+4], edx

; 543  : 
; 544  : 		if ((dwFlags & DAHEAPFLAG_NOBESTFIT) == 0)

	test	BYTE PTR [edi+12], 2
	jne	SHORT $LN30@free

; 545  : 			sort(pUpper);

	mov	ecx, edi
	call	?sort@HeapInstance@@QAIXPAUFREE_BLOCK@@@Z ; HeapInstance::sort
	pop	edi

; 556  : }

	pop	esi
	mov	eax, 1
	pop	ebx
	ret	0
$LN44@free:

; 546  : 	}
; 547  : 	else
; 548  : 	{
; 549  : 		// just relink the block into the list
; 550  : 
; 551  : 		pBlock->dwSize &= ~1;		// remove the allocation marker

	mov	eax, DWORD PTR [esi]
	and	eax, -2					; fffffffeH
	mov	DWORD PTR [esi], eax
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.h

; 264  :   	if ((pStart = pFirstFreeBlock) == 0)		

	mov	ecx, DWORD PTR [edi+20]
	test	ecx, ecx
	jne	SHORT $LN33@free

; 265  : 	{
; 266  : 		// empty list
; 267  : 		pFirstFreeBlock = pBlock;

	mov	DWORD PTR [edi+20], esi
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\HeapInst.cpp

; 555  : 	return 1;

	lea	eax, DWORD PTR [ecx+1]
	pop	edi
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.h

; 268  : 		pBlock->pPrev = 

	mov	DWORD PTR [esi+12], esi
	mov	DWORD PTR [esi+8], esi
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\HeapInst.cpp

; 556  : }

	pop	esi
	pop	ebx
	ret	0
$LN33@free:
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.h

; 273  : 	if ((dwFlags & DAHEAPFLAG_NOBESTFIT) == 0)

	test	BYTE PTR [edi+12], 2
	jne	SHORT $LN34@free

; 274  : 	{
; 275  : 		FREE_BLOCK *pTmp;
; 276  : 		DWORD dwSize;
; 277  : 
; 278  : 		pTmp = pStart;

	mov	edx, ecx

; 279  : 		dwSize = pBlock->dwSize;
; 280  : 
; 281  : 		if (dwSize < pStart->dwSize)

	cmp	eax, DWORD PTR [ecx]
	jae	SHORT $LN39@free

; 282  : 			pFirstFreeBlock = pBlock;

	mov	DWORD PTR [edi+20], esi
	jmp	SHORT $LN46@free
$LN39@free:

; 283  : 		else
; 284  : 		{
; 285  : 			while ((pStart = pStart->getNext()) != pTmp)

	mov	ecx, DWORD PTR [ecx+12]
	cmp	ecx, edx
	je	SHORT $LN46@free
$LL31@free:

; 286  : 			{
; 287  : 				if (dwSize <= pStart->dwSize)

	cmp	eax, DWORD PTR [ecx]
	jbe	SHORT $LN46@free

; 283  : 		else
; 284  : 		{
; 285  : 			while ((pStart = pStart->getNext()) != pTmp)

	mov	ecx, DWORD PTR [ecx+12]
	cmp	ecx, edx
	jne	SHORT $LL31@free
$LN46@free:

; 288  : 					break;
; 289  : 			}
; 290  : 		}
; 291  : 		
; 292  : 		pStart = pStart->getPrev();

	mov	ecx, DWORD PTR [ecx+8]
$LN34@free:

; 293  : 	}
; 294  : 
; 295  : 	pBlock->pNext = pStart->pNext;

	mov	eax, DWORD PTR [ecx+12]
	mov	DWORD PTR [esi+12], eax

; 296  : 	pBlock->pPrev = pStart;

	mov	DWORD PTR [esi+8], ecx

; 297  : 	pStart->pNext = pBlock;

	mov	DWORD PTR [ecx+12], esi

; 298  : 	pBlock->pNext->pPrev = pBlock;

	mov	eax, DWORD PTR [esi+12]
	mov	DWORD PTR [eax+8], esi
$LN30@free:
	pop	edi
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\HeapInst.cpp

; 556  : }

	pop	esi
	mov	eax, 1
	pop	ebx
	ret	0
?free@HeapInstance@@QAIHPAUFREE_BLOCK@@@Z ENDP		; HeapInstance::free
_TEXT	ENDS
; Function compile flags: /Ogtp
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\HeapInst.cpp
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.h
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\HeapInst.cpp
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.h
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\HeapInst.cpp
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.h
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\HeapInst.cpp
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.h
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\HeapInst.cpp
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.h
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\HeapInst.cpp
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.h
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\HeapInst.cpp
;	COMDAT ?malloc@HeapInstance@@QAIPAUBASE_BLOCK@@K@Z
_TEXT	SEGMENT
?malloc@HeapInstance@@QAIPAUBASE_BLOCK@@K@Z PROC	; HeapInstance::malloc, COMDAT
; _this$ = ecx
; _dwNumBytes$ = edx

; 425  : 	FREE_BLOCK *pBlock, *pStart;
; 426  : 	DWORD dwRemainder;
; 427  : 
; 428  : 
; 429  : 	dwNumBytes = (dwNumBytes + dwBaseBlockSize + 7) & ~7;	// enforce quad-word alignment
; 430  : 	//	dwNumBytes = __max(sizeof(FREE_BLOCK), dwNumBytes);		// already ensured
; 431  : 
; 432  : 	// search the free list for available block
; 433  : 
; 434  : 	if ((pBlock = pFirstFreeBlock) == 0)

	mov	eax, DWORD PTR [ecx+20]
	push	ebx
	lea	ebx, DWORD PTR [edx+7]
	add	ebx, DWORD PTR [ecx+24]
	push	esi
	and	ebx, -8					; fffffff8H
	push	edi
	test	eax, eax
	je	SHORT $Error$32

; 435  : 		goto Error;		// out of memory
; 436  : 
; 437  : 	pStart = pBlock;	// mark beginning of list

	mov	edx, eax
$LL4@malloc:

; 438  : 
; 439  : 	do
; 440  : 	{
; 441  : 		if ((long)(dwRemainder = pBlock->dwSize - dwNumBytes) >= 0)

	mov	esi, DWORD PTR [eax]
	mov	edi, esi
	sub	edi, ebx
	jns	SHORT $LN24@malloc

; 442  : 			break;		// found a block
; 443  : 	} while ((pBlock = pBlock->getNext()) != pStart);

	mov	eax, DWORD PTR [eax+12]
	cmp	eax, edx
	jne	SHORT $LL4@malloc
$Error$32:
	pop	edi

; 477  : }

	pop	esi
	xor	eax, eax
	pop	ebx
	ret	0
$LN24@malloc:

; 444  : 
; 445  : 	if ((long)dwRemainder < 0)
; 446  : 		goto Error;		// out of memory
; 447  : 
; 448  : 
; 449  : 	if (dwRemainder < sizeof(FREE_BLOCK)*2)

	cmp	edi, 32					; 00000020H
	jae	SHORT $LN10@malloc
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.h

; 307  : 	if ((pNext = pBlock->getNext()) == pBlock)

	mov	edx, DWORD PTR [eax+12]
	cmp	edx, eax
	jne	SHORT $LN15@malloc
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\HeapInst.cpp

; 477  : }

	pop	edi
	pop	esi
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.h

; 311  : 		pFirstFreeBlock = 0;

	mov	DWORD PTR [ecx+20], 0
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\HeapInst.cpp

; 453  : 		pBlock->dwSize |= 1;	// mark as allocated

	or	DWORD PTR [eax], 1

; 477  : }

	pop	ebx
	ret	0
$LN15@malloc:
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.h

; 315  : 	if (pBlock == pFirstFreeBlock)

	cmp	eax, DWORD PTR [ecx+20]
	jne	SHORT $LN16@malloc

; 316  : 		pFirstFreeBlock = pNext;

	mov	DWORD PTR [ecx+20], edx
$LN16@malloc:

; 317  : 
; 318  : 	// unlink the element
; 319  : 
; 320  : 	pPrev = pBlock->getPrev();

	mov	ecx, DWORD PTR [eax+8]
	pop	edi
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\HeapInst.cpp

; 477  : }

	pop	esi
	pop	ebx
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.h

; 322  : 	pPrev->pNext = pNext;

	mov	DWORD PTR [ecx+12], edx

; 323  : 	pNext->pPrev = pPrev;

	mov	DWORD PTR [edx+8], ecx
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\HeapInst.cpp

; 453  : 		pBlock->dwSize |= 1;	// mark as allocated

	or	DWORD PTR [eax], 1

; 477  : }

	ret	0
$LN10@malloc:
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.h

; 83   : 	return (BASE_BLOCK *) (((C8 *)this) + (dwSize & ~1));

	and	esi, -2					; fffffffeH
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\HeapInst.cpp

; 461  : 		pBlock->dwSize = dwRemainder;

	mov	DWORD PTR [eax], edi
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.h

; 83   : 	return (BASE_BLOCK *) (((C8 *)this) + (dwSize & ~1));

	add	esi, eax
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\HeapInst.cpp

; 463  : 		if ((dwFlags & DAHEAPFLAG_NOBESTFIT) == 0)

	test	BYTE PTR [ecx+12], 2
	jne	SHORT $LN12@malloc

; 464  : 			sort(pBlock);

	mov	edx, eax
	call	?sort@HeapInstance@@QAIXPAUFREE_BLOCK@@@Z ; HeapInstance::sort
$LN12@malloc:

; 465  : 
; 466  : 		pTmp->pUpper = pBlock = (FREE_BLOCK *) (((char *)pTmp->pUpper) + dwRemainder);

	mov	edx, DWORD PTR [esi+4]

; 467  : 
; 468  : 		// pBlock -> new block
; 469  : 		pBlock->dwSize = dwNumBytes + 1;		// mark allocated

	lea	ecx, DWORD PTR [ebx+1]
	lea	eax, DWORD PTR [edx+edi]
	mov	DWORD PTR [esi+4], eax
	pop	edi

; 477  : }

	pop	esi
	mov	DWORD PTR [eax], ecx
	mov	DWORD PTR [eax+4], edx
	pop	ebx
	ret	0
?malloc@HeapInstance@@QAIPAUBASE_BLOCK@@K@Z ENDP	; HeapInstance::malloc
_TEXT	ENDS
; Function compile flags: /Ogtp
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\HeapInst.cpp
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.h
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\HeapInst.cpp
;	COMDAT ?sort@HeapInstance@@QAIXPAUFREE_BLOCK@@@Z
_TEXT	SEGMENT
?sort@HeapInstance@@QAIXPAUFREE_BLOCK@@@Z PROC		; HeapInstance::sort, COMDAT
; _this$ = ecx
; _pBlock$ = edx

; 353  : {

	push	ebx
	push	esi
	mov	esi, edx
	mov	ebx, ecx
	push	edi

; 354  : 	ASSERT(pBlock);

	test	esi, esi
	jne	SHORT $LN8@sort
	push	OFFSET ??_C@_06DPHEOBMB@pBlock@
	push	354					; 00000162H
	push	OFFSET ??_C@_0EA@LACNAHJK@E?3?2GitHub?2projects?2ConquestFWR?2@
	push	OFFSET ??_C@_0CE@JBJGEEGD@?$CFs?$CI?$CFd?$CJ?5?3?5FATAL?3Assertion?5failed@
	push	1048640					; 00100040H
	call	DWORD PTR _FDUMP
	add	esp, 20					; 00000014H
$LN8@sort:

; 355  : 
; 356  : 	FREE_BLOCK *pFirst = pFirstFreeBlock, *edi, *esi;
; 357  : 	DWORD dwSize = pBlock->dwSize;
; 358  : 
; 359  : 	// see if we have any work to do at all
; 360  : 
; 361  : 	edi = pBlock->getNext();

	mov	edi, DWORD PTR [esi+12]
	mov	eax, edi
	mov	ecx, DWORD PTR [ebx+20]
	mov	edx, DWORD PTR [esi]

; 362  : 	if (edi == pBlock->getPrev())

	cmp	eax, DWORD PTR [esi+8]
	jne	SHORT $LN9@sort

; 363  : 	{
; 364  : 		// one or two members in the list
; 365  : 		if (edi == pBlock)

	cmp	eax, esi
	je	SHORT $LN15@sort

; 366  : 			return;	// only member of the list
; 367  : 		// assume we are the smaller block
; 368  : 		pFirstFreeBlock = pBlock;

	mov	DWORD PTR [ebx+20], esi

; 369  : 		if (dwSize >= edi->dwSize)

	cmp	edx, DWORD PTR [eax]
	jb	SHORT $LN15@sort

; 420  : }

	pop	edi
	pop	esi
	mov	DWORD PTR [ebx+20], eax
	pop	ebx
	ret	0
$LN9@sort:

; 370  : 			pFirstFreeBlock = edi;		// oops! 
; 371  : 		return;
; 372  : 	}
; 373  : 
; 374  : 	// else see if we are not in the correct order
; 375  : 
; 376  : 	if (dwSize <= edi->dwSize || edi == pFirst)

	cmp	edx, DWORD PTR [eax]
	jbe	SHORT $LN13@sort
	cmp	eax, ecx
	jne	SHORT $LN14@sort
$LN13@sort:

; 377  : 	{
; 378  : 		edi = pBlock->pPrev;

	mov	eax, DWORD PTR [esi+8]

; 379  : 		if (dwSize >= edi->dwSize || pBlock == pFirst)

	cmp	edx, DWORD PTR [eax]
	jae	SHORT $LN15@sort
	cmp	esi, ecx
	je	SHORT $LN15@sort
$LN14@sort:
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.h

; 307  : 	if ((pNext = pBlock->getNext()) == pBlock)

	cmp	edi, esi
	jne	SHORT $LN25@sort

; 308  : 	{
; 309  : 		// list is empty
; 310  : 
; 311  : 		pFirstFreeBlock = 0;

	mov	DWORD PTR [ebx+20], 0

; 312  : 		return;

	jmp	SHORT $LN24@sort
$LN25@sort:

; 313  : 	}
; 314  : 
; 315  : 	if (pBlock == pFirstFreeBlock)

	cmp	esi, ecx
	jne	SHORT $LN26@sort

; 316  : 		pFirstFreeBlock = pNext;

	mov	DWORD PTR [ebx+20], edi
$LN26@sort:

; 317  : 
; 318  : 	// unlink the element
; 319  : 
; 320  : 	pPrev = pBlock->getPrev();

	mov	ecx, DWORD PTR [esi+8]

; 321  : 
; 322  : 	pPrev->pNext = pNext;

	mov	DWORD PTR [ecx+12], edi

; 323  : 	pNext->pPrev = pPrev;

	mov	DWORD PTR [edi+8], ecx
$LN24@sort:
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\HeapInst.cpp

; 387  : 	pFirst = pFirstFreeBlock;

	mov	edi, DWORD PTR [ebx+20]

; 388  : 
; 389  : 	if (pBlock->pPrev != edi)

	cmp	DWORD PTR [esi+8], eax
	je	SHORT $LN16@sort
$LL4@sort:

; 390  : 	{
; 391  : 		// stop when guy to the right is higher than us, or is the FirstMemBlock
; 392  : 		do
; 393  : 		{
; 394  : 			esi = edi;

	mov	ecx, eax

; 395  : 			edi = edi->pNext;

	mov	eax, DWORD PTR [eax+12]

; 396  : 		} while (edi != pFirst && dwSize > edi->dwSize);

	cmp	eax, edi
	je	SHORT $LN6@sort
	cmp	edx, DWORD PTR [eax]
	ja	SHORT $LL4@sort

; 397  : 	}

	jmp	SHORT $LN6@sort
$LN16@sort:

; 398  : 	else
; 399  : 	{
; 400  : 		//	;stop when guy to the left is lower than us, or we stopped on the FirstMemBlock
; 401  : 		//@@Loop2:
; 402  : 		esi = edi;

	mov	ecx, eax
$LL7@sort:

; 403  : 		do
; 404  : 		{
; 405  : 			edi = esi;

	mov	eax, ecx

; 406  : 			esi = esi->pPrev;

	mov	ecx, DWORD PTR [ecx+8]

; 407  : 		} while (edi != pFirst && dwSize < esi->dwSize);

	cmp	eax, edi
	je	SHORT $LN6@sort
	cmp	edx, DWORD PTR [ecx]
	jb	SHORT $LL7@sort
$LN6@sort:

; 408  : 	}
; 409  : 
; 410  : 
; 411  : 	// @@FoundPlace:	; esi-> prev block, edi->next block, ebx -> us
; 412  : 
; 413  : 	pBlock->pPrev = esi;

	mov	DWORD PTR [esi+8], ecx

; 414  : 	pBlock->pNext = edi;

	mov	DWORD PTR [esi+12], eax

; 415  : 	esi->pNext = pBlock;

	mov	DWORD PTR [ecx+12], esi

; 416  : 	edi->pPrev = pBlock;

	mov	DWORD PTR [eax+8], esi

; 417  : 
; 418  : 	if (dwSize < pFirst->dwSize)		// are we now the smallest block of them all?

	cmp	edx, DWORD PTR [edi]
	jae	SHORT $LN15@sort

; 419  : 		pFirstFreeBlock = pBlock;

	mov	DWORD PTR [ebx+20], esi
$LN15@sort:
	pop	edi

; 420  : }

	pop	esi
	pop	ebx
	ret	0
?sort@HeapInstance@@QAIXPAUFREE_BLOCK@@@Z ENDP		; HeapInstance::sort
_TEXT	ENDS
; Function compile flags: /Ogtp
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\HeapInst.cpp
;	COMDAT ?initHeap@HeapInstance@@QAE?AW4GENRESULT@@PAUDAHEAPDESC@@@Z
_TEXT	SEGMENT
_lpDesc$ = 8						; size = 4
?initHeap@HeapInstance@@QAE?AW4GENRESULT@@PAUDAHEAPDESC@@@Z PROC ; HeapInstance::initHeap, COMDAT
; _this$ = ecx

; 296  : {

	push	ebp
	mov	ebp, esp
	push	ebx
	push	esi
	push	edi
	mov	edi, DWORD PTR _lpDesc$[ebp]
	mov	esi, ecx

; 297  : 	BASE_BLOCK *pEnding;
; 298  : 	FREE_BLOCK *pStart;
; 299  : 	DWORD dwSize;
; 300  : 
; 301  : 	ASSERT(lpDesc);

	test	edi, edi
	jne	SHORT $LN2@initHeap
	push	OFFSET ??_C@_06JMELBMAE@lpDesc@
	push	301					; 0000012dH
	push	OFFSET ??_C@_0EA@LACNAHJK@E?3?2GitHub?2projects?2ConquestFWR?2@
	push	OFFSET ??_C@_0CE@JBJGEEGD@?$CFs?$CI?$CFd?$CJ?5?3?5FATAL?3Assertion?5failed@
	push	1048640					; 00100040H
	call	DWORD PTR _FDUMP
	add	esp, 20					; 00000014H
$LN2@initHeap:

; 302  : 
; 303  : 	dwSize = __max((sizeof(FREE_BLOCK)*4 + sizeof(HeapInstance)), lpDesc->heapSize);

	mov	eax, DWORD PTR [edi+8]
	mov	ecx, 128				; 00000080H
	cmp	eax, ecx
	cmovb	eax, ecx

; 304  : 	dwSize = (dwSize+0xFFF)&~0xFFF;

	lea	ebx, DWORD PTR [eax+4095]
	and	ebx, -4096				; fffff000H

; 305  : 
; 306  : 	if ((long)lpDesc->growSize <= 0)

	cmp	DWORD PTR [edi+16], 0
	jg	SHORT $LN13@initHeap

; 307  : 	{
; 308  : 		if (lpDesc->flags & DAHEAPFLAG_GROWHEAP)

	test	BYTE PTR [edi+12], 32			; 00000020H
	je	SHORT $LN13@initHeap

; 348  : }

	pop	edi
	pop	esi
	mov	eax, -2					; fffffffeH
	pop	ebx
	pop	ebp
	ret	4
$LN13@initHeap:

; 309  : 			return GR_INVALID_PARMS;
; 310  : 	}
; 311  : 	
; 312  : 	if ((pHeapBase = VirtualAlloc(0, dwSize, MEM_COMMIT, PAGE_READWRITE)) == 0)

	push	4
	push	4096					; 00001000H
	push	ebx
	push	0
	call	DWORD PTR __imp__VirtualAlloc@16
	mov	DWORD PTR [esi+28], eax
	test	eax, eax
	jne	SHORT $LN5@initHeap

; 313  : 	{
; 314  : 		doError(DAHEAP_VALLOC_FAILED, dwSize);

	push	eax
	push	ebx
	push	7
	mov	ecx, esi
	call	?doError@BaseHeap@@QAEJKKK@Z		; BaseHeap::doError
	pop	edi

; 348  : }

	pop	esi
	mov	eax, -4					; fffffffcH
	pop	ebx
	pop	ebp
	ret	4
$LN5@initHeap:

; 315  : 		return GR_OUT_OF_MEMORY;
; 316  : 	}
; 317  : 
; 318  : 	dwHeapSize = dwSize;

	mov	DWORD PTR [esi+32], ebx

; 319  : 	dwFlags = lpDesc->flags;
; 320  : 	dwBaseBlockSize = (dwFlags & DAHEAPFLAG_NOMSGS) ? 8 : 16;

	mov	eax, 0
	mov	ecx, DWORD PTR [edi+12]
	test	cl, 16					; 00000010H
	mov	DWORD PTR [esi+12], ecx
	sete	al
	lea	eax, DWORD PTR [eax*8+8]
	mov	DWORD PTR [esi+24], eax

; 321  : 	dwGrowSize = lpDesc->growSize;

	mov	eax, DWORD PTR [edi+16]
	mov	DWORD PTR [esi+36], eax

; 322  : 
; 323  : 	if (dwFlags & DAHEAPFLAG_MULTITHREADED)

	test	cl, 1
	je	SHORT $LN6@initHeap

; 324  : 		InitializeCriticalSection(&criticalSection);	

	lea	eax, DWORD PTR [esi+40]
	push	eax
	call	DWORD PTR __imp__InitializeCriticalSection@4
$LN6@initHeap:

; 325  : 
; 326  : 	pStart = (FREE_BLOCK *) pHeapBase;

	mov	ecx, DWORD PTR [esi+28]

; 327  : 	pEnding = (BASE_BLOCK *) (((char *)pHeapBase) + dwHeapSize - dwBaseBlockSize);

	mov	eax, DWORD PTR [esi+32]
	sub	eax, DWORD PTR [esi+24]

; 328  : 
; 329  : 	//----------------------------------------
; 330  : 	// Initialize heap
; 331  : 	//----------------------------------------
; 332  : 
; 333  : 	pStart->dwSize = (DWORD)pEnding - (DWORD)pStart;

	mov	DWORD PTR [ecx], eax

; 334  : 	pStart->pUpper = 0;		// first block in list

	mov	DWORD PTR [ecx+4], 0

; 335  : 	pStart->pPrev = 

	mov	DWORD PTR [ecx+12], ecx
	mov	DWORD PTR [ecx+8], ecx

; 336  : 	pStart->pNext = pStart;
; 337  : 	
; 338  : 	pFirstFreeBlock = pStart;

	mov	DWORD PTR [esi+20], ecx

; 339  : 
; 340  : 	pEnding->dwSize = 1;		// mark as the last block in the heap

	mov	DWORD PTR [eax+ecx], 1

; 341  : 	pEnding->pUpper = pStart;

	mov	DWORD PTR [eax+ecx+4], ecx

; 342  : 
; 343  : 	// initialize all memory to -1
; 344  : 
; 345  : 	memset(pStart+1, -1, pStart->dwSize - sizeof(FREE_BLOCK));

	mov	eax, DWORD PTR [ecx]
	sub	eax, 16					; 00000010H
	push	eax
	lea	eax, DWORD PTR [ecx+16]
	push	-1
	push	eax
	call	_memset
	add	esp, 12					; 0000000cH

; 346  : 
; 347  : 	return GR_OK;

	xor	eax, eax
	pop	edi

; 348  : }

	pop	esi
	pop	ebx
	pop	ebp
	ret	4
?initHeap@HeapInstance@@QAE?AW4GENRESULT@@PAUDAHEAPDESC@@@Z ENDP ; HeapInstance::initHeap
_TEXT	ENDS
; Function compile flags: /Ogtp
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\HeapInst.cpp
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.h
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\HeapInst.cpp
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.h
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\HeapInst.cpp
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.h
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\HeapInst.cpp
;	COMDAT ?SetBlockMessage@HeapInstance@@UAGJPAXPBD@Z
_TEXT	SEGMENT
_this$ = 8						; size = 4
_allocatedBlock$ = 12					; size = 4
_msg$ = 16						; size = 4
?SetBlockMessage@HeapInstance@@UAGJPAXPBD@Z PROC	; HeapInstance::SetBlockMessage, COMDAT

; 197  : {

	push	ebp
	mov	ebp, esp
	push	esi
	mov	esi, DWORD PTR _this$[ebp]
	push	edi
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.h

; 332  : 	if (_pBlock == 0)

	mov	edi, DWORD PTR _allocatedBlock$[ebp]
	test	edi, edi
	je	SHORT $LN2@SetBlockMe

; 333  : 		return 0;
; 334  : 		
; 335  : 	pBlock = (BASE_BLOCK *) (((C8 *)_pBlock) - dwBaseBlockSize);

	mov	ecx, edi
	sub	ecx, DWORD PTR [esi+24]

; 336  : 	if (dwFlags & DAHEAPFLAG_NOVERIFYPTR)

	test	BYTE PTR [esi+12], 4
	jne	SHORT $LN10@SetBlockMe

; 83   : 	return (BASE_BLOCK *) (((C8 *)this) + (dwSize & ~1));

	mov	eax, DWORD PTR [ecx]
	and	eax, -2					; fffffffeH

; 340  : 	if (pBlock->getLower()->getUpper() != pBlock)

	cmp	DWORD PTR [eax+ecx+4], ecx
	jne	SHORT $Error$29

; 341  : 		goto Error;
; 342  : 	// upper block check
; 343  : 	if (pBlock->getUpper() && pBlock->getUpper()->getLower() != pBlock)

	mov	edx, DWORD PTR [ecx+4]
	test	edx, edx
	je	SHORT $LN10@SetBlockMe

; 83   : 	return (BASE_BLOCK *) (((C8 *)this) + (dwSize & ~1));

	mov	eax, DWORD PTR [edx]
	and	eax, -2					; fffffffeH
	add	eax, edx

; 343  : 	if (pBlock->getUpper() && pBlock->getUpper()->getLower() != pBlock)

	cmp	eax, ecx
	jne	SHORT $Error$29
$LN10@SetBlockMe:
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\HeapInst.cpp

; 200  : 	if ((pBlock = verifyBlock(allocatedBlock)) != 0)

	mov	eax, 12					; 0000000cH
	test	ecx, ecx
	je	SHORT $LN2@SetBlockMe
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.h

; 88   : 	return (dwSize & 1);

	test	BYTE PTR [ecx], 1
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\HeapInst.cpp

; 202  : 		if (pBlock->isAllocated() && (dwFlags & DAHEAPFLAG_NOMSGS) == 0)

	je	SHORT $LN3@SetBlockMe
	test	BYTE PTR [eax+esi], 16			; 00000010H
	jne	SHORT $LN3@SetBlockMe

; 203  : 			pBlock->setMsg(msg);

	mov	eax, DWORD PTR _msg$[ebp]
	mov	DWORD PTR [ecx+8], eax
$LN3@SetBlockMe:

; 204  : 		return 1;

	pop	edi
	mov	eax, 1

; 207  : }

	pop	esi
	pop	ebp
	ret	12					; 0000000cH
$Error$29:
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.h

; 348  : 	if (EnumerateBlocks(0,0) == 0)

	mov	eax, DWORD PTR [esi]
	push	0
	push	0
	push	esi
	call	DWORD PTR [eax+32]

; 349  : 		doError(DAHEAP_HEAP_CORRUPTED);
; 350  : 	else
; 351  : 		doError(DAHEAP_INVALID_PTR, (DWORD)_pBlock);
; 352  : 	return 0;

	xor	edx, edx
	mov	ecx, esi
	test	eax, eax
	push	0
	cmovne	edx, edi
	push	edx
	xor	edx, edx
	test	eax, eax
	setne	dl
	add	edx, 4
	push	edx
	call	?doError@BaseHeap@@QAEJKKK@Z		; BaseHeap::doError
$LN2@SetBlockMe:
	pop	edi
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\HeapInst.cpp

; 206  : 	return 0;

	xor	eax, eax

; 207  : }

	pop	esi
	pop	ebp
	ret	12					; 0000000cH
?SetBlockMessage@HeapInstance@@UAGJPAXPBD@Z ENDP	; HeapInstance::SetBlockMessage
_TEXT	ENDS
; Function compile flags: /Ogtp
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\HeapInst.cpp
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.h
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\HeapInst.cpp
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.h
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\HeapInst.cpp
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.h
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\HeapInst.cpp
;	COMDAT ?GetBlockOwner@HeapInstance@@UAGKPAX@Z
_TEXT	SEGMENT
_this$ = 8						; size = 4
_allocatedBlock$ = 12					; size = 4
?GetBlockOwner@HeapInstance@@UAGKPAX@Z PROC		; HeapInstance::GetBlockOwner, COMDAT

; 581  : {

	push	ebp
	mov	ebp, esp
	push	esi
	mov	esi, DWORD PTR _this$[ebp]
	push	edi
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.h

; 332  : 	if (_pBlock == 0)

	mov	edi, DWORD PTR _allocatedBlock$[ebp]
	test	edi, edi
	je	SHORT $LN26@GetBlockOw

; 333  : 		return 0;
; 334  : 		
; 335  : 	pBlock = (BASE_BLOCK *) (((C8 *)_pBlock) - dwBaseBlockSize);

	mov	ecx, edi
	sub	ecx, DWORD PTR [esi+24]

; 336  : 	if (dwFlags & DAHEAPFLAG_NOVERIFYPTR)

	test	BYTE PTR [esi+12], 4
	jne	SHORT $LN13@GetBlockOw

; 83   : 	return (BASE_BLOCK *) (((C8 *)this) + (dwSize & ~1));

	mov	eax, DWORD PTR [ecx]
	and	eax, -2					; fffffffeH

; 340  : 	if (pBlock->getLower()->getUpper() != pBlock)

	cmp	DWORD PTR [eax+ecx+4], ecx
	jne	SHORT $Error$36

; 341  : 		goto Error;
; 342  : 	// upper block check
; 343  : 	if (pBlock->getUpper() && pBlock->getUpper()->getLower() != pBlock)

	mov	edx, DWORD PTR [ecx+4]
	test	edx, edx
	je	SHORT $LN13@GetBlockOw

; 83   : 	return (BASE_BLOCK *) (((C8 *)this) + (dwSize & ~1));

	mov	eax, DWORD PTR [edx]
	and	eax, -2					; fffffffeH
	add	eax, edx

; 343  : 	if (pBlock->getUpper() && pBlock->getUpper()->getLower() != pBlock)

	cmp	eax, ecx
	jne	SHORT $Error$36
$LN13@GetBlockOw:
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\HeapInst.cpp

; 585  : 	if ((pBlock = verifyBlock(allocatedBlock)) == 0)

	mov	eax, 12					; 0000000cH
	test	ecx, ecx
	je	SHORT $LN26@GetBlockOw
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.h

; 88   : 	return (dwSize & 1);

	test	BYTE PTR [ecx], 1
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\HeapInst.cpp

; 588  : 	if (pBlock->isAllocated())

	je	SHORT $LN26@GetBlockOw

; 589  : 	{
; 590  : 		if ((dwFlags & DAHEAPFLAG_NOMSGS) == 0)

	test	BYTE PTR [eax+esi], 16			; 00000010H
	jne	SHORT $LN5@GetBlockOw

; 591  : 			result = pBlock->getOwner();
; 592  : 		else
; 593  : 			result = 0xFFFFFFFF;		// signal that block is allocated, but we don't know who owns it
; 594  : 	}
; 595  : 
; 596  : Done:
; 597  : 	return result;

	mov	eax, DWORD PTR [ecx+12]
	pop	edi

; 598  : }

	pop	esi
	pop	ebp
	ret	8
$LN5@GetBlockOw:
	pop	edi

; 591  : 			result = pBlock->getOwner();
; 592  : 		else
; 593  : 			result = 0xFFFFFFFF;		// signal that block is allocated, but we don't know who owns it
; 594  : 	}
; 595  : 
; 596  : Done:
; 597  : 	return result;

	or	eax, -1

; 598  : }

	pop	esi
	pop	ebp
	ret	8
$Error$36:
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.h

; 348  : 	if (EnumerateBlocks(0,0) == 0)

	mov	eax, DWORD PTR [esi]
	push	0
	push	0
	push	esi
	call	DWORD PTR [eax+32]

; 349  : 		doError(DAHEAP_HEAP_CORRUPTED);
; 350  : 	else
; 351  : 		doError(DAHEAP_INVALID_PTR, (DWORD)_pBlock);
; 352  : 	return 0;

	xor	edx, edx
	mov	ecx, esi
	test	eax, eax
	push	0
	cmovne	edx, edi
	push	edx
	xor	edx, edx
	test	eax, eax
	setne	dl
	add	edx, 4
	push	edx
	call	?doError@BaseHeap@@QAEJKKK@Z		; BaseHeap::doError
$LN26@GetBlockOw:
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\HeapInst.cpp

; 598  : }

	xor	eax, eax
$Done$37:
	pop	edi
	pop	esi
	pop	ebp
	ret	8
?GetBlockOwner@HeapInstance@@UAGKPAX@Z ENDP		; HeapInstance::GetBlockOwner
_TEXT	ENDS
; Function compile flags: /Ogtp
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\HeapInst.cpp
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.h
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\HeapInst.cpp
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.h
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\HeapInst.cpp
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.h
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\HeapInst.cpp
;	COMDAT ?SetBlockOwner@HeapInstance@@UAGJPAXK@Z
_TEXT	SEGMENT
_this$ = 8						; size = 4
_allocatedBlock$ = 12					; size = 4
_owner$ = 16						; size = 4
?SetBlockOwner@HeapInstance@@UAGJPAXK@Z PROC		; HeapInstance::SetBlockOwner, COMDAT

; 560  : {

	push	ebp
	mov	ebp, esp
	push	esi
	mov	esi, DWORD PTR _this$[ebp]
	push	edi
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.h

; 332  : 	if (_pBlock == 0)

	mov	edi, DWORD PTR _allocatedBlock$[ebp]
	test	edi, edi
	je	SHORT $LN22@SetBlockOw

; 333  : 		return 0;
; 334  : 		
; 335  : 	pBlock = (BASE_BLOCK *) (((C8 *)_pBlock) - dwBaseBlockSize);

	mov	ecx, edi
	sub	ecx, DWORD PTR [esi+24]

; 336  : 	if (dwFlags & DAHEAPFLAG_NOVERIFYPTR)

	test	BYTE PTR [esi+12], 4
	jne	SHORT $LN11@SetBlockOw

; 83   : 	return (BASE_BLOCK *) (((C8 *)this) + (dwSize & ~1));

	mov	eax, DWORD PTR [ecx]
	and	eax, -2					; fffffffeH

; 340  : 	if (pBlock->getLower()->getUpper() != pBlock)

	cmp	DWORD PTR [eax+ecx+4], ecx
	jne	SHORT $Error$31

; 341  : 		goto Error;
; 342  : 	// upper block check
; 343  : 	if (pBlock->getUpper() && pBlock->getUpper()->getLower() != pBlock)

	mov	edx, DWORD PTR [ecx+4]
	test	edx, edx
	je	SHORT $LN11@SetBlockOw

; 83   : 	return (BASE_BLOCK *) (((C8 *)this) + (dwSize & ~1));

	mov	eax, DWORD PTR [edx]
	and	eax, -2					; fffffffeH
	add	eax, edx

; 343  : 	if (pBlock->getUpper() && pBlock->getUpper()->getLower() != pBlock)

	cmp	eax, ecx
	jne	SHORT $Error$31
$LN11@SetBlockOw:
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\HeapInst.cpp

; 564  : 	if ((pBlock = verifyBlock(allocatedBlock)) == 0)

	mov	eax, 12					; 0000000cH
	test	ecx, ecx
	je	SHORT $LN22@SetBlockOw
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.h

; 88   : 	return (dwSize & 1);

	test	BYTE PTR [ecx], 1
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\HeapInst.cpp

; 570  : 	if (pBlock->isAllocated() && (dwFlags & DAHEAPFLAG_NOMSGS) == 0)

	je	SHORT $LN4@SetBlockOw
	test	BYTE PTR [eax+esi], 16			; 00000010H
	jne	SHORT $LN4@SetBlockOw

; 571  : 	  	pBlock->setOwner(owner);

	mov	eax, DWORD PTR _owner$[ebp]
	mov	DWORD PTR [ecx+12], eax
$LN4@SetBlockOw:

; 576  : 	return result;

	pop	edi
	mov	eax, 1

; 577  : }

	pop	esi
	pop	ebp
	ret	12					; 0000000cH
$Error$31:
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.h

; 348  : 	if (EnumerateBlocks(0,0) == 0)

	mov	eax, DWORD PTR [esi]
	push	0
	push	0
	push	esi
	call	DWORD PTR [eax+32]

; 349  : 		doError(DAHEAP_HEAP_CORRUPTED);
; 350  : 	else
; 351  : 		doError(DAHEAP_INVALID_PTR, (DWORD)_pBlock);
; 352  : 	return 0;

	xor	edx, edx
	mov	ecx, esi
	test	eax, eax
	push	0
	cmovne	edx, edi
	push	edx
	xor	edx, edx
	test	eax, eax
	setne	dl
	add	edx, 4
	push	edx
	call	?doError@BaseHeap@@QAEJKKK@Z		; BaseHeap::doError
$LN22@SetBlockOw:
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\HeapInst.cpp

; 576  : 	return result;

	xor	eax, eax
$Done$32:
	pop	edi

; 577  : }

	pop	esi
	pop	ebp
	ret	12					; 0000000cH
?SetBlockOwner@HeapInstance@@UAGJPAXK@Z ENDP		; HeapInstance::SetBlockOwner
_TEXT	ENDS
; Function compile flags: /Ogtp
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\HeapInst.cpp
;	COMDAT ?GetErrorHandler@HeapInstance@@UAGP6AHUErrorCode@@PBDZZXZ
_TEXT	SEGMENT
_this$ = 8						; size = 4
?GetErrorHandler@HeapInstance@@UAGP6AHUErrorCode@@PBDZZXZ PROC ; HeapInstance::GetErrorHandler, COMDAT

; 290  : {

	push	ebp
	mov	ebp, esp

; 291  : 	return pErrorHandler;

	mov	eax, DWORD PTR _this$[ebp]
	mov	eax, DWORD PTR [eax+8]

; 292  : }

	pop	ebp
	ret	4
?GetErrorHandler@HeapInstance@@UAGP6AHUErrorCode@@PBDZZXZ ENDP ; HeapInstance::GetErrorHandler
_TEXT	ENDS
; Function compile flags: /Ogtp
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\HeapInst.cpp
;	COMDAT ?SetErrorHandler@HeapInstance@@UAGP6AHUErrorCode@@PBDZZP6AH01ZZ@Z
_TEXT	SEGMENT
_this$ = 8						; size = 4
_proc$ = 12						; size = 4
?SetErrorHandler@HeapInstance@@UAGP6AHUErrorCode@@PBDZZP6AH01ZZ@Z PROC ; HeapInstance::SetErrorHandler, COMDAT

; 280  : {

	push	ebp
	mov	ebp, esp

; 281  : 	DA_ERROR_HANDLER result = pErrorHandler;

	mov	edx, DWORD PTR _this$[ebp]

; 282  : 
; 283  : 	pErrorHandler = proc;

	mov	ecx, DWORD PTR _proc$[ebp]
	mov	eax, DWORD PTR [edx+8]
	mov	DWORD PTR [edx+8], ecx

; 284  :  	
; 285  : 	return result;
; 286  : }

	pop	ebp
	ret	8
?SetErrorHandler@HeapInstance@@UAGP6AHUErrorCode@@PBDZZP6AH01ZZ@Z ENDP ; HeapInstance::SetErrorHandler
_TEXT	ENDS
; Function compile flags: /Ogtp
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\HeapInst.cpp
;	COMDAT ?GetHeapSize@HeapInstance@@UAGKXZ
_TEXT	SEGMENT
_this$ = 8						; size = 4
?GetHeapSize@HeapInstance@@UAGKXZ PROC			; HeapInstance::GetHeapSize, COMDAT

; 274  : {

	push	ebp
	mov	ebp, esp

; 275  : 	return dwHeapSize - (dwBaseBlockSize*3) - sizeof(HeapInstance);

	mov	edx, DWORD PTR _this$[ebp]
	mov	eax, DWORD PTR [edx+24]
	lea	ecx, DWORD PTR [eax+eax*2]
	mov	eax, DWORD PTR [edx+32]
	sub	eax, ecx
	sub	eax, 64					; 00000040H

; 276  : }

	pop	ebp
	ret	4
?GetHeapSize@HeapInstance@@UAGKXZ ENDP			; HeapInstance::GetHeapSize
_TEXT	ENDS
; Function compile flags: /Ogtp
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\HeapInst.cpp
;	COMDAT ?GetLargestBlock@HeapInstance@@UAGKXZ
_TEXT	SEGMENT
_this$ = 8						; size = 4
?GetLargestBlock@HeapInstance@@UAGKXZ PROC		; HeapInstance::GetLargestBlock, COMDAT

; 243  : {

	push	ebp
	mov	ebp, esp
	push	edi

; 244  : 	U32 result=0;
; 245  : 	FREE_BLOCK *pBlock = pFirstFreeBlock;

	mov	edi, DWORD PTR _this$[ebp]
	xor	edx, edx
	mov	ecx, DWORD PTR [edi+20]

; 246  : 	
; 247  : 	if (pBlock)

	test	ecx, ecx
	je	SHORT $LN16@GetLargest

; 248  : 	{
; 249  : 		if ((dwFlags & DAHEAPFLAG_NOBESTFIT) == 0)

	test	BYTE PTR [edi+12], 2
	jne	SHORT $LN6@GetLargest

; 250  : 			result = pBlock->getPrev()->dwSize - dwBaseBlockSize;

	mov	eax, DWORD PTR [ecx+8]
	mov	eax, DWORD PTR [eax]
	sub	eax, DWORD PTR [edi+24]
	pop	edi

; 270  : }

	pop	ebp
	ret	4
$LN6@GetLargest:
	push	ebx
	push	esi

; 251  : 		else
; 252  : 		{
; 253  : 			FREE_BLOCK *pStart = pFirstFreeBlock;

	mov	ebx, ecx

; 254  : 			S32 loops=10000;

	mov	esi, 10000				; 00002710H
	npad	4
$LL4@GetLargest:

; 255  : 			
; 256  : 			do
; 257  : 			{
; 258  : 				pBlock = pBlock->getNext();

	mov	ecx, DWORD PTR [ecx+12]
	mov	eax, DWORD PTR [ecx]

; 259  : 				result = __max(result, pBlock->dwSize);
; 260  : 				if (--loops <= 0)

	cmp	edx, eax
	cmova	eax, edx
	dec	esi
	mov	edx, eax
	test	esi, esi
	jle	SHORT $LN3@GetLargest

; 261  : 					break;
; 262  : 
; 263  : 			} while (pBlock != pStart);

	cmp	ecx, ebx
	jne	SHORT $LL4@GetLargest
$LN3@GetLargest:

; 264  : 
; 265  : 			result -= dwBaseBlockSize;

	sub	edx, DWORD PTR [edi+24]

; 266  : 		}
; 267  : 	}
; 268  : 	
; 269  : 	return result;

	pop	esi
	pop	ebx
$LN16@GetLargest:

; 270  : }

	mov	eax, edx
	pop	edi
	pop	ebp
	ret	4
?GetLargestBlock@HeapInstance@@UAGKXZ ENDP		; HeapInstance::GetLargestBlock
_TEXT	ENDS
; Function compile flags: /Ogtp
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\HeapInst.cpp
;	COMDAT ?GetAvailableMemory@HeapInstance@@UAGKXZ
_TEXT	SEGMENT
_this$ = 8						; size = 4
?GetAvailableMemory@HeapInstance@@UAGKXZ PROC		; HeapInstance::GetAvailableMemory, COMDAT

; 222  : {

	push	ebp
	mov	ebp, esp
	push	ebx

; 223  : 	U32 result=0;
; 224  : 	S32 loops=10000;
; 225  : 	FREE_BLOCK *pBlock = pFirstFreeBlock;

	mov	ebx, DWORD PTR _this$[ebp]
	xor	eax, eax
	push	esi
	push	edi
	mov	esi, 10000				; 00002710H
	mov	edx, DWORD PTR [ebx+20]

; 226  : 	FREE_BLOCK *pStart = pFirstFreeBlock;

	mov	edi, edx

; 227  : 
; 228  : 	if (pBlock)

	test	edx, edx
	je	SHORT $LN3@GetAvailab

; 232  : 		result += pBlock->dwSize - dwBaseBlockSize;

	mov	ebx, DWORD PTR [ebx+24]
	npad	4
$LL4@GetAvailab:

; 229  : 	do
; 230  : 	{
; 231  : 		pBlock = pBlock->getNext();

	mov	edx, DWORD PTR [edx+12]

; 233  : 		if (--loops <= 0)

	dec	esi
	mov	ecx, DWORD PTR [edx]
	sub	ecx, ebx
	add	eax, ecx
	test	esi, esi
	jle	SHORT $LN3@GetAvailab

; 234  : 			break;
; 235  : 
; 236  : 	} while (pBlock != pStart);

	cmp	edx, edi
	jne	SHORT $LL4@GetAvailab
$LN3@GetAvailab:
	pop	edi

; 237  : 
; 238  : 	return result;
; 239  : }

	pop	esi
	pop	ebx
	pop	ebp
	ret	4
?GetAvailableMemory@HeapInstance@@UAGKXZ ENDP		; HeapInstance::GetAvailableMemory
_TEXT	ENDS
; Function compile flags: /Ogtp
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\HeapInst.cpp
;	COMDAT ?DidAlloc@HeapInstance@@UAGJPAX@Z
_TEXT	SEGMENT
_this$ = 8						; size = 4
_allocatedBlock$ = 12					; size = 4
?DidAlloc@HeapInstance@@UAGJPAX@Z PROC			; HeapInstance::DidAlloc, COMDAT

; 211  : {

	push	ebp
	mov	ebp, esp

; 212  : 	if (((DWORD)(pHeapBase) > (DWORD)allocatedBlock) ||

	mov	eax, DWORD PTR _this$[ebp]
	mov	ecx, DWORD PTR _allocatedBlock$[ebp]
	mov	edx, DWORD PTR [eax+28]
	cmp	edx, ecx
	ja	SHORT $LN3@DidAlloc
	mov	eax, DWORD PTR [eax+32]
	add	eax, edx
	cmp	ecx, eax
	sbb	eax, eax
	neg	eax

; 216  : 	}
; 217  : 	return 1;
; 218  : }

	pop	ebp
	ret	8
$LN3@DidAlloc:

; 213  : 			((DWORD)(pHeapBase) + dwHeapSize <= (DWORD)allocatedBlock))
; 214  : 	{
; 215  : 		return 0;

	xor	eax, eax

; 216  : 	}
; 217  : 	return 1;
; 218  : }

	pop	ebp
	ret	8
?DidAlloc@HeapInstance@@UAGJPAX@Z ENDP			; HeapInstance::DidAlloc
_TEXT	ENDS
; Function compile flags: /Ogtp
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\HeapInst.cpp
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.h
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\HeapInst.cpp
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.h
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\HeapInst.cpp
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.h
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\HeapInst.cpp
;	COMDAT ?GetBlockMessage@HeapInstance@@UAGPBDPAX@Z
_TEXT	SEGMENT
_this$ = 8						; size = 4
_allocatedBlock$ = 12					; size = 4
?GetBlockMessage@HeapInstance@@UAGPBDPAX@Z PROC		; HeapInstance::GetBlockMessage, COMDAT

; 184  : {

	push	ebp
	mov	ebp, esp
	push	esi
	mov	esi, DWORD PTR _this$[ebp]
	push	edi
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.h

; 332  : 	if (_pBlock == 0)

	mov	edi, DWORD PTR _allocatedBlock$[ebp]
	test	edi, edi
	je	SHORT $LN3@GetBlockMe

; 333  : 		return 0;
; 334  : 		
; 335  : 	pBlock = (BASE_BLOCK *) (((C8 *)_pBlock) - dwBaseBlockSize);

	mov	ecx, edi
	sub	ecx, DWORD PTR [esi+24]

; 336  : 	if (dwFlags & DAHEAPFLAG_NOVERIFYPTR)

	test	BYTE PTR [esi+12], 4
	jne	SHORT $LN10@GetBlockMe

; 83   : 	return (BASE_BLOCK *) (((C8 *)this) + (dwSize & ~1));

	mov	eax, DWORD PTR [ecx]
	and	eax, -2					; fffffffeH

; 340  : 	if (pBlock->getLower()->getUpper() != pBlock)

	cmp	DWORD PTR [eax+ecx+4], ecx
	jne	SHORT $Error$29

; 341  : 		goto Error;
; 342  : 	// upper block check
; 343  : 	if (pBlock->getUpper() && pBlock->getUpper()->getLower() != pBlock)

	mov	edx, DWORD PTR [ecx+4]
	test	edx, edx
	je	SHORT $LN10@GetBlockMe

; 83   : 	return (BASE_BLOCK *) (((C8 *)this) + (dwSize & ~1));

	mov	eax, DWORD PTR [edx]
	and	eax, -2					; fffffffeH
	add	eax, edx

; 343  : 	if (pBlock->getUpper() && pBlock->getUpper()->getLower() != pBlock)

	cmp	eax, ecx
	jne	SHORT $Error$29
$LN10@GetBlockMe:
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\HeapInst.cpp

; 187  : 	if ((pBlock = verifyBlock(allocatedBlock)) != 0)

	mov	eax, 12					; 0000000cH
	test	ecx, ecx
	je	SHORT $LN3@GetBlockMe
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.h

; 88   : 	return (dwSize & 1);

	test	BYTE PTR [ecx], 1
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\HeapInst.cpp

; 189  : 		if (pBlock->isAllocated() && (dwFlags & DAHEAPFLAG_NOMSGS) == 0)

	je	SHORT $LN3@GetBlockMe
	test	BYTE PTR [eax+esi], 16			; 00000010H
	jne	SHORT $LN3@GetBlockMe

; 190  : 			return pBlock->getMsg();

	mov	eax, DWORD PTR [ecx+8]
	pop	edi

; 193  : }

	pop	esi
	pop	ebp
	ret	8
$Error$29:
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.h

; 348  : 	if (EnumerateBlocks(0,0) == 0)

	mov	eax, DWORD PTR [esi]
	push	0
	push	0
	push	esi
	call	DWORD PTR [eax+32]

; 349  : 		doError(DAHEAP_HEAP_CORRUPTED);
; 350  : 	else
; 351  : 		doError(DAHEAP_INVALID_PTR, (DWORD)_pBlock);
; 352  : 	return 0;

	xor	edx, edx
	mov	ecx, esi
	test	eax, eax
	push	0
	cmovne	edx, edi
	push	edx
	xor	edx, edx
	test	eax, eax
	setne	dl
	add	edx, 4
	push	edx
	call	?doError@BaseHeap@@QAEJKKK@Z		; BaseHeap::doError
$LN3@GetBlockMe:
	pop	edi
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\HeapInst.cpp

; 192  : 	return 0;

	xor	eax, eax

; 193  : }

	pop	esi
	pop	ebp
	ret	8
?GetBlockMessage@HeapInstance@@UAGPBDPAX@Z ENDP		; HeapInstance::GetBlockMessage
_TEXT	ENDS
; Function compile flags: /Ogtp
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\HeapInst.cpp
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.h
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\HeapInst.cpp
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.h
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\HeapInst.cpp
;	COMDAT ?GetBlockSize@HeapInstance@@UAGKPAX@Z
_TEXT	SEGMENT
_this$ = 8						; size = 4
_allocatedBlock$ = 12					; size = 4
?GetBlockSize@HeapInstance@@UAGKPAX@Z PROC		; HeapInstance::GetBlockSize, COMDAT

; 169  : {

	push	ebp
	mov	ebp, esp
	push	esi
	mov	esi, DWORD PTR _this$[ebp]
	push	edi
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.h

; 332  : 	if (_pBlock == 0)

	mov	edi, DWORD PTR _allocatedBlock$[ebp]
	test	edi, edi
	je	SHORT $LN19@GetBlockSi

; 333  : 		return 0;
; 334  : 		
; 335  : 	pBlock = (BASE_BLOCK *) (((C8 *)_pBlock) - dwBaseBlockSize);

	mov	ecx, edi
	sub	ecx, DWORD PTR [esi+24]

; 336  : 	if (dwFlags & DAHEAPFLAG_NOVERIFYPTR)

	test	BYTE PTR [esi+12], 4
	jne	SHORT $LN10@GetBlockSi

; 83   : 	return (BASE_BLOCK *) (((C8 *)this) + (dwSize & ~1));

	mov	eax, DWORD PTR [ecx]
	and	eax, -2					; fffffffeH

; 340  : 	if (pBlock->getLower()->getUpper() != pBlock)

	cmp	DWORD PTR [eax+ecx+4], ecx
	jne	SHORT $Error$26

; 341  : 		goto Error;
; 342  : 	// upper block check
; 343  : 	if (pBlock->getUpper() && pBlock->getUpper()->getLower() != pBlock)

	mov	edx, DWORD PTR [ecx+4]
	test	edx, edx
	je	SHORT $LN10@GetBlockSi

; 83   : 	return (BASE_BLOCK *) (((C8 *)this) + (dwSize & ~1));

	mov	eax, DWORD PTR [edx]
	and	eax, -2					; fffffffeH
	add	eax, edx

; 343  : 	if (pBlock->getUpper() && pBlock->getUpper()->getLower() != pBlock)

	cmp	eax, ecx
	jne	SHORT $Error$26
$LN10@GetBlockSi:
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\HeapInst.cpp

; 174  : 	if ((pBlock = verifyBlock(allocatedBlock)) == 0)

	mov	eax, 24					; 00000018H
	lea	edx, DWORD PTR [eax+esi]
	test	ecx, ecx
	je	SHORT $LN19@GetBlockSi

; 175  : 		result = 0;
; 176  : 	else
; 177  : 		result = (pBlock->dwSize - dwBaseBlockSize) & ~1;

	mov	eax, DWORD PTR [ecx]
	sub	eax, DWORD PTR [edx]
	pop	edi
	and	eax, -2					; fffffffeH

; 180  : }

	pop	esi
	pop	ebp
	ret	8
$Error$26:
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.h

; 348  : 	if (EnumerateBlocks(0,0) == 0)

	mov	eax, DWORD PTR [esi]
	push	0
	push	0
	push	esi
	call	DWORD PTR [eax+32]

; 349  : 		doError(DAHEAP_HEAP_CORRUPTED);
; 350  : 	else
; 351  : 		doError(DAHEAP_INVALID_PTR, (DWORD)_pBlock);
; 352  : 	return 0;

	xor	edx, edx
	mov	ecx, esi
	test	eax, eax
	push	0
	cmovne	edx, edi
	push	edx
	xor	edx, edx
	test	eax, eax
	setne	dl
	add	edx, 4
	push	edx
	call	?doError@BaseHeap@@QAEJKKK@Z		; BaseHeap::doError
$LN19@GetBlockSi:
	pop	edi
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\HeapInst.cpp

; 179  : 	return result;

	xor	eax, eax

; 180  : }

	pop	esi
	pop	ebp
	ret	8
?GetBlockSize@HeapInstance@@UAGKPAX@Z ENDP		; HeapInstance::GetBlockSize
_TEXT	ENDS
; Function compile flags: /Ogtp
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\HeapInst.cpp
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.h
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\HeapInst.cpp
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.h
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\HeapInst.cpp
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.h
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\HeapInst.cpp
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.h
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\HeapInst.cpp
;	COMDAT ?EnumerateBlocks@HeapInstance@@UAGJP6GJPAUIHeap@@PAXK1@Z1@Z
_TEXT	SEGMENT
_this$ = 8						; size = 4
_proc$ = 12						; size = 4
_context$ = 16						; size = 4
?EnumerateBlocks@HeapInstance@@UAGJP6GJPAUIHeap@@PAXK1@Z1@Z PROC ; HeapInstance::EnumerateBlocks, COMDAT

; 132  : {

	push	ebp
	mov	ebp, esp
	push	ebx
	push	esi
	push	edi

; 133  : 	BOOL32 result=1;
; 134  : 	DWORD dwFlags;
; 135  : 	FREE_BLOCK *pBlock = (FREE_BLOCK *) pHeapBase;

	mov	edi, DWORD PTR _this$[ebp]
	mov	edx, 1
	mov	esi, DWORD PTR [edi+28]
$LL2@EnumerateB:

; 136  : 
; 137  : 	while (result && pBlock->dwSize != 1)

	mov	ecx, DWORD PTR [esi]
	cmp	ecx, 1
	je	SHORT $LN25@EnumerateB
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.h

; 88   : 	return (dwSize & 1);

	mov	ebx, ecx
	and	ebx, 1
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\HeapInst.cpp

; 139  : 		if ((dwFlags = pBlock->isAllocated()) == 0)

	jne	SHORT $LN6@EnumerateB

; 140  : 		{
; 141  : 			// check the free list (circular list)
; 142  : 			if (pBlock->getNext()->getPrev() != pBlock)

	mov	eax, DWORD PTR [esi+12]
	cmp	DWORD PTR [eax+8], esi
	mov	eax, 2
	cmovne	ebx, eax

; 143  : 				dwFlags |= DAHEAPFLAG_CORRUPTED_BLOCK;
; 144  : 			if (pBlock->getPrev()->getNext() != pBlock)

	mov	eax, DWORD PTR [esi+8]
	cmp	DWORD PTR [eax+12], esi
	je	SHORT $LN6@EnumerateB

; 145  : 				dwFlags |= DAHEAPFLAG_CORRUPTED_BLOCK;

	or	ebx, 2
$LN6@EnumerateB:
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.h

; 83   : 	return (BASE_BLOCK *) (((C8 *)this) + (dwSize & ~1));

	and	ecx, -2					; fffffffeH
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\HeapInst.cpp

; 149  : 		if (pBlock->getLower()->getUpper() != pBlock)

	cmp	DWORD PTR [ecx+esi+4], esi
	je	SHORT $LN7@EnumerateB

; 150  : 			dwFlags |= DAHEAPFLAG_CORRUPTED_BLOCK;

	or	ebx, 2
$LN7@EnumerateB:

; 152  : 		if (pBlock->getUpper() && pBlock->getUpper()->getLower() != pBlock)

	mov	ecx, DWORD PTR [esi+4]
	test	ecx, ecx
	je	SHORT $LN8@EnumerateB
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.h

; 83   : 	return (BASE_BLOCK *) (((C8 *)this) + (dwSize & ~1));

	mov	eax, DWORD PTR [ecx]
	and	eax, -2					; fffffffeH
	add	eax, ecx
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\HeapInst.cpp

; 152  : 		if (pBlock->getUpper() && pBlock->getUpper()->getLower() != pBlock)

	cmp	eax, esi
	je	SHORT $LN8@EnumerateB

; 153  : 			dwFlags |= DAHEAPFLAG_CORRUPTED_BLOCK;

	or	ebx, 2
$LN8@EnumerateB:

; 154  : 
; 155  : 		if (proc)

	mov	ecx, DWORD PTR _proc$[ebp]
	test	ecx, ecx
	je	SHORT $LN9@EnumerateB

; 156  : 			result = proc(this, ((char *)pBlock)+dwBaseBlockSize, dwFlags, context);

	push	DWORD PTR _context$[ebp]
	mov	eax, DWORD PTR [edi+24]
	push	ebx
	add	eax, esi
	push	eax
	push	edi
	call	ecx
	mov	edx, eax
$LN9@EnumerateB:

; 157  : 
; 158  : 		if (dwFlags & DAHEAPFLAG_CORRUPTED_BLOCK)

	test	bl, 2
	jne	SHORT $LN24@EnumerateB
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.h

; 83   : 	return (BASE_BLOCK *) (((C8 *)this) + (dwSize & ~1));

	mov	ecx, DWORD PTR [esi]
	and	ecx, -2					; fffffffeH
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\HeapInst.cpp

; 161  : 			pBlock = (FREE_BLOCK *) pBlock->getLower();

	add	esi, ecx
	test	edx, edx
	jne	SHORT $LL2@EnumerateB
$LN25@EnumerateB:
	pop	edi

; 162  : 	}
; 163  : 	
; 164  : 	return result;
; 165  : }

	pop	esi
	mov	eax, edx
	pop	ebx
	pop	ebp
	ret	12					; 0000000cH
$LN24@EnumerateB:
	pop	edi
	pop	esi
	xor	eax, eax
	pop	ebx
	pop	ebp
	ret	12					; 0000000cH
?EnumerateBlocks@HeapInstance@@UAGJP6GJPAUIHeap@@PAXK1@Z1@Z ENDP ; HeapInstance::EnumerateBlocks
_TEXT	ENDS
; Function compile flags: /Ogtp
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\HeapInst.cpp
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.h
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\HeapInst.cpp
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.h
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\HeapInst.cpp
;	COMDAT ?FreeMemory@HeapInstance@@UAGJPAX@Z
_TEXT	SEGMENT
_this$ = 8						; size = 4
_allocatedBlock$ = 12					; size = 4
?FreeMemory@HeapInstance@@UAGJPAX@Z PROC		; HeapInstance::FreeMemory, COMDAT

; 114  : {

	push	ebp
	mov	ebp, esp
	push	esi
	push	edi
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.h

; 332  : 	if (_pBlock == 0)

	mov	edi, DWORD PTR _allocatedBlock$[ebp]
	test	edi, edi
	je	SHORT $LN19@FreeMemory

; 333  : 		return 0;
; 334  : 		
; 335  : 	pBlock = (BASE_BLOCK *) (((C8 *)_pBlock) - dwBaseBlockSize);

	mov	esi, DWORD PTR _this$[ebp]
	mov	edx, edi
	sub	edx, DWORD PTR [esi+24]

; 336  : 	if (dwFlags & DAHEAPFLAG_NOVERIFYPTR)

	test	BYTE PTR [esi+12], 4
	jne	SHORT $LN10@FreeMemory

; 83   : 	return (BASE_BLOCK *) (((C8 *)this) + (dwSize & ~1));

	mov	eax, DWORD PTR [edx]
	and	eax, -2					; fffffffeH

; 340  : 	if (pBlock->getLower()->getUpper() != pBlock)

	cmp	DWORD PTR [eax+edx+4], edx
	jne	SHORT $Error$26

; 341  : 		goto Error;
; 342  : 	// upper block check
; 343  : 	if (pBlock->getUpper() && pBlock->getUpper()->getLower() != pBlock)

	mov	ecx, DWORD PTR [edx+4]
	test	ecx, ecx
	je	SHORT $LN10@FreeMemory

; 83   : 	return (BASE_BLOCK *) (((C8 *)this) + (dwSize & ~1));

	mov	eax, DWORD PTR [ecx]
	and	eax, -2					; fffffffeH
	add	eax, ecx

; 343  : 	if (pBlock->getUpper() && pBlock->getUpper()->getLower() != pBlock)

	cmp	eax, edx
	jne	SHORT $Error$26
$LN10@FreeMemory:
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\HeapInst.cpp

; 118  : 	if ((pBlock = verifyBlock(allocatedBlock)) == 0)

	test	edx, edx
	je	SHORT $LN19@FreeMemory

; 119  : 	{
; 120  : 		result = 0;
; 121  : 		goto Done;
; 122  : 	}
; 123  : 
; 124  : 	result = free((FREE_BLOCK *)pBlock);

	mov	ecx, esi
	call	?free@HeapInstance@@QAIHPAUFREE_BLOCK@@@Z ; HeapInstance::free
	pop	edi

; 128  : }

	pop	esi
	pop	ebp
	ret	8
$Error$26:
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.h

; 348  : 	if (EnumerateBlocks(0,0) == 0)

	mov	eax, DWORD PTR [esi]
	push	0
	push	0
	push	esi
	call	DWORD PTR [eax+32]

; 349  : 		doError(DAHEAP_HEAP_CORRUPTED);
; 350  : 	else
; 351  : 		doError(DAHEAP_INVALID_PTR, (DWORD)_pBlock);
; 352  : 	return 0;

	xor	ecx, ecx
	test	eax, eax
	push	0
	cmovne	ecx, edi
	push	ecx
	xor	ecx, ecx
	test	eax, eax
	setne	cl
	add	ecx, 4
	push	ecx
	mov	ecx, esi
	call	?doError@BaseHeap@@QAEJKKK@Z		; BaseHeap::doError
$LN19@FreeMemory:
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\HeapInst.cpp

; 127  : 	return result;

	xor	eax, eax
$Done$27:
	pop	edi

; 128  : }

	pop	esi
	pop	ebp
	ret	8
?FreeMemory@HeapInstance@@UAGJPAX@Z ENDP		; HeapInstance::FreeMemory
_TEXT	ENDS
; Function compile flags: /Ogtp
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\HeapInst.cpp
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.h
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\HeapInst.cpp
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.h
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\HeapInst.cpp
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.h
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\HeapInst.cpp
;	COMDAT ?ReallocateMemory@HeapInstance@@UAGPAXPAXKPBD@Z
_TEXT	SEGMENT
_this$ = 8						; size = 4
_allocatedBlock$ = 12					; size = 4
_result$3$ = 12						; size = 4
_newSize$ = 16						; size = 4
_msg$ = 20						; size = 4
?ReallocateMemory@HeapInstance@@UAGPAXPAXKPBD@Z PROC	; HeapInstance::ReallocateMemory, COMDAT

; 86   : {

	push	ebp
	mov	ebp, esp
	push	ebx
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.h

; 332  : 	if (_pBlock == 0)

	mov	ebx, DWORD PTR _allocatedBlock$[ebp]
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\HeapInst.cpp

; 86   : {

	push	esi
	push	edi
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.h

; 332  : 	if (_pBlock == 0)

	test	ebx, ebx
	je	$LN24@Reallocate

; 333  : 		return 0;
; 334  : 		
; 335  : 	pBlock = (BASE_BLOCK *) (((C8 *)_pBlock) - dwBaseBlockSize);

	mov	edi, DWORD PTR _this$[ebp]
	mov	esi, ebx
	sub	esi, DWORD PTR [edi+24]

; 336  : 	if (dwFlags & DAHEAPFLAG_NOVERIFYPTR)

	test	BYTE PTR [edi+12], 4
	jne	SHORT $LN15@Reallocate

; 83   : 	return (BASE_BLOCK *) (((C8 *)this) + (dwSize & ~1));

	mov	eax, DWORD PTR [esi]
	and	eax, -2					; fffffffeH

; 340  : 	if (pBlock->getLower()->getUpper() != pBlock)

	cmp	DWORD PTR [eax+esi+4], esi
	jne	SHORT $Error$34

; 341  : 		goto Error;
; 342  : 	// upper block check
; 343  : 	if (pBlock->getUpper() && pBlock->getUpper()->getLower() != pBlock)

	mov	ecx, DWORD PTR [esi+4]
	test	ecx, ecx
	je	SHORT $LN15@Reallocate

; 83   : 	return (BASE_BLOCK *) (((C8 *)this) + (dwSize & ~1));

	mov	eax, DWORD PTR [ecx]
	and	eax, -2					; fffffffeH
	add	eax, ecx

; 343  : 	if (pBlock->getUpper() && pBlock->getUpper()->getLower() != pBlock)

	cmp	eax, esi
	jne	SHORT $Error$34
$LN15@Reallocate:
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\HeapInst.cpp

; 90   : 	if ((pBlock = verifyBlock(allocatedBlock)) == 0)

	test	esi, esi
	je	SHORT $LN24@Reallocate

; 91   : 	{
; 92   : 		result = 0;
; 93   : 		goto Done;
; 94   : 	}
; 95   : 
; 96   : 	if (newSize == 0)

	mov	ecx, DWORD PTR _newSize$[ebp]
	test	ecx, ecx
	jne	SHORT $LN4@Reallocate

; 97   : 	{
; 98   : 		free((FREE_BLOCK *)pBlock);

	mov	edx, esi
	mov	ecx, edi
	call	?free@HeapInstance@@QAIHPAUFREE_BLOCK@@@Z ; HeapInstance::free
	pop	edi

; 110  : }

	pop	esi
	xor	eax, eax
	pop	ebx
	pop	ebp
	ret	16					; 00000010H
$LN4@Reallocate:

; 99   : 		result=0;
; 100  : 	}
; 101  : 	else
; 102  : 	if ((result = AllocateMemory(newSize, msg)) != 0)

	push	DWORD PTR _msg$[ebp]
	mov	eax, DWORD PTR [edi]
	push	ecx
	push	edi
	call	DWORD PTR [eax+16]
	mov	edx, eax
	mov	DWORD PTR _result$3$[ebp], edx
	test	edx, edx
	je	SHORT $Done$35

; 103  : 	{
; 104  : 		memcpy(result, allocatedBlock, __min((pBlock->dwSize&~1), newSize));

	mov	ecx, DWORD PTR [esi]
	mov	eax, DWORD PTR _newSize$[ebp]
	and	ecx, -2					; fffffffeH
	cmp	ecx, eax
	cmovb	eax, ecx
	push	eax
	push	ebx
	push	edx
	call	_memcpy
	add	esp, 12					; 0000000cH

; 105  : 		free((FREE_BLOCK *)pBlock);

	mov	edx, esi
	mov	ecx, edi
	call	?free@HeapInstance@@QAIHPAUFREE_BLOCK@@@Z ; HeapInstance::free

; 106  : 	}
; 107  : 
; 108  : Done:
; 109  : 	return result;

	mov	eax, DWORD PTR _result$3$[ebp]
	pop	edi

; 110  : }

	pop	esi
	pop	ebx
	pop	ebp
	ret	16					; 00000010H
$Error$34:
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\BaseHeap.h

; 348  : 	if (EnumerateBlocks(0,0) == 0)

	mov	eax, DWORD PTR [edi]
	push	0
	push	0
	push	edi
	call	DWORD PTR [eax+32]

; 349  : 		doError(DAHEAP_HEAP_CORRUPTED);
; 350  : 	else
; 351  : 		doError(DAHEAP_INVALID_PTR, (DWORD)_pBlock);
; 352  : 	return 0;

	xor	ecx, ecx
	test	eax, eax
	push	0
	cmovne	ecx, ebx
	push	ecx
	xor	ecx, ecx
	test	eax, eax
	setne	cl
	add	ecx, 4
	push	ecx
	mov	ecx, edi
	call	?doError@BaseHeap@@QAEJKKK@Z		; BaseHeap::doError
$LN24@Reallocate:
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\HeapInst.cpp

; 110  : }

	xor	eax, eax
$Done$35:
	pop	edi
	pop	esi
	pop	ebx
	pop	ebp
	ret	16					; 00000010H
?ReallocateMemory@HeapInstance@@UAGPAXPAXKPBD@Z ENDP	; HeapInstance::ReallocateMemory
_TEXT	ENDS
; Function compile flags: /Ogtp
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\HeapInst.cpp
;	COMDAT ?AllocateMemory@HeapInstance@@UAGPAXKPBD@Z
_TEXT	SEGMENT
_this$ = 8						; size = 4
_numBytes$ = 12						; size = 4
_msg$ = 16						; size = 4
?AllocateMemory@HeapInstance@@UAGPAXKPBD@Z PROC		; HeapInstance::AllocateMemory, COMDAT

; 70   : {

	push	ebp
	mov	ebp, esp

; 71   : 	BASE_BLOCK *result;
; 72   : 
; 73   : 	if ((result = malloc(numBytes)) == 0)

	mov	edx, DWORD PTR _numBytes$[ebp]
	push	esi
	mov	esi, DWORD PTR _this$[ebp]
	mov	ecx, esi
	call	?malloc@HeapInstance@@QAIPAUBASE_BLOCK@@K@Z ; HeapInstance::malloc
	mov	ecx, eax
	test	ecx, ecx
	jne	SHORT $LN2@AllocateMe
	pop	esi

; 82   : }

	pop	ebp
	ret	12					; 0000000cH
$LN2@AllocateMe:

; 74   : 		return result;
; 75   : 
; 76   : 	if ((dwFlags & DAHEAPFLAG_NOMSGS) == 0)

	test	BYTE PTR [esi+12], 16			; 00000010H
	jne	SHORT $LN3@AllocateMe

; 77   : 	{
; 78   : 	  	result->setMsg(msg);

	mov	eax, DWORD PTR _msg$[ebp]
	mov	DWORD PTR [ecx+8], eax

; 79   : 	  	result->setOwner(0);

	mov	DWORD PTR [ecx+12], 0
$LN3@AllocateMe:

; 80   : 	}
; 81   : 	return (void *) ((char *)result+dwBaseBlockSize);

	mov	eax, DWORD PTR [esi+24]
	add	eax, ecx
	pop	esi

; 82   : }

	pop	ebp
	ret	12					; 0000000cH
?AllocateMemory@HeapInstance@@UAGPAXKPBD@Z ENDP		; HeapInstance::AllocateMemory
_TEXT	ENDS
; Function compile flags: /Ogtp
; File E:\GitHub\projects\ConquestFWR\Code\Libs\Src\DACOM\HeapInst.cpp
;	COMDAT ?Release@HeapInstance@@UAGKXZ
_TEXT	SEGMENT
_this$ = 8						; size = 4
?Release@HeapInstance@@UAGKXZ PROC			; HeapInstance::Release, COMDAT

; 50   : {

	push	ebp
	mov	ebp, esp
	push	esi

; 51   : 	if (dwRefs > 0)

	mov	esi, DWORD PTR _this$[ebp]
	mov	eax, DWORD PTR [esi+4]
	test	eax, eax
	je	SHORT $LN10@Release

; 52   : 		dwRefs--;

	dec	eax
	mov	DWORD PTR [esi+4], eax

; 53   : 
; 54   : 	if (dwRefs == 0)

	test	eax, eax
	jne	SHORT $LN1@Release
$LN10@Release:

; 55   : 	{
; 56   : 		if (pNext)

	mov	ecx, DWORD PTR [esi+16]
	test	ecx, ecx
	je	SHORT $LN4@Release

; 57   : 			pNext->Release();

	mov	eax, DWORD PTR [ecx]
	push	ecx
	call	DWORD PTR [eax+8]
$LN4@Release:

; 58   : 		
; 59   : 		VirtualFree(pHeapBase, 0, MEM_RELEASE);

	push	32768					; 00008000H
	push	0
	push	DWORD PTR [esi+28]
	call	DWORD PTR __imp__VirtualFree@12

; 60   : 		//pHeapBase=0;	// we have allocated from within our own heap
; 61   : 		//delete this;
; 62   : 		return 0;

	xor	eax, eax
$LN1@Release:
	pop	esi

; 63   : 	}
; 64   : 
; 65   : 	return dwRefs;
; 66   : }

	pop	ebp
	ret	4
?Release@HeapInstance@@UAGKXZ ENDP			; HeapInstance::Release
_TEXT	ENDS
END
