// ExceptionTest.cpp
//
// 
//


#include <windows.h>
#include "DarthTest.h"
#include "DACOM.h"

//

static ICOManager		*s_DACOM = NULL;
static HANDLE			s_Module = 0;

static char *s_Name			= "ExceptionTest";
static char *s_Description	= "This will verify that the Darth Runtime correctly "
							  "responds to tests that cause unhandled exceptions.\n"
							  "\n"
							  "The runtime should correctly catch and handle any "
							  "exceptions generated by this test.  The exception "
							  "handling may cause a dialog to be popped up that  "
							  "prompts the user (you) for input on how to handle "
							  "the exception.  In the case of this test, the user"
							  "can safely ignore the exception as the test simply"
							  "exits.";
static char *s_Category		= "Runtime";
static char *s_Contact		= "pbleisch";

//

DARTH_DEFINE_NAME(			s_Name )
DARTH_DEFINE_CONTACT(		s_Contact )
DARTH_DEFINE_CATEGORY(		s_Category )
DARTH_DEFINE_DESCRIPTION(	s_Description )
DARTH_DEFINE_DLLMAIN(		s_Module )

__declspec( dllexport ) HRESULT RunTest( IDarthRuntime *RunTime )
{
	*((int*)NULL) = 42;
	return DARTH_TEST_PASS;
}

//
