
/////////////////////////////////////////////////////////////
//
// Source file for UTFBulletinBoard
//
//    This file is generated by RapidApp 1.2
//
//    This class is derived from UTFBulletinBoardUI which 
//    implements the user interface created in 
//    RapidApp. This class contains virtual
//    functions that are called from the user interface.
//
//    When you modify this source, limit your changes to 
//    modifying the sections between the
//    "//---- Start/End editable code block" markers
//
//    This will allow RapidApp to integrate changes more easily
//
//    This class is a ViewKit user interface "component".
//    For more information on how components are used, see the
//    "ViewKit Programmers' Manual", and the RapidApp
//    User's Guide.
/////////////////////////////////////////////////////////////

extern "C" {
#include <stdio.h>
}

#include "utfbulletinboard.h"
#include <Vk/VkEZ.h>
#include <Xm/BulletinB.h> 
#include <Xm/Label.h> 
#include <Xm/ToggleB.h> 
#include <Vk/VkResource.h>
#include <Vk/VkDialogManager.h>


extern void VkUnimplemented ( Widget, const char * );

///////////////////////////////////////////////////////////////////////////////
// The following non-container elements are created by UTFBulletinBoardUI and are
// available as protected data members inherited by this class
//
//  XmLabel		    _label3
//  XmToggleButton		    _outputMaterials
//  XmToggleButton		    _animation
//  XmLabel		    _label2
//  XmLabel		    _label1
//  XmToggleButton		    _vertexColors
//  XmToggleButton		    _outputTransformations
//  XmToggleButton		    _outputPivots1
//  XmToggleButton		    _indexCounters
//  XmToggleButton		    _polygonNormals
//  XmToggleButton		    _textureCoordinates
//  XmToggleButton		    _vertexNormals
//  XmLabel		    _label
//
///////////////////////////////////////////////////////////////////////////////


//---- Start editable code block: headers and declarations

#include <options.h>

int              utf_output_materials  = TRUE;
int              utf_no_mipmaps  = FALSE;
int              utf_convex_hull  = FALSE;
int              utf_remove_constant_channels  = FALSE;

int              utf_mesh  = FALSE;
//int              utf_skeleton  = FALSE;
int              utf_animation  = FALSE;
int              utf_combined  = FALSE;

int              utf_old_format  = FALSE;
int              utf_output_textures   = TRUE;
int              utf_output_hierarchy  = FALSE;
int              utf_output_animation  = FALSE;

int              utf_output_vert_norms = FALSE;
int              utf_output_vert_colors = FALSE;
int              utf_output_poly_norms = FALSE;
int              utf_show_index_counters = FALSE;
int              utf_output_pivots     = FALSE;
int              utf_output_transforms =  FALSE;
int              utf_output_tex_coords =  FALSE;

//---- End editable code block: headers and declarations



//---- UTFBulletinBoard Constructor

UTFBulletinBoard::UTFBulletinBoard(const char *name, Widget parent) : 
                   UTFBulletinBoardUI(name, parent) 
{ 
    // This constructor calls UTFBulletinBoardUI(parent, name)
    // which calls UTFBulletinBoardUI::create() to create
    // the widgets for this component. Any code added here
    // is called after the component's interface has been built

    //---- Start editable code block: UTFBulletinBoard constructor


    //---- End editable code block: UTFBulletinBoard constructor



}    // End Constructor



UTFBulletinBoard::UTFBulletinBoard(const char *name) : 
                   UTFBulletinBoardUI(name) 
 { 
    // This constructor calls UTFBulletinBoardUI(name)
    // which does not create any widgets. Usually, this
    // constructor is not used

    //---- Start editable code block: UTFBulletinBoard constructor 2


    //---- End editable code block: UTFBulletinBoard constructor 2



}    // End Constructor



UTFBulletinBoard::~UTFBulletinBoard()
{
    // The base class destructors are responsible for
    // destroying all widgets and objects used in this component.
    // Only additional items created directly in this class
    // need to be freed here.

    //---- Start editable code block: UTFBulletinBoard destructor


    //---- End editable code block: UTFBulletinBoard destructor



}    // End Destructor


const char * UTFBulletinBoard::className() // classname
{
    return ("UTFBulletinBoard");
} // End className()


void UTFBulletinBoard::apply( Widget w, XtPointer callData )
{


    //---- Start editable code block: UTFBulletinBoard apply

    //--- Comment out this line when this function is implemented:

    ::VkUnimplemented ( NULL, "UTFBulletinBoard::apply" );




    //---- End editable code block: UTFBulletinBoard apply

}    // End UTFBulletinBoard::apply()


void UTFBulletinBoard::cancel( Widget w, XtPointer callData )
{


    //---- Start editable code block: UTFBulletinBoard cancel

    //--- Comment out this line when this function is implemented:

    ::VkUnimplemented ( NULL, "UTFBulletinBoard::cancel" );




    //---- End editable code block: UTFBulletinBoard cancel

}    // End UTFBulletinBoard::cancel()


void UTFBulletinBoard::ok( Widget w, XtPointer callData )
{

    //---- Start editable code block: UTFBulletinBoard ok

    //--- Comment out this line when this function is implemented:


//	utf_output_vert_norms = EZ( _vertexNormals );
	utf_no_mipmaps = EZ( _outputMIPmaps );
	utf_convex_hull = EZ( _outputConvexHull );
	utf_remove_constant_channels = EZ( _removeComstantChannels );
	utf_mesh = EZ( _outputMesh );
//	utf_skeleton = EZ( _outputSkeleton );
	utf_animation = EZ( _outputAnimation );
	utf_combined = 0; //EZ( _outputCombined );
//	utf_old_format = EZ( _OldFormat );
	utf_output_textures = EZ( _outputTextures );
//	utf_output_poly_norms = EZ( _polygonNormals );
//	utf_show_index_counters = EZ( _indexCounters );
//	utf_output_pivots     = EZ( _outputPivots1 );
//	utf_output_transforms = EZ( _outputTransformations );
//	utf_output_vert_colors = EZ( _vertexColors );
//	utf_output_materials   = EZ( _outputMaterials );
//	utf_output_animation   = EZ( _animation );
//	utf_output_hierarchy   = EZ( _outputHierarchy );




    //---- End editable code block: UTFBulletinBoard ok

}    // End UTFBulletinBoard::ok()





///////////////////////////////////////////////////////////////////
// static creation function, for importing class into rapidapp
// or dynamically loading, using VkComponent::loadComponent
///////////////////////////////////////////////////////////////////


VkComponent *UTFBulletinBoard::CreateUTFBulletinBoard( const char *name, Widget parent ) 
{  
    VkComponent *obj =  new UTFBulletinBoard ( name, parent );
    return ( obj );
} // End CreateUTFBulletinBoard


///////////////////////////////////////////////////////////////////
// Function for accessing a description of the dynamic interface
// to this class.
///////////////////////////////////////////////////////////////////


// WARNING: This structure is different than that used with 1.1 RapidApp.
// See the RapidApp release notes for details

struct InterfaceMap {
  char  *resourceName;
  char  *methodName;
  char  *argType;
  char  *definingClass; // Optional, if not this class
  void (VkCallbackObject::*method)(...); // Reserved, do not set
};


void *UTFBulletinBoard::RegisterUTFBulletinBoardInterface()
{ 
    // This structure registers information about this class
    // that allows RapidApp to create and manipulate an instance.
    // Each entry provides a resource name that will appear in the
    // resource manager palette when an instance of this class is
    // selected, the name of the member function as a string,
    // the type of the single argument to this function, and an.
    // optional argument indicating the class that defines this function.
    // All member functions must have the form
    //  
    //     void memberFunction ( Type );
    //
    // where "Type" is one of:
    //    const char *    (Use XmRString)
    //    Boolean         (Use XmRBoolean)
    //    int             (Use XmRInt)
    //    float           (Use XmRFloat)
    //    No argument     (Use VkRNoArg or "NoArg"
    //    A filename      (Use VkRFilename or "Filename")
    //    An enumeration  (Use "Enumeration:ClassName:Type: VALUE1, VALUE2, VALUE3")
    //    A callback      (Use XmRCallback)


    static InterfaceMap map[] = {
    //---- Start editable code block: UTFBulletinBoardUI resource table

      // { "resourceName", "setAttribute", XmRString},
    //---- End editable code block: UTFBulletinBoardUI resource table
      { NULL }, // MUST be NULL terminated
    };

    return map;
} // End RegisterUTFBulletinBoardInterface()






//---- End of generated code

//---- Start editable code block: End of generated code


//---- End editable code block: End of generated code


