
//////////////////////////////////////////////////////////////
//
// Source file for UTFConverter
//
//    This file is generated by RapidApp 1.2
//
//    This class is a ViewKit VkDialogManager subclass
//    See the VkDialogManager man page for info on the API
//
//    Restrict changes to those sections between
//    the "//--- Start/End editable code block" markers
//    This will allow RapidApp to integrate changes more easily
//
//    This class is a ViewKit user interface "component".
//    For more information on how ViewKit dialogs are used, see the
//    "ViewKit Programmers' Manual"
//
//////////////////////////////////////////////////////////////
#include "utfconverter.h"


#include <Vk/VkApp.h>
#include <Vk/VkResource.h>


// Externally defined classes referenced by this class: 

#include "utfbulletinboard.h"

extern void VkUnimplemented ( Widget, const char * );


//---- Start editable code block: headers and declarations


//---- End editable code block: headers and declarations


UTFConverter::UTFConverter(const char * name) : VkGenericDialog( name )
{
    _allowMultipleDialogs = FALSE;

    //---- Start editable code block:  constructor


    //---- End editable code block:  constructor


}


Widget UTFConverter::createDialog ( Widget parent )
{
    Widget rTGDialogBaseWidget =  VkGenericDialog::createDialog ( parent );

    _rTGBulletinBoard = new UTFBulletinBoard("rTGBulletinBoard",rTGDialogBaseWidget);

    XtVaSetValues ( _rTGBulletinBoard->baseWidget(),
                    XmNwidth, 408, 
                    XmNheight, 328, 
                    (XtPointer) NULL );
    _rTGBulletinBoard->show();
    //---- Start editable code block:  createDialog


    //---- End editable code block:  createDialog
    return (rTGDialogBaseWidget);
}

UTFConverter::~UTFConverter()
{
    //---- Start editable code block: UTFConverter destructor


    //---- End editable code block: UTFConverter destructor

}

const char *UTFConverter::className()
{
    return ("UTFConverter");
}

Widget UTFConverter::prepost ( const char      *msg, 
                                        XtCallbackProc   okCB,
                                        XtCallbackProc   cancelCB,
                                        XtCallbackProc   applyCB,
                                        XtPointer       clientData,
                                        const char      *helpString,
                                        VkSimpleWindow  *parentWindow)
{
    Widget dialog = VkGenericDialog::prepost ( msg,
                                               okCB,
                                               cancelCB,
                                               applyCB,
                                               clientData,
                                               helpString,
                                               parentWindow);

    // This  function is called each time this dialog is posted. The dialog Widget
    // is the actual Motif dialog widget being displayed, which may vary from
    // call to call as opposed to this object, which is the same
    // unless an application deliberately creates multiple instances

    //---- Start editable code block: UTFConverter prepost

    //---- End editable code block: UTFConverter prepost
    return dialog;
}

/////////////////////////////////////////////////////////////// 
// The following functions are called from the dialog buttons 
// and routed to the object contained by this dialog class.
/////////////////////////////////// 

void UTFConverter::apply ( Widget w, XtPointer callData ) 
{
    // Pass this function on to the contained object

    _rTGBulletinBoard->apply ( w, callData );
}

void UTFConverter::cancel ( Widget w, XtPointer callData ) 
{
    // Pass this function on to the contained object

    _rTGBulletinBoard->cancel ( w, callData );

    // Must also call base class to handle dismissal

    VkDialogManager::cancel ( w, callData );
}

void UTFConverter::ok ( Widget w, XtPointer callData ) 
{
    // Pass this function on to the contained object

    _rTGBulletinBoard->ok ( w, callData );

    // Must also call base class to handle dismissal

    VkDialogManager::ok ( w, callData );
}





/////////////////////////////////////////////////////////////// 
// The following functions are static member functions used to 
// interface with Motif.
/////////////////////////////////// 



//---- Start editable code block: End of generated code


//---- End editable code block: End of generated code
