#ifndef __NAMES_H
#define __NAMES_H

#define Mesh_name			"Mesh name"
#define Bone				"Bone"
#define MultiLevel			"MultiLevel"
#define Switch				"Switch"
#define openFLAME_3D_N_mesh "openFLAME 3D N-mesh"
#define Faces 				"Faces"
#define Face_count 				"Face count"
#define Face_vertex_count 		"Face vertex count"
#define Face_initial_vertex 	"Face initial vertex"
#define Face_edge_chain			"Face edge chain"
#define Face_material 			"Face material"
#define Face_normal 			"Face normal"
#define Face_D_coefficient 		"Face D-coefficient"
#define Face_property 			"Face property"

#define Normals 			"Normals"
#define Surface_normal_count 		"Surface normal count"
#define Surface_normal_list 		"Surface normal list"

#define Vertices 			"Vertices"
#define Vertex_reference_count 		"Vertex reference count"
#define Object_vertex_chain 		"Object vertex chain"
#define Texture_vertex_chain 		"Texture vertex chain"
#define Object_vertex_count 		"Object vertex count"
#define Object_vertex_list 			"Object vertex list"
#define LOD_object_vertex_list 		"LOD object vertex list"
#define Texture_vertex_count 		"Texture vertex count"
#define Texture_vertex_list 		"Texture vertex list"
#define Vertex_normal 				"Vertex normal"
#define Vertex_D_coefficient 		"Vertex D-coefficient"

#define Vertex_bone_count		"Vertex bone count"  
#define Bone_id_list			"Bone id list"  
#define Bone_weight_list		"Bone weight list"
#define Bone_vertex_list		"Bone vertex list" 
#define Bone_normal_list		"Bone normal list" 

// used by bones
#define Vertex_count			"Vertex_count"
#define Vertex_chain			"Vertex_chain"

#define UVChannel_library		"UVChannel library"
#define Material_library 		"Material library"
#define Material_count 			"Material count"
#define Material_identifier 		"Material identifier"
#define Ambient 			"Ambient"
#define Diffuse 			"Diffuse"
#define Specular 			"Specular"
#define Emission 			"Emission"
#define Shininess 			"Shininess"
#define Transparency 			"Transparency"
#define Material_texture 		"Material texture"
#define Texture_name			"Texture name"

#define Texture_library 		"Texture library"
#define Texture_count 			"Texture count"
#define Texture_identifier 		"Texture identifier"
#define Texture_U_limit 		"Texture U limit"
#define Texture_V_limit 		"Texture V limit"
#define Texture_MIP_count 		"Texture MIP count"
#define MIP_level_0 			"MIP level 0"
#define Image_X_size 			"Image X size"
#define Image_Y_size 			"Image Y size"
#define Image_color_count 		"Image color count"
#define Image_RGB_palette 		"Image RGB palette"
#define Image_linear_bitmap 		"Image linear bitmap"
#define Palette_8_bit			"Palette 8 bit"
#define Palette_color_count		"Palette color count"
#define Palette_RGB_888			"Palette RGB 888"
#define Image_indices			"Image indices"
#define Transparent_index		"Transparent index"
#define Alpha_8_bit			"Alpha 8 bit"
#define True_RGB_565			"True RGB 565"
#define Image_colors			"Image colors"

#define Rigid_body 			"Rigid body"
#define Mass_properties 		"Mass properties"
#define Mass 				"Mass"
#define Center_of_mass 			"Center of mass"
#define Inertia_tensor 			"Inertia tensor"
#define Center 				"Center"
#define Box 				"Box"
#define Center 				"Center"
#define half_x 				"half x"
#define half_y 				"half y"
#define half_z 				"half z"

#endif
