//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by asciiexp.rc
//
#define IDS_VERSION                     1
#define IDS_ASCIIEXP                    2
#define IDS_CATEGORY                    3
#define IDS_EXTENSION1                  4
#define IDABORT2                        5
#define IDC_LOAD_OPT                    6
#define IDS_LONGDESC                    7
#define IDC_BATCH_EXP                   8
#define IDS_SHORTDESC                   9
#define IDS_COPYRIGHT                   10
#define IDS_PROGRESS_MSG                11
#define IDS_VERSIONSTRING               12
#define IDS_LIBDESCRIPTION              13
#define IDS_EXTENSION2                  14
#define IDS_EXTENSION3                  15
#define IDS_EXTENSION4                  16
#define IDS_EXTENSION5                  17
#define IDS_EXTENSION6                  18
#define IDD_PANEL                       101
#define IDD_ABOUTBOX                    102
#define IDD_ASCIIEXPORT_DLG             103
#define IDC_CLOSEBUTTON                 1000
#define IDC_MESHDATA                    1002
#define IDC_ANIMKEYS                    1003
#define IDC_MATERIAL                    1004
#define IDC_MESHANIM                    1005
#define IDC_NORMALS                     1006
#define IDC_TEXCOORDS                   1007
#define IDC_OBJ_GEOM                    1008
#define IDC_OBJ_SHAPE                   1009
#define IDC_OBJ_CAMLIGHT                1010
#define IDC_OBJ_CAMERA                  1011
#define IDC_OBJ_HELPER                  1012
#define IDC_COMBINE                     1013
#define IDC_RADIO_USEKEYS               1016
#define IDC_RADIO_SAMPLE                1017
#define IDC_IKJOINTS                    1018
#define IDC_OBJ_LIGHT                   1019
#define IDC_VERTEXCOLORS                1020
#define IDC_SLIDER1                     1039
#define IDC_LIST1                       1040
#define IDC_COMBO1                      1041
#define IDC_SAVE_OPT                    1043
#define IDC_CONT_STEP                   1155
#define IDC_CONT_STEP_SPIN              1156
#define IDC_MESH_STEP                   1157
#define IDC_CONT_STEP3                  1158
#define IDC_MESH_STEP_SPIN              1159
#define IDC_CONT_STEP_SPIN3             1160
#define IDC_STATIC_FRAME                1161
#define IDC_STATIC_FRAME_SPIN           1162
#define IDC_PREC                        1163
#define IDC_CONT_STEP2                  1164
#define IDC_PREC_SPIN                   1165
#define IDC_CONT_STEP_SPIN2             1166
#define IDC_DENS                        1167
#define IDC_DENS_SPIN                   1168
#define IDC_MIP                         1169
#define IDC_565                         1170
#define IDC_SPLIT                       1171
#define IDC_DEFAULT_MAT                 1172
#define IDC_CHARACTER                   1173
#define IDC_MESH                        1174
#define IDC_SKELETON                    1175
#define IDC_SCALE                       1176
#define IDC_ANIMATION                   1177
#define IDC_LIGHT                       1178
#define IDC_CAMERA                      1179
#define IDC_SELECTED                    1180
#define IDC_SELECTED2                   1181
#define IDC_SCALE_SPIN                  1182
#define IDC_LOD_PERCENT                 1183
#define IDC_LOD_PERCENT_SPIN            1184
#define IDC_LOD_CLOSEST                 1185
#define IDC_LOD_CLOSEST_SPIN            1186
#define IDC_LOD_FURTHEST                1187
#define IDC_LOD_FURTHEST_SPIN           1188
#define IDC_LOD_COUNT                   1189
#define IDC_LOD_DROPOUT                 1190
#define IDC_LOD_COUNT_SPIN              1191
#define IDC_LOD_DROPOUT_SPIN            1192
#define IDC_MTL_BOUNDARY                1193
#define IDC_MTL_BOUNDARY_SPIN           1194
#define IDC_TXT_WEIGHT                  1195
#define IDC_TXT_WEIGHT_SPIN             1196
#define IDC_BIPED_Y_UP                  1197
#define IDC_IGNORE_WARNINGS             1198
#define IDC_NO_PHYSICS                  1199
#define IDC_ROTATE_X                    1200
#define IDC_ROTATE_X_SPIN               1201
#define IDC_ROTATE_Y                    1202
#define IDC_ROTATE_Y_SPIN               1203
#define IDC_ROTATE_Z                    1204
#define IDC_ROTATE_Z_SPIN               1205
#define IDC_CENTER_MASS                 1206
#define IDC_VERTEX_COLOR                1207
#define IDC_EDIT                        1208
#define IDC_IK_EXT                      1209
#define IDC_SM_GRP                      1210
#define IDC_EX_AVI                      1211
#define IDC_HEAD                        1212
#define IDC_ALLOW_LOSE_J                1213
#define IDC_HEAD2                       1214
#define IDC_NOT_UNIQUE                  1215
#define IDC_SEL_ANIM_ONLY               1216
#define IDC_LOOSE_J                     1217
#define IDC_SPHERE_J                    1218
#define IDC_SAVE_MAX_OPT                1218
#define IDC_EX_TXT                      1219
#define IDC_ROOT_ANIM                   1220
#define IDC_IN_WORLD                    1221
#define IDC_ALLIGN_HEADING              1222
#define IDC_888                         1223
#define IDC_REL_ANIM                    1224
#define IDC_DITHER                      1225

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        107
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1044
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
