#define VALID      0
#define INVALID    1
#define POSTPONE   2
#define DOCANCEL   3
extern BOOL Told;
extern HWND g_hCDWnd;


#define PRO_CLASS	"PRO"

#ifndef RCCOMPILE

extern BOOL fUserQuit;

BOOL    APIENTRY ProDlgProc(HWND, WORD, WPARAM, LONG);
LONG    APIENTRY ProBarProc(HWND, UINT, WPARAM, LONG);
BOOL    APIENTRY ControlInit(HANDLE, HANDLE);
BOOL    APIENTRY ProInit(HANDLE,HANDLE);
VOID    APIENTRY ProClear(HWND hDlg);
HWND    APIENTRY ProOpen(HWND);
BOOL    APIENTRY ProClose(HWND);
BOOL    APIENTRY ProSetCaption (LPSTR);
BOOL    APIENTRY ProSetBarRange(INT);
BOOL    APIENTRY ProSetBarPos(INT);
BOOL    APIENTRY ProDeltaPos(INT);
BOOL    APIENTRY ProSetText(INT, LPSTR);
LONG    APIENTRY fnText(HWND, UINT, WPARAM, LONG);
VOID    APIENTRY wsDlgInit(HWND);
BOOL    APIENTRY fnErrorMsg(INT);
#endif


#define BAR_RANGE 0
#define BAR_POS   2

#define BAR_SETRANGE  WM_USER+BAR_RANGE
#define BAR_SETPOS    WM_USER+BAR_POS
#define BAR_DELTAPOS  WM_USER+4
