//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by app.rc
//
#define VERSION_INFO                    1
#define IDC_RESET                       3
#define IDB_DUMMY                       112
#define IDD_VIDEO_DEVICE                114
#define IDD_AUDIO_DEVICE                115
#define IDD_ADVANCED_VIDEO_DIALOG       118
#define IDB_BITMAP1                     161
#define IDB_BITMAP2                     162
#define IDB_BITMAP3                     163
#define IDB_BITMAP4                     165
#define SETUP                           174
#define IDB_SM_LOGO                     184
#define IDB_HW                          186
#define STR_COPYRIGHT_NOTICE            402
#define STR_REGKEY_PLAYERNAME           600
#define STR_REGKEY_DEFNAME              602
#define STR_LAUNCHEXECLS                604
#define STR_PROMPTUNINSTALL             605
#define STR_NTDIR_LOCALFILES            606
#define STR_LOCALDIRNAME                607
#define STR_RETAILINSTALLED             611
#define STR_BADCHARINNAME               612
#define STR_INSERTDISK1                 613
#define STR_CDVOLNAME1                  614
#define STR_CLOSEGAME                   615
#define STR_TRIALVERSIONHERE            616
#define STR_REG_GAMEVALUE               617
#define STR_WINNTOR95                   618
#define ID_BAR                          650
#define DTICON                          660
#define INSTALL                         700
#define INSTALLDN                       701
#define UNINSTALL                       703
#define UNINSTALLDN                     704
#define UNINSTALLGR                     705
#define REINSTALL                       706
#define REINSTALLDN                     707
#define REINSTALLGR                     708
#define EXIT                            709
#define EXITDN                          710
#define WEBLINK                         712
#define WEBLINKDN                       713
#define HELP                            715
#define HELPDN                          716
#define PLAY                            718
#define PLAYDN                          719
#define CONFIGURE                       721
#define CONFIGUREDN                     722
#define README                          722
#define STR_RESTART                     729
#define STR_NONT                        730
#define STR_CANCELCOPY                  731
#define STR_DIRECTXNOTINSTALLED         732
#define STR_NODIRECTX                   733
#define STR_LAUNCHURL                   734
#define STR_NEEDBROWSER                 735
#define STR_SERVICEPACK3                736
#define IDS_NOT_ENUF_DISK_SPACE         737
#define IDS_NOT_ENUF_APP_SPACE          738
#define IDS_NOT_ENUF_SYS_SPACE          739
#define STR_REAL_EXENAME                740
#define STR_CREATEDIR                   741
#define IDS_CONFIG_DIALOG_TITLE         742
#define CDICON                          745
#define COPYSTATUS                      746
#define BG_BMP                          747
#define IDB_CHECK                       748
#define PROGRESS                        751
#define IDD_EULA                        752
#define EULA_EDIT                       753
#define ID_PRINT                        754
#define ID_DLGEDITCONTROL               1000
#define GETROOTDLG                      1000
#define ID_DLGEDITCONTROL2              1004
#define ID_DLGSTATICCONTROL             1005
#define ID_BROWSE                       1006
#define ID_DLGEDITCONTROL3              1006
#define ID_BACK                         1007
#define GETGRPDLG                       1008
#define IDC_AUDIO_COMBO                 1008
#define ID_PERFTEXT                     1009
#define IDC_LOCKING                     1010
#define IDC_D3DTEXTURE                  1011
#define IDC_GDI                         1012
#define IDC_HW_CURSOR                   1013
#define IDC_ADVANCED_VIDEO              1017
#define ID_TOTALCOPIED                  1019
#define ID_FULL                         1019
#define ID_LAST                         1020
#define ID_TYPICAL                      1021
#define IDC_RESOLUTION_COMBO            1021
#define ID_TOTAL                        1022
#define ID_MINIMUM                      1023
#define ID_STATUS1                      1024
#define ID_STATUS2                      1025
#define ID_CHECKLIST                    1026
#define IDC_CDRESULTS                   1027
#define STR_DONEDX5                     1028
#define IDS_DXListColWhatHappensHeader  1029
#define IDS_DXListColRecommendationHeader 1030
#define IDS_DXListColDriverHeader       1031
#define IDS_WhatHappensInstall          1032
#define IDS_RECOMMENDED                 1033
#define IDS_NOTRECOMMENDED              1034
#define IDS_AUTOINSTALL                 1035
#define IDS_WhatHappensSkip             1036
#define STR_NOTADMIN                    1037
#define STR_CDTESTRESULTS               1038
#define STR_CDTESTOKRESULTS             1039
#define STR_INSTALLDESKTOP              1040
#define STR_DEFPLAYERNAME               1041
#define IDC_RICHEDIT1                   1041
#define STR_GETPIDDLGTITLE              1042
#define STR_NEEDHIGHERRES               1043
#define IDC_STATIC1                     1043
#define IDC_COMPONENT1                  1044
#define ID_SYSTEMAVAIL                  1045
#define ID_GAMEAVAIL                    1046
#define ID_TOTALAVAIL                   1047
#define ID_SYSTEMREQ                    1048
#define IDC_CHECK1                      1048
#define IDC_EAX                         1048
#define ID_GAMEREQ                      1049
#define IDC_ANIMATE1                    1049
#define IDC_A3D                         1049
#define ID_TOTALREQUIRED                1050
#define IDC_SLIDER1                     1050
#define ID_SYSTEMTEXT                   1051
#define IDC_SLIDER2                     1051
#define ID_TOTALTEXT                    1052
#define IDC_SLIDER3                     1052
#define STR_EULANOTFOUND                1053
#define STR_DX_PROMPTING                1054
#define STR_NODIRECTXCD                 1055
#define IDC_VIDEO_COMBO                 1064
#define TABKEY                          40001

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        187
#define _APS_NEXT_COMMAND_VALUE         40002
#define _APS_NEXT_CONTROL_VALUE         1054
#define _APS_NEXT_SYMED_VALUE           405
#endif
#endif
