//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by ObjectViewer.rc
//
#define IDR_APPLICATION_MENU            102
#define IDR_APP_ACCEL                   105
#define IDD_LISTDIALOG                  107
#define IDD_MATERIALDIALOG              108
#define IDD_RPMATDIALOG                 112
#define IDD_TEXTUREDIALOG               113
#define IDD_DEVICEDIALOG                114
#define IDR_3DWINDOW_MENU               116
#define IDR_OBJECT_MENU                 118
#define IDD_NEWWINDOWDIALOG             119
#define IDI_SWICON                      120
#define IDR_MENU1                       121
#define IDC_ACTION_0                    1004
#define IDC_ACTION_1                    1005
#define IDC_LISTLIST                    1006
#define IDC_ACTION_2                    1007
#define IDC_MATERIALLIST                1008
#define IDC_ADD_MATERIAL                1009
#define IDC_REMOVE_MATERIAL             1010
#define IDC_VIEW_MATERIAL               1012
#define IDC_DIFFUSE_CONST_R             1015
#define IDC_DIFFUSE_CONST_G             1016
#define IDC_DIFFUSE_CONST_B             1017
#define IDC_DIFFUSE_CONST_A             1018
#define IDC_DIFFUSE_MAP                 1019
#define IDC_DIFFUSE_ENABLE              1020
#define IDC_DIFFUSE_CONST               1021
#define IDC_DIFFUSE_LIGHTMAP_ENABLE     1022
#define IDC_BUMP_CONST                  1023
#define IDC_DIFFUSE_CONST_R2            1024
#define IDC_BUMP_MAP                    1025
#define IDC_BUMP_ENABLE                 1026
#define IDC_ALPHA_CONST                 1027
#define IDC_ALPHA_MAP                   1028
#define IDC_ALPHA_ENABLE                1029
#define IDC_SHINY_CONST                 1030
#define IDC_SHINY_MAP                   1031
#define IDC_SHINY_ENABLE                1032
#define IDC_DIFFUSE_CONST_RGB_PICK      1033
#define IDC_DIFFUSE_CONST_G2            1034
#define IDC_ACTION_3                    1034
#define IDC_DIFFUSE_CONST_B2            1035
#define IDC_RPMATLIST                   1035
#define IDC_DIFFUSE_CONST_A2            1036
#define IDC_VIEW_RPMATERIAL             1036
#define IDC_DIFFUSE_CONST_RGB_PICK2     1037
#define IDC_ADD_RPMATERIAL              1037
#define IDC_REMOVE_RPMATERIAL           1038
#define IDC_MATMAP_NUMBER_COMBO         1039
#define IDC_MATMAP_TEXTURE_STATE_COMBO  1040
#define IDC_MATMAP_TEXTURE_ID           1041
#define IDC_MATMAP_TEXTURE_STATE_VALUE_COMBO 1042
#define IDC_DIFFUSE_CONST_R3            1043
#define IDC_MATMAP_TEXTURE_ID_BROWSE    1043
#define IDC_DIFFUSE_CONST_G3            1044
#define IDC_DIFFUSE_CONST_B3            1045
#define IDC_FACTOR_R                    1045
#define IDC_DIFFUSE_CONST_A3            1046
#define IDC_FACTOR_G                    1046
#define IDC_DIFFUSE_CONST_RGB_PICK3     1047
#define IDC_FACTOR_B                    1047
#define IDC_DIFFUSE_CONST_R4            1048
#define IDC_FACTOR_A                    1048
#define IDC_DIFFUSE_CONST_G4            1049
#define IDC_FACTOR_PICK                 1049
#define IDC_DIFFUSE_CONST_B4            1050
#define IDC_NOTES                       1050
#define IDC_DIFFUSE_CONST_A4            1051
#define IDC_DIFFUSE_CONST_RGB_PICK4     1052
#define IDC_VIEW_TEXTURE                1052
#define IDC_ADD_TEXTURE                 1053
#define IDC_REMOVE_TEXTURE              1054
#define IDC_TEXTURELIST                 1056
#define IDC_SELECT_TEXTURE              1058
#define IDC_SELECT_MATERIAL             1062
#define IDC_DEVICE_COMBO                1064
#define IDC_ABILITIES_LIST              1065
#define IDC_SELECT_DEVICE               1066
#define IDC_TEST_DEVICE                 1067
#define IDC_DEVICE_DESC                 1068
#define IDC_TXMWINDOW                   1069
#define IDC_WINDOWTYPE                  1070
#define IDC_BUTTON3                     1073
#define IDC_BUTTON4                     1074
#define IDC_BUTTON5                     1075
#define IDC_BUTTON6                     1076
#define IDC_BUTTON7                     1077
#define IDC_BUTTON8                     1078
#define IDC_BUTTON9                     1079
#define IDC_BUTTON10                    1080
#define IDC_BUTTON11                    1081
#define IDC_BUTTON12                    1082
#define ID_VIEW_WORLD_AXIS              40001
#define ID_OBJECT_RELOAD                40021
#define ID_OBJECT_VIEW_HARDPOINT_NAMES  40025
#define ID_OBJECT_VIEW_HARDPOINT_AXIS   40026
#define ID_LIGHTING_AMBIENTLIGHT        40031
#define ID_OBJECT_REMOVE                40036
#define ID_OBJECT_VIEW_AXIS             40037
#define ID_OBJECT_VIEW_WIREFRAME        40038
#define ID_OBJECT_VIEW_SHADED           40039
#define ID_OBJECT_VIEW_STATISTICS       40040
#define ID_OBJECT_VIEW_NAMES            40041
#define ID_LIGHT_LIST                   40044
#define ID_CAMERA_LIST                  40045
#define ID_OBJECT_PROPERTIES            40048
#define ID_OBJECT_LIST                  40049
#define ID_OBJECT_MATERIALS_LIST        40050
#define ID_VIEW_TEXTURES                40069
#define ID_VIEW_WORLDAXIS               40076
#define ID_VIEW_FRAMERATE_COUNTERS      40077
#define ID_VIEW_STATISTICS              40078
#define ID_VIEW_FRAMERATE_GRAPH         40081
#define ID_FILE_INSERT                  40083
#define ID_SYSTEM_RENDERPIPELINE_PROFILELOGGING 40085
#define ID_OBJECT_VIEW_ANIMATIONS       40088
#define ID_OBJECT_VIEW_JOINTS           40089
#define ID_OBJECT_VIEW_HARDPOINTS       40090
#define ID_FILE_DEVICE                  40091
#define ID_FILE_NEW_WINDOW              40092
#define ID_CLOSE_WINDOW                 40093
#define ID_INSERT_ITEM                  40094
#define ID_VIEWWORLDAXIS                40099
#define ID_VIEWSTATISTICS               40100
#define ID_INSERT                       40104
#define ID_CLOSE                        40105
#define ID_VIEW_FRAMERATE               40108
#define ID_RELOAD                       40109
#define ID_REMOVE                       40110
#define ID_VIEW_LOCALAXIS               40111
#define ID_VIEW_VERTICES                40112
#define ID_VIEW_EDGES                   40113
#define ID_VIEW_FACES                   40114
#define ID_VIEW_SHADED                  40115
#define ID_VIEW_VERTEX_NORMALS          40116
#define ID_VIEW_FACENORMALS             40117
#define ID_VIEW_NAMES                   40118
#define ID_VIEW_AVITEST                 40120
#define ID_FILE_NEW_SCENEWINDOW         40121
#define ID_FILE_NEW_DIRECTSHOWWINDOW    40122
#define ID_FILE_NEW_TEXTUREVIEWER       40123
#define ID_FILE_NEW_OTHER               40124
#define ID_CAMERAS_DEFAULTCAMERA_APEX   40125
#define ID_CAMERAS_DEFAULTCAMERA_CLOSEUP 40126
#define ID_CAMERAS_DEFAULTCAMERA_EXTERNAL 40127
#define ID_CAMERAS_DEFAULTCAMERA_INTERNAL 40128
#define ID_CAMERAS_DEFAULTCAMERA_TRACK  40129
#define ID_CAMERAS_DEFAULTCAMERA_PAN    40130
#define ID_CAMERAS_DEFAULTCAMERA_FOLLOW 40131
#define ID_CAMERAS_DEFAULTCAMERA_OTHER  40132
#define ID_CAMERAS_                     40134
#define ID_CAMERAS_DEFAULTCAMERA        40135
#define ID_LIGHTS_AMBIENT               40136
#define ID_LIGHTS_LIGHTA_ON             40137
#define ID_LIGHTS_LIGHTA_VISIBLE        40138

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        123
#define _APS_NEXT_COMMAND_VALUE         40139
#define _APS_NEXT_CONTROL_VALUE         1074
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
