[Video]
GDI = on                 ; on  = GDI compatible with full screen 3D

;
; Defines the DLL's to load
;
[Libraries]
Dll\DOSFile.dll
Dll\Renderer.dll
Dll\x86math.dll
Dll\GrannyManager.dll
Dll\SoundSys.dll
Dll\Streamer.dll
