//EffectEvent.cpp

#include "stdafx.h"
#include "globals.h"
#include "IEffectEvent.h"
#include "IEffectAction.h"
#include "IEffectTarget.h"
#include "EventGraph.h"

#include <DACOM.h>
#include <filesys.h>
#include <TSmartPointer.h>

#include <stdio.h>

struct EffectEvent: public IEffectEvent
{
	IEffectEvent * next;
	char name[64];
	SINGLE offSetTime;
	EventSave::EventType eventType;
	bool bFileDependant;//true if this event was generated by a file load
	U32 refCount;//only used by particle filters.
	U32 context;

	S32 iconXPos;
	S32 iconYPos;
	S32 iconWidth;
	S32 iconHeight;

	IEffectAction * firstAction;

	IEffectAction * parent;

	EffectEvent();

	~EffectEvent();

	//IEffectTarget
	virtual IEffectEvent * GetNextEvent();

	virtual void SetNextEvent(IEffectEvent * target);

	virtual struct IEffectAction * GetFirstAction();

	virtual void SetFirstAction(struct IEffectAction * target);

	virtual void RemoveAction(struct IEffectAction * target);

	virtual struct IEffectAction * GetParent();

	virtual void SetParent(struct IEffectAction * target);

	virtual const char * GetName();

	virtual void SetName(const char * newName);

	virtual void SetEventType(enum EventSave::EventType type);

	virtual enum EventSave::EventType GetEventType();

	virtual SINGLE GetOffset();

	virtual void SetOffset(SINGLE setting);

	virtual void TriggerEvent();

	virtual void SaveCore(struct IFileSystem * outFile);

	virtual void LoadCore(struct IFileSystem * inFile, U32 _context);

	virtual void LoadCoreLate(struct IFileSystem * inFile, U32 _context);

	virtual void SetFileDependant(bool bSetting);

	virtual bool IsFileDependant();

	virtual void NullTarget(struct IEffectTarget * target);

	virtual void NullTarget(struct ITargetAnim * target);

	virtual void NullTarget(struct ITargetHp * target);

	virtual IEffectEvent * CreateCopy(IEffectAction * _newParent);

	virtual void AddRef();

	virtual void RemoveRef();

	virtual U32 GetRef();

	virtual S32 GetIconXPos();

	virtual S32 GetIconYPos();

	virtual void SetDimentions(S32 newWidth, S32 newHeight);

	virtual bool HitTest(S32 x, S32 y); 

	virtual void RealitveIconMove(S32 x, S32 y);

	virtual void SetIconPos(S32 x, S32 y);
};

EffectEvent::EffectEvent()
{
	strcpy(name,"newName");
	next = NULL;
	firstAction = NULL;
	offSetTime = 0;
	eventType = EventSave::START_TRIGGERED;
	parent = NULL;
	bFileDependant = false;
	refCount = 0;
	context = 0;
	iconXPos = 0;
	iconYPos = 0;
	iconWidth = 10;
	iconHeight = 10;
}

EffectEvent::~EffectEvent()
{
	while(firstAction)
	{
		IEffectAction * tmp = firstAction;
		firstAction = firstAction->GetNextAction();
		delete tmp;
	}
}

IEffectEvent * EffectEvent::GetNextEvent()
{
	return next;
}

void EffectEvent::SetNextEvent(IEffectEvent * target)
{
	next = target;
}

IEffectAction * EffectEvent::GetFirstAction()
{
	return firstAction;
}

void EffectEvent::SetFirstAction(struct IEffectAction * target)
{
	firstAction = target;

	S32 testPosX = iconWidth+20;
	S32 testPosY = 0;
	IEffectAction * search = firstAction;
	while(search)
	{
		testPosY += (iconHeight +25);
		search = search->GetNextAction();
	}
	
	search = firstAction;
	while(search)
	{
		testPosY -= (iconHeight +25);
		if(search->GetParent() != this)
		{
			search->SetParent(this);
			search->SetIconPos(testPosX,testPosY);
		}
		search = search->GetNextAction();
	}
	EventGraph::InvalidateEventGraph();
}

void EffectEvent::RemoveAction(struct IEffectAction * target)
{
	IEffectAction * search = GetFirstAction();
	IEffectAction * prev = NULL;
	while(search)
	{
		if(target == search)
		{
			if(prev)
				prev->SetNextAction(search->GetNextAction());
			else
				firstAction = search->GetNextAction();
			return;
		}
		prev = search;
		search = search->GetNextAction();
	}
	EventGraph::InvalidateEventGraph();
}

struct IEffectAction * EffectEvent::GetParent()
{
	return parent;
}

void EffectEvent::SetParent(struct IEffectAction * target)
{
	parent = target;
}

const char * EffectEvent::GetName()
{
	return name;
}

void EffectEvent::SetName(const char * newName)
{
	strncpy(name,newName,63);
	name[63] = 0;
}

void EffectEvent::SetEventType(enum EventSave::EventType type)
{
	eventType = type;
}

enum EventSave::EventType EffectEvent::GetEventType()
{
	return eventType;
}

SINGLE EffectEvent::GetOffset()
{
	if(offSetTime == END_OFFSET)
	{
		return (SINGLE)(parent->GetDrawWidth());
	}
	return offSetTime;
}

void EffectEvent::SetOffset(SINGLE setting)
{
	offSetTime = setting;
}

void EffectEvent::TriggerEvent()
{
	IEffectAction * search = firstAction;
	while(search)
	{
		search->StartAction();
		search = search->GetNextAction();
	}
}

void EffectEvent::SaveCore(struct IFileSystem * outFile)
{
	U32 dwWritten;
	DAFILEDESC fdesc2 = "EVENTDATA";
	fdesc2.lpImplementation = "DOS";
	fdesc2.dwDesiredAccess = GENERIC_READ|GENERIC_WRITE;
//	fdesc2.dwShareMode = 0;  // no sharing
	fdesc2.dwCreationDistribution = CREATE_NEW;
	
	COMPTR<IFileSystem> eventFile;
	if (outFile->CreateInstance(&fdesc2, eventFile) == GR_OK)
	{
		EventSave eSave;
		eSave.type = eventType;
		if(eventType == EventSave::ANIM_CUE_TRIGGERED)
		{
			eSave.targetID = 0;
			if(parent)
			{
				IActionAnimation * aParent = parent->GetActionAnimation();
				if(aParent)
					eSave.targetID = aParent->GetTarget()->GetTargetID();
			}
			strcpy(eSave.stingParam,name);
		}
		else if(eventType == EventSave::ANIM_FINISHED)
		{
			eSave.targetID = 0;
			if(parent)
			{
				IActionAnimation * aParent = parent->GetActionAnimation();
				if(aParent)
					eSave.targetID = aParent->GetTarget()->GetTargetID();
			}
		}
		else if(eventType == EventSave::PARTICLE_CUE_TRIGGERED)
		{
			eSave.targetID = 0xFFFFFFFF;
			strcpy(eSave.stingParam,name);
		}
		else if(eventType == EventSave::SWITCH)
		{
			eSave.targetID = 0xFFFFFFFF;
			strcpy(eSave.stingParam,name);
		}
		else
		{
			eSave.targetID = 0xFFFFFFFF;
			eSave.stingParam[0] = 0;
		}
		eSave.xPos = iconXPos;
		eSave.yPos = iconYPos;
		eventFile->WriteFile(0,&eSave ,sizeof(EventSave),&dwWritten);
	}


	U32 fileId = 0;
	IEffectAction * search = firstAction;
	while(search)
	{
		char buffer[255];
		sprintf(buffer,"Action%d",fileId);
		outFile->CreateDirectory(buffer);
		
		if (outFile->SetCurrentDirectory(buffer) == 0)
			return;

		search->SaveCore(outFile);
		
		if (outFile->SetCurrentDirectory("..") == 0)
			return;
		search = search->GetNextAction();
		++fileId;
	}
}

void EffectEvent::LoadCore(struct IFileSystem * inFile, U32 _context)
{
	context = _context;
	DAFILEDESC fdesc = "EVENTDATA";
	fdesc.dwDesiredAccess = GENERIC_READ;
	fdesc.dwShareMode = 0;  // no sharing
		
	COMPTR<IFileSystem> baseData;
	if (inFile->CreateInstance(&fdesc, baseData) == GR_OK)
	{
		EventSave save;
		U32 dwWritten;
		baseData->ReadFile(0,&save ,sizeof(EventSave),&dwWritten);
		eventType = save.type;
		iconXPos = save.xPos;
		iconYPos = save.yPos;
		if(eventType == EventSave::ANIM_CUE_TRIGGERED)
		{
			strcpy(name,save.stingParam);
		}
	}
	
	WIN32_FIND_DATA data;
	HANDLE handle;
	handle = inFile->FindFirstFile("Action*",&data);
	if(handle != INVALID_HANDLE_VALUE)
	{
		do
		{
			if(data.dwFileAttributes&FILE_ATTRIBUTE_DIRECTORY)
			{
				if (inFile->SetCurrentDirectory(data.cFileName) == 0)
					return;
				IEffectAction * action = LoadActionCore(inFile,context);
				action->SetNextAction(firstAction);
				firstAction = action;
				action->SetParent(this);
				if (inFile->SetCurrentDirectory("..") == 0)
					return;
			}
		}while(inFile->FindNextFile(handle,&data));
		inFile->CloseHandle(handle);
	}	
}

void EffectEvent::LoadCoreLate(struct IFileSystem * inFile, U32 _context)
{
	context = _context;

	DAFILEDESC fdesc = "EVENTDATA";
	fdesc.dwDesiredAccess = GENERIC_READ;
	fdesc.dwShareMode = 0;  // no sharing
	COMPTR<IFileSystem> baseData;
	if (inFile->CreateInstance(&fdesc, baseData) == GR_OK)
	{
		EventSave save;
		U32 dwWritten;
		baseData->ReadFile(0,&save ,sizeof(EventSave),&dwWritten);
		iconXPos = save.xPos;
		iconYPos = save.yPos;
	}

	WIN32_FIND_DATA data;
	HANDLE handle;
	handle = inFile->FindFirstFile("Action*",&data);
	if(handle != INVALID_HANDLE_VALUE)
	{
		do
		{
			if(data.dwFileAttributes&FILE_ATTRIBUTE_DIRECTORY)
			{
				if (inFile->SetCurrentDirectory(data.cFileName) == 0)
					return;
				IEffectAction * action = LoadActionCore(inFile,context);
				action->SetNextAction(firstAction);
				firstAction = action;
				action->SetParent(this);
				if (inFile->SetCurrentDirectory("..") == 0)
					return;
			}
		}while(inFile->FindNextFile(handle,&data));
		inFile->CloseHandle(handle);
	}	
}

void EffectEvent::SetFileDependant(bool bSetting)
{
	bFileDependant = bSetting;
}

bool EffectEvent::IsFileDependant()
{
	return bFileDependant;
}

void EffectEvent::NullTarget(struct IEffectTarget * target)
{
	IEffectAction * search = firstAction;
	while(search)
	{
		search->NullTarget(target);
		search = search->GetNextAction();
	}
}

void EffectEvent::NullTarget(struct ITargetAnim * target)
{
	IEffectAction * search = firstAction;
	while(search)
	{
		search->NullTarget(target);
		search = search->GetNextAction();
	}
}

void EffectEvent::NullTarget(struct ITargetHp * target)
{
	IEffectAction * search = firstAction;
	while(search)
	{
		search->NullTarget(target);
		search = search->GetNextAction();
	}
}

IEffectEvent * EffectEvent::CreateCopy(IEffectAction * _newParent)
{
	EffectEvent * event = new EffectEvent();
	if(next)
		event->next = next->CreateCopy(_newParent);
	else
		event->next = NULL;
	strcpy(event->name,name);
	event->offSetTime = offSetTime;
	event->eventType = eventType;
	event->bFileDependant = bFileDependant;
	if(firstAction)
	{
		event->firstAction = firstAction->CreateCopy();
		IEffectAction * search = event->firstAction;
		while(search)
		{
			search->SetParent(this);
			search = search->GetNextAction();
		}
	}
	else
		event->firstAction = NULL;
	event->parent = _newParent;
	return event;
}

void EffectEvent::AddRef()
{
	++refCount;
}

void EffectEvent::RemoveRef()
{
	--refCount;
}

U32 EffectEvent::GetRef()
{
	return refCount;
}

S32 EffectEvent::GetIconXPos()
{
	if(parent)
		return parent->GetIconXPos()+iconXPos;
	return iconXPos;
}

S32 EffectEvent::GetIconYPos()
{
	if(parent)
		return parent->GetIconYPos()+iconYPos;
	return iconYPos;
}

void EffectEvent::SetDimentions(S32 newWidth, S32 newHeight)
{
	iconWidth = newWidth;
	iconHeight = newHeight;
}

bool EffectEvent::HitTest(S32 x, S32 y)
{
	if(x >= GetIconXPos() && x <= GetIconXPos()+iconWidth && y >= GetIconYPos() && y <= GetIconYPos()+iconHeight)
		return true;
	return false;
}

void EffectEvent::RealitveIconMove(S32 x, S32 y)
{
	iconXPos += x;
	iconYPos += y;
}

void EffectEvent::SetIconPos(S32 x, S32 y)
{
	iconXPos = x;
	iconYPos = y;
}

IEffectEvent * MakeEffectEvent()
{
	return new EffectEvent();
}

