//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Script1.rc
//
#define IDR_MAINMENU                    101
#define IDD_TARGET_VIEW                 101
#define IDB_NEWBUTTON                   102
#define IDD_ADD_TARGET                  102
#define IDB_LOADBUTTON                  103
#define IDB_SAVEBUTTON                  104
#define IDD_PARAMETER_VIEW              105
#define IDD_TARGET_INFO                 106
#define IDD_ADD_HARDPOINT               107
#define IDD_ADD_ANIMATION               108
#define IDD_EVENT_SELECT                109
#define IDD_NEW_ACTION                  110
#define IDD_ANIMATION_DIALOG            112
#define IDD_TARGET_ANIM_INFO            113
#define IDR_PREVIEWMENU                 114
#define IDD_PARTICLE_ACTION_HEADER      116
#define IDD_NEW_PARTICLE_EFFECT         117
#define IDD_ACTION_LISTEN               120
#define IDB_TARGET_LIST                 127
#define IDB_PARAMETER_LIST              128
#define IDD_GENERAL_FILTER_DIALOG       129
#define IDD_EDIT_FILTER_NAME            130
#define IDD_FLOAT_EDITOR                131
#define IDD_EDIT_RAMP_KEY               132
#define IDD_EDIT_TRANS                  133
#define IDD_STRING_EDITOR               134
#define IDD_EDIT_ENUM                   135
#define IDD_EDIT_TARGET                 136
#define IDD_ACTION_SOUND                137
#define IDD_ACTION_SWITCH               138
#define IDD_ACTION_HIDE_TARGET          139
#define IDR_ACCELERATOR                 143
#define ID_VIEW_MATERIALMANAGER         144
#define IDR_FILTER_POPUP                145
#define ID_DELETE                       146
#define ID_EDIT                         147
#define IDD_MATH_LAYOUT                 148
#define IDR_MATH_STANDARD_RIGHT         149
#define ID_NEWFLOAT                     150
#define ID_NEWKEY                       151
#define ID_NEWTRANS                     152
#define ID_DUMMY_SEP                    153
#define ID_SAVE                         154
#define ID_LOAD                         155
#define IDR_MATH_CONTEXT_RIGHT          156
#define ID_DUMMY_DELETE                 157
#define ID_DUMMY_EDIT                   158
#define ID_RESORT                       159
#define IDD_ACTION_GAMEEVENT            160
#define IDD_ACTION_JOINT_TRACK          161
#define IDC_TARGET_LIST                 1000
#define IDC_ADD_TARGET                  1001
#define IDC_DELETE_TARGET               1002
#define IDC_TARGET_NAME                 1002
#define IDC_OK_BUTTON                   1003
#define IDC_SELECT_TARGET               1004
#define IDC_CANCEL_BUTTON               1004
#define IDC_MOVEUP_TARGET               1005
#define IDC_HARDPOINTLIST               1005
#define IDC_MOVEDOWN_TARGET             1006
#define IDC_ADD_HARDPOINT               1006
#define IDC_DELETE_HARDPOINT            1007
#define IDC_ANIMATIONLIST               1008
#define IDC_ADD_ANIMATION               1009
#define IDC_LOAD_ANIMATION              1010
#define IDC_DELETE_ANIMATION            1011
#define IDC_TARGET_NAME_2               1012
#define IDC_SELECT_ANIMATION            1013
#define IDC_ATTACH_LIST                 1014
#define IDC_PARAM_LIST                  1017
#define IDC_VALUE_EDIT                  1018
#define IDC_EVENT_NAME                  1019
#define IDC_ADD_ACTION                  1020
#define IDC_ACTION_TYPE                 1021
#define IDC_TARGET_COMBO                1022
#define IDC_ANIM_COMBO                  1023
#define IDC_LOAD_MESH                   1023
#define IDC_HP_COMBO                    1023
#define IDC_HARDPOINT_COMBO             1023
#define IDC_SOURCE_COMBO                1023
#define IDC_MESH_NAME                   1024
#define IDC_AXIS_COMBO                  1024
#define IDC_TARGET_ANIM_NAME            1025
#define IDC_MESH_HP                     1025
#define IDC_PARENT_TARGET               1026
#define IDC_ANIM_FILE_NAME              1027
#define IDC_ASSIGN_FILENAME             1028
#define IDC_REMOVE_FILENAME             1029
#define IDC_SCRIPTED                    1031
#define IDC_TO_PARENT                   1032
#define IDC_LOOPING_CHECK               1035
#define IDC_CUE_LIST                    1036
#define IDC_FORCE_CALL                  1036
#define IDC_MAX_PARTICLES               1038
#define IDC_FREQUENCY                   1039
#define IDC_NAME_EDIT                   1039
#define IDC_LIFETIME                    1040
#define IDC_ADD_EFFECT                  1040
#define IDC_EFFECT_TYPE_COMBO           1041
#define IDC_OUTPUT                      1043
#define IDC_MATERIAL                    1044
#define IDC_OUTPUT2                     1044
#define IDC_SCALE                       1045
#define IDC_INPUT                       1047
#define IDC_MIN_SPEED                   1051
#define IDC_MAX_SPEED                   1052
#define IDC_ANGLE_I                     1053
#define IDC_ANGLE_J                     1054
#define IDC_ANGLE_K                     1055
#define IDC_NAME                        1058
#define IDC_EVENT_STRING                1059
#define IDC_ACTION_NAME                 1060
#define IDC_MIN_RANGE                   1061
#define IDC_NUM_CHOICES                 1061
#define IDC_MAX_RANGE                   1062
#define IDC_START_COMBO                 1066
#define IDC_STARTHP_COMBO               1067
#define IDC_STOP_COMBO                  1068
#define IDC_STOPHP_COMBO                1069
#define IDC_SPEED_EDIT                  1070
#define IDC_TOP_DIST                    1076
#define IDC_BOTTOM_DIST                 1077
#define IDC_TOP_OUTTER                  1078
#define IDC_DRAG_EDIT                   1078
#define IDC_TOP_INNER                   1079
#define IDC_BOTTOM_OUTTER               1080
#define IDC_BOTTOM_INNER                1081
#define IDC_DELETE                      1081
#define IDC_EDIT_NAME                   1085
#define IDC_TYPE_COMBO                  1086
#define IDC_VALUE1                      1088
#define IDC_EDIT_VALUE1                 1089
#define IDC_KEY_LIST                    1092
#define IDC_ADD_KEY                     1093
#define IDC_DELETE_KEY                  1094
#define IDC_PARAM_1                     1095
#define IDC_PARAM_2                     1096
#define IDC_VALUE                       1097
#define IDC_KEY_EDIT                    1098
#define IDC_FILTER_EDIT                 1101
#define IDC_OFFX                        1102
#define IDC_OFFY                        1103
#define IDC_OFFZ                        1104
#define IDC_BASE_TRANS                  1105
#define IDC_STRING_EDIT                 1106
#define IDC_ENUM_COMBO                  1107
#define IDC_PARAM1_DISP                 1108
#define IDC_PARAM2_DISP                 1109
#define IDC_VALUE_DISP                  1110
#define IDC_SOUND                       1113
#define IDC_LOOPING                     1116
#define IDC_SPIN_C1                     1117
#define IDC_HIDE_CHECK                  1118
#define IDC_ATTACH_ID                   1119
#define IDC_NEW_ATTACH                  1120
#define IDC_DELETE_ATTACH               1121
#define IDC_HARDPOINT_NAME              1123
#define IDC_DETACH_ALL                  1123
#define IDC_ATTACH_INDEX                1124
#define IDC_STATIC_FILTER               1124
#define IDC_EXPORT                      1125
#define IDC_IMPORT                      1126
#define IDC_RESPONCE_CHECK              1128
#define IDC_EFFECTEND_CHECK             1129
#define IDC_DISTANCE_CHECK              1130
#define IDC_DISABLE                     1133
#define IDC_WORK_COMBO                  1134
#define IDC_LISTEN_STRING               1136
#define IDC_LISTEN_STRING2              1137
#define IDC_ANG_VELOCITY_STRING         1137
#define IDC_JOINT_STRING                1138
#define ID_FILE_LOAD                    40002
#define IDD_FILE_LOAD                   40002
#define ID_FILE_SAVEAS                  40004
#define IDD_FILE_SAVEAS                 40004
#define IDD_FILE_NEW                    40005
#define IDD_FILE_SAVE                   40006
#define IDD_FILE_EXIT                   40007
#define IDD_SELECT_TARGET               40008
#define IDM_SELECT_PARAM                40009
#define IDM_PREVIEW_WINDOW              40010
#define ID_PLAYBACK_PLAY                40011
#define ID_PLAYBACK_STOP                40012
#define IDM_CUT                         40013
#define IDM_PASTE                       40014
#define IDM_COPY                        40015

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        161
#define _APS_NEXT_COMMAND_VALUE         40018
#define _APS_NEXT_CONTROL_VALUE         1139
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
